### ISSUE TITLE
Use in conky

### ISSUE THREAD

**Issue by mikaelbrun** [karlstav/cava#101]
Hey! 
I find this a pretty nice visualizer, but I would like to add it to conky. Is this possible? 

Or is it possible to echo the values, so I can use it as a graph in conky? Can you add a flag, that gives me everything but the visualization? 

-Mikael

**Comment by karlstav** [comment]
@mikaelbrun I guess this could be related to #100, do you know if conky could read the values from a fifo?

**Comment by mikaelbrun** [comment]
It might be the same. I am new to this «advanced» configuring of conky. A quick search on the www indicates that fifo and conky can work together. I will look further into this.

**Comment by karlstav** [comment]
we have the raw output mode now, so I'll close this
