### ISSUE TITLE
Raspberry Pi 3, cava not work with alsa HiFiBerry

### ISSUE THREAD

**Issue by AlessandroFerri** [karlstav/cava#102]
Hi Karl,
I have made two different installations of CAVA for my raspberry Pi3, one with also installed pulseaudio and CAVA works well, another without installing pulseaudio and then only with alsa. In this case CAVA runs but does not detect the sound, it seems that alsa-loopback does not work. In practice, the Audio Visualizer bars remain at zero. Can you help me?

**Comment by AlessandroFerri** [comment]
Hi Karl,
I stand corrected, I did some more proof and when I run

`aplay -D hw:0 Europa.wav`

I hear the sound in the headphones but CAVA does not work, but when I run

`aplay -D hw:1 Europa.wav`

CAVA works but I do not hear the sound with headphones. Is there a way to do the same thing simultaneously, that is, to hear the sound in the headphones and to work CAVA?

**Comment by karlstav** [comment]
@AlessandroFerri if you don't have pulseaudio you need to use the alsa multi channel, read more about it in the [readme](https://github.com/karlstav/cava#alsa-multi-channel-hard).

**Comment by AlessandroFerri** [comment]
I configured everything as readme, I turned on alas-loopback and in /etc/asound.conf I added

```
pcm.xxx {
    type plug       # <-- no { here
    slave.pcm {
        type multi
        slaves {
            a { channels 2 pcm "hw:1,0" }  # the real device
            b { channels 2 pcm "hw:5,0" }  # the loopback driver
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable [
        [ 1 0 1 0 ]   # left  -> a.left,  b.left
        [ 0 1 0 1 ]   # right -> a.right, b.right
    ]
}
```
and it works, but I have audio or on the headset, or on CAVA, not both.

**Comment by karlstav** [comment]
I don't think you have the right config. Try to replace your asound.conf with the file located in `cava/example_files/etc/asound.conf`

**Comment by AlessandroFerri** [comment]
Hi Karl,
so now I started the installation again. I downloaded a new image Debian **Raspin Jessie** and I run in my **Raspberry Pi3**:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo rbi-update
```

I configured everything according with readme, so:

`sudo modprobe snd_aloop`

add the line `snd-sloop` to "/etc/modules"
add the line `options snd-aloop index=1` to "/etc/modprobe.d/alsa-base.conf"

and

`sudo cp /home/pi/cava-master/example_files/etc/asound.conf etc/asound.conf`

Now I have:

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
```
I change the config file `/home/pi/cava-master/example_files/config` and I removed the comment from lines

```
method = alsa  
source = hw:Loopback,1 

```
In one terminal I run

pi@raspberrypi:~/cava-master $ ./cava -p /home/pi/cava-master/example_files/config

and in the other

```
pi@raspberrypi:~ $ aplay Europa.wav -D hw:0
Playing WAVE 'Europa.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo

```
I **hear** the music in the headphones, but cava **does not work**. Stop and run again

```
pi@raspberrypi:~ $ aplay Europa.wav -D hw:1
Playing WAVE 'Europa.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Warning: rate is not accurate (requested = 48000Hz, got = 44100Hz)
         please, try the plug plugin
```

I do **not hear** the music in the headphones, and cava **works**.
I have forgotten something? or have I done something wrong?

**Comment by karlstav** [comment]
try to use aplay without specifying an output device (use 'default')

**Comment by AlessandroFerri** [comment]
It's the same, I hear the music in the headphones, but cava does not work.

**Comment by karlstav** [comment]
this might be a problem with sample rate. the loopback only works at 44100 rate. Can you try to force aplay to use 44100? -r 44100 or something

**Comment by AlessandroFerri** [comment]
I run

```
pi@raspberrypi:~ $ aplay Europa.wav -D hw:1 -r 44100
Playing WAVE 'Europa.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Warning: rate is not accurate (requested = 48000Hz, got = 44100Hz)
         please, try the plug plugin

```
with the same result, see above.
In effect, the Europa.wav files was created with VLC to 48000 Hz sampling. I can remake the file simply by sampling at 44100 Hz, you say that it is a test to check?

**Comment by karlstav** [comment]
note that you **must** use the _default_ alsa device when playing the audio. hw:1 is loopback (connected to cava) and will always only send the sound to cava, hw:0 is your headphones jack and will always only send the audio to the headphones.

the asound.conf file you are using tries to use create a third device (default) that is hw0 and hw1 combined.

**Comment by AlessandroFerri** [comment]
So I know, now I run

```
pi@raspberrypi:~ $ aplay Europa.wav -r 44100
Playing WAVE 'Europa.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
```
in one terminal and in the other i run

`pi@raspberrypi:~/cava $ ./cava -p /home/pi/cava/example_files/config
`

but I confirm you that I get the same result,  I hear the music in the headphones, but cava does not work.

**Comment by karlstav** [comment]
it is still playing it at 48000, could you try to remake the wav file with 44100 sample rate?

**Comment by AlessandroFerri** [comment]
I try with this file, but I find always the same results:

```
pi@raspberrypi:~ $ aplay Desperado.wav
Playing WAVE 'Desperado.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

```
I hear the music in the headphones, but cava does not work.

```
pi@raspberrypi:~ $ aplay Desperado.wav -D hw:0
Playing WAVE 'Desperado.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

```
I hear the music in the headphones, but cava does not work.

```
pi@raspberrypi:~ $ aplay Desperado.wav -D hw:1
Playing WAVE 'Desperado.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo

```
I do not hear the music in the headphones, and cava works.

**Comment by karlstav** [comment]
strange, maybe it's something with how also is implemented in the pi. I'm afraid I can't help you any further. Maybe you're stuck with using pulseaudio.

**Comment by AlessandroFerri** [comment]
with what you've tested cava? with the raspberry Pi or Pi2 or Pi3? because I'm testing quarry with raspberry Pi 3 and Rsbian Jessie.
I wanted to test cava with mpd.fifo input file. What kind of files cava wants?

**Comment by AlessandroFerri** [comment]
Hi Karl,
I made a stupid mistake.
If I do run aplay the default device, CAVA works fine and I hear the audio output, like this:
`aplay Europa.wav -D default`
But now I find myself with another issue. I've enabled my HiFiBerry card. So now I have:
```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: sndrpihifiberry [snd_rpi_hifiberry_amp], device 0: HifiBerry AMP HiFi tas5713-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
If I configure `/etc/asound.conf` in this manner:
```
pcm.!default {
    type plug       # <-- no { here
    slave.pcm {
        type multi
        slaves {
            a { channels 2 pcm "hw:0,0" }  # the real device
            b { channels 2 pcm "hw:Loopback,0" }  # the loopback driver
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable [
        [ 1 0 1 0 ]   # left  -> a.left,  b.left
        [ 0 1 0 1 ]   # right -> a.right, b.right
    ]
}
```
as your file, I hear the sound from the headphones and CAVA works fine. If I instead I configure `/etc/asound.conf` in this way:
```
pcm.!default {
    type plug       # <-- no { here
    slave.pcm {
        type multi
        slaves {
            a { channels 2 pcm "hw:2,0" }  # CHANGE WITH MY CARD!!!!!!
            b { channels 2 pcm "hw:Loopback,0" }  # the loopback driver
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable [
        [ 1 0 1 0 ]   # left  -> a.left,  b.left
        [ 0 1 0 1 ]   # right -> a.right, b.right
    ]
}
```
 I find this issue:
```
pi@raspberrypi:~ $ aplay Europa.wav -D default
Playing WAVE 'Europa.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
ALSA lib pcm_params.c:2162:(snd1_pcm_hw_refine_slave) Slave PCM not usable
aplay: set_params:1204: Broken configuration for this PCM: no configurations available
```
issue: **Broken configuration for this PCM: no configurations available**

You know why? can you help me?

**Comment by anko** [comment]
@AlessandroFerri [Control experiment](https://en.wikipedia.org/wiki/Scientific_control): Does the device `hw:2,0` work separately?

```
aplay --device="hw:2,0" Europa.wav
```

**Comment by anko** [comment]
Actually, I can reproduce a similar problem:

I get the same error if I start _cava first_, before any sound is played, and then try to play _music after_.

If I start my _music first_, then _cava after_, it's fine. It's fine even if I stop the music, as long as I don't quit cava in between.

**Comment by karlstav** [comment]
I'm not able to reproduce, can it be related to rate? I know the loopback only works at 44100.

**Comment by AlessandroFerri** [comment]
I have found the solution. I must enable i2s-mmap. I add the following line to `/boot/config.txt `and reboot:
`dtoverlay=i2s-mmap`

and I configure /etc/asound.conf in this way:

```
# /etc/asound.conf or .asoundrc
pcm.multi {
    type route
    slave.pcm {
        type multi
        slaves {
            a { channels 2 pcm "output" }  # the real device
            b { channels 2 pcm "loopin" }  # the loopback driver
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable [
        [ 1 0 1 0 ]   # left  -> a.left,  b.left
        [ 0 1 0 1 ]   # right -> a.right, b.right
    ]
}

pcm.!default {
	type plug
	slave.pcm "multi"
} 

pcm.output {
	type hw
	card 2
}

pcm.loopin {
	type plug
	slave.pcm "hw:Loopback,0,0"
}

pcm.loopout {
	type plug
	slave.pcm "hw:Loopback,1,0"
}
```
My `aplay -l `report is:

```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: sndrpihifiberry [snd_rpi_hifiberry_amp], device 0: HifiBerry AMP HiFi tas5713-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

Thank you all.

**Comment by karlstav** [comment]
@AlessandroFerri that's great, I might add something about this to the readme

**Comment by fabio323ti** [comment]
@AlessandroFerri  Sorry if i reopen that, i follow  your setup, iìm using Volumio ans Cava is working on loopback, only with audio come from webradio or local file....
with External audio for ex. spotify , airplay, upnp, dlna , cava is not showing spectrum.. 

my question is : asound.conf combine two stream, why with external source cava is not working?

any solution?
