### ISSUE TITLE
Record and play sound in CAVA with Raspberry Pi

### ISSUE THREAD

**Issue by legregtom** [karlstav/cava#105]
Hi Karl,

I have followed your tutorial on how to install CAVA.
I have a few questions about how to record and play sound.

So first, the command:
`cava -i fifo`
gives me this error:
cava : invalid option -- 'i'
Do you have any idea of why I get this ?

And secondly, I don't really understand how to visualize the sound in CAVA.
I'm on Raspberry Pi and I would want to record the sound from hw:1,0 and play it on hw:0,0.
So in cava/example_files/config I have put source = hw:1,0 in [input] section.
To record I did:
`cd cava`
`arecord --channels=1 --duration=5 --format=dat --vumeter=stereo test.wav`
To play the sound I did:
`aplay -D hw:0,0 test.wav`
The sound is played but I don't see it in the visualizer.

EDIT: I saw in a video that we can record with:
`cava -i alsa -d 'hw:1,0'`
But I still have the same error:
cava : invalid option -- 'i'

Maybe it's because on the last installation step:
`sudo make install`
I have the following error:
gcc: error: /home/pi/cava/iniparser/.libs/libiniparser.so: No such file or directory

Thanks for any help.

**Comment by karlstav** [comment]
@legregtom you are following instructions for an older version of cava, as of 0.4.0 all options are specified in config file, see in '/home/username/.config/cava/' .

I would also recommend installing and using pulseaudio instead. If you must use alsa, read the readme carefully.

**Comment by metalphoenix** [comment]
@karlstav The "config files are in /home/<username>/.config" doesn't show up anywhere in your documentation that I saw. :(
