### ISSUE TITLE
bus error?

### ISSUE THREAD

**Issue by eebssk1** [karlstav/cava#106]
when i run cava ,it just give me "bus error"…

build with gcc4.9.2
ON ARM64 CPU device…

**Comment by karlstav** [comment]
I haven't tested it on an ARM64 device and I don't have any for testing. Maybe it's just not compatible :confused: Do you build and run it on the same ARM64 device?

Isn't rpi3 ARM64? You would think that more people would have tried it...

**Comment by eebssk1** [comment]
i'll  try it on ARM system.
i ran it on smartphone with debian ARM64 installed.
