### ISSUE TITLE
Running on Raspberry Pi via Shairport?

### ISSUE THREAD

**Issue by AlphaT3ch** [karlstav/cava#107]
Hey Karl, thanks for the greatly detailed instruction guide on how to install C.A.V.A. I've followed it with no errors occurring anywhere. I'm quite a newb when it comes to Linux Audio so I'm not quite sure what I've done wrong here. I'm streaming audio from an iPhone using [Shairport](https://github.com/abrasive/shairport) and it's playing perfectly via HDMI through my Raspberry Pi. I installed C.A.V.A. and used the default pulse audio method and when running the cava command, nothing. I figured the Alsa and other methods would be way too complicated for me. What do I need to do to get this thing to work?

**Comment by AlphaT3ch** [comment]
Using abrasive's shairport, I don't believe that file is available. While running option "-o pulse" it says pulse is not a valid option, only alsa, dummy, and pipe.

**Comment by karlstav** [comment]
@AlphaT3ch my mistake, you have to manually [sett up](http://sticksnglue.com/wordpress/setting-up-the-best-airplay-speakers-with-shairport-and-raspberry-pi/) shairport to be used as a service. Pretty straight forward.

Also shairport should support pulseuadio. Did you install pulseaudio after you built shairport? If so run:

```
./configure
make
sudo make install
```

again

**Comment by AlphaT3ch** [comment]
Oh, I was using an outdated Shairport Repo. Thanks for the awesome support! It looks great especially when paired with an Arduino and Adafruit Neopixel LED strips to also react to the audio. Thanks again!
