### ISSUE TITLE
Visualize audio output instead of audio input

### ISSUE THREAD

**Issue by Smile4ever** [karlstav/cava#108]
Can you do that already? If so, how? If not, consider this a feature request.

P.S. I use PulseAudio.

**Comment by Smile4ever** [comment]
Workaround:
1) Set PulseAudio as source
2) Install and open pavucontrol
3) Go to the recording tab, changing the audio source for cava to "Internal sound Analog stereo"

**Comment by karlstav** [comment]
To visualize audio output should be the default behavior with cava when using pulseaudio.

pulseaudio has a "monitor" source (input) that loopbacks audio for each sink (output). 

What cava should do if  `source = auto` in config is to listen to audio on the monitor interface for the default output. So what you are describing with pavucontrol is actually supposed to happen automatically .
