### ISSUE TITLE
Feature Request: Bars Colored by Hex Color Codes

### ISSUE THREAD

**Issue by nadehi18** [karlstav/cava#114]
Would you consider adding a feature that in the config you could assign the foreground and background colors as hex colors such as #000000 or in my case #242424, just for setups where the default colors aren't enough.  I'm not sure what this entails without diving into your code and I'm not a C programmer so I probably wouldn't understand what it means anyways.  Just wanted to ask if it could be added.

**Comment by karlstav** [comment]
this is actually the same as issue #91 only we didn't discus the use of hex codes there, which we definently should use. @hashhar have you got anything on this so far? If no, I'll be happy to implement it, also with hex codes. But no right now, no time :frowning_face:

**Comment by hashhar** [comment]
@karlstav I'm really sorry. I almost forgot about this since campus placements were going on in college. Actually I received an offer letter today itself.

I'll get on it later tonight.

**Comment by nikp123** [comment]
@nadehi18 Actually my version of cava does support colors. However it may be buggy, so beware. Also hex colors only work in X or sdl mode. Link: http://github.com/nikp123/cava

**Comment by hashhar** [comment]
@nikp123 See #91. I am looking to add truecolour support too. Your fork looks good, I did not run it but the code seems okay at a quick read.

**Comment by nikp123** [comment]
@hashhar It's a simple solution. I like it

**Comment by karlstav** [comment]
@hashhar no problem, and good luck with your studies. 

@nadehi18 I'm gonna close this issue since it's so close to #91. Let's continue any further discussion there.
