### ISSUE TITLE
make install error on raspbian jessie

### ISSUE THREAD

**Issue by gonzo28** [karlstav/cava#117]
I followed the instructions on git and installed all dependencies. Then when typing make install I get this error:

> Making install in iniparser
make[1]: Entering directory '/home/pi/cava/iniparser'
make[2]: Entering directory '/home/pi/cava/iniparser'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libiniparser.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libiniparser.so.4.0.0 /usr/local/lib/libiniparser.so.4.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libiniparser.so.4.0.0': Permission denied
Makefile:348: recipe for target 'install-libLTLIBRARIES' failed
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/home/pi/cava/iniparser'
Makefile:530: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/pi/cava/iniparser'
Makefile:513: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by karlstav** [comment]
sudo make install   ...?

**Comment by gonzo28** [comment]
oh god, yes. thanks.
