### ISSUE TITLE
No such File or Directory errors, installed with Yaourt

### ISSUE THREAD

**Issue by ErraticFox** [karlstav/cava#119]
Hello, I installed Cava via Yaourt and I keep getting these errors here
```

/usr/bin/cava: line 202: cd: /tmp/yaourt-tmp-fox/aur-cava/src/cava-0.4.2: No such file or directory
gcc: error: cava-cava.o: No such file or directory
gcc: error: /tmp/yaourt-tmp-fox/aur-cava/src/cava-0.4.2/iniparser/.libs/libiniparser.so: No such file or directory

```
Why is this? Obviously, because there's none of those files or directorys. When I mean *Why* I mean, why didn't they get created when installing with Yaourt or anything?

**Comment by karlstav** [comment]
dunno, I think you must ask your question at AUR:

https://aur.archlinux.org/packages/cava/
