### ISSUE TITLE
cava not working(solved)

### ISSUE THREAD

**Issue by LordNDHuy** [karlstav/cava#121]
I am using Arch. 
I have tried installing cava from distinct ways.
my mpd is working just fine.
I can run it, but it is not working. there is just a blank terminal screen, nothing jumps.
I have edited the config file many ways, but.
how can i fix it?

**Comment by karlstav** [comment]
@LordNDHuy are you using pulseaudio, alsa or fifo?

**Comment by LordNDHuy** [comment]
@karlstav for mpd, i set up all three methods
for cava, i have tried using each of them, as well as all of them.

**Comment by karlstav** [comment]
fifo should work well for mpd. How do you configure mpd and cava for fifo?

**Comment by LordNDHuy** [comment]
this is my mpd
`audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}`
this is cava
`[input]
method=fifo
source=/tmp/mpd.fifo`
is there any problem?

**Comment by karlstav** [comment]
is it actually in one line in the config file? I think it must be separated by line breaks.
```
[input] 
method = fifo 
source = /tmp/mpd.fifo
```

**Comment by LordNDHuy** [comment]
yeah yeah sorry 
my false.
it is separated by line breaks.
is there anything wrong beside that??

**Comment by karlstav** [comment]
no, the config looks fine.

can you be experiencing the same as issue #109 ?

**Comment by LordNDHuy** [comment]
yeah kind of. 
it appears to be a blank screen, and there is a  row in the bottom if i change the background color. it tried the noncurses thing, but it is still the same, and the terminal seemed to be not responding.
i also use tty mode, it is not stable, just columns of no. 8 with no.1 on the top.

**Comment by karlstav** [comment]
but where the bars moving in tty mode? see #116 for the issue with the numbers.

**Comment by LordNDHuy** [comment]
yes, i fixed it in tty. it is column-shaped now. but it doesnot jump.
beside i need it to work on terminal. 
sorry for bothering you so much XD.

**Comment by LordNDHuy** [comment]
It seems that file mpd.fifo is the problem.
since my ncmpcpp visualizer does not work, either. ~~.

**Comment by mosamabinomar** [comment]
mine is also not working. I'm using Arch Linux with i3wm and the terminal is **urxvt**. Any sloution?

**Comment by karlstav** [comment]
@LordNDHuy you can check if there is anything there at all by running `cat /tmp/mpd.fifo` when music is playing. You should see a lot of giberish in the terminal.

@mosamabinomar I think we need more info from you in order to help. Source? (pulse, alsa, mpd) config... Error message, blank terminal, bars lying still in the bottom of the terminal?

**Comment by LordNDHuy** [comment]
sorry for late reply, ive been alitte busy.
yeah it got some kind of symbols jumping. moreover, it looks just like when i run cava with 
[output]
method = raw

**Comment by karlstav** [comment]
@LordNDHuy it means the fifo is working. Maybe there is a problem with file permissions, even though I doubt it. I'm kinda running out of ideas

**Comment by LordNDHuy** [comment]
do you think it is the font problem?
![screenshot from 2016-12-16 11-34-21](https://cloud.githubusercontent.com/assets/22956925/21251819/abb61cde-c383-11e6-8df0-d55579249f68.png)
Since it looks like this?

**Comment by karlstav** [comment]
is this when you run cava?

**Comment by LordNDHuy** [comment]
it is when 
[output]
method = raw

**Comment by karlstav** [comment]
ok, it is supposed to look like that, how does it look when you set `method = ncurses`?

**Comment by LordNDHuy** [comment]
only using raw will it show something on the window. none of the others works.

**Comment by karlstav** [comment]
Have you tried changing the font?

On Dec 18, 2016 12:53, "HuyNguyen01" <notifications@github.com> wrote:

only using raw will it show something on the window. none of the others
works.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/karlstav/cava/issues/121#issuecomment-267817077>, or mute
the thread

**Comment by mosamabinomar** [comment]
the problem, in my case, was my windows manager. I was using i3wm, after switching to gnome, cava worked.

**Comment by LordNDHuy** [comment]
sorry XD, but what do u mean by changing font?
what i am supposed to do?? since i seem to get some problem with fonts in other stuffs.

**Comment by karlstav** [comment]
it's a long shot but cava uses chrachters do draw the bars so changing the font might give us some indication of whats wrong.


Is there a completley blanc screen when it is not working or is it a line at the bottom?

**Comment by LordNDHuy** [comment]
It completely blank just like this 
![screenshot from 2016-12-20 21-58-32](https://cloud.githubusercontent.com/assets/22956925/21355207/b3c51f22-c6ff-11e6-8180-ad43bcef7748.png)
u can see there is a row at the bottom but it is not actually a line, i think.

**Comment by karlstav** [comment]
is that row part of cava? Does it change color with the `foreground-color` parameter?

**Comment by LordNDHuy** [comment]
yeah maybe, ive done so.anyway i just think so. since if i use the terminal window as floating mode, there is no such row. it seems to be getting alittle difficult XD

**Comment by karlstav** [comment]
yes it is getting tricky, but it's good to solve each issue. For everyone one reporting a problem, there are probably many other people having the same issue.

Have you tried highlighting the terminal to see if it may be similar to #109 ?

**Comment by LordNDHuy** [comment]
ah yeah 
i once accidentally highlighted it when i run cava. it actually showed some columns, it was just the columns no jumping at all. but it just the only time, i never able to highlight again until now.

**Comment by karlstav** [comment]
so it might be related to #109 or it might not, this is not getting any easier... have you tried other terminal emulators?

**Comment by LordNDHuy** [comment]
ah i have tried many terminal emulators, none works.
yeah it is kind of like #109.
i tried to highlight it, once it showed me the jumping bars only once.
i also tried distinct output methods as i told u.

**Comment by LordNDHuy** [comment]
haha it was my fault for not setting the "locale" things.
> $ localectl set-locale LANG=en_US.UTF-8    
i did that and cava works perfectly

**Comment by Zanark** [comment]
I have the same configuration but I'm using pulseaudio.
It is able to take input from the source but displays nothing on the terminal.

Arch Linux
wm: i3wm
terminal: xfce4-terminal

**Comment by shgsys** [comment]
Same error with pulseaudio.
Arch Linux, KDE plasma, konsole

**Comment by Siddhartha351** [comment]
I Tried above fixes. 
Didn't work.
I am on Arch too,KDE plasma 6, and my terminal is kitty.

I recently upgraded my PC in the previous PC it used to work but now on the new PC it doesn't work(both running Arch Linux).
Down grade to a previous version maybe?

**Comment by youngcoder45** [comment]
> I Tried above fixes. 
> Didn't work.
> I am on Arch too,KDE plasma 6, and my terminal is kitty.
> 
> I recently upgraded my PC in the previous PC it used to work but now on the new PC it doesn't work(both running Arch Linux).
> Down grade to a previous version maybe?

Same issue to me @Siddhartha351

**Comment by pallaswept** [comment]
Friends, this issue has been resolved since 9 years ago.
