### ISSUE TITLE
I had errors while installing, here is what fixed it.

### ISSUE THREAD

**Issue by TechnologyClassroom** [karlstav/cava#128]
I had errors at ./autogen.sh
`error: Libtool library used but 'LIBTOOL' is undefined`

Imme22009's solution from http://stackoverflow.com/questions/18978252/error-libtool-library-used-but-libtool-is-undefined fixed it for me on Ubuntu 16.04.

```
sudo apt-get install -y libtool
libtoolize
aclocal
./autogen.sh
./configure
make
```

**Comment by karlstav** [comment]
@TechnologyClassroom you are right `libtool` is required, it is often installed in linux systems already, but not in ubuntu, I'll but it down in the readme.
