### ISSUE TITLE
Hex colors not working

### ISSUE THREAD

**Issue by honzi97** [karlstav/cava#130]
Hey,
I downloaded it via apt-get and the config file was empty. So I copied another one I found on the net. Things like "green" and "red" are working, but the hex color don't. I tried both ' and ". Is the problem only because I might not have the right version of the config file?

**Comment by karlstav** [comment]
@honzi97 to get hex colors you must build it from source for now. 

start from here in the reamdme:

https://github.com/karlstav/cava#build-requirements

good luck!

**Comment by honzi97** [comment]
Alright, thanks!
