### ISSUE TITLE
Cava sensitivity in config not working

### ISSUE THREAD

**Issue by rawsh** [karlstav/cava#135]
Whenever I start cava, the bars shoot way over the terminal and I have to wait for the autosense to see anything change. What my config looks like:

```
[general]

sensitivity = 30


# smoothing mode, can be normal, scientific or waves.
; mode = normal
 
# Framerate Default: 60. Accepts only non-negative values.
; framerate = 60 

...
```

Even with a low value I get no difference. I tried 0.9 as well and nothing shows at all. A reboot does not help.

**Comment by karlstav** [comment]
@rawsh autosens needs to be turned off in order for manual sensitivity setting to have any effect:
```
autosens = 0
```
I should explain this better in the config file...

**Comment by rawsh** [comment]
@karlstav Thank you, it's working now.
