### ISSUE TITLE
configure.ac requires .git folder around, fails for Git snapshot tarballs

### ISSUE THREAD

**Issue by hartwork** [karlstav/cava#139]
Hi!

While updating the Gentoo packaging for cava to 0.4.2 I noticed that `configure.ac` is calling out to Git:
```
AC_INIT([cava], [m4_esyscmd_s([git describe --always --tags --dirty])], [karl@stavestrand.no])
```
... which fails when compiling for a Git snapshot tarball so I have to do patching like this:
https://gitweb.gentoo.org/proj/betagarden.git/tree/media-sound/cava/files/cava-0.4.2-configure.patch?id=a97c02f6051d945ba75badb6bbe5825ab14086c7

Please consider calling a new small wrapper script that can deal with absence of the `.git` folder better, instead. Thanks for your consideration!

Best, Sebastian

**Comment by karlstav** [comment]
it uses git to get the current release version. 

The autoconf script is not my expertise, do you think it's possible to check for presence of .git and if not found use a hard coded string for the version? 

Why do you use `echo ${PV}`, what does that give?

**Comment by hartwork** [comment]
Hi!

`echo ${PV}` only works because [in Gentoo Ebuild context that variable is set to the version I'm packaging](https://devmanual.gentoo.org/ebuild-writing/variables/). It's auto-extracted from the package filename, `cava-0.4.2.ebuild` here.

For a solution that works for everyone I think the core questions is if you are okay with hardcoding the latest release version in a file somewhere. If that's okay, how about something like:

version.sh:
```
#! /bin/bash
if [[ -d .git ]]; then
  git describe --always --tags --dirty
else
  echo 0.4.2
fi
```

If not, maybe:
```
#! /bin/bash
if [[ -d .git ]]; then
  git describe --always --tags --dirty
elif [[ -f VERSION ]]; then
  cat VERSION  # for distribution people
else
  echo ???
fi
```

Both would preserve the feature of post-release build identification. If you don't really need that either, just put 0.4.2 in and bump manually.

What do you think?

**Comment by karlstav** [comment]
looks ok, should we just run the cript in the configure.ac script like so:

```
AC_INIT([cava], [m4_esyscmd_s([./version.sh])], [karl@stavestrand.no])
```
?

somehow that doesn't look right..

maybe we should run the version script in the autogen.sh script, output the version number to a file and then cat that file in the ac script like:

in autogen.sh:

```
#! /bin/bash
if [[ -d .git ]]; then
  git describe --always --tags --dirty > version
elif [[ -f VERSION ]]; then
  cat VERSION > version # for distribution people like me
else
  echo 0.4.2 > version 
fi
```

in configure.ac

```
AC_INIT([cava], [m4_esyscmd_s([cat version])], [karl@stavestrand.no])
```

What do you think? Am i missing something. config scripts are mostly magic to me.

**Comment by hartwork** [comment]
Calling to `./version.sh` was what I had in mind, yes. However, `autogen.sh` would work just fine, too.

If you are writing to a file `version`, we don't need a second `VERSION` file any more so things get a bit simpler. How about this addition to `autogen.sh`?
```
if [ -d .git ]; then
  git describe --always --tags --dirty > version
else
  echo 0.4.2 > version 
fi
```
Packagers could re-write the `version` file if they want to between calls to `./autogen.sh` and `./configure ....` still.

What do you think?

**Comment by karlstav** [comment]
@hartwork does it work now?

**Comment by hartwork** [comment]
Looks pretty good.

In detail:


a) From a clone:
```
# cd "$(mktemp -d)"
# git clone https://github.com/karlstav/cava.git
# cd cava/
# ./autogen.sh

# fgrep PACKAGE_VERSION= configure
PACKAGE_VERSION='0.4.2-31-g94a8a0c'
```

b) From a tarball:
```
# cd "$(mktemp -d)"
# wget https://github.com/karlstav/cava/archive/ac98e0f6b4d171c1791bd29792610823abe1b643.tar.gz
# tar xf ac98e0f6b4d171c1791bd29792610823abe1b643.tar.gz
# cd cava-ac98e0f6b4d171c1791bd29792610823abe1b643/
# ./autogen.sh

# fgrep PACKAGE_VERSION= configure
PACKAGE_VERSION='0.4.2'
```

Cool to have that fixed!
