### ISSUE TITLE
executable stack

### ISSUE THREAD

**Issue by jubalh** [karlstav/cava#142]
Building cava for openSUSE I get:
```
cava.i586: W: executable-stack /usr/bin/cava
The binary declares the stack as executable.  Executable stack is usually an
error as it is only needed if the code contains GCC trampolines or similar
constructs which uses code on the stack.  One common source for needlessly
executable stack cases are object files built from assembler files which don't
define a proper .note.GNU-stack section.
```

**Comment by jubalh** [comment]
Do you use nested functions somewhere? Or any asm code?
Couldnt find either so far.

**Comment by jubalh** [comment]
https://wiki.ubuntu.com/SecurityTeam/Roadmap/ExecutableStacks

**Comment by karlstav** [comment]
this was written by @dpayne to get the name of the default pulseaudio sink, which without would make setup a lot more complicated. I can't remember if I ever really understood how it works. I'm afraid I really can't see a way to do without them. Maybe it is possible, don't know...

**Comment by dpayne** [comment]
It should be possible to move the nested functions out entirely from the `getPulseDefaultSink` function and make them separate functions. I have them as separate static functions here https://github.com/dpayne/cli-visualizer/blob/master/src/Source/PulseAudioSource.cpp#L63, I know it's technically C++ code not C but it should still work with some small changes.

**Comment by karlstav** [comment]
ok, so nested like a function within a function. I forgot to think before I commented...

I can see no reason why this functions are nested in the first place. I guess I didn't know it was a problem. I'll get right on fixing it.

**Comment by karlstav** [comment]
is it ok now @jubalh ?

@dpayne actually there was a reason why I had nested them, I could not find a way to close the main loop after I found the name of the default sink. Because I could not get the mainloop object passed to the other functions. I solved it now by declaring it globally, it will probably cause other problems in the future. If you have any other ideas, please let me know!

**Comment by jubalh** [comment]
Yep! Thanks @karlstav
