### ISSUE TITLE
just can't get cava working correctly, need help trouble shooting

### ISSUE THREAD

**Issue by borysn** [karlstav/cava#145]
i'm not sure where to start. it works just fine on my laptop. it's a driver/monitor issue, i know that much.

definitely confused on the difference between using alsa or pulse, almost every modern system requires alsa & pulse for audio, they use each other. but cava doesn't work with either for my desktop.

**Comment by karlstav** [comment]
if you are using puseaudo on your system you must use pulseaudio for cava. The option for using just alsa is for smaller dedicated system that don't have or don't want to use pulseaudio.

we can begin by getting some info about your system, distro version etc...

**Comment by borysn** [comment]
@karlstav, thank you. i'm sorry, i was just tired & exhausted last night. i got it working last night at some point. that'll teach me to work without proper rest. i'm going to close the issue out.
