### ISSUE TITLE
allow global and local config file

### ISSUE THREAD

**Issue by jubalh** [karlstav/cava#149]
It would be cool if we could install a default configuration file.
Which then lets the user just run `cava` and it will be default use pulse.

For this to work cava should check for a global config file too.

**Comment by karlstav** [comment]
I don't really understand. cava does use pulse as default. When should it use the global config file?

**Comment by jubalh** [comment]
It does?
Oh my, I just tried again, and of course..
Sorry seems I was a bit too tired last night. I thought that it only worked after I created a config file in my homedir.
