### ISSUE TITLE
Getting A Different Audio Monitor

### ISSUE THREAD

**Issue by Alkali-Metal** [karlstav/cava#153]
Okay, so, I am relatively new to Linux and am not completely familiar with everything yet, so forgive any newbness at the moment.

So, I am wanting CAVA to monitor my headset as when I try to do it without changing anything it will only detect audio from the main speakers on my laptop. When I run the following command I get this output
```
alkali@laptop~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: ALC3236 Analog [ALC3236 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Chroma [Razer Kraken 7.1 Chroma], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
The device I am wanting to try and monitor the audio from is the `Razer Kraken 7.1 Chroma` and according to [this](https://superuser.com/questions/53957/what-do-alsa-devices-like-hw0-0-mean-how-do-i-figure-out-which-to-use) page the thing I want to put into the configuration file would be `hw:2,0` for the ALSA source

This is what I tried for the config
```
# Audio capturing method. Possible methods are: 'pulse', 'alsa' or 'fifo'.
# Defaults to 'pulse', 'alsa' or 'fifo', in that order, dependent on what support cava was built with.
#
# All input methods uses the same config variable 'source'
# to define where it should get the audio.
#
# For pulseaudio 'source' will be the source. Default: 'auto', which uses the monitor source of the default sink
# (all pulseaudio sinks(outputs) have 'monitor' sources(inputs) associated with them).
# 
# For alsa 'source' will be the capture device.
# For fifo 'source' will be the path to fifo-file.
# method = pulse
# source = auto

 method = alsa
 source = hw:2,0

; method = fifo
; source = /tmp/mpd.fifo
```

but when I run `cava` I get the base of the visualizer, but it doesn't actually detect any audio (or if it does it isn't displaying anything)

Any and all help is appreciated, thank you.

**Comment by karlstav** [comment]
@Alkali-Metal if you are new to linux you would want to use pulseaudio instead. It is sort of a "layer" running on top of alsa, making things a lot easier. If you are not running a very hacked distro it is for sure already running on your system.

Just re-add the semi-colons in front of:

```
 method = alsa
 source = hw:2,0
```

Make sure to select your headphones in you systems audio setting and then run cava. It should work.

**Comment by Alkali-Metal** [comment]
@karlstav Awesome! Its working, thank you!
