### ISSUE TITLE
Gradient!

### ISSUE THREAD

**Issue by karlstav** [karlstav/cava#156]
I initially thought that ncurses was limited to only eight different colors at a time and that each of this eight colors could be defined with a 8-bit palette (256-different colors). I therefore recently made a 'rainbow'-branch where the idea was to make a rainbow-version of cava (7 different colors + background) not very cool, but something.

I soon discovered that I could have 256 different colors at a time, each defined with a 24-bit palette (thousands of colors)! I immediately realized that this opens for much cooler possibilities, an actual gradient! 

The gradient is already well underway in the 'rainbow' branch. But I could need some help with testing. I also have one issue with restoring the original colors. (for some reason it only restores the first eight colors the rest are replaced with a cycle of the eight standard colors defined in ncurses.h). 

So for anyone interested, please head over to the 'rainbow' branch, test, explore, report any issues back here. @jubalh @chelovechishko @hashhar

**Comment by hashhar** [comment]
I didn't experience any issues yet apart from the one you yourself mentioned about the colors not getting reset. Also I don't ncurses has any way to reset colour definitions. You will most probably have to save the current colour definitions during startup and restore them on exit. But when running in a virtual console, using `reset` works but not when running a terminal emulator.

If you'd want me to test anything specific, tell me.

I'll also try on Windows and the Virtual Console later.

**Comment by karlstav** [comment]
> You will most probably have to save the current colour definitions during startup and restore them on exit.

that's what cava is already trying to do, but maybe it can only save eight? Or maybe something is wrong with the code...



> a way to set a threshold to decide when the gradient is applied would be good.

or maybe the possibility to set more colors? or both?

**Comment by chelovechishko** [comment]
Previously i missed that there are [this](https://github.com/karlstav/cava/blob/d1cd6768000d3756de6c4ab196d8dc597c0d5895/output/terminal_ncurses.c#L121). It should be right after [this](https://github.com/karlstav/cava/blob/d1cd6768000d3756de6c4ab196d8dc597c0d5895/output/terminal_ncurses.c#L86), i suppose.

Isn't we exceed `COLORS` or `COLOR_PAIRS` anywhere?

`MAX_COLOR_REDEFINITION` still less than `gradient_size`.

Why is [there](https://github.com/karlstav/cava/blob/d1cd6768000d3756de6c4ab196d8dc597c0d5895/output/terminal_ncurses.c#L106) `- 2` at the end?

Isn't it supposed to be that `change_color_definition` should be before `init_pair`?

// Too lazy to check.

**Comment by karlstav** [comment]
> Previously i missed that there are this. It should be right after this, i suppose.

fixed



> Isn't we exceed COLORS or COLOR_PAIRS anywhere?

What do you mean about this?



> MAX_COLOR_REDEFINITION still less than gradient_size.

fixed, no change

> Why is there - 2 at the end?

don't know, removed.

> Isn't it supposed to be that change_color_definition should be before init_pair?

maybe, don't know if it matters, tried it, no change.

**Comment by chelovechishko** [comment]
I mean ncurses has two variables which `respectively defining the maximum number of colors and color-pairs the terminal can support`.
```
if( COLORS < gradient_size ) {
	cleanup_terminal_ncurses();
	exit( -1 );
	}
if( COLOR_PAIRS <= gradient_size ) {
	cleanup_terminal_ncurses();
	exit( -2 );
	}
```
`bg_color_number = change_color_definition(0...)` must not start from `0` while `remember_color_definition()` has `int index = color_number - 1; // array starts from zero and colors - not`

`attron(COLOR_PAIR(color_pair_number));` should also be moved with `if (bg_color_number != -1)` because `color_pair_number` relate to it. But it also related and to `fg_color_number`, so i don't know what this code doing now. `refresh()` right after this supposed to repaint all terminal background to the new color.

**Comment by karlstav** [comment]
I have now checked that COLOS and COLOR_PAIRS both are 256, still `color_content` is only able to find the first eight colors in the color palette of the terminal. Tried with gnome terminal and rxvt. [Here](https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263) is a nice test script to print all colors in the terminal. Try to run it before and after cava. 

If I haven't missed some obvious error, this looks like a bug/limitation in ncurses.

**Comment by hashhar** [comment]
@karlstav Here's a screenshot. Cava only manages to change the 16 colours to non-default values. The other colour values are not disturbed in my case.

![2017-04-21-161704_1366x768_scrot](https://cloud.githubusercontent.com/assets/10473142/25274526/062e0f72-26ae-11e7-83b8-13f854ba364c.png)

**Comment by chelovechishko** [comment]
> this looks like a bug/limitation in ncurses

On first sight at [init_color_table()](http://pastebin.calculate-linux.ru/en/show/15078) it indeed may store wrong at `SP_PARM->_color_table[n] = tp[n % MAX_PALETTE];`
I didn't go any	further.

**Comment by karlstav** [comment]
or does this `#define MAX_PALETTE	8` at line 353 simply limit it to 8? And uses `DefaultPalette` for the rest?

**Comment by chelovechishko** [comment]
It always use `DefaultPalette`. But do with it something when store above the `MAX_PALETTE`

**Comment by karlstav** [comment]
so it is a bug then? report to `bug-ncurses@gnu.org`?

**Comment by chelovechishko** [comment]
I don't sure that it is a bug. This define there for some reason (may be legacy reason, and this reason has to be for do not change existing behaviour).  Also i checked only 5.9.

**Comment by karlstav** [comment]
Actually I don't think ncurses can restore the colors. According to [this](https://cboard.cprogramming.com/linux-programming/150031-ncurses-restore-color-endwin.html) forum post:
```
ncurses has no way of knowing what the original colors were, so it cannot restore the colors.
```
Running a simple `system("reset");` in the `void cleanup_terminal_ncurses(void)` solves the issue though...

**Comment by hashhar** [comment]
The left one is after running Cava, the right one is before. It seems like it changed the first 19 colours only.

![2017-04-21-230735_1366x768_scrot](https://cloud.githubusercontent.com/assets/10473142/25289503/7b848c18-26e7-11e7-8fcf-215c84b1eb58.png)

**Comment by karlstav** [comment]
@hashhar I figured it out, turns out ncurses can't figure out the color palette of the terminal at all. But a simple `system("reset");`solves the problem.

**Comment by chelovechishko** [comment]
You can look at your terminfo via `infocmp`.

`man terminfo`
#### Color Handling
> The `op` (original pair) string resets foreground and background colors to their default values for the terminal

`infocmp | grep op`
"memu=\Em, op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM,"

> The `oc` string resets all colors or color-pairs to their default values for the terminal

`infocmp | grep oc`

> On  a  Tektronix-like  terminal, the capability `ccc` may be present to indicate that colors can be modified

`infocmp | grep ccc`
"am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,"

It's for gnome-terminal-3.22.2.
"Reconstructed via infocmp from file: /usr/share/terminfo/x/xterm-256color"
