### ISSUE TITLE
raspberry pi: no bars.  pulseaudio vs alsa issue?

### ISSUE THREAD

**Issue by gtoal** [karlstav/cava#162]
First - here's what's needed to compile cava on a pi.  There are a few more apt-get installs needed than are listed in the github doc...
$ cd
$ sudo apt-get install autoconf libtool libpulse-dev libfftw3-dev libncurses5-dev libncursesw5-dev
$ mkdir ~/src
$ cd ~/src
$ wget https://github.com/karlstav/cava/archive/master.zip
$ unzip master.zip
$ cd cava-master
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
$ emacs -nw ~/.config/cava/config  # uncomment method = pulse
$ cava

I have a USB soundcard installed and it listens to the mic OK - I can record using:
 sudo arecord -D hw:1 -f S16_LE -d 10 -r 48000 test.wav

It plays back on the headphone jack using:
sudo aplay test.wav

Is there anything else I need to do to get cava to process the input to the mic?

Pulseaudio is running:
$ ps auxww|fgrep pulse
pi         809  0.0  0.8 111220  7292 ?        S<l  May04   0:07 /usr/bin/pulseaudio --start --log-target=syslog

There are some messages in syslog like the one below but I get them all the time anyway - I don't think they're caused by cava:
May  6 02:08:45 hive0001 kernel: [115435.809581] usb 1-1.3: 2:1: cannot get freq at ep 0x86

It did occur to me that I might need to run cava under 'sudo' but doing so showed nothing on the display (no output at all, just the cursor underneath the command line, until I typed ^C, at which point it cleared the display and reported "CTRL-C pressed -- goodbye".)  I did run 'script' to capture what was sent to the screen on ^C and the message "setterm: terminal screen does not support --blank" had been printed between the ^C and the clear screen.

Any advice?

thanks,

Graham

**Comment by karlstav** [comment]
If you really want to use the audio from the mic you must specify the mic as source in the config file. Use `pacmd list-sources` to find the name of your mic. If the source is not specified cava will try to use the audio from the default sink (output). Use `pacmd list-sinks` to find your sinks, the default should have a `*` before `index: `. You can change default sink with `pacmd set-default-sink NAME`

**Comment by gtoal** [comment]
Thanks - I've now tried all these:
device = pulse
source = alsa_input.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-mono
source = hw:1
source = 2
source = usb-GeneralPlus_USB_Audio_Device-00-Device
source = /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/sound/card1
source = platform-3f980000.usb-usb-0:1.3:1.0
source = audio-card-usb

With that not working, I tried the second option you suggest above.

pi@hive0001 ~/.config/cava $ pacmd set-default-sink 1
pi@hive0001 ~/.config/cava $ sudo cava -p ~pi/.config/cava/config

looking at the list-sinks output confirms that the USB soundcard now has the default (*) next to it.

Instead of reporting an error now, sudo cava just hangs with no output, and cava without sudo does show the bars but no response to any sound.

Attached should be the output from the pacmd commands.  Could you look at them please and tell me specifically what the parameters I should give should be?  Thanks.

[SOURCES.txt](https://github.com/karlstav/cava/files/981847/SOURCES.txt)
[SINKS.txt](https://github.com/karlstav/cava/files/981848/SINKS.txt)

G

**Comment by karlstav** [comment]
to use audio from the usb sound card use: `alsa_output.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-stereo.monitor`  as source.  `alsa_input.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-mono`  is the microphone input of your USB sound card and  `alsa_output.0.analog-stereo.monitor`  is the output of the internal soundcard on the pi.

**Comment by gtoal** [comment]
This is the only change from the default config:

method = pulse
source = alsa_output.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-stereo.monitor

pi@hive0001 ~/.config/cava $ sudo cava -p ~pi/.config/cava/config
input/pulse.c: Could not open pulseaudio source: alsa_output.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-stereo.monitor, Connection refused. To find a list of your pulseaudio sources run 'pacmd list-sources'

Running without sudo does show bars, but again absolutely no response to sounds of any kind.

Just to eliminate stupid errors like the mic actually not working, I rechecked using
sudo arecord -D hw:1 -f S16_LE -d 10 -r 48000 test.wav
and
sudo aplay test.wav
and confirmed that I am still getting audio OK from that mic.

Is there any debugging or tracing I can do that might show what is missing?  And can you confirm whether or not this should normally work without sudo?

G

**Comment by gtoal** [comment]
> to use audio from the usb sound card use: alsa_output.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-stereo.monitor as source. alsa_input.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-mono is the microphone input of your USB sound card and alsa_output.0.analog-stereo.monitor is the output of the internal soundcard on the pi.

Success!  I entered the mic name instead and it leapt into life :-)  Thanks!

method = pulse
source = alsa_input.usb-GeneralPlus_USB_Audio_Device-00-Device.analog-mono

Now to extract the data as a stream and save it to file along with the video for the corresponding recording period.  This is going to be used in a 24x7 monitor of a beehive, to correlate behaviour with hive noises, and perhaps predict behaviour such as imminent swarming as happens in colony collapse disorder.

**Comment by karlstav** [comment]
@gtoal that sounds great. No sudo should not be required. 

Sounds like an interesting project! note that cava is not intended for scientific uses, it's just made to look cool when listening to music. You might be more interested in the applications listed [here](https://unix.stackexchange.com/questions/271749/linux-audio-spectrum-analyser)

**Comment by gtoal** [comment]
Thanks.  I did read your caveat about it being more for display than science, but of the various packages I looked at, it seemed the easiest to get started since it didn't require X windows (we don't run X inside the beehive - just bash :-) )   Would I be right in assuming that the raw data doesn't have any filtering applied, except for log range compression?

With these parameters:

bars = 200
bar_width = 1
bar_spacing = 0
higher_cutoff_freq = 2000
method = raw
style = mono
data_format = ascii

I get lines like this when listening to a recording taken inside a hive:

10;14;12;10;8;9;10;14;13;11;16;19;14;9;12;8;6;8;12;18;12;8;9;8;10;9;11;17;24;19;29;41;38;57;38;28;18;19;30;36;37;33;47;56;46;69;98;65;81;110;73;56;83;86;130;125;83;55;54;81;110;81;53;37;28;42;28;33;48;63;42;27;32;42;58;54;36;24;32;42;31;20;14;19;22;32;30;45;68;56;85;81;91;78;91;82;61;89;123;82;61;73;67;44;58;64;55;44;67;44;57;85;128;85;92;118;78;79;52;63;44;56;64;84;78;117;129;89;77;116;79;76;111;89;62;67;101;134;111;81;91;61;45;67;45;34;52;78;104;69;51;50;74;106;159;110;73;49;48;42;41;59;77;101;67;74;53;67;101;67;45;43;55;72;56;84;118;78;82;66;43;40;34;48;52;73;53;47;31;37;29;43;66;77;51;33;25;38;58;53;

How do I know what frequency range each bin represents?  Is it just intervals of (2000-50)/200 starting at 50, or is there something else going on?

One final question I should have asked earlier... I'm sure a github issues log is not the best place to ask general questions but I couldn't find anywhere else.  Do you have a preferred forum for cava discussions?  (I'll close this as an issue after you reply.)

thanks again.

Graham

**Comment by karlstav** [comment]
@gtoal github kind of lacks a forum for these kind of questions, maybe the issues could be used as support forum as well, don't really know. 

Raw data has the same filters as the other output modes. It was designed to drive LED cubes and that sort of things. 




> How do I know what frequency range each bin represents?

You can try to use the debug configure option. 
```
./configure --enable-debug   
```
this should give you a list of the frequency bands and the peak intensity within each band. You would want to turn down the framerate. Note that I haven't really maintained the debug mode for a long time, it might not work at all :confused:

**Comment by gtoal** [comment]
Thanks.  Since the raw output reflects the display bars I'ld better be careful with the parameter that affects the settling time.

I have some other unrelated questions.  I'll close this now and open a new issue and call it something like "general support questions" so that people have somewhere to post stuff that isn't bug reports, and that way we won't clutter up your github issues log with non-issues.  Thanks again for the help.

**Comment by gtoal** [comment]
PS Thought you might like to see the waterfall chart I generated from the cava raw output.  It's acceptable for our purposes.  Gives us a quick fingerprint of hive activity.
![bee](https://cloud.githubusercontent.com/assets/8899318/25835745/1584e24c-3447-11e7-97d7-066a8fe8a07c.jpg)

**Comment by karlstav** [comment]
not sure what I am looking at, but I am guessing that color saturation is intensity, frequency is x and time y?



> How do I know what frequency range each bin represents?

If you don't wont to go through with the debugging option you can always playback some audio files with test frequencies to get some reference points. Remember it is a log scale so use more than two!

**Comment by gtoal** [comment]
That's right. I'm going to try the debug thing, but the bottom line is that for the way we'll probably use this, knowing the exact values isn't immediately important.  It's enough just to have some visual correlation of particular types of activity (as noted from visual inspection from the camera or various sensors embedded in the hive) and the sonogram.

By moving from the sound domain into the visual domain, we can use a whole bunch of image processing tricks and tools to filter the data, for which the equivalents in the audio domain are nowhere near as well developed.  I've already run ImageMagick's sigmoidal thresholding and cleaned up the image to highlight just significant sounds.

Thanks for pointing out that the frequency scale is log-compressed.  I knew the volume was handled like that but I hadn't noticed that the frequencies were too.

**Comment by gtoal** [comment]
I turned on debug - it runs in ncurses mode but crashes if set to raw mode.

Scraping the cursor addressing out of the redirected output gives the data below.  The display appears to have been clipped to 44 lines of in as that is the largest size I can make my text screen, so I can't get the frequency info for all 200 bars. (I'm mostly interested in values around 400hz and 1200hz roughly)
The last displayed range was for 128.534912->131.388443 which tells me that the separation is ballpark for what I'm looking for. A little narrower around the 200-400 range would have been nice but a 3-5hz wide bin will be usable for a first approximation.  Something more like 10hz per bin at that frequency would be a problem.
![image](https://cloud.githubusercontent.com/assets/8899318/25869478/0ee82c3a-34c6-11e7-97fd-d3c1f4e96765.png)

The above image is an fft taken over an entire 5 minute sample using audacity.  The two main peaks are where the activity will be happening.  Not just those two frequencies however - other hive activity not in this sample will be at other frequencies in those two general areas.

---
$ cava
height: 168 width: 44 bars:168 bar width: 1 rest: 0
1: 50.000008 -> 51.110027 (1 -> 1)
2: 51.110027 -> 52.244694 (2 -> 2)
3: 52.244694 -> 53.404552 (3 -> 3)
4: 53.404552 -> 54.590157 (4 -> 4)
5: 54.590157 -> 55.802082 (5 -> 5)
6: 55.802082 -> 57.040916 (6 -> 6)
7: 57.040916 -> 58.307251 (7 -> 7)
8: 58.307251 -> 59.601696 (8 -> 8)
9: 59.601696 -> 60.924881 (9 -> 9)
10: 60.924881 -> 62.277443 (10 -> 10)
11: 62.277443 -> 63.660030 (11 -> 11)
12: 63.660030 -> 65.073311 (12 -> 12)
13: 65.073311 -> 66.517967 (13 -> 13)
14: 66.517967 -> 67.994698 (14 -> 14)
15: 67.994698 -> 69.504211 (15 -> 15)
16: 69.504211 -> 71.047241 (16 -> 16)
17: 71.047241 -> 72.624519 (17 -> 17)
18: 72.624519 -> 74.236816 (18 -> 18)
19: 74.236816 -> 75.884911 (19 -> 19)
20: 75.884911 -> 77.569588 (20 -> 20)
21: 77.569588 -> 79.291664 (21 -> 21)
22: 79.291664 -> 81.051979 (22 -> 22)
23: 81.051979 -> 82.851372 (23 -> 23)
24: 82.851372 -> 84.690712 (24 -> 24)
25: 84.690712 -> 86.570885 (25 -> 25)
26: 86.570885 -> 88.492790 (26 -> 26)
27: 88.492790 -> 90.457375 (27 -> 27)
28: 90.457375 -> 92.465569 (28 -> 28)
29: 92.465569 -> 94.518349 (29 -> 29)
30: 94.518349 -> 96.616699 (30 -> 30)
31: 96.616699 -> 98.761635 (31 -> 31)
32: 98.761635 -> 100.954185 (32 -> 32)
33: 100.954185 -> 103.195419 (33 -> 33)
34: 103.195419 -> 105.486397 (34 -> 34)
35: 105.486397 -> 107.828247 (35 -> 35)
36: 107.828247 -> 110.222084 (36 -> 36)
37: 110.222084 -> 112.669060 (37 -> 37)
38: 112.669060 -> 115.170372 (38 -> 38)
39: 115.170372 -> 117.727203 (39 -> 39)
40: 117.727203 -> 120.340805 (40 -> 40)
41: 120.340805 -> 123.012428 (41 -> 41)
42: 123.012428 -> 125.743355 (42 -> 42)
43: 125.743355 -> 128.534912 (43 -> 43)
f:50.000008->51.110027 (1->1)peak:10
f:51.110027->52.244694 (2->2)peak:7
2: f:52.244694->53.404552 (3->3)peak:9
3: f:53.404552->54.590157 (4->4)peak:6
4: f:54.590157->55.802082 (5->5)peak:4
5: f:55.802082->57.040916 (6->6)peak:2
6: f:57.040916->58.307251 (7->7)peak:1
7: f:58.307251->59.601696 (8->8)peak:1
8: f:59.601696->60.924881 (9->9)peak:2
9: f:60.924881->62.277443 (10->10)peak:1
f:62.277443->63.660030 (11->11)peak:1
f:63.660030->65.073311 (12->12)peak:0
f:65.073311->66.517967 (13->13)peak:1
f:66.517967->67.994698 (14->14)peak:0
f:67.994698->69.504211 (15->15)peak:1
f:69.504211->71.047241 (16->16)peak:0
f:71.047241->72.624519 (17->17)peak:0
f:72.624519->74.236816 (18->18)peak:0
f:74.236816->75.884911 (19->19)peak:1
f:75.884911->77.569588 (20->20)peak:0
f:77.569588->79.291664 (21->21)peak:0
f:79.291664->81.051979 (22->22)peak:0
f:81.051979->82.851372 (23->23)peak:1
f:82.851372->84.690712 (24->24)peak:1
f:84.690712->86.570885 (25->25)peak:0
f:86.570885->88.492790 (26->26)peak:0
f:88.492790->90.457375 (27->27)peak:1
f:90.457375->92.465569 (28->28)peak:0
f:92.465569->94.518349 (29->29)peak:0
f:94.518349->96.616699 (30->30)peak:0
f:96.616699->98.761635 (31->31)peak:1
f:98.761635->100.954185 (32->32)peak:1
f:100.954185->103.195419 (33->33)peak:0
f:103.195419->105.486397 (34->34)peak:0
f:105.486397->107.828247 (35->35)peak:1
f:107.828247->110.222084 (36->36)peak:1
f:110.222084->112.669060 (37->37)peak:1
f:112.669060->115.170372 (38->38)peak:0
f:115.170372->117.727203 (39->39)peak:0
f:117.727203->120.340805 (40->40)peak:1
f:120.340805->123.012428 (41->41)peak:0
f:123.012428->125.743355 (42->42)peak:0
f:125.743355->128.534912 (43->43)peak:0
f:128.534912->131.388443 (44->44)peak:0

**Comment by karlstav** [comment]
maybe it is limited to 44 lines of info, 

I mainly used this option during development to be sure sure I got the frequency response right.  It hasn't really been maintained in a while. You can try to limit the number of bras to 44, or just decrease the font size...
