### ISSUE TITLE
Post all general support questions in this thread.

### ISSUE THREAD

**Issue by gtoal** [karlstav/cava#164]
Karl, do you know a way to either A) have cava take its input from a recording in a wav file (or any sort of file) rather than live from a mic; *or* B) do you know how to have two programs read from the mic at the same time (specifically 'arecord' and cava)?

thanks

Graham

**Comment by karlstav** [comment]
A) you can use the fifo input in cava. Maybe you will need to play the wav file to a fifo.

B) Maybe you can use [dmix](https://www.alsa-project.org/main/index.php/Asoundrc#dmix), not sure, not really an expert on alsa.

**Comment by gtoal** [comment]
A is a little tricky getting the timing right :-/  A minute's worth of audio seems to get swallowed up in a few seconds when I do:
( mplayer -novideo -ao pcm:nowaveheader:file=/tmp/mpd.fifo bees.mp3 > /tmp/mplayer.log 2>&1 & ); cava

I'll keep trying...

**Comment by conlowe009** [comment]
Karl, 

I'm sorry, but I cannot get the gradient function to work. I'm a bit new to this sort of linux customization, so I apologize if I'm missing something obvious, but I followed the config file in your master branch, un-commented gradient and gradient colors, set the value to 1, and chose my colors for the gradient. I then reloaded everything and it just won't change from the default colors. I've attached my config file that I'm using as well. 

[config.txt](https://github.com/karlstav/cava/files/1307931/config.txt)

**Comment by karlstav** [comment]
Your config works fine, a nice purple -> blue gradient.

What terminal emulator are you using?

**Comment by conlowe009** [comment]
I'm trying to get used to Urxvt, so I had a .config file for a solarized theme that I just copied and pasted. I wondered if the color scheme was somehow interfering with it, so I removed that config file and tried things as default. Unfortunately I had no luck, so I tried to run cava in both terminator and gnome terminal as well - it all outputs the same default blue color that can be changed with the "c" command.

**Comment by karlstav** [comment]
what version of cava are you using? what is the output of `cava -v`

**Comment by anko** [comment]
Why is the title of this issue *Post all general support questions in this thread*?

I think a centralised "support thread" is a terrible idea. The various sub-issues' replies will get mixed together and difficult to follow, and their statuses won't be individually trackable.

**Comment by gtoal** [comment]
Sorry, that was my fault.  It was because the github mechanism was only for
reporting bugs and there was no general support area for asking questions,
ie where the problem was not a bug with the code but the user himself (ie
me) who didn't know how to do something.  There was no-where else to ask
general support questions and I though that keeping all such questions in
one thread would be better for Karl than posting a bunch of bug reports
that weren't really bug reports.

**Comment by karlstav** [comment]
I understand what your thinking @gtoal, but I think GitHub's definition of "issue" is actually much broader then just reporting bugs. When opening a new issue you can chose labels such as "question" or "bug".

Trackability is always best. It's much better to have too many issues than too few. For anyone having a problem there is probably a bunch of other people struggling with the same thing

**Comment by karlstav** [comment]
I'll close this. 

@conlowe009 I suspect maybe you are using an older version of cava, if you're still experiencing problems you can raise a separate issue

**Comment by conlowe009** [comment]
It looks like I'm using version 0.4.1, so I'm guess I'm pretty far behind. I installed cava through the Ubuntu ppa, because I didn't quite understand how to do it manually - but I'll try and give that a shot so I can get the correct version working.
