### ISSUE TITLE
Crash on specific number of config reloads

### ISSUE THREAD

**Issue by bspammer** [karlstav/cava#165]
I have a setup to automatically change cava's color scheme frequently, which involves reloading cava's config. On my machine though cava crashes after exactly 14 reloads, so this is possibly indicative of a memory leak?

Backtrace here: https://pastebin.com/v6teXbkN

Tested both with reloading with `r` and sending cava `SIGUSR1`.

**Comment by karlstav** [comment]
@bspammer this is confirmed, I can also see that the memory usage increases after each config reload. I suspect that some buffer in the pulseaudio input thread (`input/pulse.c`) is not freed when terminated. Will look into it soon, no time right now.

**Comment by bspammer** [comment]
Hey thanks a lot for getting to this so quickly! It reloads at lightning speed now too.

**Comment by karlstav** [comment]
yes I also get a crash after a good number of reloads. Do you also get this error message:
```
input/pulse.c: Could not open pulseaudio source: alsa_output.0.analog-stereo.monitor, Connection terminated. To find a list of your pulseaudio sources run 'pacmd list-sources'
```

**Comment by bspammer** [comment]
Yep that exact same error message
