### ISSUE TITLE
Autosens increase not just decrease and auto recognize Bluetooth sink reconnect

### ISSUE THREAD

**Issue by pijulius** [karlstav/cava#167]
Hi Karl,

First of all let me thank you for this quick c equalizer that does exactly what I was looking for!!!

Now setting it up I faced two main problems that I was having and so would like to share my solutions in case it may be helpful to others or even you to include it in the next release.

1. When autosens is on and lets say Cava automatically calibrates itself having Volume Level set to 90% everything looks great, but if you turn down the volume to 30% Cava won't almost have anything to display as the sound is to low so it is like not working.

I fixed this by adding autosens to the lower values too by having a new `undershoot = 20` value in cava config which will make sens to be increased if bar falls below 20% of the window height and so Cava will start to show the bars correctly even if volume is increased or decreased (and also as side effect it even works nicely for low sound musics like downtempo :)) Also by default undershoot is set to 0 and so this change should be backward compatible with old setups.

2. When using bluetooth device lets say I have `source = bluez_sink.XX_XX_XX_XX_XX_XX.monitor` in the config file and start Cava everything works just fine, the problem is that if I turn of my speaker the sink will become invalid (but reading still works so pulse doesn't die out just returns empty data). Now when I reconnect the device the source will still be empty as we need a new sink for it to work.

What I did here to fix it was trying to subscribe to pulse audio sink changes and so when a new connection is happening I reconnect with the pa_simple_new and so Cava will work again. I know this will always reconnect whenever something new is connected (even if not the output cava has configured in the config file) but it looks to be working fine and couldn't find any better/quicker way to do it right now.

As for some reason I cannot attach patch files here you can find it including both patches to the master tree (first is sens upwards and the second is reconnect to sink).

http://pijulius.com/julius/cava/cava-master.patch

As this is the first time ever I digg into pulse audio, not sure if the second patch (reconnecting to new sinks) is the best way to do it but I tried to free up everything before doing any reconnect and thought a callback would be better then doing an if check in the loop over an over again.

Hope you will find the changes useful and maybe you can include this fixes (even if you implement your own methods) in the next release as otherwise everything looks/works just great and love it's simplicity.

Regards,
Julius

**Comment by karlstav** [comment]
@pijulius thanks for the contributions and considerations!

There is already a "run once" autosens for low values at startup. Have you taken that in to consideration when you made the patch?

I have fantasized about making this function before, but I haven't been able to solve the following:

1) what about if there is a long stretch in the music when there is silence or close to silence will the bars slowly creep upwards? 

2) What happens when you pause the music?

How have you solved this?

**Comment by pijulius** [comment]
Hi Karl,

1. Yep, they slowly start to crawl up as on each run it's only increased by 1.01 and so it doesn't immediately jumps up but slowly gets higher and higher till one of the bars reaches the height set with `undershoot` (for e.g. 20%). Also if while playing silence sound and a big drum comes in the bars will jump up to max but they will get corrected by the `overshoot` quickly so it doesn't looks to bad in my opinion. I would suggest you give it a try, for now I had it working all day and worked just fine.

Also changed this so sens doesn't end up to high if to silence music is playing for too long:
`if (senseLow && !silence) sens = sens * 1.01;`
to:
`if (senseLow && !silence && sens < 2) sens = sens * 1.01;`

2. On pause they just stay there meaning the bars simply froze down :) and if you click play they start to move again from the same place so nothing wrong here. Also if bluetooth speaker disconnects the bars simply fall down to 0 and that's all but they will restart perfectly once box is connected back.

Hope this answers your questions, if there is anything I can help you with to test please don't hesitate to let me know.

Regards,
J

**Comment by karlstav** [comment]
I'll be sure to check it out! 

Is there anyway you can make it in to a pull request instead of a patch?

**Comment by karlstav** [comment]
@pijulius I can't get it to work :confused: if i set `undershoot = 20` and turn the volume almost all the way down the bars stll just stay there. 

also cava crashes when reloading config with 'r':
```
Assertion 'c' failed at pulse/context.c:1009, function pa_context_disconnect(). Aborting.
                                                                                         Aborted
```

**Comment by raffomania** [comment]
A workaround for the missing lower autosens I'm currently using:
```
keep_restarting() {
    while true; do
        sleep 5m
        pkill -USR1 cava
    done
}

keep_restarting &
cava
```

**Comment by karlstav** [comment]
I am trying to think of a way to solve this, but can't think of any good way per now....

**Comment by karlstav** [comment]
I have something going on in the 0.6.0 branch regarding autosens of low values. Looks pretty good IMO.

**Comment by karlstav** [comment]
autosens of low values is now default in master

**Comment by raffomania** [comment]
Thanks a lot for putting in the work! cava is an awesome piece of software!

**Comment by karlstav** [comment]
@pijulius If you want to, you can make a new PR just with the Bluetooh reconnect, but you have to resolve the issue with it crashing on reload with `r`
