### ISSUE TITLE
Install on ubuntu 16.10 ? 

### ISSUE THREAD

**Issue by Epistol** [karlstav/cava#174]
Hi, I tried to install CAVA on my Ubuntu 16.10 but it's impossible since the ppa is not updated for it.

Help ?

**Comment by karlstav** [comment]
you have to install it from source:
```
sudo apt-get install libfftw3-dev libasound2-dev libncursesw5-dev libpulse-dev libtool
git clone https://github.com/karlstav/cava
cd cava
./autogen.sh
./configure
make
sudo make install
```
should get you most of the way.

**Comment by funilrys** [comment]
It'll be interesting to create the .deb file ☺

**Comment by Epistol** [comment]
Perfect, work like a charm :)

And yep, a .deb would be cool but eh, it works !
