### ISSUE TITLE
ST terminal has issues displaying

### ISSUE THREAD

**Issue by UltimaQuazar** [karlstav/cava#175]
Cava doesn't seem to run fluidly on the suckless [st](st.suckless.org) terminal.
The visualizer tears and seems to lag a bit in comparison to running it on URxvt which runs it smoothly.

**Comment by Bfgeshka** [comment]
Cannot reproduce, using pretty recent st version from master, cava works fine here.

**Comment by karlstav** [comment]
Works fine here as well using 0.4.1, not as smooth as URxvt, but smoother than Gnome terminal. 

I get the issue with the horizontal lines, but I think that's just because of the font.

**Comment by anko** [comment]
How is this a cava issue? Do other similar applications run better on `st`?

**Comment by karlstav** [comment]
@UltimaQuazar I'm closing this for now, if you have some more info on this issue just reopen it.
