### ISSUE TITLE
Ubuntu installation via apt does not work anymore!

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [karlstav/cava#176]
I just tried installing it via provided instructions from README.md for Ubuntu.

After apt update I get this error messages:

```
W: The repository 'http://ppa.launchpad.net/tehtotalpwnage/ppa/ubuntu zesty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Fehlschlag beim Holen von http://ppa.launchpad.net/tehtotalpwnage/ppa/ubuntu/dists/zesty/main/binary-i386/Packages  404  Not Found
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
```

I will now start compiling it from source, but the README should be updated / fixed.

**Comment by karlstav** [comment]
have you reported it to the packet maintainer?

**Comment by 0xFEEDC0DE64** [comment]
Oh i missed that you arent the maintainer. Maybe he will find out himself!

**Comment by TehTotalPwnage** [comment]
Hi, said package maintainer here!

I've been so busy with school that I completely forgot about maintaining this PPA (it's been a while since I've had free time to do anything).

I spent the last few hours reviewing how to properly package on Debian, and a release should be ready within the [next hour](https://launchpad.net/~tehtotalpwnage/+archive/ubuntu/ppa/+packages).

Let me know if you have any other concerns.

**Comment by karlstav** [comment]
great work @TehTotalPwnage 

The -v flag doesn't work, but maybe that's not so important.

**Comment by WuerfelDev** [comment]
Hi @TehTotalPwnage 
is it possible that you can also add a build for bionic? Getting 404 on your ppa

**Comment by TehTotalPwnage** [comment]
Sure thing. I wasn't planning on putting up Bionic until the point release, but I can probably get a build up later when I get home.

**Comment by sibblegp** [comment]
This is no longer working on Ubuntu 18.04.1 @ttpcodes

**Comment by hsheth2** [comment]
Since it doesn't look like @ttpcodes is going to update it, I went ahead and made a new PPA for Ubuntu 18.04 and newer. Take a look at #350.
```
sudo add-apt-repository ppa:hsheth2/ppa
sudo apt-get update
sudo apt-get install cava
```
