### ISSUE TITLE
Cava unworking after no use for a long time

### ISSUE THREAD

**Issue by Gaderr** [karlstav/cava#177]
Hello !
Backstory : One day I've installed cava, it worked perfectly and I've not used it for a long time until today.
So I've wanted to re-used again but at the launch, there was only tiny bars at the bottom of the window, just like if there was no music/sound playing. 

![evidence](https://i.imgur.com/K77QvZF.png)

I've re-installed Cava but nothing happend.
Other thing, the first time I've installed and used cava, I was not using a config file, and I made one after re-installing, by the config file in exemple_files directory into 

    $HOME/.config/cava/config 
and uncommented the lines

    method = pulse
    source = auto
but nothing get better
Thanks for your help !

**Comment by karlstav** [comment]
I'm not sure what the problem might be here, but it might relate to the system default audio setting.

cava uses the default auto output when set to auto, but sometimes your audio application might not be using the default output. Go to your audio settings and make sure to select the correct output.

**Comment by Gaderr** [comment]
Thanks for reply ! Indeed it was in pulseaudio settings, one of the input devices "Monitor" was muted... I've unmted it obviously. Sorry it was really simple... :no_mouth: 
Thank you kind sir !

**Comment by karlstav** [comment]
no problem!
