### ISSUE TITLE
Cava ignoring config file settings

### ISSUE THREAD

**Issue by UnbendableStraw** [karlstav/cava#180]
Setting it to 0, 50, 100, 200, or 300 all have no effect on the actual dropoff of the eq bars

I tried setting this uncommented flag in the default config file as well as specifying a custom config and neither worked

Appears to be a new issue after recently updating cava, as I did not see this issue before updating cava recently

**Comment by UnbendableStraw** [comment]
The stereo/mono flag also appears to not work. Setting MONO still puts the low ends in the middle and high ends on the  ends

**Comment by UnbendableStraw** [comment]
Gonna just go all out and say cava just doesn't respect anything in the config file anymore

Cutoff doesnt appear to take
bars, widht, spacing doesnt take

**Comment by UnbendableStraw** [comment]
Need to run cava as root to make config effective

**Comment by karlstav** [comment]
@UnbendableStraw probably an issue with you system, if you run cava as root it will try to load a config file from your /root directory or something and not your /home/USER directory. I have been struggling with similar things myself.
