### ISSUE TITLE
Strange behavior matrix spectrogram

### ISSUE THREAD

**Issue by japrogramer** [karlstav/cava#182]
![screen_2017-10-16-16-38-15](https://user-images.githubusercontent.com/1387859/31636568-9ceede78-b290-11e7-9010-f29b060fd0ac.png)
Enter the matrix

**Comment by karlstav** [comment]
cool, can you get it in dark green? 

I'm trying to figure out what might cause this effect, but I can't really figure it out. 

What terminal emulator are you using? It might be related to cava not getting the correct dimensions, or something with ncurses.

**Comment by japrogramer** [comment]
Yeah, I can get it in a dark green. Im using urxvt, The cause is probably due to me resizing the terminal really fast with xmonad. The drawn spots do scroll up which is a cool effect.

**Comment by karlstav** [comment]
ok, I can't reproduce it by resizing as fast as I can using urxvt on Fedora (gnome 3). Nothing to do really.

Does it clear if you reload with 'r'?

**Comment by japrogramer** [comment]
It does not clear after 'r'. Im using it inside tmux, maybe thats what sets it off. I tried it outside of tmux and it wouldn't glitch out but inside it did.

**Comment by karlstav** [comment]
most likely, have you checked this:

https://unix.stackexchange.com/questions/139075/tmux-ncurses-apps-are-displayed-wrong-with-garbage-and-so-on

**Comment by japrogramer** [comment]
yes, I have looked at that for a different issue. I ended up doing this in my .tmux.conf to fix previous issue
set-option -g default-terminal "tmux-256color"

cava glitching out isn't really a problem, It only happens when i change the layout for my work space really fast.
