### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Skippythekangoo** [karlstav/cava#186]
Hi...

I use Gentoo and I have installed FFTW package.

I'm not a big bos in compilation and in C language.

I try to compil your CAVA (I like this... :), but I have this error : 

skippy@Gentoo ~/compilations/cava $ make
make[1] : on entre dans le répertoire « /home/skippy/compilations/cava »
gcc -DPACKAGE_NAME=\"cava\" -DPACKAGE_TARNAME=\"cava\" -DPACKAGE_VERSION=\"0.6.0-12-g51e48d8\" -DPACKAGE_STRING=\"cava\ 0.6.0-12-g51e48d8\" -DPACKAGE_BUGREPORT=\"karl@stavestrand.no\" -DPACKAGE_URL=\"\" -DPACKAGE=\"cava\" -DVERSION=\"0.6.0-12-g51e48d8\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_H=1 -DHAVE_CURSES_H=1 -DHAVE_INIPARSER_H=1 -I.  -DPACKAGE=\"cava\" -DVERSION=\"0.6.0-12-g51e48d8\" -D_POSIX_SOURCE -D _POSIX_C_SOURCE=200809L  -DHAVE_ALLOCA_H -DALSA -DPULSE -D_GNU_SOURCE -I/usr/include/ncursesw -DNCURSES -std=c99 -Wall -Wextra -Wno-unused-result -Wno-maybe-uninitialized  -g -O2 -MT cava-cava.o -MD -MP -MF .deps/cava-cava.Tpo -c -o cava-cava.o `test -f 'cava.c' || echo './'`cava.c
In file included from cava.c:69:0:
config.c: Dans la fonction ‘load_config’:
config.c:389:2: erreur : too many arguments to function ‘iniparser_getseckeys’
  iniparser_getseckeys(ini, "eq", keys);
  ^
In file included from cava.c:66:0:
/usr/include/iniparser.h:142:9: note : declared here
 char ** iniparser_getseckeys(dictionary * d, char * s);
         ^
make[1]: *** [Makefile:527: cava-cava.o] Error 1
make[1] : on quitte le répertoire « /home/skippy/compilations/cava »
make: *** [Makefile:577: all-recursive] Error 1

It's my mistake or what...

Thanks, and sorry for my english, I'm so french... :p

**Comment by karlstav** [comment]
hi @Skippythekangoo this is actually the same as #83 

configure with this option:
```
./configure --legacy-iniparser
```

then run `make` again
