### ISSUE TITLE
initparser issue

### ISSUE THREAD

**Issue by AinsworthK** [karlstav/cava#187]
Hi, I just updated initparser and cava give to following error and can't launch.

`cava: error while loading shared libraries: libiniparser.so.0: cannot open shared object file: No such file or directory
`

tried reinstall initparser package and cava, nothing changed.
Using Arch linux, install from AUR.

**Comment by karlstav** [comment]
Might this be an issue with the [package](https://aur.archlinux.org/packages/cava/) on AUR? I can see that the iniparser on AUR was recently upgraded to 4.1, maybe there is something there.

Have you tried to build cava from the source instead?

**Comment by AinsworthK** [comment]
seems like AUR package problem, just build from source and it work. Sorry, should have try it before asking.
