### ISSUE TITLE
CAVA GUI Overshooting

### ISSUE THREAD

**Issue by rharish101** [karlstav/cava#188]
When I use cava in the terminal, it works fine without overshooting, with a sensitivity of 1:
![cava-no-overshoot](https://user-images.githubusercontent.com/25344287/33703314-9af50044-db4d-11e7-8a9d-d5120b990db9.png)

But, when I use the GUI version, it overshoots, even with the lowest sensitivity (=1):
![cava-overshoot](https://user-images.githubusercontent.com/25344287/33703319-a06bf47e-db4d-11e7-9ee7-875296a61849.png)

Using the down arrow button, I can lower the sensitivity in the GUI enough so that it doesn't overshoot, but I can't manually set the sensitivity in the config file to be, say 0.3, as lower than 1 values are treated as 0. I have turned autosense off and set overshoot to 0.

**Comment by karlstav** [comment]
@rharish101 the GUI version is still maintained in its own [fork](https://github.com/nikp123/cava), I don't know if separate issues can be raced on forks. I have been planning on looking into merging, but I am still not sure about it.

Anyways it is @nikp123 that must look into this issue.

**Comment by nikp123** [comment]
Will look into it...

**Comment by nikp123** [comment]
@rharish101 try turning on autosense.
Or if the issue still persists, you can try reinstalling the AUR package. (because it seems you're using ArchLinux, right?)
If necessary I might submit a patch that resolves renderer issues. Basically TUI uses x8 height and GUI doesn't. (since every eighth height represents a new character and pixels are 1:1 in terms of height)

**Comment by nikp123** [comment]
Just letting everyone know, I have added the patch that fixes sens.

Just recompile and try the new build.

**Comment by rharish101** [comment]
@nikp123 I tried re-installing the AUR package, and the overshooting is still present, even with autosense on. Am I missing the patch?

**Comment by nikp123** [comment]
@rharish101 may you share the configuration file as I can't recreate the issue?

**Comment by rharish101** [comment]
Here's it:
[config.txt](https://github.com/karlstav/cava/files/1556122/config.txt)
I added the .txt extension as GitHub wasn't allowing me to upload elsewise.

**Comment by nikp123** [comment]
There is a dollar sign ($) in the output section and also avoid putting strings in quotes (fxp. method = x instead of method = 'x'), it doesn't work for some reason. Possible iniparser bug, but not sure.

If it still doesn't work, I'll have to update AUR, I guess.

**Comment by rharish101** [comment]
I tried those, still didn't work.

**Comment by nikp123** [comment]
A workaround (at least in pulseaudio) is to adjust the cava input volume level in pavucontrol.

**Comment by nikp123** [comment]
I have no idea as to what is wrong. (aka. it works fine on my machine)

Are you running a foreign architecture (like ARM or something)?

**Comment by nikp123** [comment]
Found out that compiling from source works, but AUR doesn't. Fairly weird, I'll try updating AUR (to see if it fixes it).

**Comment by nikp123** [comment]
LMAO, I found out that AUR pulls from karlstavs repo instead of mine. Just need @karlstav to pull my changes to the gui branch and we're all set.

**Comment by nikp123** [comment]
Updated AUR to pull from my repo to avoid issues like this.

**Comment by karlstav** [comment]
@nikp123 maybe AUR should pull from your repo and not mine? I am still not sure if I should merge the GUI branch, there is a lot of things here that I would not be able to maintain. 

BTW I tried to build it and I forgot to install the prerequisites and I got a bunch of [errors](https://github.com/karlstav/cava/files/1560780/errors.txt). It should probably configure it to build without gui-support if not `libx11-dev` or `libsdl2-dev` is present (and build with x only if libsdl is not present and vice versa if possible). 

There is also alot of warnings.

Also I got an error when trying 'x':
```
TERMINATED
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  28
  Current serial number in output stream:  28
```

here is my [config](https://github.com/karlstav/cava/files/1560794/config.txt)

**Comment by nikp123** [comment]
libtool should have done that...

I guess I may have missed something.

**Comment by nikp123** [comment]
turns out GLX was the dependency you were missing not libx11 or sdl2

added a check for that

**Comment by nikp123** [comment]
and it can build without graphical support

**Comment by rharish101** [comment]
Nice, it works now.
