### ISSUE TITLE
[feature] Clock feature that can be toggled

### ISSUE THREAD

**Issue by syfluqs** [karlstav/cava#189]
A simple clock overlay on the visualizer that can be toggled on or off with <kbd>=</kbd>.

**Comment by karlstav** [comment]
It does look ok, but I have to agree with anko on this. I like to keep it simple and to the point and although it's a neat feature it really doesn't enhance the visualizer as a visualizer. Terminal multiplexer would be the way to achieve something like this.

**Comment by syfluqs** [comment]
@anko @karlstav Completely agree with the both of you, I just added the clock thing for my awesomewm configuration, I thought it could be a nice feature for some people. No worries, however.
