### ISSUE TITLE
Per channel bars with current sound volume level for surrond 5.1 and 7.1 pulseaudio modes

### ISSUE THREAD

**Issue by MurzNN** [karlstav/cava#193]
Will be good to have option for see per-channel current sound volume, especially for 5.1 and 7.1 outputs.
For this needs we don't need full equalizer, only one bar per channel, that showing current sound level.

**Comment by karlstav** [comment]
don't really see the point of this. Also a bit to the side of what cava is. Surround would only be useful when watching movies and then you wouldn't be watching a visualizer....?

**Comment by MurzNN** [comment]
I want to see in console, in which channels sound are go, and with which volume. I need to remote monitor via ssh console 5.1 & 7.1 music system status, for understand which speakers are working and which not. Sometimes music plays on 2 channels, sometimes on 7.1 or 5.1.

So I want something like `pavumeter` but for console, and I found only your `cava` that can show anything about sound volume from pulseaudio in console.
![pavumeter](https://i.imgur.com/EV3ZNQh.png)

**Comment by karlstav** [comment]
I see, unfortunately cava is not a volume meter :slightly_frowning_face: so you will have to look somewhere else. Maybe there is some info to get out of `pacmd list-sinks`

**Comment by MurzNN** [comment]
I search already long time tool to cli display `pulseaudio` volume meter in console via ssh, but found nothing. :( 
I know that pulseaudio have cli interface (pacmd and pactl) that can output raw data about volume meters, but I need some visualized output, and hope that do this based on `canva` will be easier that writing script from scratch.
