### ISSUE TITLE
Cava configuration issues with konsole

### ISSUE THREAD

**Issue by Stephr1** [karlstav/cava#194]
I am running Fedora 27 with kde 5 and have finally been able to put cava in my background. I have only been able to make transparency and desktop configurations work with konsole, however now cava only creates brick like bars and gradiant as shown: 

![screenshot](https://user-images.githubusercontent.com/35380751/34922320-30e10d10-f943-11e7-854f-64d7d16dae27.png)

It works normally in gnome-terminal on the right, even though the cava configurations are the same. 

This happened before when the user define gradients were not real colour codes, but when gradient is disabled the bars are still brick shaped. 

Any ideas? Thanks.

**Comment by karlstav** [comment]
If i remember correctly konsole doesn't support chaining the color definitions, I thought it should throw an error if you try to define a color with hex color codes, but I can see now that it doesn't (bug).

**Comment by karlstav** [comment]
the function that checks this is part of [curses.h](https://linux.die.net/man/3/can_change_color). I am not sure why it doesn't work, I know that it has worked before, as I tested this with konsole when this was implemented.

**Comment by Scrumplex** [comment]
It probably has to do with fonts in part. Try changing the Konsole font to Monospace. It is the best performing for CAVA.

**Comment by karlstav** [comment]
@Stephr1, I was finally able to test this with konsole on something else then fedora (Mint 18.3) and there cava exits and throws the error:

```
Your terminal can not change color definitions, please use one of the predefined colors.
```

when trying to change color definitions (gradient needs to change color definitions to work). 


Konsole is Version 15.12.3 and ncursesw 6.0.20160213

**Comment by karlstav** [comment]
On fedora 27 I have konsole Version 17.08.1 and ncursesw 6.0.20170722. And yes, instead of throwing the error it runs cava without changing the colors.

My guess is that for some reason Konsole 17 thinks it can change the color definitions, but obviously it can't. Maybe report to [konsole forum](https://forum.kde.org/viewforum.php?f=227)?

**Comment by bunder2015** [comment]
Hi, I recently upgraded to kde and it appears this still messed up, it seems this is a konsole thing from reading this issue, but I thought I'd let you know.

https://i.imgur.com/GHEMsUL.png

Cheers

**Comment by Faithxull** [comment]
I Also have the same problem on konsole

**Comment by enderprism** [comment]
fixed by changing the output method to `noncurses`

**Comment by enderprism** [comment]
> Hi, I recently upgraded to kde and it appears this still messed up, it seems this is a konsole thing from reading this issue, but I thought I'd let you know.
> 
> [i.imgur.com/GHEMsUL.png](https://i.imgur.com/GHEMsUL.png) (konsole on the left, mate-terminal on the right)
> 
> Cheers

it's also a thing with QTerminal, so i guess all qt-based terminals are affected if they use `ncurses` as their output method

**Comment by karlstav** [comment]
did custom (hex code defined) colors also work with noncurses? If so i am surprised, i thought it was impossible to change color definitions in konsole.

**Comment by enderprism** [comment]
by affected i meant 'use the wrong colors'. both QTerminal and Konsole display the wrong colors if the output method is set to `ncurses` (tested with catppuccin/cava, which uses custom gradients), and konsole works fine with `noncurses` (haven't tested QTerminal.
sorry if i was unclear.

**Comment by enderprism** [comment]
by affected i meant 'use the wrong colors'. both QTerminal and Konsole display the wrong colors if the output method is set to `ncurses` (tested with catppuccin/cava, which uses custom gradients), and konsole works fine with `noncurses` (haven't tested QTerminal.
sorry if i was unclear.

PS.
shortcuts (`q` to quit, `r` to refresh, etc.) seem to stop working with `noncurses` but i don't know if it's intentional or not

**Comment by karlstav** [comment]
ok, shortcuts should work in the most recent version

**Comment by Papagemabodi** [comment]
> by affected i meant 'use the wrong colors'. both QTerminal and Konsole display the wrong colors if the output method is set to `ncurses` (tested with catppuccin/cava, which uses custom gradients), and konsole works fine with `noncurses` (haven't tested QTerminal. sorry if i was unclear.
> 
> PS. shortcuts (`q` to quit, `r` to refresh, etc.) seem to stop working with `noncurses` but i don't know if it's intentional or not

I changed output to noncurses in config, did not worked
