### ISSUE TITLE
Properly exit ncurses on failure

### ISSUE THREAD

**Issue by meMuszr** [karlstav/cava#195]
When the program exits outside of a SIGINT, it fails to properly clean up after itself.

Calling `cleanup()` before any `exit(1)` should make this more polished.

**Comment by karlstav** [comment]
I added a cleanup to the 'reload config' scenario. It should take care of the most exits. There will still be problems if one of the audio threads fail, but I'm not sure how to fix that.

**Comment by meMuszr** [comment]
I wouldn't mind giving it a go if you could direct me on how to recreate  ~

**Comment by karlstav** [comment]
@meMuszr sorry for the delay. A way to recreate this would be to kill pulseaudio `pulseaudio -k` while cava is running. (that is if you are using pulseaudio to capture audio)

**Comment by karlstav** [comment]
just remembered I solved a similar problem earlier by using a shared pointer. 

I now made a way for threads to exit more softly. Only implemented for pulseaudio as for now, alsa/fifo is not that likely to crash.
