### ISSUE TITLE
Raw output from mpd fifo does not appear correct

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#197]
Hi

I am writing an OLED spectrum display for Volumio, which uses mpd. I set up a fifo in mpd.conf

```
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd_vol_oled"
    format                  "44100:16:2"
}
```
I wrote a test program cava_read.cpp which runs cava as a subprocess and  reads its raw output in 8bit.

``` C++
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string>

using std::string;

string print_config_file(int bars, string fifo_name)
{
  char templt[] = "/tmp/cava_config_XXXXXX";
  int fd = mkstemp(templt);
  if(fd == -1)
    return "";  // failed to open file and confert to file stream
  FILE *ofile = fdopen(fd, "w");
  if(ofile == NULL)
    return "";  // failed to open file and confert to file stream

  fprintf(ofile, "[general]\n"
                 "bars = %d\n"
                 "\n"
                 "[input]\n"
                 "method = fifo\n"
                 "source = /tmp/mpd_vol_oled\n"
                 //"method = pulse\n"
                 //"source = auto\n"
                 "\n"
                 "[output]\n"
                 "method = raw\n"
                 "data_format = binary\n"
                 "channels = mono\n"
                 "raw_target = %s\n"
                 "bit_format = 8bit\n",
          bars, fifo_name.c_str());
  fclose(ofile);
  return templt;
}

int main(int argc, char *argv[])
{
  int bars = 20;
  const string fifo_name = "/tmp/cava_fifo";
  if (argc > 1)
    bars = atoi(argv[1]);
  if (bars < 1) {
    fprintf(stderr, "error: bars is '%d', must be 1 or more\n", bars);
    exit(EXIT_FAILURE);
  }

unlink(fifo_name.c_str());
  if(mkfifo(fifo_name.c_str(), 0666) == -1) {
    perror("could not create cava FIFO for writing");
    exit(EXIT_FAILURE);
  } 

  string config_file_name = print_config_file(bars, fifo_name);
  if (config_file_name == "") {
    perror("could not create cava config file");
    exit(EXIT_FAILURE);
  }

  string cava_cmd = "cava -p " + config_file_name;
  fprintf(stderr, "cmd ='%s'\n", cava_cmd.c_str());
  FILE *from_cava = popen(cava_cmd.c_str(), "r");
  if (from_cava == NULL) {
    perror("could not start cava program");
    exit(EXIT_FAILURE);
  }

  FILE *fifo_file = fopen(fifo_name.c_str(), "rb");
  if(fifo_file == NULL) {
    fprintf(stderr, "could not open cava FIFO for reading");
    exit(EXIT_FAILURE);
  }

  unsigned char bar_heights[bars];
  while (true) {
    int num_read = fread(bar_heights, sizeof(unsigned char), bars, fifo_file);
    if(num_read < bars) {
      fprintf(stderr, "no more data from cava");
      exit(EXIT_FAILURE);
    }
    for (int i=0; i<bars; i++)
      fprintf(stdout, "%3d ", bar_heights[i]);
    fprintf(stdout, "\n");
    fflush(stdout); 
  }

  pclose(from_cava);

  return 0;
}


```
Using the cava_read and the mpd fifo the values are in a low range and do not appear to be correct relative to each other. Running cava on its own and reading from the same fifo the spectrum appears correct.
I have the same results on a Raspberry Pi running Volumio and on an Intel PC running Ubuntu

Using cava_read and pulse as a source (on Ubuntu) the values are in a normal range and look like they are probably correct relative to each other.

Here is the cava config file used by cava_read when reading from the mpd fifo

```
[general]
bars = 10

[input]
method = fifo
source = /tmp/mpd_vol_oled

[output]
method = raw
data_format = binary
channels = mono
raw_target = /tmp/cava_fifo
bit_format = 8bit

```

This is some typical output for pop music with the mpd fifo, which appears incorrect

![cava_read_mpd_fifo](https://user-images.githubusercontent.com/2940060/36943934-821471fc-1f92-11e8-96cf-c375783b6881.png)

And this is some typical output for pop music with pulse, which appears correct

![cava_read_youtube_pulse](https://user-images.githubusercontent.com/2940060/36943935-824a95ca-1f92-11e8-90f0-0e8021f40d64.png)

Thanks

Adrian.

**Comment by karlstav** [comment]
This is strange, input and output is completely independent from each other. So if 8-bit raw output was incorrect, it should be just as incorrect for pulseaudio as for mpd. I think the problem is most likely with the mpd input. How does the two compare with normal ncurses output?

**Comment by antiprism** [comment]
The cava  ncurses  display appears fine both with the mpd fifo and with pulse (on Ubuntu). I used a configuration file like the one used by the read_cava program

```
[general]
bars = 10

[input]
method = fifo
source = /tmp/mpd_vol_oled
#method pulse
#source auto

[output]
method = ncurses
# method = raw
data_format = binary
channels = mono
raw_target = /tmp/cava_fifo
bit_format = 8bit

```

Here is a screenshot of the cava ncurses didplay with input from the mpd fifo

![cava_mpd_fifo_ncurses](https://user-images.githubusercontent.com/2940060/36947080-71f18d66-1fc7-11e8-97f1-f05ba2ef0e56.png)

**Comment by karlstav** [comment]
could it be related to volume settings in mpd? I'm not really sure if that affects the fifo output, but it is something to check out.

**Comment by antiprism** [comment]
Changing the mpd volume doesn't affect the cava ncurses display or the cava_read output.

**Comment by karlstav** [comment]
have you tried to check it with the the ascii output instead of binary? You could use space (32) as bar_delimiter and line feed (10) as frame_delimiter to get the same effect as your cava_read application.

**Comment by antiprism** [comment]
I saw how to play mpd through pulseaudio on Ubuntu, and so here is a screenshot of simultaneous (but maybe not synchronised) cava raw ascii output for input from mpd fifo (left) and pulse (right). The fifo values are very small, like in the raw binary output.

![cava_ascii_radio1](https://user-images.githubusercontent.com/2940060/36972643-29a2c1fc-2070-11e8-809c-75d96ce7a88b.png)

**Comment by karlstav** [comment]
can you test it with ncurses again, but with autosens disabled? You might have to adjust the sensitivity a lot to get it in view.

I'm going to try to reproduce the issue tomorrow, haven't had much time lately.

**Comment by karlstav** [comment]
Well I try to resolve every issue as there are always more people having the same problem. 

There is a bar height value in the ascii output:
```
; ascii_max_range = 1000
```
for binary this will of course automatically be 255 for 8bit and 65535 for 16bit.

I thought that also that the sensitivity value should affect the raw output as well. Do you mean that it doesn't? Not sure if I am following you on that last part.

**Comment by antiprism** [comment]
You can scale the raw bar values with the sensitivity value, but autosens doesn't appear to work with the raw values. Setting autosens=1 doesn't affect the small fifo raw bar values, but gives a normal range of bar heights in the ncurses window.

**Comment by karlstav** [comment]
can finally confirm very low values from fifo input. I don't know why I decided that autosens should not be implemented for raw output, it is absolutely necessary. I will look into both low values from fifo and autosens for raw out ASAP.

**Comment by karlstav** [comment]
@antiprism could you check out the new branch iss197? it should have a fix for low fifo values and autosens for raw. Binary raw is not tested.

I just remembered that alsa and mpd do have much lower values then pulseaudio. I limited them to just use the highest 10 bits in the sample instead of all 16. Now why on earth did I do that :confused: Probably because it was like the first piece of code that I wrote on this project and I didn't know better. 

Glad to be finaly cleaning this up.

**Comment by antiprism** [comment]
The ascii values read from the mpd fifo look good.

The 8bit and 16bit values appear to be in a good range, but with the values inverted so that

   returned value = max-value - correct _value

Except that at the quietest the high values become 0.

Here is some example 8bit output for some baroque music, which contains mainly middle frequencies

![cava_inv](https://user-images.githubusercontent.com/2940060/37087609-142a7c66-21fb-11e8-9847-b509c653c15d.png)

I am not sure about NORMALIZE_AND_WRITE. It appears to be multiplying the maximum value of a unsigned type by a signed integer

```
uint##type##_t f_##type = UINT##type##_MAX;
f_##type *= f[i];
```

Maybe this is multiplying the signed integer f by -1 and then converting the result to the unsigned type, producing the high/low flip.

**Comment by karlstav** [comment]
I don't really understand that piece of the code myself. It was rewritten by someone else a wile back. 

I just rewrote that whole thing in a much simpler way. I tested it with your code and I think it looks good.

**Comment by antiprism** [comment]
It appears to be working correctly, thanks!

I don't know if you noticed but you have to hit CTRL-C twice to stop my test program. Would it be better if there was no signal handler installed for raw output? (I also wanted to see the last raw output when I hit CTRL-C, but the screen was cleared.)

I'll see if I can get the cava output displaying on the OLED on the Raspberry Pi, and then post an update to confirm that raw output is working correctly.

**Comment by antiprism** [comment]
Correction: CTRL-C doesn't need to be pressed twice, there is just an exit message without the prompt displayed.

**Comment by antiprism** [comment]
Works great! (Not the best photo, the bars are actually separated by pixel wide black lines).

![cava_oled](https://user-images.githubusercontent.com/2940060/37170575-789aa73c-230b-11e8-98da-c41140419abb.jpg)

Initially, the display didn't match the audio at all. This turned out to be because the cava framerate was greater than the OLED update speed. I set the cava framerate to 40 and the display is now synchronised perfectly with the audio,

Thanks again!

Adrian.

**Comment by karlstav** [comment]
Looks cool, you should make a video or gif! 

What sort of display is that? Maybe I should make a thing like that myself.

**Comment by antiprism** [comment]
The display is a I2C SSH11036 1.3" OLED. It cost around $5

   https://www.aliexpress.com/wholesale?SearchText=ssh1106

I am using it with a $10 Raspberry Pi Zero W, which is fine for running Volumio (and Cava at the the same time), and a $4 I2S PCM5102 DAC, which provides reasonable audio output.

I plan to put up an installation guide for the spectrum display for Volumio/mpd users. I might make a short video of the steps to go with it.

**Comment by karlstav** [comment]
cool, thanks for all the input/troubleshooting!
