### ISSUE TITLE
Lenovo on Docking

### ISSUE THREAD

**Issue by carepack** [karlstav/cava#198]
Hi all,

I'm writing here because didn't know where else I should ask. Btw. thx for cava - makes my desktop more bautiful.
I have a lenovo t470p with a lenovo docking station. To the docking and the monitor are connected via displayport and the jack of the docking is connected to my amplifier. I'm usin pulse, and control it via alsa-mixer or pavucontrol. At the beginning I used only the speakers of the monitor via displayport and cava worked out of the box and is still. But from time to time I want to hear my music loud via the amplifier and in the moment when I switch my output to the jack cava stops working. For example playin songs from spotify - cava won't show any equalizer activity. I also configured mpd fifo - that's working. So how can I get equalizer functionality when running spotify over jack? I didn't got how to configure the pulseaudio card config in cava.conf. Hopefully somebody has an idea. Thx in advance!

**Comment by karlstav** [comment]
hi @carepack 

Cava defaults to using the selected pulseaudio output. But I haven't find  way to automatically detect if the output changes (although I remember vaguely discussing that with someone here). You will have to reload cava, either by pressing `r` or by sending cava a `SIGUSR1` signal. Read more in the [readme](https://github.com/karlstav/cava#configuration)

**Comment by carepack** [comment]
thx for replying. sigterm cava or restart isn't working because I don't switch the output. It's so that when the first output  after boot is jack it doesn't work. But its always working when I output through dp via monitor but never by jack. I can switch to dp cava and when I switch to jack it's never working independent with which output I start.

**Comment by karlstav** [comment]
I'm going to need the output of your `pacmd list-sinks`

**Comment by carepack** [comment]
Hi and thx for replying,

here's the ouput:
https://pastebin.com/vcQUtsXy

**Comment by karlstav** [comment]
could you give me the output of `pacmd list-sources` as well?

**Comment by carepack** [comment]
sure:
thats analog stereo (jack) ouput:
https://hastebin.com/hewegipoca

and here via dp monitor:
https://hastebin.com/pevozosife

**Comment by karlstav** [comment]
If you specify 

    source = alsa_output.pci-0000_00_1f.3.analog-stereo.monitor

in the config file. It should work. I thought it should have worked without the need to specify that as well, don't know what the issue might be.

**Comment by carepack** [comment]
thx for the reply, unfortunately it isn't working now on dp and jack. no function at all with the config add

**Comment by karlstav** [comment]
The problem might be that the volume of the .monitor input of your headphones output is turned to 0%. Look at line 9 in your `pacmd list-sources`.

Look around in pavucontrol to find out where to raise it.

The monitor source (input) is a way to record audio directly from an output. It is what cava uses to capture audio.

**Comment by carepack** [comment]
it's all unmuted
https://imgur.com/a/G3eEq

**Comment by karlstav** [comment]
don't think it will turn up in alsamixer. Try pavucontrol, look under [recording](https://camo.githubusercontent.com/596d592b061b8cfd77a5a729c8494aa6b4af028b/68747470733a2f2f696d672e75676a6b612e6e65742f64725378447055412e706e67)

**Comment by karlstav** [comment]
or run `pacmd set-source-volume 4 65536`

**Comment by karlstav** [comment]
maybe the index changes run `pacmd list-sources` again to find it.

also maybe cava have to be running for the source to show up under recording.

**Comment by carepack** [comment]
Yeah, index changed to 10. But unfortunately 
pacmd set-source-volume 10 65536
didn't help

**Comment by karlstav** [comment]
Then I don't know. But my suspicion is that the problem lies around there somewhere.
