### ISSUE TITLE
I have made installable packages of cava available for Fedora

### ISSUE THREAD

**Issue by larsks** [karlstav/cava#199]
Hi there!  I've created cava packages for Fedora 26 and 27 using Fedora's COPR service.  You can find the packages here:

    https://copr.fedorainfracloud.org/coprs/larsks/cava/

To install packages from this repository:

    dnf copr enable larsks/cava
    dnf install cava

These packages are generated from the spec file hosted at <https://github.com/larsks-packages/cava>.

To report problems with the packages (or to request new builds for new releases), please use my issue tracker at <https://github.com/larsks-packages/cava/issues>.

**Comment by karlstav** [comment]
hi @larsks ,

Great work, I will add it to the readme. The old spec file linked to there seems to be outdated also.
