### ISSUE TITLE
Make is setting `rpath` unconditionally

### ISSUE THREAD

**Issue by larsks** [karlstav/cava#200]
`Makefile.am` sets `cava_LDFLAGS` to:

    cava_LDFLAGS = -L/usr/local/lib -Wl,-rpath /usr/local/lib

The arguments to `-L` and `-rpath` should probably be set based on the configured installation prefix, rather than using `/usr/local/lib` all the time.

I would additionally suggest that the `Makefile` should not be setting `-rpath` in any case.

**Comment by karlstav** [comment]
This has already been considered, please check out #144

**Comment by karlstav** [comment]
hi @larsks, have you checked out the other issues surrounding this? I'll be happy to resolve this, but as you can see I'm not sure how.

**Comment by karlstav** [comment]
can this perhaps be done in the `autogen.sh` script?
