### ISSUE TITLE
No Bars on Cava

### ISSUE THREAD

**Issue by MarzioPi** [karlstav/cava#202]
Hey everybody. Like the title suggest, i can’t see bar when i run cava. Since last week it worked perfectly, but for some reason I decided to reset my RaspberryPi3. Since the moment I did it, I tried to reinstall Cava. 
When I ran “./autogen.sh” something went wrong and ad the debug message suggest me i added “AC_CONFIG_MACRO_DIRS([4])” to the “configure.ac” file. Ran libtoolize and aclocal. No error message after that, then ./configure, no error message and make. Script created cava, i ran it with ./cava as i always used to but I see nothing else than a blank black page. I just tried to remove and reinstall al the packeta without success. All the packets wrote in the readme.md file are installed. I really don’t know how to do, and what went wrong. Furthermore it is not like no sound input, in that case I could see bars as a dash, but I see really nothing. Please help me and thanks in advance for reply.

**Comment by karlstav** [comment]
What OS are you running? Raspbian? Maybe there is some issue with ncuses, you could try setting output to noncurses

**Comment by MarzioPi** [comment]
Hi Karl! Yes I’m running Raspbian. I already tried to set ouput to noncurses without success. The strangest thing is that I worked with cava and installed without any problem in the past, and now in ./Autogen.sh it told me to add the line cited before and in configure now i can read just one strange thing: WARNINGS: No sndio dev files found building without sndio support. Could be this? How to solve it?

**Comment by karlstav** [comment]
no, sndio is an audio framework for bsd that was added a while back. I don't know what version of cava that you had before, but a lot of changes can have been made since that time. Also a lot of changes can have been made in rasbian. Are you using pulseaudio or alsa?

**Comment by MarzioPi** [comment]
I am using Alsa with the Loopback driver, config file of cava is set like it always used to be when i used to use it. It’s not so long ago, I am talking of about 1/2 weeks ago. I seems I’m talking about too far in the past it’s in spite of my english ahaha I’m not mother tongue.

**Comment by karlstav** [comment]
Your english is understandable, don't worry about that. But cava changes all the time so if you haven't been actively pulling new source code from github you might have been running an older version. How does your config file look?

**Comment by MarzioPi** [comment]
## Configuration file for CAVA. Default values are commented out. Use either ';' or '#' for commenting.
 
 
[general]
# Smoothing mode. Can be 'normal', 'scientific' or 'waves'. DEPRECATED as of 0.6.0
; mode = normal
 
# Accepts only non-negative values.
; framerate = 60
# 'autosens' will attempt to decrease sensitivity if the bars peak. 1 = on, 0 = off
# new as of 0.6.0 autosens of low values (dynamic range)
# 'overshoot' allows bars to overshoot (in % of terminal height) without initiating autosens. DEPRECATED as of 0.6.0
; autosens = 1
; overshoot = 20
# Manual sensitivity in %. Autosens must be turned off for this to take effect.
# 200 means double height. Accepts only non-negative values.
; sensitivity = 100
# The number of bars (0-200). 0 sets it to auto (fill up console).
# Bars' width and space between bars in number of characters.
; bars = 0
bar_width = 1
bar_spacing = 0
 
# Lower and higher cutoff frequencies for lowest and highest bars
# the bandwidth of the visualizer.
# Note: there is a minimum total bandwidth of 43Mhz x number of bars.
# Cava will automatically increase the higher cutoff if a too low band is specified.
; lower_cutoff_freq = 50
; higher_cutoff_freq = 10000
 
 
 
[input]
# Audio capturing method. Possible methods are: 'pulse', 'alsa' or 'fifo'.
# Defaults to 'pulse', 'alsa' or 'fifo', in that order, dependent on what support cava was built with.
#
# All input methods uses the same config variable 'source'
# to define where it should get the audio.
#
# For pulseaudio 'source' will be the source. Default: 'auto', which uses the monitor source of the default sink
# (all pulseaudio sinks(outputs) have 'monitor' sources(inputs) associated with them).
# 
# For alsa 'source' will be the capture device.
# For fifo 'source' will be the path to fifo-file.
; method = pulse
; source = auto
 
method = alsa
; source = hw:Loopback,1
 
; method = fifo
; source = /tmp/mpd.fifo
 
 
 
[output]
# Ouput method. Can be 'ncurses', 'noncurses' or 'raw'. 
# 'noncurses' is for systems that does not suport ncurses.
# 'raw' is a 16 bit data stream of the bar heights that can be used to send to other applications.
# 'raw' defaults to 200 bars, which can be adjusted in the 'bars' option above.
method = noncurses
# Visual channels. Can be 'stereo' or 'mono'.
# 'stereo' mirrors both channels with low frequencies in center.
# 'mono' averages both channels and outputs left to right lowest to highest frequencies.
; channels = stereo
# Raw output target. A fifo will be created if target does not exist.
; raw_target = /dev/stdout
# Raw data format. Can be 'binary' or 'ascii'.
; data_format = binary
# Binary bit format, can be '8bit' (0-255) or '16bit' (0-65530).
; bit_format = 16bit
# Ascii max value. In 'ascii' mode range will run from 0 to value specified here
; ascii_max_range = 1000
# Ascii delimiters. In ascii format each bar and frame is separated by a delimiters.
# Use decimal value in ascii table (i.e. 59 = ';' and 10 = '\n' (line feed)).
; bar_delimiter = 59
; frame_delimiter = 10
 
 
 
[color]
# Colors can be one of seven predefined: black, blue, cyan, green, magenta, red, white, yellow.
# Or defined by hex code '#xxxxxx' (hex code must be within ''). User defined colors requires a
# terminal that can change color definitions such as Gnome-terminal or rxvt.
background = black
foreground = red
# Gradient mode, only hex defined colors are supported, background must also be defined in hex
# or remain commented out. 1 = on, 0 = off. Warning: for certain terminal emulators cava will
# not able to restore color definitions on exit, simply restart your terminal to restore colors.
; gradient = 0
; gradient_color_1 = '#0099ff'
; gradient_color_2 = '#ff3399'
 
 
 
[smoothing]
# Percentage value for integral smoothing. Takes values from 0 - 100.
# Higher values means smoother, but less precise. 0 to disable.
; integral = 70
# Disables or enables the so-called "Monstercat smoothing" with or without "waves". Set to 0 to disable. 
; monstercat = 1
; waves = 0;
# Set gravity percentage for "drop off". Higher values means bars will drop faster.
# Accepts only non-negative values. 50 means half gravity, 200 means double. Set to 0 to disable "drop off".
; gravity = 100
 
# In bar height, bars that would have been lower that this will not be drawn.
; ignore = 0
 
 
[eq]
# This one is tricky. You can have as much keys as you want.
# Remember to uncomment more then one key! More keys = more precision.
# Look at readme.md on github for further explanations and examples.
; 1 = 2 # bass
; 2 = 2
; 3 = 1 # midtone
; 4 = 1
; 5 = 0.5 # treble

**Comment by karlstav** [comment]
looks good. If you change the background color, does it also change when you run cava?

**Comment by MarzioPi** [comment]
Yes, when I click on the cava windows and move it as i’m selecting text I see different colors, then it works perfectly but still no bars. Can you suggest me a command to delete all files connected to cava? Just deleting git repository from home and config file, I think that something remains on the system. I would try to delete and reinstall all the packets around cava, if it’s possible and, if i’m lucky, usefull. Thanks

**Comment by karlstav** [comment]
can you check #121 and #109 ? Can it be related? that was solved by setting locale:


```
localectl set-locale LANG=en_US.UTF-8
```

**Comment by MarzioPi** [comment]
Beautifull! Really sorry, I didn’t see connection between problem in those issues and mine, but now Cava works perfectly! Thank you very much for that and for Cava!

**Comment by karlstav** [comment]
no problem, I knew that there was a reason that I didn't close that issue. Maybe I have to add something in the readme...
