### ISSUE TITLE
How to get spotify to use loopback

### ISSUE THREAD

**Issue by enzobarrett** [karlstav/cava#203]
Hello, I use cmus for music usually. I have a loopback interface setup for the audio and cava works fine. Today I was using spotify and the loop back does not work at all. Could anyone help me with this? Thanks

**Comment by karlstav** [comment]
how to you set up cmus do make it work? Are you using the ALSA multi channel?

**Comment by enzobarrett** [comment]
I just setup a alsa multichannel like the readme says to.

**Comment by enzobarrett** [comment]
@karlstav I did, Spotify used pulse while mcp used alsa! Thanks.

**Comment by karlstav** [comment]
yes, you can't really change any audio settings in spotify, it's a bit annoying. I think it will use alsa if you uninstall pulseaudio. Anyways I will close this as it is more of a spotify issue,
