### ISSUE TITLE
Build error if ncurses is not present

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#207]
I am building Cava on MoodeAudio, based on Raspbian Stretch Lite release 2018-03-13.

The Cava build fails if libncursesw5-dev package is not installed (and succeeds if it is installed).

```
gcc -DPACKAGE_NAME=\"cava\" -DPACKAGE_TARNAME=\"cava\" -DPACKAGE_VERSION=\"0.6.0-29-gcbe6d56\" -DPACKAGE_STRING=\"cava\ 0.6.0-29-gcbe6d56\" -DPACKAGE_BUGREPORT=\"karl@stavestrand.no\" -DPACKAGE_URL=\"\" -DPACKAGE=\"cava\" -DVERSION=\"0.6.0-29-gcbe6d56\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_H=1 -I.  -DPACKAGE=\"cava\" -DVERSION=\"0.6.0-29-gcbe6d56\" -D_POSIX_SOURCE -D _POSIX_C_SOURCE=200809L -Iiniparser/src -DHAVE_ALLOCA_H -DALSA -std=c99 -Wall -Wextra -Wno-unused-result -Wno-maybe-uninitialized  -g -O2 -MT cava-cava.o -MD -MP -MF .deps/cava-cava.Tpo -c -o cava-cava.o `test -f 'cava.c' || echo './'`cava.c
In file included from cava.c:42:0:
output/terminal_noncurses.c: In function ‘init_terminal_noncurses’:
output/terminal_noncurses.c:61:2: warning: implicit declaration of function ‘system’ [-Wimplicit-function-declaration]
  system("setterm -cursor off");
  ^~~~~~
cava.c: In function ‘cleanup’:
cava.c:94:6: warning: implicit declaration of function ‘cleanup_terminal_ncurses’ [-Wimplicit-function-declaration]
      cleanup_terminal_ncurses();
      ^~~~~~~~~~~~~~~~~~~~~~~~
cava.c: In function ‘directory_exists’:
cava.c:127:31: error: ‘FALSE’ undeclared (first use in this function)
     if (dir == NULL) exists = FALSE;
                               ^~~~~
cava.c:127:31: note: each undeclared identifier is reported only once for each function it appears in
cava.c:128:19: error: ‘TRUE’ undeclared (first use in this function)
     else exists = TRUE;
                   ^~~~
cava.c: In function ‘main’:
cava.c:426:20: error: ‘FALSE’ undeclared (first use in this function)
  bool reloadConf = FALSE;
                    ^~~~~
cava.c:427:18: error: ‘TRUE’ undeclared (first use in this function)
  bool senseLow = TRUE;
                  ^~~~
Makefile:528: recipe for target 'cava-cava.o' failed
make[1]: *** [cava-cava.o] Error 1
```
Here is the configuration log: [config.log](https://github.com/karlstav/cava/files/1954384/config.log)

**Comment by karlstav** [comment]
@antiprism this relates to some old issue with ncurses on debian, stdlib and alloca.h. Sorry, don't have much time to look at it now. Have you searched through the old issues?

**Comment by antiprism** [comment]
I just did a search and found the same build issues reported here: https://github.com/karlstav/cava/issues/157

**Comment by antiprism** [comment]
I had a quick look at the build issues.

**TRUE FALSE undeclared errors:**
As mentioned in https://github.com/karlstav/cava/issues/157, the TRUE and FALSE macros are not defined in standard C, but may be included by some library header. If you are using 'bool' then the standard comparison values are 'true' and 'false' (from stdbool.h, which is already included in cava.c).

**warning: implicit declaration of function ‘system’**
system() needs stdlib.h to be included. output/terminal_noncurses.c is included in cava.c, but the prior include for stdlib.h in cava.c is conditional . Instead stdlib.h could be specifically included in output/terminal_noncurses.c.

**warning: implicit declaration of function ‘cleanup_terminal_ncurses’**
cleanup_terminal_ncurses() is unconditionally referenced in cava.c, but its definition is in output/terminal_ncurses.h,  which is not included if ncurses is not being used.

**Comment by karlstav** [comment]
are you saying that if we change them fro uppercase to lowercase everything will work smoothly? 

stdlib.h could probably be included in output/terminal_noncurses.c. Can't see why not. 

cleanup_terminal_ncurses() should not be referred to if ncurses is not being used. should be within `#ifdef NCURSES`

If you want to, you can make the changes yourself and create a PR? I Won't be able to for a while..

**Comment by antiprism** [comment]
'true' and 'false'  are defined to be 1 and 0 in stdbool.h, which is the same values as TRUE and FALSE are defined in ncurses.h.

**Comment by karlstav** [comment]
great work, thanks!
