### ISSUE TITLE
JACK support

### ISSUE THREAD

**Issue by Bfgeshka** [karlstav/cava#217]
Is it planned anytime soon? Cava could be quite useful in JACK setup.

**Comment by karlstav** [comment]
not planned, but it did cross my mind under early development. I have no time now, but I'll but it on the todo list for later.

**Comment by ionenwks** [comment]
I would very much like this as well, but can live without if no time for it. For those interested meanwhile, not happy with the solution but right now using CAVA with Jack using the fifo intended for mpd (method = fifo) and:
`jack_capture --daemon -ws > /path/to/cava/fifo`
Has no "noticeable" delays and jack_capture has sub-1% cpu usage. jack_capture connects to every jack ports by default as well which saves doing additional setup (If jack support is implemented here it would probably be handy to be able to do the same using the hooks that tells when new clients connect and let user disable if need be. The user can setup external solutions either way so it's not super important. JACK users should be familiar with this already).

**Comment by MathiasKandelborg** [comment]
So I've had cava working on my system after I installed JACK to play with ardour, etc.

It still works and I think I can whip up a small guide if there's enough interest for it.

I use a bridge to pulseaudio, so pulseaudio is still there, and I'm not an audio shark by any means so that might cause most to not bother anyways.

In my JACK manager ([Cadence](https://kx.studio/Applications:Cadence)) I set the bridging to go Alsa > pulse > Jack (plugin)

It works really well with some defaults set in pavucontrol, otherwise, all I have to do is change the cava recorder from pulse to the correct output.

**Comment by karlstav** [comment]
as long as you have pulseaudio there should be little need for jack in order to capture audio. since pulseaudio has monitor sources to connect to. 

I guess you could use jack to send audio to a fifo or alsa loopback? I don't know much about jack. but guides for that would maybe be useful.

**Comment by ionenwks** [comment]
> I implemented the JACK input backend: https://github.com/bsdcode/cava/tree/jack
> 
> Let me know if that looks good to you.

Haven't really looked at the code but gave it a quick try and it's working as expected :+1:

**Comment by karlstav** [comment]
Just make a pr @bsdcode, I have no experience with jack myself and no time now to really test it. But if people say it works, I have nothing against pulling it into the repo.

**Comment by bsdcode** [comment]
I added the option `autoconnect`. It controls the port connection strategy used by CAVA.

`autoconnect = 0`: don't connect automatically
`autoconnect = 1`: connect once at startup
`autoconnect = 2`: connect regularly (default)

The automatic connection strategy works much like what the program `jack_capture` does: rescan the input ports of the physical audio device whenever the JACK graph reorder hook fires and apply the same connections to CAVA.

#545

**Comment by ionenwks** [comment]
Tried autoconnect and works nicely out-of-the-box from what I can see (tested with jack2). Glad to be able to get rid of my old jack_capture + fifo hack.

**Comment by bsdcode** [comment]
Thank you for testing. It's good to hear that it works for other people too and that my efforts are not in vain ;)

**Comment by karlstav** [comment]
better late than never, almost six years since this issue was opened! thanks @bsdcode
