### ISSUE TITLE
WM_CLASS not fully set

### ISSUE THREAD

**Issue by Kaukoa** [karlstav/cava#218]
Hello, I really like this fork, but was unable to set rules for it in my WM (bspwm)
For bspwm to be able to set rules the XWindow class must be set.
Locally I modified graphical_x.c and added
cavaXClassHint.res_class = (char *)"Cava";
right below
cavaXClassHint.res_name = (char *)"Cava";
It works now fine with bspwm for me.
This would be a nice QOL change for bspwm users

**Comment by Kaukoa** [comment]
I am sorry; this is about the branch cava-gui
I'll see myself out

**Comment by karlstav** [comment]
@nikp123 is still maintaining the gui branch in his own [fork](https://github.com/nikp123/cava), but we are planning to merge it here in some time. How is the work coming along @nikp123?

**Comment by nikp123** [comment]
@Kaukoa sorry i totally forgot about this, the patch is now live

**Comment by nikp123** [comment]
anyway @karlstav can you add a bit in the README that redirects issues from your repo to mine, just so accidents like this dont happen

**Comment by karlstav** [comment]
@nikp123 I don't understand what you mean by "redirecting" issues, but it still looks like you haven't enabled issues on your repo. I think issues are disabled by default on a fork, just og to settings and options to enable.

**Comment by nikp123** [comment]
@karlstav sorry my bad, didn't notice
