### ISSUE TITLE
Best smoothing options

### ISSUE THREAD

**Issue by vaskark** [karlstav/cava#220]
Hi. I'm getting stumped setting the best smoothing options for the cava app. I want the bars to react best to the music. I've been doing trial and error for a while now and have yet to hit upon the ideal combo. Can someone maybe share what they've been using?
Thanks.

P.S. Not really an issue, I realize. If it isn't appropriate to ask here ... please delete.

**Comment by karlstav** [comment]
> react best to the music

what do you mean that specifically? If you want it more precise then lowering integral and increasing gravity might be what you want. You might also want to disable the monstercat filter. 

I'm always glad to help, you might call it an issue with the documentation in the config file. It can always be better.

**Comment by vaskark** [comment]
Thanks for responding. I guess I meant I wanted the animation to appear visually closer to what I was hearing. Maybe I need to configure it to use more base over treble or something. I'm not sure. I'll keep monkeying with it.

**Comment by karlstav** [comment]
No problem! Depending on what soft of music you listen to, you might want t adjust the eq, as you say. You might also try the things i mention in the post. Also increasing the number of bars will help to get more nuances out of the visualization.
