### ISSUE TITLE
Looks weird in suckless ST

### ISSUE THREAD

**Issue by chromz** [karlstav/cava#222]
Hi, Cava bars look strange on [st](https://st.suckless.org/)  0.8.1, maybe this is an issue related to my st configuration. This doesn't happens with [cli-visualizer](https://github.com/dpayne/cli-visualizer) bars though. Already tried changing font and character spacing but the problem persist.

Screenshot:
![1528993502](https://user-images.githubusercontent.com/8508965/41425184-36128d04-6fbd-11e8-9ad8-8e341804d98b.png)

**Comment by karlstav** [comment]
I don't think so, cava does not use double height characters. Maybe st just adds a line of space between the lines. It probably shouldn't though, maybe it can be reported as a bug.

Do you see the same lines in other ncurses applications such as alsamixer?

**Comment by chromz** [comment]
Here is a [screenshot](https://imgur.com/rcEwiha) of alsamixer, the bar looks good but the borders have the same bug.

**Comment by chromz** [comment]
I found a fix, I just patched st with [vertcenter](https://st.suckless.org/patches/vertcenter/) and changed the character spacing (chscale) and it worked.

**Comment by legofarmer** [comment]
> Found a fix, I just patched st with [vertcenter](https://st.suckless.org/patches/vertcenter/) and changed the character spacing (chscale) and this time it worked. Not related to cava.

What did you change chscale to?

**Comment by chromz** [comment]
Depends on the font, at the time I think I was using DejaVu Sans Mono with
chscale 1.1
