### ISSUE TITLE
Strange C.A.V.A. screen artifacts.

### ISSUE THREAD

**Issue by thecsw** [karlstav/cava#223]
Hey! Love C.A.V.A, using it for a year+ plus, mad respect! However, lately (1-2 weeks) I started receiving some strange screen artifacts (leftovers) on my urxvt.

[Proof](https://imgur.com/a/1jiR5Bb) 

btw, I use arch. I deleted my cava and reinstalled with AUR version of cava-git. But even after I compiled it, the problem stayed. Is this a common issue or my machine wanted to laugh at me?

Thanks!

Sincerely,
@thecsw

**Comment by karlstav** [comment]
Hi @thecsw, thanks for the mad respect. 

My guess is that this must be related to the terminal emulator or font.  Try other terminal emulator and/or different font to see if the problem persist.

**Comment by thecsw** [comment]
Interesting, launched it in terminator and it worked. That is really strange because I never had this issue on my urxvt, I've been using it for more than a year. I think that's it. Terminal, maybe a terminal update broke it?

**Comment by karlstav** [comment]
acording to [this](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/rxvt-unicode) there hasn't been any mayor updates to urxvt in years. Could you try it in urxvt with a different font?

**Comment by thecsw** [comment]
Yeah, I just tried switching urxvt fonts from Inconsolata and the artifacts disappeared. This issue started with my recent [pywal](https://github.com/dylanaraps/pywal) update. Thanks for your help! I think this is it for now. Best of luck!

**Comment by thecsw** [comment]
Hey! I am reopening this issue as I found a way to trigger it.

**Comment by thecsw** [comment]
I use `.Xdefaults` to configure urxvt fonts and when I was changing the font size, cava's behavior was changing. 
1. ![2018-06-25-231204_1366x768_scrot](https://user-images.githubusercontent.com/16922860/41870694-d298ec4a-78cd-11e8-8d5a-54d94d4c3e43.png) 

This is `Inconsolata` with font size 14. Everything behaves as expected and cava has the "blocks".

2. ![2018-06-25-231218_1366x768_scrot](https://user-images.githubusercontent.com/16922860/41870726-e9fe677a-78cd-11e8-9107-f10493a0ec93.png)

When I change it to 13, I have the above C.A.V.A. "artifacts".

3. ![2018-06-25-231831_1366x768_scrot](https://user-images.githubusercontent.com/16922860/41870815-2e2ea3d8-78ce-11e8-9725-be936dcca7c9.png)

Setting to 12 font size, everything's back to normal.

**Comment by karlstav** [comment]
interesting I'll leave this open for now, however it is probably an issue with urxvt and or the font.

**Comment by karlstav** [comment]
@thecsw I know this is over a year old, but are you able to test this with the latest added changes? If not I will just close this issue.

**Comment by thecsw** [comment]
Hey @karlstav!
Merry Christmas!

I think it's all working fine now! Thank you
I'll close the issue
