### ISSUE TITLE
How can I compile CAVA on Slackware?

### ISSUE THREAD

**Issue by GittyMejorado** [karlstav/cava#225]
Good Day:
I have installed ttf-console-fonts and the compilation error keeps coming up, I think it's a problem of shared libraries but I do not know how to fix it
I leave the error output

make[2]: Do nothing to 'install-data-am'
make[2]: leave the directory '/root/Downloads/cava-master/iniparser'
make[1]: leave the directory '/root/Downloads/cava-master/iniparser'
make[1]: enter the directory '/root/Downloads/cava-master'
make[2]: enter the directory '/root/Downloads/cava-master'
 /usr/bin/mkdir -p '/usr/local/bin'
  /bin/sh ./libtool   --mode=install /usr/bin/ginstall -c cava '/usr/local/bin'
libtool: install: /usr/bin/ginstall -c .libs/cava /usr/local/bin/cava
 /usr/bin/mkdir -p '/usr/share/consolefonts'
 /usr/bin/ginstall -c -m 644 cava.psf '/usr/share/consolefonts'
make[2]: leave the directory '/root/Downloads/cava-master'
make[1]: leave the directory '/root/Downloads/cava-master'

**Comment by karlstav** [comment]
@GittyMejorado is it really an error though? I am not following...

**Comment by SHGuy1** [comment]
did you do `sudo make install`?
