### ISSUE TITLE
Apt Install Broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by corbanvilla** [karlstav/cava#227]
$ sudo apt-get update
Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                   
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic InRelease                          
Ign:4 http://ppa.launchpad.net/tehtotalpwnage/ppa/ubuntu bionic InRelease           
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease                  
Hit:6 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease                
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease                  
Err:8 http://ppa.launchpad.net/tehtotalpwnage/ppa/ubuntu bionic Release             
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                     
E: The repository 'http://ppa.launchpad.net/tehtotalpwnage/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Looks like there's no release file for bionic

I know you're busy so just when you get a second :)

**Comment by karlstav** [comment]
hi @corbanvilla, I think you have to report this directly at launchpad or to the packet maintainer in some other way. Github is just for the source code.

**Comment by willpiam** [comment]
Was the packet maintainer notified? issue persists...

**Comment by hsheth2** [comment]
Since it doesn't look like the original package maintainer is going to update it, I went ahead and made a new PPA for Ubuntu 18.04 and newer. Take a look at #350.
```
sudo add-apt-repository ppa:hsheth2/ppa
sudo apt-get update
sudo apt-get install cava
```
