### ISSUE TITLE
More colors on gradient

### ISSUE THREAD

**Issue by iamsubhranil** [karlstav/cava#229]
Hi.
I love cava, especially its smoothness and everything. But the number of colors in gradient is fixed to 2, which is a real bummer. Can it be increased like cli-visualizer's rainbow scheme?

Edit: I've already been able to modify the code to achieve this. Mind if I send a PR?

![cava](https://i.imgur.com/yVHSSEp.jpg)

[cava2](https://imgur.com/a/yxUMqNz)

**Comment by karlstav** [comment]
Please do!

I remember limiting it to two just because it was a lot easier to code and I didn't think that more was necessary at the time.

**Comment by iamsubhranil** [comment]
actually, doing a generic one is more easier than you think. I have even made it backwards compatible so that it will even provide same results when an older config is used.

**Comment by karlstav** [comment]
added in #230
