### ISSUE TITLE
Time and Date

### ISSUE THREAD

**Issue by jeanluc162** [karlstav/cava#23]
I'd suggest to Show time, date or even both (maybe selectable over arguments) in the Top-Right Corner.

**Comment by anko** [comment]
Seems out of scope.  Cava is a music visualiser, not a clock.  Run it in [tmux][1]?

[1]: http://en.wikipedia.org/wiki/Tmux

**Comment by jeanluc162** [comment]
I'd like the visual Style of cava, and I would like a clock that integrates perfect with it. But maybe you are right, and this isn't something that belongs in this Software.
Anyway, maybe i should try to do it myself.
