### ISSUE TITLE
Error while laoding shared libraries: libtinfow.so.6

### ISSUE THREAD

**Issue by FelipeMarcelino** [karlstav/cava#232]
When I try execute cava in arch linux + i3, the following message appears: 

`cava: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory`

Someone has experienced this issue?

**Comment by karlstav** [comment]
@FelipeMarcelino have you been able to resolve this?

I think the issue might be with arch.

**Comment by karlstav** [comment]
there seems to be some related issue discussed on [AUR](https://aur.archlinux.org/packages/cava/)

**Comment by FelipeMarcelino** [comment]
OK, I will take a look!

**Comment by alackie3** [comment]
I am having the exact same issue and this problem has never been address or fixed. At least form what I have found.

Whenever I run cava, I get this error:

`cava: error while loading shared libraries: libtinfow.so.6: cannot open shared object file: No such file or directory`

**Comment by karlstav** [comment]
hi @alackie3,

make sure ncurses is installed. If the problem persist, you will need to provide more details about your system.

BTW I think the problem is with ncurses on arch. If you are using the package from AUR, try reporting it there.

**Comment by KindaMoody21** [comment]
yay -Sy sndio 
that should work now
