### ISSUE TITLE
Gradient color bug in Konsole

### ISSUE THREAD

**Issue by 6GVp8WcnM9TPDBrw** [karlstav/cava#233]
I don't know why, but the color with gradient are all bugged in Konsole (work fine in "normal" mode), while in gnone-terminal everything is ok

https://i.imgur.com/yOWm66Z.png

Left = Konsole
Right = Gnome Terminal

**Comment by karlstav** [comment]
this is a duplicate of #194 that i closed for some reason. I will reopen that issue and close this.
