### ISSUE TITLE
Reload colors only

### ISSUE THREAD

**Issue by dgrisham** [karlstav/cava#235]
I already started the PR for this at https://github.com/karlstav/cava/pull/234, but wanted to make an issue to go with it.

As stated in the PR, I have an application where reloading the colors only is desirable -- the visualizer bar height is reset on a full config reload, which is a messy transition for something that happens during regular listening. To change this, I made it so that colors only, rather than the entire config, can be reloaded with `SIGUSR2`.

I think this is a generally useful feature for testing colors as well, which is why I decided to see if there was interest in merging this change to the main project.

Also, after considering the options of what key to bind to this feature and realizing that `c` (for **c**olor reload) was already bound to the foreground color cycle function, I decided to make `f` the **f**oreground reload key instead (which nicely mirrors `b` for **b**ackground reload) and use `c` to reload colors. I understand that this is a backwards-incompatible change, so I wanted to make it part of the discussion as well.

Thoughts @karlstav?

**Comment by karlstav** [comment]
Sounds good. Actually the config reload was faster before, but that was because i didn't shut down the audio thread  (or ncurses) correctly, causing a minor memory leak. So I think this is a wanted feature for more people.

I don't think anyone is using the 'c' and 'b' to cycle colors, it was a fun feature i added long before I added custom colors. 

I want to do some testing first, then I will probably merge it soon.

**Comment by dgrisham** [comment]
Yeah, I personally don't cycle colors with those keys either, but I wasn't sure how important that feature was.

And nice, yeah you should definitely test yourself. It's not like I fully understood how the program worked before implementing, I just read enough to get a gist and kept trying things until it worked haha. A more familiar eye is definitely good here.

**Comment by dgrisham** [comment]
Hm, what does a broken terminal look like in your case? I appear to get the same result when I reload with a color config error error regardless of whether I use `SIGUSR2` or `c`. I do get a broken terminal, though, still looking into that.

**Comment by dgrisham** [comment]
@karlstav Okay, after looking at it a bit, here's where I'm at:

The line that reloads colors is [here](https://github.com/karlstav/cava/pull/234/files#diff-10fcdb86aea9ceffa1373be8d7f2b15dR667). If I add a call to `cleanup()` just before that call to `load_config()`, then the broken terminal issue is fixed. However, calling `cleanup()` causes a momentary lag in the output, so the visualizer doesn't show for a moment. This is something I personally would want to be as quick of an update as possible, based on my setup.

The next thing I did was have `load_config()` output a `bool` that signifies whether the config was successfully loaded or not. That way we can run `cleanup()` only when `load_config()` returns `false`. Unfortunately, running `cleanup()` removes the error output that was printed by `load_confg()` (or one of it's sub-functions). So, even though `cava` exits cleanly and the terminal isn't broken afterward, the user is unable to see the error output.

So, to fix this last issue, I figured we could pass a pointer to a string array to `load_config()`, then if there's an error we could fill the array with the error output, return `false` from `load_config()`, then in `cava.c` we would be able to print the error output after we call `cleanup()` whenever `load_config()` returns false.

I'm personally a fan of this proposed refactor, because 1. I like the idea of propagating errors up to the highest level before printing them/exiting, and 2. it provides more flexibility to the code, in a way that also gives a clean implementation of this feature.

What're your thoughts on this approach?

**Comment by karlstav** [comment]
@dgrisham agreed, I did something similar in the pulseaudio input module. There is an  `error_message` string within the `audio_data` struct defined in `fifo.c` and the `audio_data` struct is itself used as a pointer so error messages from the audio thread can be propagated to the main thread.

**Comment by dgrisham** [comment]
:+1: nice, yeah I see that now. I'll make those changes soon.

**Comment by dgrisham** [comment]
Closed by https://github.com/karlstav/cava/pull/234.

**Comment by gldtn** [comment]
Sorry for replying this old issue.. sending SIGUSR2 doesn not update background color. I could only get the background color to apply correctly by sending SIGUSR1 signal. Was this intentional?

Let me know if you would like me to open a new issue!

**Comment by karlstav** [comment]
Hi @gldtn 

This sounds like a regression at some point. Just open a new issue, it's a lot easier to track that way.
