### ISSUE TITLE
Non-moving bars 

### ISSUE THREAD

**Issue by n3wyen** [karlstav/cava#238]
Hello,
Recently started using the Linux partition on my laptop again and it seems cava does not respond to any audio input anymore. I've tried purge autoremove and reinstalling, even installing from source but it seems no matter what I do cava only stays at minimum bar level and is unresponsive to audio input.

**Comment by karlstav** [comment]
look through the readme and the config file then try again. If it still fails you will need to provide more info, in order to resolve the issue.

**Comment by xabispacebiker** [comment]
I have the same problem. I just installed from source. My configuration is an Audiophile card running liquidsoap to broadcast a stream using the ALSA input source. In the config I have set it to alsa which is supposed to grab the audio input by default, but the bars are not moving.

**Comment by karlstav** [comment]
@xabispacebiker, alsa uses loopback interface by default, use `arecord -l` to find a list of your input devices. Is I understand your setup correctly you have to specify the input of your Audiophile card as the source in the cava config file.

**Comment by xabispacebiker** [comment]
I get this error: `unable to set hw parameters: Device or resource busy`

In cava config I have:

```
method = alsa
source = hw:0,0
```
I tried also with hw:0,1


```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Audiophile192 [M Audio Audiophile192], device 0: ICE1724 [ICE1724]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: Audiophile192 [M Audio Audiophile192], device 1: ICE1724 IEC958 [ICE1724 IEC958]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
```

**Comment by karlstav** [comment]
My mistake, cava and liquidsoap can't have the input open at the same time. Take a look at [dsnoop](https://alsa.opensrc.org/Dsnoop), I think it's what you need to solve your issue.
