### ISSUE TITLE
Autobars getting active on raw output

### ISSUE THREAD

**Issue by TilCreator** [karlstav/cava#242]
Even if the the output method is set to raw Cava still checks if the bar count is to big for the ( sometimes not existing ) termial and sets autobars ( internal var that lets Cava set the bar count itself ). That can be really confusing, especially if one is writing a binary parser that suddenly, when requesting more than 67 bars, the output starts rolling.

Quick workaround:
Make bars via config infinitely small:
```ini
[general]
bar_width = 0
bar_spacing = 0
```

Fix suggestion:
Add check for raw output mode in https://github.com/karlstav/cava/blob/c3d75c1d9269210f2755be6bb5de84ee8086ba3f/cava.c#L527-L531

**Comment by karlstav** [comment]
Yes, when using raw output cava should not check those things at all. Maybe there should also be a check in the config to see if number of bars are set manually when using raw output.

I will look at this some time later, @TilCreator If you are interested you could make a PR yourself.
