### ISSUE TITLE
support for Squeezelite

### ISSUE THREAD

**Issue by dnalor** [karlstav/cava#243]
I've written an input module for [Squeezelite](https://en.wikipedia.org/wiki/Squeezelite).
As Squeezelite can export it's audio data as shared memory, it's a simple solution without external dependencies.
If this is of interest, I can contribute it to the project.

**Comment by karlstav** [comment]
cool, just make a PR. I guess I should make some kind of input module contribution guideline. But just make it consistent with the other modules.
