### ISSUE TITLE
No audio after installing CAVA

### ISSUE THREAD

**Issue by elcuevero** [karlstav/cava#245]
Using Cava to drive mpd_oled as instructed here: https://github.com/antiprism/mpd_oled/blob/master/INSTALL_VOLUMIO.md
Had two working raspi volumio environments, did fresh install to ver 2.502. Audio is lost after running make statement.
Bug report at: http://logs.volumio.org/volumio/o1cRaUm.html
This is the output when it breaks:
Making all in iniparser
make[1]: Entering directory '/home/volumio/cava/iniparser'
depbase=echo src/iniparser.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||';
/bin/bash ../libtool --tag=CC --mode=compile gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" -DPACKAGE_STRING="cava\ 0.6.1-13-gc3d75c1" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DHAVE_ALLOCA_H -DALSA -g -O2 -MT src/iniparser.lo -MD -MP -MF $depbase.Tpo -c -o src/iniparser.lo src/iniparser.c &&
mv -f $depbase.Tpo $depbase.Plo
libtool: compile: gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" "-DPACKAGE_STRING="cava 0.6.1-13-gc3d75c1"" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DHAVE_ALLOCA_H -DALSA -g -O2 -MT src/iniparser.lo -MD -MP -MF src/.deps/iniparser.Tpo -c src/iniparser.c -fPIC -DPIC -o src/.libs/iniparser.o
libtool: compile: gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" "-DPACKAGE_STRING="cava 0.6.1-13-gc3d75c1"" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DHAVE_ALLOCA_H -DALSA -g -O2 -MT src/iniparser.lo -MD -MP -MF src/.deps/iniparser.Tpo -c src/iniparser.c -o src/iniparser.o >/dev/null 2>&1
depbase=echo src/dictionary.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||';
/bin/bash ../libtool --tag=CC --mode=compile gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" -DPACKAGE_STRING="cava\ 0.6.1-13-gc3d75c1" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DHAVE_ALLOCA_H -DALSA -g -O2 -MT src/dictionary.lo -MD -MP -MF $depbase.Tpo -c -o src/dictionary.lo src/dictionary.c &&
mv -f $depbase.Tpo $depbase.Plo
libtool: compile: gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" "-DPACKAGE_STRING="cava 0.6.1-13-gc3d75c1"" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DHAVE_ALLOCA_H -DALSA -g -O2 -MT src/dictionary.lo -MD -MP -MF src/.deps/dictionary.Tpo -c src/dictionary.c -fPIC -DPIC -o src/.libs/dictionary.o
libtool: compile: gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" "-DPACKAGE_STRING="cava 0.6.1-13-gc3d75c1"" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DHAVE_ALLOCA_H -DALSA -g -O2 -MT src/dictionary.lo -MD -MP -MF src/.deps/dictionary.Tpo -c src/dictionary.c -o src/dictionary.o >/dev/null 2>&1
/bin/bash ../libtool --tag=CC --mode=link gcc -std=gnu99 -g -O2 -version-info 4 -o libiniparser.la -rpath /usr/local/lib src/iniparser.lo src/dictionary.lo -lpthread -lasound -lm -lfftw3
libtool: link: gcc -shared -fPIC -DPIC src/.libs/iniparser.o src/.libs/dictionary.o -lpthread -lasound -lm -lfftw3 -O2 -Wl,-soname -Wl,libiniparser.so.4 -o .libs/libiniparser.so.4.0.0
libtool: link: (cd ".libs" && rm -f "libiniparser.so.4" && ln -s "libiniparser.so.4.0.0" "libiniparser.so.4")
libtool: link: (cd ".libs" && rm -f "libiniparser.so" && ln -s "libiniparser.so.4.0.0" "libiniparser.so")
libtool: link: ar cru .libs/libiniparser.a src/iniparser.o src/dictionary.o
libtool: link: ranlib .libs/libiniparser.a
libtool: link: ( cd ".libs" && rm -f "libiniparser.la" && ln -s "../libiniparser.la" "libiniparser.la" )
make[1]: Leaving directory '/home/volumio/cava/iniparser'
make[1]: Entering directory '/home/volumio/cava'
gcc -std=gnu99 -DPACKAGE_NAME="cava" -DPACKAGE_TARNAME="cava" -DPACKAGE_VERSION="0.6.1-13-gc3d75c1" -DPACKAGE_STRING="cava\ 0.6.1-13-gc3d75c1" -DPACKAGE_BUGREPORT="karl@stavestrand.no" -DPACKAGE_URL="" -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_PTHREAD_H=1 -I. -DPACKAGE="cava" -DVERSION="0.6.1-13-gc3d75c1" -D_POSIX_SOURCE -D _POSIX_C_SOURCE=200809L -Iiniparser/src -DHAVE_ALLOCA_H -DALSA -std=c99 -Wall -Wextra -Wno-unused-result -Wno-maybe-uninitialized -g -O2 -MT cava-cava.o -MD -MP -MF .deps/cava-cava.Tpo -c -o cava-cava.o test -f 'cava.c' || echo './'cava.c
In file included from cava.c:69:0:
config.c: In function 'load_config':
config.c:337:25: warning: initialization from incompatible pointer type
struct error_s *error = (struct error *)err;
^
mv -f .deps/cava-cava.Tpo .deps/cava-cava.Po
/bin/bash ./libtool --tag=CC --mode=link gcc -std=gnu99 -std=c99 -Wall -Wextra -Wno-unused-result -Wno-maybe-uninitialized -g -O2 -L/usr/local/lib -Wl,-rpath /usr/local/lib -o cava cava-cava.o -liniparser -Liniparser/.libs -lpthread -lasound -lm -lfftw3
libtool: link: gcc -std=gnu99 -std=c99 -Wall -Wextra -Wno-unused-result -Wno-maybe-uninitialized -g -O2 -Wl,-rpath /usr/local/lib -o .libs/cava cava-cava.o -L/usr/local/lib /home/volumio/cava/iniparser/.libs/libiniparser.so -Liniparser/.libs -lpthread -lasound -lm -lfftw3
make[1]: Leaving directory '/home/volumio/cava'
volumio@volumio:/cava$ sudo make install
[sudo] password for volumio:
Making install in iniparser
make[1]: Entering directory '/home/volumio/cava/iniparser'
make[2]: Entering directory '/home/volumio/cava/iniparser'
/bin/mkdir -p '/usr/local/lib'
/bin/bash ../libtool --mode=install /usr/bin/install -c libiniparser.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libiniparser.so.4.0.0 /usr/local/lib/libiniparser.so.4.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libiniparser.so.4.0.0 libiniparser.so.4 || { rm -f libiniparser.so.4 && ln -s libiniparser.so.4.0.0 libiniparser.so.4; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libiniparser.so.4.0.0 libiniparser.so || { rm -f libiniparser.so && ln -s libiniparser.so.4.0.0 libiniparser.so; }; })
libtool: install: /usr/bin/install -c .libs/libiniparser.lai /usr/local/lib/libiniparser.la
libtool: install: /usr/bin/install -c .libs/libiniparser.a /usr/local/lib/libiniparser.a
libtool: install: chmod 644 /usr/local/lib/libiniparser.a
libtool: install: ranlib /usr/local/lib/libiniparser.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/lib
Libraries have been installed in:
/usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:

add LIBDIR to the `LD_LIBRARY_PATH' environment variable
during execution
add LIBDIR to the `LD_RUN_PATH' environment variable
during linking
use the `-Wl,-rpath -Wl,LIBDIR' linker flag
have your system administrator add LIBDIR to `/etc/ld.so.conf'
See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/volumio/cava/iniparser'
make[1]: Leaving directory '/home/volumio/cava/iniparser'
make[1]: Entering directory '/home/volumio/cava'
make[2]: Entering directory '/home/volumio/cava'
/bin/mkdir -p '/usr/local/bin'
/bin/bash ./libtool --mode=install /usr/bin/install -c cava '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/cava /usr/local/bin/cava
/bin/mkdir -p '/usr/share/consolefonts'
/usr/bin/install -c -m 644 cava.psf '/usr/share/consolefonts'
make[2]: Leaving directory '/home/volumio/cava'
make[1]: Leaving directory '/home/volumio/cava'

**Comment by karlstav** [comment]
looks like a good install. Doesn't make sense that the audio is lost after running make. Your issue is probably with volumio.
