### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Leviathan220** [karlstav/cava#246]
So I've been working on a shell script for configuring cava. If you would like to include it into cava once I'm done with it you're more than welcome to. However I'm not sure of all the values used in configuring cava. Like I know ehat values I use in configuring cava to my pleasing but I'm not sure of all of the possible ones or what each one does. I can include a copy of my script if you would like. Be warned it is about 60-70% done it completely functions. I just wanted to be able to configure each value through my shell script as well as set up a proper default config since the cava one comes blank.

**Comment by Leviathan220** [comment]
Sorry for poor punctuation it's not my strong suit but I'd love to help improve cava as it's something that runs 24/7 on my laptop.

**Comment by karlstav** [comment]
> since the cava one comes blank.

The config is not supposed to be blank. The file `example_files/config` contains all values and explains what they do. It is supposed to be copied to your config dir when running the `autogen.sh` script.

**Comment by Leviathan220** [comment]
Hey sorry it took a few days to respond. I fount the `example_files/config`. I did not use any sort of `autogen.sh` to run cava. Although I suppose that doesn't matter since the default values are commented out. I work to complete my script for configuring cava. It's more for a test to see if you like your config before choosing to save it. It works especially well if you like running multiple differently configured instances of cava like I do. I'll send it to you after I complete all the code for configuring each setting. Now that I have a more detailed config than my blank one it shouldn't take too long.
