### ISSUE TITLE
Cava causes pulseaudio %cpu to jump from ~1-3% to ~20-22% 

### ISSUE THREAD

**Issue by naterich2** [karlstav/cava#247]
When I am not running cava, my pulseaudio process hangs around 1-3% cpu, however, when I start running cava, it jumps and stays around 19%-23%., on top of that the cava process uses another 10-15% which I expected, but I didn't expect the change to the pulseaudio process.  I have also tried the cli-visualizer, which it seems is based on cava.  I like the look of cava better and would prefer to use cava, but cli-visualizer seems to have better cpu performance, both in the process itself, and cli-visualizer does not cause my pulseaudio to jump nearly as much (~6-9% cpu while in use).

I have also tried reducing the framerate from 60 to 30.

Details:

Arch linux 4.19.4
pulseadio 12.2
cava 0.6.0 (output of `cava -v`, but output of `pacman -Qs cava` is `local/cava 0.6.1-1`) 
config: [pastebin](https://pastebin.com/40Xxk8XN)

**Comment by karlstav** [comment]
I think cli-visualizer would use slightly less cpu in itself as it doesn't have as high resolution as cava. But pulseaudio cpu usage should be about the same. This is an issue that i have to look into. I have noticed the cpu usage before, but I thought it was just normal. 

Thanks for the heads up!

**Comment by karlstav** [comment]
@naterich2 no I don't think the thread is the problem. However, I played around with the buffer size and I think that cava is reading from the audio stream more often then necessary. 

I created a branch where the buffer is increased from 1024 bytes to 4096 bytes. I was afraid that this would create a noticeable latency, but it looks good. Do you mind testing it before I merge it to the master branch?

**Comment by karlstav** [comment]
@naterich2 thanks that would be great. Since I don't have any automated testing, I need all the testing I can get.

**Comment by karlstav** [comment]
merged fix `iss247`
