### ISSUE TITLE
Cava stopped visualzing for pulse audio

### ISSUE THREAD

**Issue by sumdog** [karlstav/cava#248]
I had been using Cava (from the gentoo/vampire overlay) and suddenly I stopped getting visualizations. I'm not sure exactly what updated when that happened (maybe pulseaudio?) I've tried checking it out from source and building it as well. If I look in pavucontrol, cava does show up in the recording tab with the monitor set to my device (HDMI/monitor output). I tried it with a USB output as well as still no visualization. If I set it to my Scarlet Microphone, I do get input/visual off of that and output when I pump audio to the microphone connected to it, so it works on some devices, just not any of my primary output devices.

Versions:
pulseaudio 12.2
gcc 7.3.0-r3
cava 29fb506 (build from source with enable-legacy_iniparser; get compile errors without it)

Is there a way to enable more debugging? I literally just get flat bars in cava on my main audio device.

**Comment by karlstav** [comment]
hi @sumdog , can the monitor interface be muted?

I haven't tested cava with pulseaudio 12 myself, but it was released 2018-06-20. Ubuntu 18.04 uses 11, 19.10 uses 12. Arch has of course been using 12 for quite some time, so I doubt there is a problem there. But you never know.

**Comment by sumdog** [comment]
![selection_216](https://user-images.githubusercontent.com/156601/50180845-58561380-02d0-11e9-93d2-6c643565d259.png)

Yep it's unmuted. I'm on Gentoo and it looks like it updated from Pulse 11.1 on 12/3. I downgraded it and killed/restarted pulse and it still doesn't work though. 

Cava still works for my webcam, The Scarlet microphone and even when using the Scarlet as an output (via its headphones), just not with the HDMI or Avantree (Avantree is a USB audio device to bridge to Bluetooth).

The monitor bar in pavucontrol doesn't move at all in the record tab, so I think the issue is with pulseaudio. I'll just switch to the mpd fifo for now.

**Comment by karlstav** [comment]
the output of `pacmd list-sinks` and `pacmd list-sources`, might point us in the right direction here.

It is possible to enable debug mode as a config option. But I haven't maintained it in a while, so I don't know how much help it will be. 

You will have to enable legacy iniparser also:

```
./configure --enable-legacy_iniparser --enable-debug
``` 


not 100% sure if that is how you enable more options.
