### ISSUE TITLE
Stable cava package is now in AUR

### ISSUE THREAD

**Issue by ghost** [karlstav/cava#25]
https://aur.archlinux.org/packages/cava/

If it gets 10 votes it'll be (probably) moved to `community` repo.

**Comment by livibetter** [comment]
In the `PKGBUILD`, I believe you can skip that `sed` using just:

```
make VERSION="${pkgver}"
```

Never wrote `PKGBUILD` before, I guess it's like shell scripting, right? Anyway, you get the idea.

**Comment by CelestialWalrus** [comment]
Oh yeah, forgot about that.

**Comment by CelestialWalrus** [comment]
@livibetter uploaded 0.2.0 to AUR and changed that sed to `make VERSION=`, thanks.

**Comment by CelestialWalrus** [comment]
Updated to 0.3.1.

**Comment by dylanaraps** [comment]
Both aur packages are broken and have been for at least a month now. There are working PKGBUILDS in the aur comments but CelestialWalrus hasn't been active for a while now so the official PKGBUILDS remain broken.

**Comment by CelestialWalrus** [comment]
@dylanaraps https://aur.archlinux.org/packages/cava/ works and https://aur.archlinux.org/packages/cava-git/ should work (tested it few weeks ago).

**Comment by dylanaraps** [comment]
I just tried again and it worked this time. I don't know why both packages failed to install when I commented a few days ago.

Disregard my comments.

**Comment by chelovechishko** [comment]
Isn't this supposed to be closed?

**Comment by karlstav** [comment]
I suppose, first I thought it could be nice to have it open if there where any issues with the package, but I guess that's what the AUR page is for.
