### ISSUE TITLE
My little test with c.a.v.a. ✍(◔◡◔)

### ISSUE THREAD

**Issue by AkibaIllusionLinux** [karlstav/cava#250]
( ◑‿◑)ɔ┏🍟--🍔┑٩(^◡^ )

![dmovie20181231140509](https://user-images.githubusercontent.com/44012887/50565436-3a8fa200-0d05-11e9-9dda-6fe0bf6150eb.jpg)

![dmovie20181231140558](https://user-images.githubusercontent.com/44012887/50565463-71fe4e80-0d05-11e9-963c-10491852b498.jpg)

https://youtu.be/nAahXt3xXp8

https://youtu.be/lM9UILjultY

**Comment by karlstav** [comment]
looks nice, not really an issue though. maybe something fro the wiki?

**Comment by AkibaIllusionLinux** [comment]
I really liked the effect I got with c.a.v.a.  I only showed  😆😋  I wish you to continue your project.
