### ISSUE TITLE
no bars for noise

### ISSUE THREAD

**Issue by SermirGerkan** [karlstav/cava#252]
Hi,
Thanks for cava! I use your program to display audio of the microphone input. When I play music everything is great. However, when I mute the input, the bars disappear first. So far so good. After some time, I think noise is "amplified" by the autosense, so that after some time the bars increase towards MAX, although no real signals are played. Smallest sounds or noise are displayed. Is there a lower threshold for the volume, which I can adjust to ignore very quiet sounds, or which do not adjust the autosensing down.

regards,
Semir

**Comment by karlstav** [comment]
hi @SermirGerkan , glad to hear you like my program. 

First of all, can I ask why you use the microphone to capture audio? If you use pulseaudio it is easy to capture audio directly from the output. Just read the readme.

On to you question, it is theoretically possible to implement a threshold for minimum volume for cava to respond to, but it would require some programming. I think it would be easier for you to just disable `autosens` in the config and adjust the sensitivity manually.

**Comment by SermirGerkan** [comment]
I would like to use cava in RAW mode to visualize music from different phones with an LED matrix. To do this, cava runs on a Raspberry, with a USB sound card. The problem now is that autosensing interprets even the smallest noises. Manually adjusting the sensitivity is not really practical, as the output levels of the various devices may be different.

**Comment by karlstav** [comment]
I tried playing around with some threshold values, but it messes up everything. It would be far too complex to implement what you need in cava. 

You could try [noise reduction](https://askubuntu.com/questions/18958/realtime-noise-removal-with-pulseaudio), but I don't know if it will solve your problem.

maybe you could make a script that changes the sensitivity in cava depending on what source you are using.
