### ISSUE TITLE
Invalid cast in config.c

### ISSUE THREAD

**Issue by EmilGedda** [karlstav/cava#253]
https://github.com/karlstav/cava/blob/e163ba5440e0d9e4172e0dd780fd7f4aaa7c2350/config.c#L346

Should be cast to `error_s` and not `error` I presume.
However, in C void pointers have implicit conversion to and from all other pointer types, so no cast is needed when going from `void*` to `T*` for any type T.

**Comment by karlstav** [comment]
yes it probably should, it is done correctly in the other functions:

https://github.com/karlstav/cava/blob/e163ba5440e0d9e4172e0dd780fd7f4aaa7c2350/config.c#L132

Probably should be fixed, even if it is not needed, just for the sake of consistency.
