### ISSUE TITLE
Document raw output mode

### ISSUE THREAD

**Issue by neagle** [karlstav/cava#254]
I'm happy to create a PR for this myself, soon, but I wanted to see if you'd be open to having the README document the raw output feature of Cava. I've been trying to create a custom visualizer using RGB LEDs attached to a FadeCandy, and I got it working last night due entirely to the tremendously useful way that Cava's raw output mode works. But I had to dig into issues to figure out a) that it existed, and b) how to use it.

**Comment by karlstav** [comment]
by all means please do. It is however documented in the config file:

https://github.com/karlstav/cava/blob/e163ba5440e0d9e4172e0dd780fd7f4aaa7c2350/example_files/config#L67-L70

https://github.com/karlstav/cava/blob/e163ba5440e0d9e4172e0dd780fd7f4aaa7c2350/example_files/config#L78-L93

line 69 is not correct anymore though, as it can be ascii or 8 bit also now.

I decided some time back to make the config file the main source of documentation, but maybe there is nothing wrong in also having some more documentation in the README. There should at least be something in the README that states clearly that things are documented in the config file and that the config file is also in the `example_files`directory if it is not in `XDG_CONFIG_HOME/cava/config` or `$HOME/.config/cava/config`

**Comment by neagle** [comment]
Your goal of using the config file as documentation makes sense; I should have acknowledged that the road for using `raw output` got very smooth once I found my way to the actual config file, because the documentation present in the comments was great.

I think it would be useful for future people like me to just make the path to finding that config file a little smoother. I've also taken the liberty of highlighting the raw output mode explicitly in my PR; to me, it's a big deal, worth highlighting in that way, but I respect that from your perspective it's a relatively minor and novel feature you added purely because someone asked for it. You can decide whether to use that part.
