### ISSUE TITLE
Config file not working

### ISSUE THREAD

**Issue by gabrielmmoraes** [karlstav/cava#257]
Cheers! I recently installed cava but it seems the config file is not working. I change colors, sensitivity and nothing happens. I thought at first it should have something to do with my konsole configurations but I just installed gnome-terminal and the config file is not working there either.

I also tried reinstalling from pacaur and from git but nothing changed. The program runs but the config file (it exists as ~/.config/cava/config) doesn't change anything from the application.

Thanks in advance.

**Comment by Yash-Garg** [comment]
Works fine here on Arch

**Comment by karlstav** [comment]
@gabrielmmoraes first of all are you sure you have removed the semicolon `;`in front of the parameter you are trying to change?

**Comment by gabrielmmoraes** [comment]
Oops. Thank you.

**Comment by Yash-Garg** [comment]
Mind closing it lol?
