### ISSUE TITLE
Cava tearing on ST with multiple fonts

### ISSUE THREAD

**Issue by igniscyan** [karlstav/cava#261]
I just got around to installing Cava on my new system, and am encountering a weird bug with tearing I've never experienced.

I'm currently using Suckless Terminal with Fira Code font, size 10. Config is set to default. 

Whenever I launch cava, I get frequent (almost on a one second interval) tears in the bars. I've also tried using alacritty just now, and even without transparency set with compton, the tears still happen. I'm assuming this has something to do with ncurses, but after searching around the issues page I haven't found anything that applies to me.

**Comment by karlstav** [comment]
have you checked out #196?

**Comment by igniscyan** [comment]
> have you checked out #196?

I have, none of the included methods worked for me. 
![image](https://user-images.githubusercontent.com/26984470/52515562-554e1400-2beb-11e9-9315-9b5eaa36d422.png)

This is an image of my config after tweaking the ncurses portion of config. Messing with the frame rate and related display stuff didn't work as well. Weirdly enough, it doesn't even seem like Cava is listening to my preference for the number of bars, either! I have it set to 10, but I'm getting way more than 10, and they're all split down the middle for some odd reason.

**Comment by karlstav** [comment]
Could you test to change color? Just to make sure the config is being read. It looks a lot like the previous issues, that I unfortunately still has not found the cause of. But a workaround is to use the legacy "noncurses" output.

**Comment by igniscyan** [comment]
Don't know why I didn't think to just do this in the first place but... Uninstalling an Reinstalling Cava fixed the issue for me.

**Comment by karlstav** [comment]
strange, do you know if it is now running with ncurses?

**Comment by igniscyan** [comment]
> strange, do you know if it is now running with ncurses?

Sorry for the long delay, somehow hadn't seen your reply. I just checked the config, and I did end up having to use `noncurses` to get the tearing to go away it seems. For some reason it just wasn't reading from config prior.

**Comment by karlstav** [comment]
Then this is probably the same as #196.
