### ISSUE TITLE
[Feature request] Add select channel as parameter or config

### ISSUE THREAD

**Issue by lexasub** [karlstav/cava#265]
I want select channel in config(or arg of program)(ex: channel:1)

**Comment by karlstav** [comment]
This has been on the todo list for some time. So I appreciate the initiative. However, I don't think defining it at compile time is a good idea. It definitely needs to be a config option. Maybe something called "mono channel", that could be `right`, `left` or `average`.  

Also, I think I should move some of the channel processing from the separate input modules to [here](https://github.com/karlstav/cava/blob/6f46ca1d033f89d332c8c0a8f6abc699aa71bf6d/cava.c#L704)  in cava.c . So the different input modules only populate the `audio out left` and `audio out right` buffers. While cava.c handles if it uses left, right, both or create a separate "average" buffer.

I am short on time, but hope to get around to this eventually. If someone else wants to have a go, please do!

**Comment by nocturneop15** [comment]
that will be great - I started to make some modifications for https://github.com/antiprism/mpd_oled/, which uses cava. One of my goals is to get multiple i2C displays working together with split-channel spectrum analyzer. Having direct support of single-channel spectrum in cava will make it easy

**Comment by karlstav** [comment]
done for all now
