### ISSUE TITLE
Config with Mopidy

### ISSUE THREAD

**Issue by unolee** [karlstav/cava#266]
I would like to make it work with Mopidy (I thought it works with MPD) to see at CAVA console ($ sudo cava)

So, I made config like below... but NOT working. Maybe I have to config at Mopidy not mpd.

Anyone have experience for that?

$ sudo nano /etc/mpd.conf 

audio_output {
    type     "fifo"
    name     "my_fifo"
    path     "/tmp/mpd.fifo"
    format   "44100:16:2"
}

$ sudo nano ~/.config/cava/config 

method = fifo
source = /tmp/mpd.fifo

**Comment by unolee** [comment]
Currently thi is my mopidy config 

[audio]
mixer = software
mixer_volume = 
output = autoaudiosink
buffer_time = 

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u

**Comment by karlstav** [comment]
I have not used mopidy in many years, but IIRC mopidy includes its own MPD server. So you are correct in saying 

> Maybe I have to config at Mopidy not mpd.

You would have to configure the audio in mopidy so it can be picked up by cava, either with pulseaudio or also. I would recommend to try pulseaudio first.

**Comment by unolee** [comment]
Thank you for your comment. Now I am trying with alsa because sometimes I want to play some apps at same time. (Mopidy, Shairport ... )
 
However, it couldn't show any bar moving. I am using text console from Mac os.

**Comment by karlstav** [comment]
sorry for not replying to this @unolee , simply forgot. However, there is not much to go on here. Mac os? are you running cava through ssh? that will never look any good.
