### ISSUE TITLE
Cava forground colors not changing

### ISSUE THREAD

**Issue by thespyboss** [karlstav/cava#267]
When i use Cava, i can change the background but not the foreground. B on the keyboard is for the background but i know f is for the foreground but when i hit f, the bars color does not change. Do i have to change something with the config settings? Also, I am using Solus budgie.

**Comment by karlstav** [comment]
@thespyboss 'f' should work fine, just tested it. However it does not work if gradient is enabled.

**Comment by thespyboss** [comment]
How would i disable gradient or how to change the cava forground using the config file

**Comment by karlstav** [comment]
https://github.com/karlstav/cava#configuration
