### ISSUE TITLE
add config option for FFT input array size

### ISSUE THREAD

**Issue by karlstav** [karlstav/cava#268]
as discuses briefly in #260, it could be interesting to add a config option for FFT input array size.

I already tested increasing this from the default 2048 to 8192 in the new `samplesizer` and the output of lower frequencies is notably better, however the cpu usage did increase about 1.6%.

@nikp123 do you care testing this out (only works on pulseaudio as of now)?

**Comment by nikp123** [comment]
while this does work, the balancing is way off

this is referring to the loop at cava.c (at line 624-628)

k is not properly calculated as lower frequencies tend to be lower than high ones at the same volume

I used an online generator for my testing: https://www.szynalski.com/tone-generator/

Anyway, you have two solutions:
1) figure out how to actually properly calculate that value
2) add eq_balance as a config option as i did

and changing the EQ does indeed throw the EQ balance WAY off (I'm using my code for testing this)

**Comment by nikp123** [comment]
and by increasing the fft size you'll also get lower values (so you'd need to raise sens again)

This is because by making the spectrum wider there is more values being averaged out thus making the end result lower.

I hope I mentioned everything I need to.

**Comment by nikp123** [comment]
and alsa does work but loopback doesnt seem to work :thinking:

**Comment by karlstav** [comment]
alsa would still work, but only use a quarter of the audio buffer. 

All this can be fixed by adjusting how k is calculated. However the calculation of k is a big mess as it was figured out by intense trial and error, I was literally just throwing math into that thing until I got it to look the way I wanted. Now I have to throw some more math into it. It already uses the input buffer size as a factor(`M`). But maybe I have to square it? or square root?  Log.. who knows. No time to look at it know i'm afraid

**Comment by nikp123** [comment]
well the thing is that it could be solved by brainstorming more solution until one hits

**Comment by karlstav** [comment]
I did some re-calibrations, does it look better?

**Comment by nikp123** [comment]
seperate FFTs for freq ranges wont fix the delay (unless you plan to time them differently in which case it would end up complicating everything by having to mix different FFTs at different times)

STFT is nice because its a continuous function, it allows for it to be given a small buffer (ie 1024 or even 2048) which would produce a higher resolution output since it combines the past results i.e. its a continuous function

Or if that doesnt work out we can try something similar ourselves, fxp. we can run a few small audio buffers and create a large FFT out of them. And just contantly move the whole buffer back by one whole "buffer timeframe" and fill the end with a new one and run the FFT.

**Comment by karlstav** [comment]
> unless you plan to time them differently in which case it would end up complicating everything by having to mix different FFTs at different times

that was my plan yes



> which would produce a higher resolution output since it combines the past result

if it uses past results, how will it avoid the problem of delay?



> we can run a few small audio buffers and create a large FFT out of them. And just contantly move the whole buffer back by one whole "buffer timeframe" and fill the end with a new one and run the FFT again.

that is exactly what i do today, if you look at [pulse.c](https://github.com/karlstav/cava/blob/611a2daddf6dc8692ffbc7059973c4faff389c79/input/pulse.c#L154), it reads 4096 bytes which is only 1024 samples (two channels, 16-bits per sample), and then populates the the FFT buffer `audio->audio_out_l[n]` which is 2048 samples. When the sample buffer is full it starts at the beginning of the array again. This is run in in a separate thread parallel with the FFT, so the FFT doesn't wait for the audio. 

Earlier the pulse input read a lot smaller samples, but the cpu usage was high and 1024 samples is still only 23ms with 44100 sample rate, so it the delay not noticeable.  Reading the whole 2048 samples with 46ms delay would probably work just fine. However I just realized that I did set the default fft buffer in the new branch to 4096 samples, which would probably create a noticeable delay if it had to wait.

Since the reading of audio in to the buffer and the FFT of the same buffer is done asynchronous I could easily have three different buffer sizes and three different FFTs. The hardest thing would be to splice them together in the same array for drawing as the output buffers from the FFTs would be of different sizes.

**Comment by nikp123** [comment]
thats what i was worried about, you need to sync up the output. possibly just split it into a configurable amount of different buffers idealy

if that works that would be great

just split the frequency calc loop into different parts and hope that syncronization errors (unlikely but can happen) dont happen

**Comment by karlstav** [comment]
this would be better to leave as is. I was already able to implement separate FFTW for bass, midtones and treble.
