### ISSUE TITLE
"â" instead of bars in urxvt

### ISSUE THREAD

**Issue by BurnyBoi** [karlstav/cava#271]
I've been using cava on a regular basis for around a year now, but I recently did a reinstall of my OS, and am noticing an issue. 

Previously, I would start urxvt, run cava, and it would look as expected (with solid bars). However, now when I start cava using urxvt, I get "â" characters in place of where the bars should be. 

Screenshot: https://imgur.com/a/wpiljVf

Any suggestions on how I can get urxvt to show the bars like before? I am able to get the bars on the TTY using cava.psf. It's just my terminal emulator that's having this issue. This is also happening with xterm and xfce4-terminal.

**Comment by Bfgeshka** [comment]
Have you set system locale already?

**Comment by BurnyBoi** [comment]
I believe so. In my /etc/locale.gen, I ensured that only `en_US.UTF-8 UTF-8` is uncommented, I ran `locale-gen`, ran `echo LANG=en_US.UTF-8 > /etc/locale.conf`, and finally `export LANG=en_US.UTF-8`

**Comment by BurnyBoi** [comment]
Oh wow....I missed one step. I just rebooted and now it works. Sorry, I never usually power off my desktop and didn't think that was needed.
