### ISSUE TITLE
Gradient broken in Konsole

### ISSUE THREAD

**Issue by gwentoo** [karlstav/cava#272]
Alright so i've used cava for a long time, but im  quite interested in getting the gradient working.
Whenever i enable it (trough custom configuration or the default one available on the wiki, i get this result : 
![gradient](https://user-images.githubusercontent.com/48619398/57972804-b7af7100-799f-11e9-8123-73e3a9ad9701.png)
(left is the relevent confg part, right the results)

Could anybody help ? it seems to be a true-color issue but i am unsure.

**Comment by gwentoo** [comment]
I should also note that it works fine under URxvt, only konsole gives this issue.

**Comment by karlstav** [comment]
It's a konsole issue look at #194
