### ISSUE TITLE
[Feature request] Amplitude mode instead of FFT

### ISSUE THREAD

**Issue by joshuah345** [karlstav/cava#273]
would like a mode for average amplitude (based on FFT)

**Comment by karlstav** [comment]
you have to be more specific

**Comment by joshuah345** [comment]
https://github.com/Nepeta/MitsuhaXI/blob/master/MSHJelloView.mm

i wish i could be more specific, this link is for an implementation of this on ios
unfortunately its in objective-c

you should focus on the math here

http://p5js.org/reference/#/p5.FFT

this is another reference (processing 5). what im looking for is similar to `waveform()`

(i dont know how to code a thing)

**Comment by karlstav** [comment]
I think I got it. Time domain instead of frequency domain. I will take a look at it if I find time.

**Comment by karlstav** [comment]
closing this as I don't really think it applies. Will not look very good anyway.
