### ISSUE TITLE
Multiple outputs

### ISSUE THREAD

**Issue by g3n35i5** [karlstav/cava#274]
I would like to know if it is possible to display the output of cava both in the console (ncurses) and process it as raw output at the same time?

**Comment by karlstav** [comment]
Not in the same instance. But you can always run multiple instances of cava at the same time.

**Comment by g3n35i5** [comment]
Thank you very much for the quick answer. That was also a workaround I used, I just hoped there would be a more elegant solution. But that makes the issue obsolete, so I close it.
