### ISSUE TITLE
Gradient causes a row of blocks with a slight offset in st 0.8.2

### ISSUE THREAD

**Issue by ruifm** [karlstav/cava#277]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/7440273/60968254-e94c1500-a31c-11e9-8b5b-faee22c1caf2.png)

|system | version|
|-----------|------------|
|kernel | 4.15.0-53-generic|
|os | Ubuntu 16.04 Xenial|
|terminal emulator | st 0.8.2|
|shell | bash 4.3.48(1)-release |
|Window Manager | i3 4.16.1|
|compositor | none |
|cava | 0.6.0-1 (from ubuntu repos)|

cava config:
```
## Configuration file for CAVA. Default values are commented out. Use either ';' or '#' for commenting.

# Gradient mode, only hex defined colors are supported, background must also be defined in hex
# or remain commented out. 1 = on, 0 = off. Warning: for certain terminal emulators cava will
# not able to restore color definitions on exit, simply restart your terminal to restore colors.
gradient = 1
```

**Comment by karlstav** [comment]
is this only in `st`? I can't reproduce in other terminal emulators and I'm not able to get gradient working in st on manjaro.

**Comment by ruifm** [comment]
I do not have this issue in `st` when using my arch personal laptop. Which is weird because they have the exact same cava versions and the exact same st build (I build it from source).

In my work laptop (ubuntu 16) where this issue occurs, only `st` has this issue, it works fine in gnome-terminal.

I've tried rebuilding st, same result. I am really out of ideas. Maybe the issue is related to an outdated dependency of either st or cava in Ubuntu? It is really strange that I have no issue with the exact same setup in arch.

**Comment by ruifm** [comment]
@karlstav don't sweat it to much, it is really no big deal. It's a minor graphical artifact that I can live with xD. I only opened the issue because others might have it and maybe one day it will have an easy fix.

**Comment by karlstav** [comment]
I think it must be a bug in that version of st. But I agree, would not use that much time on it since it is so hard to reproduce.
