### ISSUE TITLE
Raspberry Pi 4 Setup

### ISSUE THREAD

**Issue by Zerthick** [karlstav/cava#279]
I am trying to set up Cava on a Raspberry Pi 4 so that all audio played on the device (for example a YouTube video in the browser) is played on output sent through the pi's hdmi connection and captured by Cava.

I initially tried installing pulseaudio on the Pi and using the pulse audio method.  This worked, however the audio was very choppy, even after setting the pulse audio sample method to trivial.  I then tried to get the alsa method to work.  I was able to create the loopback interface following the instructions provided, however I am unable to get audio to play through both the loopback interface so that cava can capture it, while still being sent to the hdmi output.  I tried using the example `asound.conf` file, but it didn't seem to have any effect.  When I select a sound card in the raspbian desktop gui I can either select the loopback interface (in which case cava will work but audio will not be sent out through hdmi) or I can select the bcm2835 ALSA card (in which case audio will be sent to hdmi but cava won't be able to capture it) any tips?

**Comment by karlstav** [comment]
I haven't been able to make it work with HDMI myself. There is an issue about this already, might be closed.

**Comment by Zerthick** [comment]
*Update:* I got pulseaudio to work using the fix described here: https://ubuntu-mate.community/t/skipping-choppy-audio-on-raspberry-pi-3-running-ubuntu-mate-16-04/7275/12 😄
