### ISSUE TITLE
Disable "smoothing"

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [karlstav/cava#280]
I have no idea what to call this, so I'm just calling it "smoothing".

Basically, Cava is running at 4 frames per second, despite me having it set to 60fps. How would I be able to get it to operate more like PulseEffect's visualizer? 

[Here](https://marshmellosucks.github.io/folders/random/simplescreenrecorder-2019-08-22_22.20.12.mp4)'s a video showing what I mean.

**Comment by karlstav** [comment]
That doesn't look like 4 fps, but I know what you mean. Fps is mostly depending on the terminal emulator and the size of the window. What terminal emulator are you using? I would recommend xterm or kitty.

**Comment by MarshmelloSUCKS** [comment]
> That doesn't look like 4 fps, but I know what you mean. Fps is mostly depending on the terminal emulator and the size of the window. What terminal emulator are you using? I would recommend xterm or kitty.

Sorry for not responding. The shell is `bash 5.0.3`.

**Comment by karlstav** [comment]
The shell is not important, only the terminal software.

**Comment by karlstav** [comment]
sorry for not responding sooner @MarshmelloSUCKS, but I don't get a notification when you edit. 

Could you try xterm or kitty and tell me hoe it looks?
