### ISSUE TITLE
Does not create ~/.config if it doesn't exist.

### ISSUE THREAD

**Issue by LasseF-H** [karlstav/cava#283]
If  ~/.config doesn't exist cava prints the following error:
`Unable to access config '/home/user/.config/cava/config', exiting...`

However if it does exist, it creates ~/.config/cava just fine and copies the example config into it. Granted it's not a situation a lot of users are likely to encounter, as their DE/WM probably will have created ~/.config before they run cava for the first time.

**Comment by karlstav** [comment]
the `autogen.sh` script do use the -p option 

https://github.com/karlstav/cava/blob/80c4064fb16d0da10d817b9f969522b23b093e78/autogen.sh#L18

this is supposed to "Create any missing intermediate pathname components."

might it be a problem with the $HOME variable?

**Comment by LasseF-H** [comment]
No it isn't the problem is that the user that I tested it with wasn't the one that compiled at installed the program. In any case, shouldn't this be handled by the cava binary itself?

**Comment by vmcall** [comment]
Are we supposed to compile cava individually for every environment and user we run it on? Kind of defeats the purpose of portability
