### ISSUE TITLE
Bars Only Increasing In Height

### ISSUE THREAD

**Issue by tascord** [karlstav/cava#285]
**OS**: Arch Linux
**Terminal Emulators Tried**: Kitty, Termite, urxvt

Bars in CAVA only increasing in height, untill reset with 'c'.

[Issue In Action](https://imgur.com/a/n6Soive)
[Config File](https://hastebin.com/amorapabep.cs)

**Cava In TTY:**
Cava works in TTY displaying the numbers all good and well, however, when enabling bars (with 'b'), the bars act like the gifs shared.

I've tried a few consoles, and messing around with the config, yet nothing seems to do it.

**Comment by karlstav** [comment]
Very strange indeed. Have you tried with the original config file?

**Comment by tascord** [comment]
Sorry for the late reply, network problems are fun!
Yes I have!

**Comment by karlstav** [comment]
being a terminal application cava is only text and before i found out about ncurses I made certain optimizations in order for printf to work fast enough. printf is slow. These are still in place for ncurses even though they might not be necessary. 

The optimization is basically only drawing  the changes in each bar for each frame. If the bar goes up cava draws some blocks, if it goes down cava draws some spaces. 

What your gif looks like to me is that cava is only drawing the blocks, not the spaces. It might be a problem with ncurses, have you tried setting output method to `noncurses`?


 

> when enabling bars (with 'b'), the bars act like the gifs shared.

this is strange. `b` does not enable bars, it changes the background color. This problem might happen if background and foreground color is the same.

**Comment by tascord** [comment]
> when enabling bars (with 'b')
I'm referring to cycling through colours. In tty, the bars start with the numbers, then cycle through the colours, acting like the gif's show, only going up.

**Comment by karlstav** [comment]
sorry for the delayed answer @tascord , by numbers do you mean only the number eight? 

I just discovered that if I enable gradient and  set the background color to one of the predefined colors other than black, then I am able to reproduce the described behavior. But this is only when gradient is enabled.

This rings a bell, but I cant't remember exactly what. Will investigate more later.

**Comment by tascord** [comment]
No problem @karlstav !

In the tty, i'm getting mainly, yet not only eight's.
I'm getting exclusively one's with no audio playing, and differing numbers atop the eights.

[Attempt at a tty screenshot](https://imgur.com/a/LgK25QU)

**Comment by karlstav** [comment]
yea that would be the expected behavior when cava can't locate the custom cava.psf font required in the tty. in arch the consolefonts are in `/usr/share/kbd/consolefonts/` just move the bundled `cava.psf`there. I haven't been able to automatically detect the path yet in arch.

have you tried setting output method to `noncurses`?

how is you ~.Xresources file, maybe you can try a different one?

**Comment by tascord** [comment]
Ah, alright.

Whilst my output has been noncurses, I haven't been able to get any output at all.
Here's [my config](https://hastebin.com/afodoguvor.cs) in case i've set anything up incorrectly. (All i changed was the colors because of non not supporting hex codes, and the method)

[My Xresources](https://hastebin.com/lalesadipa.css) shouldn't interfere with anything (containing only rofi settings, but ill give it a shot anyways.

**Comment by karlstav** [comment]
ok @tascord so first of all sorry for the extremely late reply.

your config works fine for me, urxvt on manjaro 18.1.3

Did you try another Xreosurces file?

**Comment by tascord** [comment]
Yeah, no difference.
I just retried urxvt, however it hung.

**Comment by karlstav** [comment]
@tascord did recent changes have any effect on this issue?

**Comment by tascord** [comment]
@karlstav Full system update seems to have fixed issues, thank you very much for you're help.

Best wishes,
tascord
