### ISSUE TITLE
Support 24-bit audio as configuration option

### ISSUE THREAD

**Issue by Xyene** [karlstav/cava#293]
Windows has support for 24-bit audio streams, which could hypothetically be used with Cava's FIFO input running in WSL. #291 improved the Windows situation a bit, however, Cava appears to only support 16-bit audio.

(I am happy to implement this myself, but am opening this issue as per [CONTRIBUTING.md](https://github.com/karlstav/cava/blob/master/CONTRIBUTING.md).)

**Comment by karlstav** [comment]
actually the code for using any sample format exists in the alsa input module:

https://github.com/karlstav/cava/blob/9610991b3a90ba676a759f58967164a52b5e33d8/input/alsa.c#L132

This was actually the only thing that was used in the beginning. I haven't tested it in a while, but I think it still works. The comment about only one channel and biggest octet does not apply anymore.

I think the most practical approach would be to move the whole case switch for the sample format here:

https://github.com/karlstav/cava/blob/9610991b3a90ba676a759f58967164a52b5e33d8/input/fifo.c#L30

this function is used by all the audio input modules to pass audio to the input buffer used by FFTW.

Feel free to implement and create a PR.

**Comment by Xyene** [comment]
This has been implemented.
