### ISSUE TITLE
Speeding up cava reset/exit

### ISSUE THREAD

**Issue by Xyene** [karlstav/cava#305]
The ncurses backend contains a call to `reset` during cleanup. `reset` contains this code:

```c
    if (settle) {
	(void) putc('\r', stderr);
	(void) fflush(stderr);
	(void) napms(1000);	/* Settle the terminal. */
    }
```

(https://github.com/enthought/ncurses-5.5/blob/master/progs/tset.c#L962)

The code dates back to (at least) 1979, and is there for physical terminals that needed time to reset. Terminal emulators don't have such a need, so resetting the screen ourselves by sending the appropriate codes (as per terminfo) would speed up Ctrl+C by (at least) 1 second.

I noticed the call to `reset` was added by [this commit](https://github.com/karlstav/cava/commit/8d73947696f30888e1b260520318a67d55d19c57#diff-b5cc6870fd48981b2eb151abf58d51e8R231). Would it be possible to get a bit more background on the change? The colors still remain messed up in `urxvt` with gradient + `reset` after exiting, but are fine without gradient even without the `reset`.

**Comment by karlstav** [comment]
somehow I thought the reset fixed the colors issue, but I have noticed that in `urxvt` it does not work. Maybe it works in some terminal emulators, but not others?
