### ISSUE TITLE
fps can be negative

### ISSUE THREAD

**Issue by sjef** [karlstav/cava#31]

**Comment by karlstav** [comment]
yup you are right, should be easy to fix in the getopts. fps also can't be over a second because it only sets the nanosec...

**Comment by karlstav** [comment]
fixed.. also discovered and fixed a bug where setting fps to 1 resulted in drawing as fast as possible. 

actually the fps setting isn't entirely accurate as it doesn't take in to account how long the bars calculation and drawing actually times. It just sleeps of 1/fps time...
