### ISSUE TITLE
Stereo output broken

### ISSUE THREAD

**Issue by starmood** [karlstav/cava#335]
I am using mpd with CAVA by FIFO. That worked great
Recently, when I cloned latest CAVA version, I found if I set the channel to 'stereo' in config file, the output value is incorrrect. 
The left channel value is always same as right channel but in reversed order.
And if I test with channel test song files, when test left channel only, the value is actually empty. 

And I also rolled back to old CAVA version (such as 0.6.1-47-g07e6a58) to test again, there is no such issue.

**Comment by karlstav** [comment]
wow its been broken since 7a224dfa15fe5fced0886afd8f88f5076cc8fc7d, well spotted @starmood. it is also broken for all the inputs. I will fix. I suspect some kind of memory overwriting issue.
