### ISSUE TITLE
When using gradient, terminal colors are changed on exit.

### ISSUE THREAD

**Issue by mkrasnitski** [karlstav/cava#336]
I use urxvt (rxvt-unicode) with cava 0.6.1-1 on Arch Linux, and similar to #132, when I exit cava, my terminal colors are changed. This is only present when using a gradient, and not present when using a single color. I'm thinking that the issue is that the colors aren't reset back to their previous values after exit. I tested this with the latest version of cava-git as well (0.6.1-159-g47ab43b), and the issue still persists. Also, I've included some example pictures of the issue below.

Before:
![image](https://user-images.githubusercontent.com/42564254/75466606-74375980-5958-11ea-9690-26cbab03e30b.png)

During:
![image](https://user-images.githubusercontent.com/42564254/75466671-8913ed00-5958-11ea-940f-de857081c6e5.png)

After:
![image](https://user-images.githubusercontent.com/42564254/75466694-929d5500-5958-11ea-8453-6dfde1caebcf.png)

**Comment by karlstav** [comment]
unfortunately there is no way for ncurses to know the actual color definitions in the terminal so therefore it cannot be reset by ncurses. Described in detail here:

https://stackoverflow.com/questions/36051061/color-not-ended-in-curses

What we need is a way for the terminal to reset itself, `reset` does not do the trick as discussed in #305

**Comment by mkrasnitski** [comment]
Is setting the a gradient handled by ncurses whereas setting a solid color is not? I thought I saw that you still use init_color in the code, regardless of if gradient is enabled or not. Otherwise, couldn't you manually grab Xresources colors and be able to restore them that way? I guess it would be a hack, since not all terminals define their colors in Xresources.

**Comment by karlstav** [comment]
as long as you define a color with hex code (gradient or single foreground/background) it will change if for everything. only ncurses can change it. 

But I just realized that in urxvt-256 I have 256 different definitions to use, which mean I can leave the first 16 as they are. Will test this some more when I have time.

**Comment by mkrasnitski** [comment]
Looking at the code, do you just replace colors 16-31 instead of 0-15 now? This might cause a few problems with applications that still query those colors. For example, the default Powerlevel10k config file contains colors outside the range 0-15, and I think the LS_COLORS environment variable can contain any color from 0-255.

**Comment by karlstav** [comment]
That is correct. From number 16 and upwards (there might be more than 16).

The solution is not perfect. But I can't think of any better. I think usually only the first 16 is used.
