### ISSUE TITLE
Unnecessary output on startup

### ISSUE THREAD

**Issue by mkrasnitski** [karlstav/cava#337]
When starting cava with input method `pulse` and input method `auto`, the string "TERMINATED" is output to the terminal before the visualizer appears. The line of code that causes this is line 56 in `input/pulse.c`. In previous versions of cava, this line was commented out. Either this is debug output, or my pulseaudio has an issue, in which case, what's the solution on my end? Otherwise, simply commenting out the line would get rid of the output.

**Comment by karlstav** [comment]
Yea that can just be commented out again. Wonder why I haven't. Is is kind of annoying.
