### ISSUE TITLE
Chrome in the foreground, cava in the background inside gnome-terminal

### ISSUE THREAD

**Issue by andrewhodel** [karlstav/cava#342]
```
zip@aware:~$ uname -a
Linux aware 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux
```

When I bring cava through the gnome-terminal back to the foreground it shows all the bars at the bottom.

I've attached all installed packages on this system.
[dpkg.txt](https://github.com/karlstav/cava/files/4371461/dpkg.txt)

Probably difficult to recreate, using the https://en.wikipedia.org/wiki/Cinnamon_(desktop_environment)

**Comment by karlstav** [comment]
hi @andrewhodel 

yea most likely difficult to recreate I am using i3 myself. 

does the bars go back up? or is it like silence?

**Comment by andrewhodel** [comment]
It just appeared as seconds of silence while audio was playing for a short interval, after that few seconds it started showing normally. 


Thank You,
Andrew Hodel

**Comment by karlstav** [comment]
weird, are you using some special config for cava?

**Comment by andrewhodel** [comment]
Nope, just wanted you to know how it acted one time with the video driver, terminal and desktop environment I was using when I submitted the issue. 


Thank You,
Andrew Hodel
