### ISSUE TITLE
Cava solid colour

### ISSUE THREAD

**Issue by bigladadam** [karlstav/cava#344]
Getting a solid colour on cava, first it's grey, then when I hit b it changes to pink etc.

**Comment by bigladadam** [comment]
Got it working - but getting a new issue, it appears there's a very low framerate

**Comment by deckardstp** [comment]
same issue here. got nothing, then solid block. using manjaro linux. any ideas why this is happening?

**Comment by karlstav** [comment]
need to know what terminal emluators you are using, cava config would also be useful.

**Comment by karlstav** [comment]
for framerate issue terminal size could also be useful:
`tput cols`
and
`tput lines`

there will be performance issue in verry large terminals

**Comment by karlstav** [comment]
I have also noticed now that there is a bug when defining the background color, trying to hunt it down.

**Comment by deckardstp** [comment]
hey karl :)
will help you out. 
os: manjaro linux
terminal: kitty, also kde konsole
tput cols: 84
tput lines: 9
cava config is pretty standard. no things specified. 
if you need anything else. just let me know...

**Comment by karlstav** [comment]
@bigladadam 

> for framerate issue terminal size could also be useful:
> `tput cols`
> and
> `tput lines`
> 
> there will be performance issue in verry large terminals

also hw info could be useful

**Comment by bigladadam** [comment]
> @bigladadam
> 
> > for framerate issue terminal size could also be useful:
> > `tput cols`
> > and
> > `tput lines`
> > there will be performance issue in verry large terminals
> 
> also hw info could be useful

I got the issue fixed, I don't know how so sorry if you have the same issue, but my tput cols is 80 and tput lines is 7

My hw is A ryzen 5 2600 @ 3.85GHz and a GTX 1060 6gb GPU

**Comment by karlstav** [comment]
anyway good to hear that you got it fixed, a small terminal with hardware like that should not be a problem at all.

**Comment by karlstav** [comment]
@deckardstp 

> got nothing, then solid block

sounds like it might be an issue with the auto sensitivity not being able to turn it self down.

do you mean that all the bars go to the top of terminal and just stay there?

If so could you try disabling `autosens`and setting `sensitivity` to something really low.

**Comment by deckardstp** [comment]
@karlstav 
I found the issue. I can't explain it to myself but LANG in the locale wasn't set. As soon as I fixed that it works like a gem. Thanks for your help anyway!

**Comment by karlstav** [comment]
good old #109
