### ISSUE TITLE
how to change color of visualizer guys?

### ISSUE THREAD

**Issue by Belmaj** [karlstav/cava#345]
i am new user of your app sir and i want to know how to change the visualizer color
i want to look like this
![Screenshot from 2020-04-17 11-03-25](https://user-images.githubusercontent.com/57773946/79527928-5e622d00-809b-11ea-80da-8f42905e58f1.png)

**Comment by karlstav** [comment]
hi @Belmaj ,

just take a look in the config file. 

You must enable gradient and set clors acordingly.

**Comment by Belmaj** [comment]
> hi @Belmaj ,
> 
> just take a look in the config file.
> 
> You must enable gradient and set clors acordingly.

thanks i will try.

**Comment by tango0o** [comment]
> i am new user of your app sir and i want to know how to change the visualizer color i want to look like this ![Screenshot from 2020-04-17 11-03-25](https://user-images.githubusercontent.com/57773946/79527928-5e622d00-809b-11ea-80da-8f42905e58f1.png)

Try to edit your ~/.config/cava/config and find [colors] section, typing
``` 
gradient_count = 2
gradient_color_1 = '#2864FF'
gradient_color_2 = '#C620FF'
```

**Comment by olgierd8991** [comment]
i cant find config

**Comment by Ridhsuki** [comment]
> i cant find config

I can
