### ISSUE TITLE
Incorrect maximum bars with raw output

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#346]
Hi Karl

When processing music and producing raw ouput some incorrect maximum height bars are produced. It may be that these bars should be zero.

Original mpd_oled issue: https://github.com/antiprism/mpd_oled/issues/39

Config file
```
[general]
framerate = 25
bars = 21

[input]
method = fifo
source = /tmp/mpd_oled_fifo

[output]
method = raw
data_format = binary
channels = mono
raw_target = /tmp/cava_fifo_6793
bit_format = 8bit
```

Testing cava commits showed this issue was introduced with https://github.com/karlstav/cava/commit/ee96026023d331a0e68b7f68aa31f3cc847c85a3

Adrian.

**Comment by karlstav** [comment]
I knew that commit might cause some problems. 

I need som kind of automated unit test/ qa-system that checks expected output for a given input at every commit.

Is it only with raw output? or only with 21 bars and mono?

**Comment by antiprism** [comment]
I have only tested with mpd_oled, which always runs cava with raw output and mono. The 21 bars isn't a default and so the person who originally reported the issue probably uses a different number.

**Comment by antiprism** [comment]
I thought I would look at the raw ascii output on x86 Ubuntu, but this produces a segfault after printing a few lines. If you look at the f[i] values in print_raw_out, it is possible for them to be less than zero without this being handled.

**Comment by karlstav** [comment]
Well yes, negative values here would of course cause issues. I can't immediately se in the code where this whould happen. Will investigate more as soon as possible.

**Comment by karlstav** [comment]
Most likely the bar values are going above 2^16/2, therefore going into the negative range of the int. I must find our what specifically in that commit that could cause that to happen.

Also I should use unsigned ints and create a check for too high values (since the values coming out of the fftw are doubles).

**Comment by karlstav** [comment]
got it, the gravity / fall off filter could cause the bar value to drop below zero.

adding a check for it and also moving to using unsigned ints.  will test some more then push later.

**Comment by antiprism** [comment]
I have just pulled the latest commits and all is working well, thanks.

The spurious maximum bars are gone with the raw binary output on Raspian (PI Zero), and cava no longer crashes with raw ASCII output on Ubuntu x86.
