### ISSUE TITLE
built without 'shmem'

### ISSUE THREAD

**Issue by antonellocaroli** [karlstav/cava#347]
I can't get squuezelite Cava to work.

it gives me this error

Error loading config. cava was built without 'shmem' input support

how do I compile with the shmem?

**Comment by karlstav** [comment]
my bad, shmem was previously a config option that had to be enabled manually. But since it did not have any special epedencies I enabled it always. however I forgot to change som things leaving it to coincidence whether it would work or not.

should be fixed now.
