### ISSUE TITLE
Kitty runs slow and delayed compared to iterm2 and alacritty

### ISSUE THREAD

**Issue by fparrav** [karlstav/cava#349]
everything I run in kitty is much faster than the normal terminal or iterm2 but cava does not work smoothly

**Comment by karlstav** [comment]
you need to provide more detail, cava runs equally smooth on both kitty and iTerm on my mac.

**Comment by fparrav** [comment]
I would not know how to deliver more background, I am running CAVA on a Macbook Pro 13 "Early 2015 with an Intel Iris Graphics 6100. Kitty gives me an identical performance to alacritty when it comes to rendering text, both are by far superior to iTerm2, but at running in kitty does not seem to generate the same amount of characters on the screen and therefore does not look fluid and lagged.


Make a recording with [asciinema]( https://asciinema.org) and the kitty file weighs 3 times less,they both use the same font and text size.

Alacritty : 

[![asciicast](https://asciinema.org/a/325730.svg)](https://asciinema.org/a/325730)

Kitty:

[![asciicast](https://asciinema.org/a/325731.svg)](https://asciinema.org/a/325731)

**Comment by karlstav** [comment]
weird, I am running cava on a similar hw with kitty version version 0.14.6 and it look just as smooth as as with your Alacritty. Afraid I don't know what the issue might be.

**Comment by fparrav** [comment]
Update to version 0.17.4 (it was on 0.17.2) and now it has 99% smooth performance as alacritty, apparently it must have been a bug of the version that was installed. Thank you!!
