### ISSUE TITLE
No bar on Mac OS X

### ISSUE THREAD

**Issue by drselump14** [karlstav/cava#353]
Hi, I successfully installed the cava  binary. However, I can't see any moving bar.. only bunch small bars .. I have set the multiple output using soundflower, but nothing is happened... Did I miss something   here?

**Comment by karlstav** [comment]
how does your cava config file look? have you set it to use portaudio and soundflower:
```
method = portaudio
source = "Soundflower (2ch)"
```

**Comment by drselump14** [comment]
Thanks, it's solved.. had problem when launch it from tmux.. but still don't know the reason

**Comment by karlstav** [comment]
there is a general problem about the output from portaudio being very low.  might be something vwong with the code, will have a look later.
