### ISSUE TITLE
cava not reading config

### ISSUE THREAD

**Issue by hiJxCKR** [karlstav/cava#358]
Whenever i try to change anything in my cava config (~/.config/cava/config) cava does not seem to read it. After editing config i restart cava with CTRL+C and run cava again in terminal and no changes appear. I rebooted my pc and ran cava again and still no change. 'cava -v' returns: cava 0.7.0-7-ge2aef35. I am using cava on Debian 10 and i built from source.

**Comment by karlstav** [comment]
Did you uncomment the lines that you where trying to change? (Remove the semicolon)

**Comment by hiJxCKR** [comment]
Thanks! I didn't realise the semicolons were comments because it seems hashtags are aswell. Sorry for the inconvenience
