### ISSUE TITLE
[question] how would you reliably parse the raw binary output of cava via node.js?

### ISSUE THREAD

**Issue by AryToNeX** [karlstav/cava#361]
As the title says. I am trying to get it parsed by node, but the chunks I receive are all over the place and all with different lengths, which adds to the complexity of a seemingly simple task. Did anyone manage to use this on a node project?

**Comment by steveunixson** [comment]
@AryToNeX  Why do you need it in the first place?

**Comment by AryToNeX** [comment]
@steveunixson I needed it for a DIY project of mine, and data from CAVA comes in handy and lets me use a language I am decently familiar with (the alternative is Python which I don't know at all)

**Comment by AryToNeX** [comment]
Anyway I got it to work. Here's a snippet for anyone having the same issue:
```js
// let's assume that stream is our CAVA pipe (ReadableStream)
const desiredLength = 3; // whatever length your bars are
let _buffer = Buffer.alloc(0);
stream.on('data', d => handle(d));
stream.on('end', () => doStuff(_buffer));  // Do stuff with the remaining buffer

function handle(data) {
  if(_buffer.byteLength + data.byteLength > desiredLength) {
    const split = desiredLength - _buffer.byteLength;
    doStuff(Buffer.concat([_buffer, data.slice(0, split)]));
    _buffer = Buffer.alloc(0);
    handle(data.slice(split));
  }else _buffer = Buffer.concat([_buffer, data]);
}

function doStuff(data){
  console.log(data);
  // do your stuff here
}
```

**Comment by steveunixson** [comment]
@AryToNeX Indeed works! For whatever black magic you are doing)
