### ISSUE TITLE
(noob) Building on macOS

### ISSUE THREAD

**Issue by Shep029** [karlstav/cava#362]
I tried to build cava on macOS by following the instructions

Installed brew
Did `brew install fftw ncurses libtool automake portaudio`
did the glibtool stuff
then I did this

`git clone https://github.com/karlstav/cava`
`cd cava`

the problem is, when I did `./autogen.sh'
this showed up

`./autogen.sh: line 9: libtoolize: command not found`
`configure.ac:5: error: required file './ltmain.sh' not found`

how do I fix this?

**Comment by karlstav** [comment]
this is not noob related error at all! 

There is an obvious error in my building instructions. The libtoolize commands does nothing good at all. Just run `glibtoolize`in the cava source dir before running `./autogen.sh`and it should work fine.

**Comment by karlstav** [comment]
@Shep029, have you been able to build following my updated instructions?
