### ISSUE TITLE
Fedora - Spectrum shows twice?

### ISSUE THREAD

**Issue by LincolnAuster** [karlstav/cava#363]
I ran `dnf install cava` and then 'cava`. The resulting spectrum is mirrored and displayed twice.
![image](https://user-images.githubusercontent.com/46805277/85343316-c5d89680-b4a9-11ea-8700-a50908c7bc84.png)

Is this intended behavior? If it is, how do I disable it? If it's not, are there any flags or config files I should be using? Thanks!

Edit: I just noticed that the screenshot doesn't seem to show them mirrored. I think there's a lag between the two "humps", this definitely isn't just what the audio looks like.

Edit 2: 880 Hz for reference:
![image](https://user-images.githubusercontent.com/46805277/85343651-a2fab200-b4aa-11ea-9584-791154e72145.png)

**Comment by karlstav** [comment]
It's stereo, look for the channels setting in the config if you like to
have it in mono.
