### ISSUE TITLE
Manjaro - Controls not working

### ISSUE THREAD

**Issue by jaeger-2601** [karlstav/cava#364]
Downloaded cava using pacman in Manjaro. After launching the program,  it doesn't respond to any keyboard controls.
I double checked the dependencies to ensure I had all of them installed and tried building it from source and found the same issue.

**Comment by karlstav** [comment]
hi @jaeger-2601, the controls only work in ncurses output mode,  noncurses are now the default, so if you want to use the controls you must change you config. I changed noncurses to the default in 0.7.0. I didn't think anyone used the controls, but maybe I should make them work in noncurses as well.

**Comment by jaeger-2601** [comment]
I previously installed cava in ubuntu and the controls worked perfectly , so I was confused when it didn't work in manjaro . I recommend adding a little note about the change in the readme. Thanks for the explanation 🙂.
