### ISSUE TITLE
Cannot add/remove bars or change color anymore

### ISSUE THREAD

**Issue by Ferryistaken** [karlstav/cava#366]
I used to be able to add/remove bars with the arrow keys and to change colors(1-9). After an update(I can't remember which) I am not able to do that anymore. I can only stop it using Ctrl-C (before I could stop it by pressing "q") and it doesn't react to input anymore. Is this intentional? Did the keybinds change? I am on Arch Linux and I am using the latest version from the AUR

**Comment by karlstav** [comment]
#364

I'll make a new release and notify the AUR maintainer soon.

**Comment by Ferryistaken** [comment]
I fixed it by changing the config to use ncurses mode. The default config from the aur doesn't use that

**Comment by Paul-Houser** [comment]
I'm also on Arch Linux experiencing this issue. I tried changing to ncurses mode, and cava started responding to arrow keys, but still no color changes...

**Comment by karlstav** [comment]
can't reproduce the color change issue. note that the color key controls does not work if you have defined color with hex code.

**Comment by Paul-Houser** [comment]
Hmm, the [color] section of my cava config is pretty much default with no hex colors defined, and cava used to be able to cycle through my terminals color palette. I tried swapping my config for the default one that comes with the AUR package and it still doesn't cycle colors.

Sounds like maybe this is an unrelated issue
