### ISSUE TITLE
Datastream not constant

### ISSUE THREAD

**Issue by Maschine2501** [karlstav/cava#367]
Hi there!
First of all: I appreciate your work! Thank you!

I've set up cava and use it in a Python script.
You can see [here](https://github.com/Maschine2501/NR1-UI/wiki/Installation-steps-(Braun-NR1-specific)) how i did the setup and also how i configured it.
I randomly, every few seconds, got glitches in the spectrum... 
Tested on Pi3 and Pi4 with newest Volumio (fresh installation).
So i put two prints in my code, my variable for the fifo-stream is called "data", one for the len(data) and one for the containing data.
Strangely the len(data) value varies sometimes.
Here is the log:

Length of Data:  65

Fifo-Data:  ['', '9', '15', '9', '8', '7', '19', '7', '6', '5', '5', '5', '7', '8', '15', '23', '18', '13', '10', '13', '6', '2', '2', '7', '15', '10', '13', '18', '23', '15', '8', '7', '5', '5', '5', '11', '13', '20', '12', '5', '8', '15', '7', '4', '4', '4', '6', '7', '12', '7', '5', '12', '16', '12', '7', '4', '6', '5', '4', '4', '3', '3', '2', '1', '1', '1', '1', '3', '3', '5', '5', '3', '5', '9', '7', '13', '9', '11', '9', '6', '6', '4', '3', '1', '3', '4', '']

Length of Data:  87

Fifo-Data:  ['', '4', '4', '4', '1', '3', '3', '4', '5', '9', '9', '8', '6', '5', '6', '7', '5', '5', '7', '7', '4', '5', '5', '3', '1', '4', '5', '6', '3', '2', '1', '0', '0', '0', '4', '3', '1', '2', '1', '1', '1', '2', '1', '0', '1', '0', '1', '3', '4', '8', '4', '7', '13', '6', '3', '0', '4', '4', '5', '9', '8', '6', '1', '0', '0', '1', '7', '8', '9', '5', '4', '4', '1', '3', '8', '11', '9', '5', '7', '3', '4', '1', '0', '1', '1', '0', '1', '0', '1', '0', '3', '1', '3', '4', '0', '1', '1', '5', '3', '2', '5', '7', '4', '3', '6', '3', '4', '4', '5', '5', '5', '9', '5', '11', '9', '13', '16', '11', '9', '8', '7', '7', '6', '7', '5', '5', '5', '5', '']

Length of Data:  129

Fifo-Data:  ['19', '9', '4', '1', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '2', '0', '0', '1', '2', '1', '2', '3', '4', '1', '2', '5', '3', '4', '2', '6', '2', '3', '2', '2', '4', '3', '6', '4', '6', '5', '1', '3', '6', '6', '9', '7', '5', '1', '3', '']

Length of Data:  53

Fifo-Data:  ['', '1', '1', '0', '0', '0', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '2', '4', '7', '14', '25', '40', '27', '15', '8', '4', '5', '8', '5', '12', '8', '5', '8', '3', '1', '1', '3', '8', '5', '8', '12', '5', '8', '5', '4', '11', '19', '33', '40', '32', '18', '11', '5', '3', '0', '2', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '2', '6', '2', '1', '5', '1', '1', '1', '1', '0', '2', '1', '3', '3', '3', '5', '4', '6', '7', '7', '7', '8', '7', '5', '5', '5', '4', '4', '4', '4', '5', '4', '']

Length of Data:  101

Fifo-Data:  ['', '4', '5', '4', '4', '7', '8', '7', '7', '5', '5', '4', '5', '1', '4', '']

Length of Data:  16

Fifo-Data:  ['', '3', '4', '7', '12', '17', '28', '14', '8', '10', '16', '11', '8', '7', '7', '7', '5', '4', '3', '4', '5', '7', '3', '1', '5', '4', '7', '12', '4', '2', '3', '3', '0', '2', '8', '11', '8', '3', '4', '9', '4', '3', '2', '4', '2', '1', '2', '4', '5', '8', '19', '7', '4', '2', '1', '0', '3', '7', '12', '5', '4', '7', '3', '0', '0', '3', '7', '4', '5', '12', '7', '3', '1', '1', '2', '5', '9', '18', '12', '7', '6', '3', '1', '1', '3', '0', '1', '2', '4', '2', '1', '2', '9', '12', '3', '3', '4', '7', '4', '3', '9', '7', '4', '1', '2', '3', '5', '4', '3', '3', '2', '4', '4', '4', '7', '9', '9', '12', '7', '4', '10', '13', '11', '12', '7', '6', '3', '4', '']

Length of Data:  129

Fifo-Data:  ['', '3', '6', '9', '6', '7', '4', '8', '3', '0', '3', '1', '3', '2', '1', '0', '3', '10', '11', '9', '4', '1', '4', '5', '4', '4', '4', '6', '8', '4', '4', '5', '4', '3', '5', '5', '5', '8', '5', '8', '7', '5', '7', '4', '4', '4', '5', '1', '4', '2', '4', '5', '4', '5', '']

Length of Data:  55

Fifo-Data:  ['', '2', '0', '3', '4', '7', '8', '4', '8', '8', '8', '14', '11', '8', '17', '12', '11', '7', '11', '10', '12', '10', '4', '3', '4', '5', '10', '10', '5', '6', '9', '5', '5', '3', '4', '2', '4', '4', '1', '1', '0', '2', '0', '0', '1', '4', '7', '9', '12', '14', '8', '6', '4', '12', '20', '28', '21', '11', '9', '7', '15', '8', '5', '1', '1', '5', '8', '15', '8', '10', '12', '22', '30', '21', '12', '4', '4', '4', '8', '6', '4', '3', '4', '4', '3', '2', '0', '0', '1', '2', '4', '7', '5', '4', '3', '3', '4', '4', '5', '5', '11', '14', '7', '3', '4', '3', '11', '10', '14', '14', '7', '12', '16', '17', '7', '11', '14', '7', '7', '7', '3', '3', '3', '4', '2', '4', '2', '4', '']

Length of Data:  129

Fifo-Data:  ['4', '4', '4', '4', '4', '5', '5', '3', '2', '1', '3', '3', '3', '3', '3', '3', '1', '4', '4', '7', '5', '3', '2', '2', '0', '4', '5', '6', '4', '2', '2', '1', '3', '2', '1', '0', '0', '1', '0', '0', '0', '0', '0', '3', '9', '3', '5', '9', '14', '22', '16', '14', '13', '11', '13', '14', '17', '22', '16', '14', '24', '13', '8', '4', '4', '9', '16', '24', '17', '15', '24', '17', '11', '11', '11', '10', '12', '9', '15', '9', '7', '4', '3', '5', '4', '0', '0', '1', '1', '0', '0', '1', '0', '4', '4', '2', '4', '3', '4', '14', '9', '7', '4', '4', '1', '3', '4', '5', '4', '4', '4', '3', '4', '1', '3', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '6', '']

Length of Data:  129

Fifo-Data:  ['4', '4', '4', '5', '7', '7', '5', '3', '2', '1', '3', '3', '3', '3', '3', '5', '3', '7', '7', '12', '9', '5', '2', '4', '1', '4', '4', '4', '5', '2', '2', '3', '5', '2', '1', '1', '1', '1', '1', '0', '1', '0', '0', '3', '8', '3', '4', '8', '14', '24', '16', '11', '9', '7', '11', '11', '11', '20', '15', '13', '24', '13', '8', '4', '4', '8', '17', '26', '17', '14', '23', '14', '11', '9', '6', '5', '8', '8', '15', '8', '5', '2', '3', '4', '4', '0', '1', '1', '0', '1', '1', '3', '1', '5', '5', '4', '7', '5', '5', '11', '6', '5', '4', '4', '3', '3', '5', '7', '5', '4', '4', '3', '5', '1', '3', '4', '4', '4', '4', '5', '4', '5', '5', '5', '5', '5', '4', '5', '']

Length of Data:  129

Fifo-Data:  ['3', '2', '2', '3', '6', '6', '3', '1', '0', '0', '1', '3', '0', '3', '2', '4', '3', '7', '9', '13', '13', '7', '3', '4', '0', '2', '1', '3', '4', '2', '0', '2', '3', '0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '3', '7', '5', '7', '12', '21', '35', '22', '13', '9', '6', '9', '12', '9', '12', '8', '7', '18', '10', '3', '1', '2', '5', '14', '22', '10', '7', '13', '8', '11', '7', '4', '3', '4', '7', '14', '8', '4', '2', '2', '3', '3', '0', '1', '1', '1', '0', '0', '2', '0', '4', '3', '4', '6', '4', '4', '7', '4', '4', '3', '4', '3', '3', '5', '9', '5', '5', '3', '4', '5', '1', '0', '3', '4', '2', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '']

Length of Data:  129

Fifo-Data:  ['2', '0', '1', '2', '4', '4', '2', '1', '1', '1', '1', '3', '1', '3', '2', '4', '3', '5', '8', '9', '14', '7', '3', '2', '0', '2', '1', '2', '2', '1', '1', '1', '3', '1', '1', '1', '1', '0', '0', '1', '1', '1', '2', '3', '5', '5', '8', '14', '25', '40', '25', '15', '8', '8', '12', '15', '10', '10', '6', '4', '10', '5', '1', '0', '0', '2', '7', '13', '7', '5', '9', '10', '14', '12', '7', '4', '6', '8', '15', '9', '5', '3', '3', '2', '2', '2', '1', '1', '1', '0', '0', '1', '1', '5', '3', '5', '4', '3', '3', '5', '4', '5', '2', '4', '1', '2', '4', '8', '4', '4', '1', '4', '5', '2', '2', '2', '4', '1', '3', '3', '3', '3', '3', '3', '3', '3', '3', '4', '']

In my Installation script is a second cava installation, but the failure happens every time, even with a clean/fresh installation without the second instance of cava...
It happens to all kinds of sources, flac,mp3, stream no relation to codec/bitrate/samplerate.

Do you have an idea how to fix that?

And by the way: Why is there an " at the end of each stream? Can i do something to get rid of it?

Regards,

Christoph

PS: Even with this stripped-down [Test-code](https://github.com/Maschine2501/NR1-UI/blob/master/oled.py) the same issue...

**Comment by karlstav** [comment]
hi @Maschine2501,

I don't know if using readiline on the cava fifo is the way to go. It probably does not always start on the first bar, since cava is continuously writing to the fifo. Maybe you have to just throw away any incomplete frame and wait until you have a full frame.

would you expect to have length of data: 64? since you have 64 bars and newline as frame delimiter? or should it have 128 since you have two (stereo)? the extra `"` is probably related to the way you parse the data. I have probably added an extra `;` at the end of the frame, you will just have to manually subtract one.

**Comment by karlstav** [comment]
reading through your striped down code makes me pretty sure that the issue is that you are not done with the `draw.rectagnle` stuff before cava starts writing the new frame to the fifo. So either just discard any data that is shorter then expected, or you could try to reduce the cava framerate, OR speed up the `draw.rectangle` stuff.

**Comment by Maschine2501** [comment]
Thank you for your reply, i have made an if i <= 64 in my test code. The result is ok...
But I think you're right with "code is not done with draw.rectangle...." 
Have you an idea how to count the frames per second?
To count how many times my draw.rectangle stuff needs is easy for me to do, but i have no idea how to count the frames per second....

If i get to know the FPS of the fifo stream, i could adjust it to the fps of my code...

**Comment by karlstav** [comment]
You can set the framerate in the cava config, if that's what you want. As
long as it's lower than your fps. You should be in the clear.

**Comment by Maschine2501** [comment]
Ok, i know how to set the framerate... Thanks!
You said "I don't know if using readiline on the cava fifo is the way to go. " -> do you know another (better) way?

**Comment by karlstav** [comment]
I had not really thought it through when i wrote that. If the cava
framerate is not higher than what your application can handle. It should be
fine.

**Comment by Maschine2501** [comment]
Ok, misunderstood that..
Thank you for your fast support, framerate adjusted to my code`s framerate has solved it for me ;)
