### ISSUE TITLE
Color codes not working correctly in config

### ISSUE THREAD

**Issue by JustAnotherStrange** [karlstav/cava#368]
**Before you file this report**
- Are you using cava from a package repository, like AUR? **Yup, from AUR**
- If so, check out the master branch here, is your issue already resolved?  **Nope**

**Describe the bug**
In the config, I follow all instructions for the color gradient syntax. 
```
# Gradient mode, only hex defined colors (and thereby ncurses mode) are supported,
# background must also be defined in hex  or remain commented out. 1 = on, 0 = off.
# You can define as many as 8 different colors. They range from bottom to top of screen
gradient = 1
gradient_count = 8
gradient_color_1 = '#000000'
gradient_color_2 = '#80CC33'
gradient_color_3 = '#A6CC33'
gradient_color_4 = '#CCCC33'
gradient_color_5 = '#CCA633'
gradient_color_6 = '#CC8033'
gradient_color_7 = '#CC5933'
gradient_color_8 = '#CC3333'
```
Tried with capital and lowercase letters in the hex code, always get same error: 

```
Error loading config. Only 'ncurses' output method supports HTML colors. Please change the colours or the output method.
As of version 0.7.0 ncurses is no longer the default output method
Gradient color 1 is invalid. It must be HTML color of the form '#xxxxxx'.
```
Huh.

**To Reproduce**
1. Uncomment the gradient parts of the config
2. run

**Expected behavior**
Cava would run and there would be gradients on the bars

**Screenshots**
https://i.imgur.com/b0ETZRh.png - Config
https://i.imgur.com/PnC69rF.png - error message

**Desktop (please complete the following information):**
 - OS: Manjaro Linux Xfce Edition
 - Version: 20.0.3

**Terminal emulator**
- Xfce4-terminal
- 0.8.9.2

**Comment by karlstav** [comment]
probably ncurses mode was not set in your config. I made some improvements, so from now on this should not be necessary. thanks for the bug report as I am guessing more people are experiencing this issue.
