### ISSUE TITLE
Timer if no Signal: Please add a toggle and/or configuration possibility

### ISSUE THREAD

**Issue by Maschine2501** [karlstav/cava#370]
Hi there,
following the previous e-mail communication:
There iss actually a timer which shuts down the fifo stream if there is no sound for 5 seconds.

Please add a toggle (on/off) for the sleeptimer.
If possible with te possibility to set a custom sleep-timer time.

This would be great ;)

Regards,
Christoph

**Comment by karlstav** [comment]
added in https://github.com/karlstav/cava/commit/808716e7699dec1fe34ea8263c6694509b925efe
