### ISSUE TITLE
weak config file presentation for fifp... 

### ISSUE THREAD

**Issue by CaptainBloodz** [karlstav/cava#372]
gentoo dosesn't any template config file.
Trying for mpd, I had to search in closed issues to find out requirement for both:
[input] -> syntax nowhere explicitly presented in README, although keyword invocated in pulseaudio section.
source = -> lacking in README fifo section.

Thks 4 ur attention, interest & support.

**Comment by karlstav** [comment]
hi @CaptainBloodz 

if the gentoo package (or ebuild?) doesn't provide the template config, then report the issue with the maintainer. Not here.

you can find the config template here:

https://github.com/karlstav/cava/blob/master/example_files/config

**Comment by CaptainBloodz** [comment]
SIlly me,
Thks 4 ur attention, interest & support.
