### ISSUE TITLE
Top bars not cleared in "ncurses-cava"

### ISSUE THREAD

**Issue by karlstav** [karlstav/cava#38]
Issue was first raised in #36 by @CelestialWalrus, see illustration [here](http://gfycat.com/ShadyForcefulDrongo).

Might be the same as what @rolf1304 describers as " flickering cursors at the bars' tops" in #36 .

I'm not seeing the same issue in Terminator on my computer, suggesting that it might be related to something else then the terminal software. @CelestialWalrus can you provide info about font and terminal settings? @rolf1304 can you look at the gif and confirm if it is the same issue you are seeing?

**Comment by karlstav** [comment]
Tried switching of bold in the modules branch. @CelestialWalrus @rolf1304, can you check if its any improvement? For me xterm was not giving any output at all before i switched off bold, so maybe there is an issue here?

**Comment by rolf1304** [comment]
No, this is not what I meant. I don't experience this issue.
What I meant is this: http://a.pomf.se/xnairk.png
Notice the cursor at the fourth bar from the right. It'll jump from bar to bar as they are redrawn.
