### ISSUE TITLE
Friendly fork of cava

### ISSUE THREAD

**Issue by atisharma** [karlstav/cava#382]
Hi Karl,

I forked cava to [bellini](https://github.com/atisharma/bellini) and thought you may be interested. So this is not really an issue as such.

The new project has different aims from cava:
- it presents a 'scientifically accurate' spectrum visualisation.
- it writes to the framebuffer (so not really for desktop PC use, I use it with a separate amp + DAC + raspberry pi)

It also has some significant changes in the fft processing:
- no eq
- log-log plot (so musical notes equally spaced) with frequency, octave and dB markings
- Hann windowing before fft

It may be that some ideas will be useful to cava, for instance in with issue #289.

Thank you again for cava.

**Comment by karlstav** [comment]
hi @atisharma 

this looks very interesting!

I have started on 289 now, and I discovered some errors in the frequency calculations, hoping to get a fix ready soon.

**Comment by atisharma** [comment]
Great to hear, let me know if you want me to do anything.
