### ISSUE TITLE
Error opening stream

### ISSUE THREAD

**Issue by sean-flanagan** [karlstav/cava#388]
Hey Karl, I am getting an error: failure in opening stream (ffffd8f2), on macOS.

**Comment by karlstav** [comment]
Did you follow the instructions on how to capture audio on macos on the
readme?

What's your portaudio source name? Does it match the device name?

**Comment by sean-flanagan** [comment]
Hey Karl, I tried to—though having trouble with the config.c file. Not sure
exactly where to place:

Method = portaudio
Source = “Soundflower (2 Ch)”

Tried searching through the file but I’m very new to C!

**Comment by karlstav** [comment]
config.c is not the config file, it's just the part of the program that reads the config file, it probably should be named something else.

the config file is just a plain text (ini) file.

read more about configuration in the readme:

https://github.com/karlstav/cava#configuration

**Comment by vkmb** [comment]
Hi Karl, I am also facing the same issue. 

Os: macOS Monterey 12.3.1
Package Installer: Brew

config-file location: $HOME/.config/cava
<img width="1440" alt="config" src="https://user-images.githubusercontent.com/19430718/162139498-b0890d31-80a0-4049-a421-cb9f6fcdf78d.png">

Error:
<img width="1436" alt="error" src="https://user-images.githubusercontent.com/19430718/162139676-4694d5fc-73be-435b-8600-5dcd9280b6b6.png">

**Comment by karlstav** [comment]
try the solution from #428:

https://github.com/karlstav/cava/issues/428#issuecomment-1025233702

**Comment by vkmb** [comment]
As suggested, I reinstalled portaudio  with "brew update && brew reinstall portaudio" and tried it. I getting different results for running the command with and without the path for config file and both doesn't show the visualisation as indented.
$ cava 
<img width="1439" alt="cava output" src="https://user-images.githubusercontent.com/19430718/162242709-f47b5593-240d-4a84-a19e-411a3f807d46.png">
**Output**: stuck in the same state and no visual update.
$ cava -p ~/.config/cava/
<img width="1439" alt="cava -p ~/.config/cava  output" src="https://user-images.githubusercontent.com/19430718/162244517-6f7bcb29-0f44-4f02-8a87-f2993a7b67e8.png">
**Output**: Error opening stream with session broken.

**Comment by karlstav** [comment]
The default config file is most likely somewhere else then

~/.config/cava

**Comment by vkmb** [comment]
If the Privacy settings **"Allow kitty to access microphone"** dialog doesn't pop up it's going to the same issue again I guess. After building it from the source and installing it using the instructions specified in [cava.rb](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cava.rb) , the os decided to pop up the dialog box. I did try to manually do this before posting the error today. Thanks a lot for visualiser Karl, I am onestep closer in finishing the ric3. 
![out](https://user-images.githubusercontent.com/19430718/162315025-310c79f8-2e93-43eb-bb2f-e19fb2b92651.gif)


**Output**: The visualiser is working as expected. Thanks again !
