### ISSUE TITLE
Recommend Background Music App for macOS users

### ISSUE THREAD

**Issue by Matt-Gleich** [karlstav/cava#389]
**Is your feature request related to a problem? Please describe.**

The current recommendation for macOS is soundflower which requires you to create an aggregate device and you lose keyboard volume controls.

**Describe the solution you'd like**

I think that [Background Music](https://github.com/kyleneideck/BackgroundMusic/) is a much better choice as all you have to do is download it, set it as your cava output and it just works. You even get volume controls again! Background Music is also more popular and has better documentation.

**Describe alternatives you've considered**

I haven't looked at any other alternatives.

**Additional context**

If you think switching to this makes sense I would totally be up for making a PR updating the documentation.

**Comment by karlstav** [comment]
hi @Matt-Gleich ,

please do make a PR.

I don't use mac that much, soundflower was just the top hit when i searched around for a solution. 

You could list both methods, but make Background Music the top alternative if you feel it is better.
