### ISSUE TITLE
module based source code

### ISSUE THREAD

**Issue by karlstav** [karlstav/cava#39]
started working on module based source code using file structure suggested by @CelestialWalrus  in #34 . See separate branch "modules".

Only been able to push ncurses drawing out in separate files for now. Made alsa and fifo files, but haven't gotten around to move the code yet. 

It looks like it's plausible, but I have never done anything similar before. So any hints/tips much appreciated, thanks!

**Comment by karlstav** [comment]
ok so I was knee deep in errors and warnings just testing out different hunches of how to pass data  back and from threads. Then after doing some minor changes I compile... no errors(!) not even a warning, not possible. I run... and it works! Still can't believe it. 

Will do allot more testing, hoping to get some external testing too. Planning to change the modules branch to master branch after it can be confirmed as stable.

**Comment by CelestialWalrus** [comment]
@karlstav you should get rid of daemon-mode and ncurses branches. Creating FIFO output will be easy with modules, so no need for daemon-mode.

**Comment by CelestialWalrus** [comment]
@karlstav After testing it for ~2 weeks I'm sure the modules branch is bug-free.
