### ISSUE TITLE
Bars are not vertically contiguous in alacritty with font line spacing > 0.

### ISSUE THREAD

**Issue by mkrasnitski** [karlstav/cava#393]
**Describe the bug**
Using cava with alacritty and having font y-offset (basically line spacing) take on a value > 0 causes gaps to appear between the colored blocks in each bar.

**To Reproduce**
Run in alacritty with font y-offset > 0. Below are the alacritty settings I'm using to reproduce this:
```
font:
  normal:
    family: DejaVu Sans Mono Nerd Font
  size: 11.0
  offset:
    x: 0
    y: 1 # This is what causes the issue
```

**Expected behavior**
Would be best if the blocks were contiguous. Urxvt allows for increasing the line spacing, but no matter what `URxvt*lineSpace` is set to, the bars are contiguous. I'm thinking the way alacritty applies the offset is done universally (to keep the glyph height the same for all glyphs), so maybe this is an alacritty issue, and a special case should be made for color blocks? Let me know what you think.

**Screenshots**
Here with offset = 1 
![image](https://user-images.githubusercontent.com/42564254/99605505-cf711680-29d5-11eb-8c87-4e6bc117f716.png)

Here with offset = 10
![image](https://user-images.githubusercontent.com/42564254/99605734-48706e00-29d6-11eb-9938-127d02945e1f.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Kernel 5.9.8

**Terminal emulator**
alacritty 0.6.0-dev (5fd792fc)

**Comment by karlstav** [comment]
hi @mkrasnitski 

As far as I understand this is expected behavior. If there are space between the lines then there would be no way to make the bars contiguous. This is because the bars consist of characters just like everything else in the terminal (box-drawing characters).

Are you sure the line spacing option in urxvt is working correctly? I would expect the same behavior there.

I have seen similar behavior in some fonts where the bar glyphs don't fill out the entire line height.

**Comment by mkrasnitski** [comment]
Here's a screenshot of urxvt with `URxvt*lineSpace` set to 10 in `.Xresources`.

![image](https://user-images.githubusercontent.com/42564254/99702380-b151f780-2a63-11eb-9e68-f192945861d9.png)
![image](https://user-images.githubusercontent.com/42564254/99702433-c29b0400-2a63-11eb-9107-a32c3a605fdb.png)

As a side note, the only reason I have an offset set to 1 in alacritty is to match the look of urxvt, after switching from it. For some reason, there's a 1 pixel line space by default, regardless of what you set `lineSpace` to.

**Comment by mkrasnitski** [comment]
Another thing I've discovered. Seems like alacritty already supports this for some characters. For example, if I set line spacing to something like 20, things like my powerlevel10k prompt and my cursor are stretched to fill the line. 

![image](https://user-images.githubusercontent.com/42564254/99704837-e9a70500-2a66-11eb-8704-0e89f6d59e48.png)

This also happens for my vim statusline, as seen in the screenshot in my previous post.

**Comment by karlstav** [comment]
The prompt and statusbar are probably using background color (not a character) and the cursor is also not really a character (as far as I know). 

Are you sure that you are using the exact same font? If so I  think the issue is related to how alacritty handels the y offset. There seems to be some other issues related to it.

**Comment by mkrasnitski** [comment]
Yes, the same font is being used for urxvt and alacritty. What issues have you seen related to the y offset? The behavior itself seems to make sense. Maybe setting the background color for each cell in cava is the answer?

**Comment by karlstav** [comment]
https://github.com/alacritty/alacritty/issues/485

This issue makes me think y offset and line spacing might not be the same thing. 

Changing background color might work, but will require some rewriting and might cause some performance issues.

**Comment by mkrasnitski** [comment]
The solution to that issue came in the form of a `glyph_offset` option in alacritty, which changes where within the cell the glyph actually starts. It doesn't control the line spacing. The `offset` option, on the other hand, controls line spacing, at least I'm pretty sure that's the only way to do it...

For reference, here's a y-glyph_offset of 5. As you can see, it moves the glyph up within the cell, but doesn't change the line spacing.
![image](https://user-images.githubusercontent.com/42564254/99738542-b7ae9680-2a98-11eb-8295-addb7c2ea34d.png)

**Comment by karlstav** [comment]
Anyway, I think this is an issue with how alacritty handles line spacing. Maybe you should try opening an issue with them?

**Comment by mkrasnitski** [comment]
Welp, seems like the behavior is intended. What say you, what's the best way to address this issue? Even if you change the background color of the cell, it might be impossible to make it smooth, especially with large gaps. Since it's not possible to only set part of the background to a given color, it would look really choppy on anything other than small line spacings.

**Comment by karlstav** [comment]
maybe make a note [here](https://github.com/karlstav/cava#in-terminal-emulators) in the readme. I sort of already do that:

> Also character spacing affects the look of the bar spectrum.

but maybe it can be elaborated a bit more.

**Comment by rameltranquille** [comment]
I may be late and noobish. I believe that you can make your offset.y=-1. I believe that alacrity already has spacing by default so negative spacing fixes the issue for me. 

```
alacritty -o font.offset.y=-1
```
Opens a new terminal to test it out. 

New output in alacritty 
![image](https://user-images.githubusercontent.com/43153816/127758593-fab230a3-76de-4827-91d5-bef8bfd0c257.png)
