### ISSUE TITLE
allow running with a readonly configuration

### ISSUE THREAD

**Issue by jukefr** [karlstav/cava#396]
**Is your feature request related to a problem? Please describe.**
I run Nixos.
I have a declarative way of setting a cava config file with something called `home-manager`
It creates the config file at `.config/cava/config` with user:users permissions but it is readonly (to make sure that no program makes any changes and breaks the "functional stateless" nature of nix configs.

**Describe the solution you'd like**
It would be nice if cava could run on a config without writing permissions when not available.

**Describe alternatives you've considered**
I could just manage the dotfile with stow and make it not managed by nixos but it kind of defies the purpose of what I am trying to achieve.
I have used the same solution for ranger and neofetch, they both don't have write permissions but they run with no problems.

**Additional context**
Nixos/Nix is a way to make declarative os installs.
Which means that ideally the configurations are generated and managed by a runtime.
Allowing other programs to modify this configuration would break the "state". If I reinstall the same exact Nixos setup the configuration file would be different, it should not.
This is why they do not allow writing to the config file for context.

**Comment by jukefr** [comment]
For reference I get the following error 
```
Error loading config. Unable to open file '/home/user/.config/cava/config', exiting...
```

**Comment by jukefr** [comment]
Also it might not be a permission error, I'm not actually sure what the problem is i cant find a debug tag on the cava options

The default config file cava creates is user:users with 644
When I use home-manager its a symlink to the nix store and its user:users with 777 (but you can't write to the nix store by nature of it)

So maybe the fact that it has the permissions set to 777 is what is the problem...

**Comment by karlstav** [comment]
Well I don't understand why I open it with write permissions when the config file path is specified. If cava is ran without explicitly specifying the config file path, I want it to create a file if it doesn't exist, but I guess it can be done without opening it for writing.

Try removing the plus sign on line 405 in config.c

(I'm on mobile, so can't test now.)

**Comment by SeraphyBR** [comment]
Thanks!. I was having this problem now, I did an overlay to use the cava of this commit, it's working
