### ISSUE TITLE
Occasional lack of bar data?

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#400]
Hi Karl

I am seeing "flashing" of the spectrum with mpd_oled (which reads the bars from raw output)

I wonder whether this might be the same issue: https://github.com/karlstav/cava/issues/397

Here is my Cava config
```
[general]
framerate = 25
bars = 21

[input]
method = fifo
source = /tmp/mpd_oled_fifo

[output]
method = raw
data_format = binary
channels = mono
raw_target = /tmp/cava_fifo_23328
bit_format = 8bit
```
It is happenning on Debian (jessie and buster) on a Raspbarry Pi (Pi 0 and Pi 3). The input is music. At random intervals of maybe 1 second to 20 seconds the spectrum will flash, presumably because no data is read (at times the flash clearly shows the spectrum bars are missing).

Investigating on a Pi Zero, I have tracked down the commit where the behaviour is introduced: https://github.com/karlstav/cava/commit/3006603628af84698dd1d87f22af4633446f4cbb
```
cava -v
cava 0.7.2-48-g3006603
```
The previous commit (cava 0.7.2-47-g38c096b) does not show any flashing.

[ It could be a red herring but, on tests switching between the two commits, the commit with the flashing consistently uses slightly less CPU  (maybe 5% less) than the commit without the flashing.]

A lack of bar data in mpd_oled may also be the way mpd_oled is reading the data, in which case perhaps you might have some idea what might have changed in the raw data with this commit. 

Adrian.

**Comment by karlstav** [comment]
it is expected to be lower cpu usage, since the `FFTtreblebufferSize`sets the buffer size of the audio input, smaller audio buffer -> higher cpu usage.

reading the fifo input code I just can't see why this should cause the described behavior.  What is the format in the mpd fifo output?

does the issue go away if you simply set `audio.FFTtreblebufferSize` to 1024?

**Comment by antiprism** [comment]
Hi Karl

Thanks for looking at this. After some more investigating this morning I am fairly sure it is not a Cava issue. I think it is an mpd_oled timing issue, which is sensitive in some way to the change of buffering that happened at this commit. In particular, mpd_oled will scroll a song name if it is too long to fit on the screen, and if I disable the scrolling then the flashing does not occur for me with the latest Cava. I'll confirm this and then close the issue.

Thanks

Adrian.

**Comment by antiprism** [comment]
Hi Karl

The disabled scrolling didn't stop the flashing! However I have reviewed the mpd_oled timing code and have made a change that appears to have stopped the occasional flashing with the newer versions of Cava.

This isn't an issue with Cava. Thanks again for your help!

Adrian.

**Comment by karlstav** [comment]
good to know!
