### ISSUE TITLE
Flag to detect if Cava-Output/Input is Active

### ISSUE THREAD

**Issue by Maschine2501** [karlstav/cava#401]
Hi!
As discussed in a previous Issue (https://github.com/karlstav/cava/issues/370) I requestet assistance, cause cava interupts the output after a specific time.
The Informations you geve me, led to a good solution.
But!
Many of the users of my code use several Plugins, which don't always behave like a normal sound source.
This results in: Cava stops the output afte X seconds (even if music is playing) and my code with spectrum freezes.
I want to prevent this.

Here is my Idea: A "Flag" or Signal that indicates that cava actively has an input signal.
Is this possible? Have you an Idea how to make this possible?

Best wishes,

Christoph

PS:
I have two Cava instances running as a service in background.
Input is routed to Cava by mpd.conf.
Output of cava is routed to /tmp/cava_fifo   /  /tmp/cava2_fifo

**Comment by karlstav** [comment]
i sort of added this a while back, forgot to reference the issue in question:

https://github.com/karlstav/cava/commit/808716e7699dec1fe34ea8263c6694509b925efe

**Comment by Maschine2501** [comment]
That was a really quick answer!
I will try it tommorow, after that I'll give you feedback.
Many thanks!!!

**Comment by Maschine2501** [comment]
It has worked!
Many Thanks!
