### ISSUE TITLE
Idea: CAVA modules system?

### ISSUE THREAD

**Issue by nikp123** [karlstav/cava#402]
Firstly, no, the feature is not related to any issue. It's more of a development/design idea. Anyway,  hi @karlstav, I have recently made a modules system for my fork xava, whereby the visualizer loads inputs and outputs through library files (I've named it a "modules system"). This was done so that making small modifications and tweaks becomes much easier for the dev and end-user. However it required me to make a partial rewrite of the visualizer to make it work.

Let's say someone wanted to make changes to a existing output but adding a horizontal gradient. The person could fork just the output, without tainting the entire source code. And to install that change on a newer version of the visualizer, all he would have to do is to move the library file where necessary thereby descreasing maintenance costs.

Another benefit is that we would (cava and xava) be finally able to share source code without manually making sure it worked, because the "modules system" would guarantee that it works.

However this would unfortunately require a big redesign and I dont want to bother you with additional effort if you dont find it useful. And we would have to agree upon an API which works for both visualizers in this case.

Link to XAVA with the "modules system": https://github.com/nikp123/xava/tree/unstable

I would like to hear your thoughts on this  :)

**Comment by nikp123** [comment]
This issue might solve #260

**Comment by karlstav** [comment]
yea, this has been in the back of my mine, but no time to do any actual work on it.

I think this will be very much the same as discussed in #260. so let's continue the discussion there.
