### ISSUE TITLE
I can't any output

### ISSUE THREAD

**Issue by denstiny** [karlstav/cava#403]
My operating system is manjaro puseaudio

![image](https://user-images.githubusercontent.com/57088952/113280799-5f758400-9317-11eb-8b3d-f343bbba295c.png)
I copied the default configuration file, what did I do wrong

**Comment by karlstav** [comment]
Hi

If the volume is low on the application side it might just take some time
for the auto sense to kick in. How long have you tried leaving it running
with audio playing?

If still nothing happens after a minute or so give me the output of the
following commands:


pacmd list-sinks

pacmd list-sources

pacmd list-clients


With cava running.

**Comment by denstiny** [comment]
i,m ok

**Comment by Amogh-Mittal** [comment]
I'm having the same issue and it doesn't fix even after waiting for a few mins, also I didn't had the issue back when i was on ubuntu, but it's not working after I've switched to Arco (arch based). Also cava came pre-installed in arco
Here are the outputs with cava running:

> pacmd list-sinks
1 sink(s) available.
  * index: 0
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: RUNNING
	suspend cause: (none)
	priority: 9039
	volume: front-left: 17071 /  26% / -35.05 dB,   front-right: 17071 /  26% / -35.05 dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: no
	current latency: 551.20 ms
	max request: 168 KiB
	max rewind: 168 KiB
	monitor source: 1
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	used by: 1
	linked by: 1
	configured latency: 980.00 ms; range is 0.50 .. 2000.00 ms
	card: 1 <alsa_card.pci-0000_00_1b.0>
	module: 7
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "ALC662 rev1 Analog"
		alsa.id = "ALC662 rev1 Analog"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xfe400000 irq 30"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "1c20"
		device.product.name = "6 Series/C200 Series Chipset Family High Definition Audio Controller"
		device.form_factor = "internal"
		device.string = "front:0"
		device.buffering.buffer_size = "352800"
		device.buffering.fragment_size = "176400"
		device.access_mode = "mmap+timer"
		device.profile.name = "analog-stereo"
		device.profile.description = "Analog Stereo"
		device.description = "Built-in Audio Analog Stereo"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	ports:
		analog-output-lineout: Line Out (priority 9000, latency offset 0 usec, available: yes)
			properties:
				
		analog-output-headphones: Headphones (priority 9900, latency offset 0 usec, available: unknown)
			properties:
				device.icon_name = "audio-headphones"
	active port: <analog-output-lineout>




> pacmd list-sources

2 source(s) available.
  * index: 0
	name: <alsa_input.usb-Generic_USB2.0_PC_CAMERA-02.mono-fallback>
	driver: <module-alsa-card.c>
	flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE
	priority: 9040
	volume: mono: 65536 / 100% / 0.00 dB
	        balance 0.00
	base volume: 29488 /  45% / -20.81 dB
	volume steps: 65537
	muted: yes
	current latency: 0.00 ms
	max rewind: 0 KiB
	sample spec: s16le 1ch 48000Hz
	channel map: mono
	             Mono
	used by: 0
	linked by: 0
	configured latency: 0.00 ms; range is 0.50 .. 2000.00 ms
	card: 0 <alsa_card.usb-Generic_USB2.0_PC_CAMERA-02>
	module: 6
	properties:
		alsa.resolution_bits = "16"
		device.api = "alsa"
		device.class = "sound"
		alsa.class = "generic"
		alsa.subclass = "generic-mix"
		alsa.name = "USB Audio"
		alsa.id = "USB Audio"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		alsa.device = "0"
		alsa.card = "1"
		alsa.card_name = "USB2.0 PC CAMERA"
		alsa.long_card_name = "Generic USB2.0 PC CAMERA at usb-0000:00:1a.0-1.2, high speed"
		alsa.driver_name = "snd_usb_audio"
		device.bus_path = "pci-0000:00:1a.0-usb-0:1.2:1.2"
		sysfs.path = "/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.2/sound/card1"
		udev.id = "usb-Generic_USB2.0_PC_CAMERA-02"
		device.bus = "usb"
		device.vendor.id = "1908"
		device.vendor.name = "GEMBIRD"
		device.product.id = "2310"
		device.product.name = "USB2.0 PC CAMERA"
		device.serial = "Generic_USB2.0_PC_CAMERA"
		device.form_factor = "webcam"
		device.string = "hw:1"
		device.buffering.buffer_size = "192000"
		device.buffering.fragment_size = "96000"
		device.access_mode = "mmap+timer"
		device.profile.name = "mono-fallback"
		device.profile.description = "Mono"
		device.description = "USB2.0 PC CAMERA Mono"
		module-udev-detect.discovered = "1"
		device.icon_name = "camera-web-usb"
	ports:
		analog-input-mic: Microphone (priority 8700, latency offset 0 usec, available: unknown)
			properties:
				device.icon_name = "audio-input-microphone"
	active port: <analog-input-mic>
    index: 1
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo.monitor>
	driver: <module-alsa-card.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: IDLE
	suspend cause: (none)
	priority: 1030
	volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: no
	current latency: 0.00 ms
	max rewind: 168 KiB
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 0
	configured latency: 2000.00 ms; range is 0.50 .. 2000.00 ms
	monitor_of: 0
	card: 1 <alsa_card.pci-0000_00_1b.0>
	module: 7
	properties:
		device.description = "Monitor of Built-in Audio Analog Stereo"
		device.class = "monitor"
		alsa.card = "0"
		alsa.card_name = "HDA Intel PCH"
		alsa.long_card_name = "HDA Intel PCH at 0xfe400000 irq 30"
		alsa.driver_name = "snd_hda_intel"
		device.bus_path = "pci-0000:00:1b.0"
		sysfs.path = "/devices/pci0000:00/0000:00:1b.0/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "1c20"
		device.product.name = "6 Series/C200 Series Chipset Family High Definition Audio Controller"
		device.form_factor = "internal"
		device.string = "0"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"



> pacmd list-clients

7 client(s) logged in.
    index: 0
	driver: <module-systemd-login.c>
	owner module: 19
	properties:
		application.name = "Login Session 2"
		systemd-login.session = "2"
    index: 4
	driver: <protocol-native.c>
	owner module: 12
	properties:
		application.name = "Qtile-pulse"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "1530"
		application.process.user = "amogh"
		application.process.host = "i-use-arch-btw"
		application.process.binary = "python3.10"
		application.language = "C"
		window.x11.display = ":0"
		application.process.machine_id = "0b859e3dca4944428d5e983b3b8fcc10"
		application.process.session_id = "2"
    index: 7
	driver: <protocol-native.c>
	owner module: 12
	properties:
		application.name = "Spotify"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "4313"
		application.process.user = "amogh"
		application.process.host = "i-use-arch-btw"
		application.process.binary = "spotify"
		application.language = "en_IN"
		window.x11.display = ":0"
		application.process.machine_id = "0b859e3dca4944428d5e983b3b8fcc10"
		application.process.session_id = "2"
		application.icon_name = "spotify-client"
    index: 8
	driver: <protocol-native.c>
	owner module: 12
	properties:
		application.name = "WEBRTC VoiceEngine"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "5451"
		application.process.user = "amogh"
		application.process.host = "i-use-arch-btw"
		application.process.binary = "Discord"
		application.language = "en_IN"
		window.x11.display = ":0"
		application.process.machine_id = "0b859e3dca4944428d5e983b3b8fcc10"
		application.process.session_id = "2"
    index: 9
	driver: <protocol-native.c>
	owner module: 12
	properties:
		application.name = "Chromium input"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "5488"
		application.process.user = "amogh"
		application.process.host = "i-use-arch-btw"
		application.process.binary = "Discord"
		application.language = "en_IN"
		window.x11.display = ":0"
		application.process.machine_id = "0b859e3dca4944428d5e983b3b8fcc10"
		application.process.session_id = "2"
    index: 15
	driver: <protocol-native.c>
	owner module: 12
	properties:
		application.name = "Google Chrome input"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "35"
		application.process.id = "8943"
		application.process.user = "amogh"
		application.process.host = "i-use-arch-btw"
		application.process.binary = "chrome"
		application.language = "en_IN"
		window.x11.display = ":0"
		application.process.machine_id = "0b859e3dca4944428d5e983b3b8fcc10"
		application.process.session_id = "2"
    index: 33
	driver: <cli.c>
	owner module: 26
	properties:
		application.name = "UNIX socket client"

**Comment by Amogh-Mittal** [comment]
Ok fixed it the cava package from pacman is broken, I installed from source and now it's working :)

**Comment by Amogh-Mittal** [comment]
ok, now I realise I'm stupid, coz my whole config is commented and what actually fixed was the restart (as qtile created a virtual speaker because I changed something in the config and restart fixed that extra device), and I also realised that cava was using the 1st registered device which was incorrect but obviously the intended behaviour.
