### ISSUE TITLE
Error when installing from AUR

### ISSUE THREAD

**Issue by thikkachu** [karlstav/cava#406]
I am using `yay` as my pacman frontend.
Running Arch Linux 5.12.3 with KDE Plasma X11 (dont think thats important but still here just in case).
konsole 21.04.1 as the terminal.

This is most likely an issue on my end but posting here just in case. When trying to install cava on my arch system (both from source and from AUR) it returns an error:
`input/common.c:21:57: error: argument 2 of type ‘int16_t[(int)frames * 2]’ {aka ‘short int[(int)frames * 2]’} declared with mismatched bound ‘(int) frames * 2’ [-Werror=vla-parameter]
   21 | int write_to_fftw_input_buffers(int16_t frames, int16_t buf[frames * 2], void *data) {
      |                                                 ~~~~~~~~^~~~~~~~~~~~~~~
In file included from input/common.c:1:
./input/common.h:42:57: note: previously declared as ‘int16_t[(int)frames * 2]’ {aka ‘short int[(int)frames * 2]’} with bound ‘(int) frames * 2’
   42 | int write_to_fftw_input_buffers(int16_t frames, int16_t buf[frames * 2], void *data);
      |                                                 ~~~~~~~~^~~~~~~~~~~~~~~
cc1: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make[1]: *** [Makefile:644: input/cava-common.o] Error 1
make[1]: Leaving directory '/home/username/.cache/yay/cava-git/src/cava'
make: *** [Makefile:820: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
error making: cava-git`

As far as I know, this is an issue that occurs during the make. Apologies, I am still quite unknowledgeable in the deeper parts of Linux and I'm also new to reporting github issues. If I could do anything better to make me a better issue reporter please tell me (I'm fine with harsh insults so please use them :) )

**To Reproduce**
1. Use an AUR helper to install cava
2. `yay -S install cava`
3. `Makefile error`

**Expected behavior**
Cava successfully installs or returns a different error.

**Comment by karlstav** [comment]
this is related to #405 , I will merge it and draft a release.
