### ISSUE TITLE
Cava not using output when using PipeWire, displaying visualizer for input (microphone)

### ISSUE THREAD

**Issue by howardjs** [karlstav/cava#408]
**When/where was the bug introduced?**
When I began using PipeWire around a week ago. I am using PipeWire from official Arch repositories and I am using Cava from the AUR.

**Describe the bug**
Cava is not visualizing the audio that is going to my output (headphones), but is visualizing the audio that comes from my input (microphone).

**To Reproduce**
1. Install `cava-git` from the AUR on an Arch-Linux machine.
2. Install PipeWire as a replacement for PulseAudio
3. Run Cava

**Expected behavior**
I expected Cava to visualize the audio going to my output.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling (kernel `5.12.9-zen1-1-zen`)

**Terminal emulator**
- name: `rxvt-unicode` (from official Arch repositories)
- version: 9.26-2

**Comment by howardjs** [comment]
It was an issue with my audio setup, sorry

**Comment by thelazyoxymoron** [comment]
Hi @ghost, I'm facing the same issue with my machine. Can you please describe what was the issue with your audio setup?
