### ISSUE TITLE
Feature request: custom freq cutoff

### ISSUE THREAD

**Issue by CelestialWalrus** [karlstav/cava#41]
I can't figure out how to do this and would like to make it 220-370 instead of 20-12000 Hz.

**Comment by karlstav** [comment]
Great idea! Should be possible, but the calculation is a bit messy:

```
fc[n] = 10000 * pow(10, -2.37 + ((((float)n + 1) / ((float)bands + 1)) * 2.37));
```

I don't even remember what I was thinking...

It seems it only runs to 10k not 12k as it says in the reamdme...

The lower will change slightly with the number of bars, so for 25 bars it will be ~44Hz for 60 bars ~47Hz. 

I have to do some cleaning of the algorithm, but I hope to implement the feature sometime soon. 

Out of curiosity, why 220 - 370?

**Comment by CelestialWalrus** [comment]
> why 220 - 370

I've experimented with audio waveform in AE CS6.

**Comment by karlstav** [comment]
@CelestialWalrus this feature is soon ready, I'll push 0.3.3 then. hopefully already tomorrow..

**Comment by karlstav** [comment]
This was a bit harder then previously expected, so I'm pushing 0.3.3 without it.

As I should have known cava's minimum resolution is 43Hz. I.e. one bar has a minimum frequency span of 43Hz and having 50 bars gives you a minimum of 2150Hz span from the lowest to the highest bar. Increasing the resolution will make cava slower and more cpu heavy.

So how to solve the problem of user setting a narrower band then possible? In your case @CelestialWalrus there can be no more then `(370-220)/43 = 3,48` 3-4 bars (the forth bar would be outside the specified band). 

Should cava increase the band or reduce the number of bars?

**Comment by CelestialWalrus** [comment]
@karlstav IMO increase the band.

**Comment by karlstav** [comment]
@CelestialWalrus should be implemented now. The config file is not overwritten (if it already exists) so the new parameters must be manually inserted in to the config file.

**Comment by CelestialWalrus** [comment]
@karlstav: thanks, I'll test if it works and report back later.

**Comment by karlstav** [comment]
done, maybe it even could be done better in the feature. Bandwith resoultion could perhaps be improved as an option that whould also sacrifice cpu usage and/or speed.
