### ISSUE TITLE
MacOS: Cannot run/see cava visualizer

### ISSUE THREAD

**Issue by Zaitam** [karlstav/cava#411]
**Describe the bug**

**To Reproduce**
1. Install Cava
2. run

**Expected behavior**
See the an audio Visualiser

**Screenshots**
<img width="1330" alt="Screen Shot 2021-08-21 at 18 27 57" src="https://user-images.githubusercontent.com/71014214/130335202-b42169dd-15ed-41c9-ba13-0635366a683c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.4

**Terminal emulator**
- iTerm

**Additional context**
I just recived `sh: setterm: command not found` twice

**Comment by karlstav** [comment]
Sounds like locale is not set up properly. Look here:

https://stackoverflow.com/questions/7165108/in-os-x-lion-lang-is-not-set-to-utf-8-how-to-fix-it

Might be outdated, but the concept should be the same.

**Comment by Zaitam** [comment]
Thanks!
I tought I already had done that, but if forgot to save it to the `.zshrc` file
