### ISSUE TITLE
Extremely high CPU usage from /usr/libexec/Xorg when running Cava on st

### ISSUE THREAD

**Issue by Spilskinanke** [karlstav/cava#412]
Currently running Fedora 34 i3 flavor, downloaded latest edition of cava from the repository. So long as a song is playing cava will cause that particular st shell to jump to about 20%, and /usr/libexec/Xorg to about 50%. Reading about this elsewhere for other terminals such as alacritty leads me to believe that it's actually something about the terminal updating as frequently as is allowed to display the information, but I figure there must be some way in cava to limit it's use. It's not really a bug I suppose, but I'm not sure who would want over 50% of their CPU to be used up by a music display program.

**Comment by karlstav** [comment]
hi @Spilskinanke 

sorry, but I somehow missed the notification about issue.

there are some factors affecting cpu usage:

1) the framerate in the cava config, try lowering for reducing cpu usage:

https://github.com/karlstav/cava/blob/4c0acb788535beac6b3c142d5a8abc9aee4cf93e/example_files/config#L10

2) the size of the terminal/font. more characters to draw => more cpu usage

3) output mode in the cava config:

https://github.com/karlstav/cava/blob/4c0acb788535beac6b3c142d5a8abc9aee4cf93e/example_files/config#L83

generally the noncurses mode can use a lot less cpu, but with smaller terminal windows the difference is not that great.

I have also stumbled upon a bug in the nvidia drivers that caused a lot of cpu usage if the framerate was set higher than (or just close to) the monitor refresh rate. But I think that is only for hardware accelerated terminals.

**Comment by clort81** [comment]
I have experienced a number of causes of slowdowns.
- xft font rendering raspberry pi 3 - unbearablly slow, even in IRC
- compositing windowmanagers having issues with drivers
- truetype fonnts vs pcf (bitmap fonts).

I have made some 'benchmarks' for terminal graphics drawing, which helped me narrow down cause and effect.  I found xterm to suck least for my uses.
