### ISSUE TITLE
Cava questions

### ISSUE THREAD

**Issue by alexfeed1990** [karlstav/cava#414]
How do i enable gradients in cava? If the gradient value is 1:

![image](https://user-images.githubusercontent.com/76942911/136046454-f074da3f-e8c1-4dca-8e36-6007f06fdd67.png)

should'nt it be enabled by default?

Also, the cava background disables transparency in picom. As we see here side by side with a normal terminal:

![image](https://user-images.githubusercontent.com/76942911/136047031-5a08a88e-5e9b-4b9e-9050-97720c1c8057.png)

Any way to fix that?

**Comment by karlstav** [comment]
gradient is actually not enabled by default. the default config file is wrong, I will fix that. just uncomment to enable.

regarding transparency, it should work fine as long as background color is left unconfigured.
