### ISSUE TITLE
Sigill by libfftw3 on aarch64 - it's debian's problem. But just FYI

### ISSUE THREAD

**Issue by clort81** [karlstav/cava#416]
cava crashes with SIGILL on aarch64.
Devuan ceres, gcc 11.2
libfftw3-3 Version: 3.3.8-2

**Describe the bug**
```
(gdb) run
Starting program: /media/sdb2/Projects/Audio/cava/cava 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000fffff7c1108c in fftw_codelet_t1_4 () from /lib/aarch64-linux-gnu/libfftw3.so.3
(gdb) bt
#0  0x0000fffff7c1108c in fftw_codelet_t1_4 () from /lib/aarch64-linux-gnu/libfftw3.so.3
#1  0x0000fffff7c00904 in fftw_solvtab_exec () from /lib/aarch64-linux-gnu/libfftw3.so.3
#2  0x0000fffff7c85f14 in fftw_configure_planner () from /lib/aarch64-linux-gnu/libfftw3.so.3
#3  0x0000fffff7c892f0 in fftw_the_planner () from /lib/aarch64-linux-gnu/libfftw3.so.3
#4  0x0000fffff7c85ce4 in fftw_mkapiplan () from /lib/aarch64-linux-gnu/libfftw3.so.3
#5  0x0000fffff7c88d24 in fftw_plan_many_dft_r2c () from /lib/aarch64-linux-gnu/libfftw3.so.3
#6  0x0000fffff7c88388 in fftw_plan_dft_r2c () from /lib/aarch64-linux-gnu/libfftw3.so.3
#7  0x0000fffff7c8828c in fftw_plan_dft_r2c_1d () from /lib/aarch64-linux-gnu/libfftw3.so.3
#8  0x0000aaaaaaaa4458 in main ()
```

**To Reproduce**
* Build cava (latest git master) on aarch64 with debian libfftw3-3 Version: 3.3.8-2
* Run it and watch it SIGILL 

**To Fix**
- apt-get build-dep libfftw3-3
- apt-get source libfftw3-3
- cd to the dir and dpkg-buildpackage -rfakeroot -b -uc -us -nc
- cd up and sudo dpkg -i libfftw3*.deb
- apt-get build-dep cava
- git clone cava master and build it

**Comment by clort81** [comment]
I should add this is exactly the toy i wanted to make when i saw we had  ▁▅▆▅▆▅▃▃▂
Thank you for doing such a great job with it! 
If libfftw3 is a problem for more people maybe consider an alternate cheapo fast-fft.

**Comment by karlstav** [comment]
good to know, @clort81! 

Feel free to sugest some alternative fft librabry. I have been meaning to looks for something a bit lighter, but never gotten around to it.

**Comment by clort81** [comment]
Time permitting, I'll study cava some more and see what the requirements are.

I've been making unicode art since 2017 and written a few little programs.  Cava inspires me to do better and polish my work to be presentable.

Here's a perl meditation.  
[](https://gist.github.com/clort81/fb7d06f53d778b9226eedcd2259353f7
)
