### ISSUE TITLE
cava_LDFLAGS are hardcoded

### ISSUE THREAD

**Issue by chincheta0815** [karlstav/cava#419]
Hej there,

I am building a forumula for homebrew:
https://github.com/Homebrew/homebrew-core/pull/89820

So far everything works well, but they asked whether it would be possible to make cava_LDFLAGS in Makefile.am more versatile.
The options for linking against libraries are right now hardcoded (rpath and -L paths) for a reason I do not understand.
Having them more configurable or even "empty" would be better...

**Comment by carlocab** [comment]
For context, the `/usr/local` references cause build failures with Clang (the system compiler) on macOS when `/usr/local/lib` does not exist.

**Comment by karlstav** [comment]
hi @chincheta0815,

homebrew sounds cool.

this hack was added years ago (when I had no idea what I was doing) to fix an issue with rasbian (or just old debian/ubuntu) see #84, #144, #200.

I am not able to reproduce it now. I will simply remove the setting of these flags from the Makefaile. if something blows up I will just have to fix it properly next time.
