### ISSUE TITLE
Treble sensitivity

### ISSUE THREAD

**Issue by CelestialWalrus** [karlstav/cava#42]
Pre-e2a1265:

![2_114](https://cloud.githubusercontent.com/assets/6376571/8638881/76de0046-2896-11e5-8a55-17bead8486e5.png)

Post-e2a1265:

![2_113](https://cloud.githubusercontent.com/assets/6376571/8638883/7d710fac-2896-11e5-8ed1-116835ea8e74.png)

The bass is now recessed.

It happens with at least 10 tracks on my playlist. (probably more, only checked with ten)

**Comment by karlstav** [comment]
For me base was too high before :confused: I guess this varies a lot with the music. There should be a configurable "equalizer".  (yet another thing for the todo file)

You can play around with the numbers on line 386:
```
			n++)k[n] = pow(fc[n],0.85) * ((float)height/(M*4000));
```


Try decreasing the number 0.85 until you find your preferred value. Previously it was 0.62. Note that the sensitivity will be generally reduced as well, so you will have to compensate.

**Comment by CelestialWalrus** [comment]
@karlstav which format should I use for config files? INI seems like a good choice (weechat, termite).

**Comment by karlstav** [comment]
@CelestialWalrus If INI would mean a config file structured like this
```
#CONFIG FILE
paramter1=value1
;parameter2=value2
```
where ; is used to comment out a line and # are used for a block of comments. Then yes.

I'm seeing a great potential to increase user experience with this config file. So I'll create a separate issue for its development.
