### ISSUE TITLE
build error with SDL enabled in macOS

### ISSUE THREAD

**Issue by shadows1003929** [karlstav/cava#423]
**Describe the bug**
make fails

**To Reproduce**
1. macbook air (monterey)
2. make command after running ./configure in cava directory
3. /usr/local/include/SDL2/SDL_stdinc.h:482:5: error: implicit declaration of function 'memset_pattern4' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    memset_pattern4(dst, &val, dwords * 4);

**Expected behavior**
for the make to succeed

**Terminal emulator**
- iterm2
- 3.4.12

![Screenshot 2021-12-01 at 8 43 25 PM](https://user-images.githubusercontent.com/70201060/144260565-77cc2956-337f-430a-badf-c7423be66594.png)

sorry, looks congested becks was trying to solve the problem

**Comment by karlstav** [comment]
this is a very real bug that I came across when making the sdl implementation. just forgot to fix. will take a look now.

**Comment by karlstav** [comment]
fixed by setting 
```
#include <SDL2/SDL.h>
```
before 

```
#include <stdbool.h>
#include <stdlib.h>
```
instead of after

**Comment by shadows1003929** [comment]
ok
