### ISSUE TITLE
FreeBSD not detected as supported OS in configure

### ISSUE THREAD

**Issue by FernandoBryant** [karlstav/cava#424]
I would like to see support for FreeBSD 13.0 Current, if possible.
thank you. :)

**Comment by karlstav** [comment]
there is sndio support, does it not work?

https://github.com/karlstav/cava#sndio

**Comment by FernandoBryant** [comment]
When compiling cava it gives me the error below:
configure: Checking OS
configure: error: "OS freebsd13.0 is not supported"
That's why I opened this request.

**Comment by karlstav** [comment]
Oh, that's understandable. I needed an os check for sorting out some differences between macos and Linux. And I just forgot that freeBSD existed. Will look into it.

**Comment by karlstav** [comment]
@FernandoBryant try now.

**Comment by FernandoBryant** [comment]
It works, thanks.

**Comment by FernandoBryant** [comment]
Closing issue, thank you again.
