### ISSUE TITLE
input from microphone

### ISSUE THREAD

**Issue by Amogh-Mittal** [karlstav/cava#426]
So I just wanna know is there  a way for using my mic as the device cava listens to instead of speakers

**Comment by karlstav** [comment]
you just set the mic as source in your config:

https://github.com/karlstav/cava/blob/03a8c85cf5420a40ea49161feb4a9654848e7006/example_files/config#L61

**Comment by fededraetta** [comment]
I still cannot use pc microphone as cava source device
