### ISSUE TITLE
[help needed] failure in opening stream (ffffd8f2)

### ISSUE THREAD

**Issue by life-the-user** [karlstav/cava#428]
I'm on macOS I have installed cava using brew. The config dir wasn't there so I manually put it there. Background Music is running and I changed everything I could to
`method = portaudio`
`source = "Background Music"`
When running `cava` it displays that error and brakes my session.

**Comment by karlstav** [comment]
if I'm not mistaken ffffd8f2 means `paInvalidChannelCount`

we hardcode this vale to two here:

https://github.com/karlstav/cava/blob/03a8c85cf5420a40ea49161feb4a9654848e7006/input/portaudio.c#L136

could you have more or less channels on your device?

**Comment by karlstav** [comment]
there is also a [known issue](https://github.com/kyleneideck/BackgroundMusic#troubleshooting) with background music that

`Only 2-channel (stereo) audio devices are currently supported for output.`

might be related

**Comment by p0pcat** [comment]
I don't really understand what that means but I assume it means for each headphone, I tried changing the output of background music to vb-cable (and it indicated that there is only 2-channels) and at the beginning my terminal was blank but after some time it gave me same error. Now it gives me that error without being blank.

**Comment by karlstav** [comment]
hi @life-the-user,

sorry for the late reply, finally got around to actually test portaudio on mac and this does indeed happen. Luckily it is a known bug in portaudio. Just reinstall it and it should work fine. 

```
brew reinstall portaudio
```

**Comment by cybardev** [comment]
I installed and set up everything, and this Error was resolved. But now whenever I start cava, it shows the same visualization, regardless of whether something is playing or not.

Is that normal, or is the expected behaviour when nothing is playing, a flat visualizer will be shown, and when something is playing, the audio output will be visualized?

**Comment by karlstav** [comment]
> it shows the same visualization, regardless of whether something is playing or not.

elaborate,  what is "the same"? screenshot?


> is the expected behaviour when nothing is playing, a flat visualizer will be shown

yes.

**Comment by cybardev** [comment]
Like this:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/50134239/160215830-f0392c81-df53-484b-bfeb-62760d1e3e6e.png">

I'm not playing any music, and this appears. I think it's because of my BackgroundMusic installation going wrong. I'll try the other alternative.

**Comment by cybardev** [comment]
Nvm, it suddenly started working. From what I see (for my case), it's definitely because of BackgroundMusic, not cava.

**Comment by karlstav** [comment]
this is an issue with portaudio not cava.

to solve this issue reinstall portaudio:

```
brew reinstall portaudio
```

**Comment by satyajit-ink** [comment]
I have the same error on macOS, i've tried `brew reinstall portaudio`

**Comment by karlstav** [comment]
what is your macos and portaudio version? cava config? is the error code the same?

**Comment by satyajit-ink** [comment]
macOS 12.3.1
portaudio 19.7.0


```
Error: failure in opening stream (ffffd8f2)
```

Config
```
method = portaudio
source = "Background Music"
```

**Comment by karlstav** [comment]
works fine for me on macOS 11.6.4 (no time to upgrade at the moment)

that error code actually means "invalid number of channels". I just pushed a commit to print the portaudio errors as strings instead of hex number. Could there be something with your audio setup. The source needs to be two channels.

**Comment by nisiddharth** [comment]
I'm also getting exactly the same error. I've the same config:
```
method = portaudio
source = "Background Music"
```
and have tried reinstalling portaudio.

**Comment by domogami** [comment]
I'm actually also getting the same error with
Cava Version: `0.8.2.-17-g4515856-dirty`
Portaudio Version: `stable 19.7.0 (bottled), HEAD`
Background Music Version: `0.4.0`
MacOS: 12.4
M1 Max 16 inch
I have already reinstalled all of the packages and upgraded them with `brew upgrade` and I can't seem to figure out the source of this error `Error: failure in opening stream (Invalid number of channels)`. If anyone who has had this error and fixed it can provide a more detailed report of how they were able to debug this it would be greatly appreciated 🙏

My `~/.config/canva/config`
 
```
# ...
[input]
; method = portaudio
; source = "Background Music"

; method = alsa
; source = hw:Loopback,1

; method = fifo
; source = /tmp/mpd.fifo
; sample_rate = 44100
; sample_bits = 16

; method = shmem
; source = /squeezelite-AA:BB:CC:DD:EE:FF
# ...
```

**Comment by karlstav** [comment]
Your relevant config option is comented out. Try to remove the semicolon before

source = "Background Music"


If it still fails, you could try spundflower instead of background music. I recall there was some issues with background music in recent macos versions.

**Comment by domogami** [comment]
> Your relevant config option is comented out. Try to remove the semicolon before
> 
> source = "Background Music"
> 
> If it still fails, you could try spundflower instead of background music. I recall there was some issues with background music in recent macos versions.

Oh my god thank you so much. I cannot believe I didn't realize that the semicolon was a comment! It's working perfectly now! Thank you again for noticing that!
