### ISSUE TITLE
How to start without keyboard??

### ISSUE THREAD

**Issue by aaronnewsome** [karlstav/cava#429]
Thank you for such a great project. I have a system that I've been using for a few years that has audio input (vinyl turntable), and an HDMI connection to the TV.

It uses X-windows and a  bunch of hacks to display a spectrum analyzer of the turntable on a 65inch Vizio, via HDMI on the computer. Everything is set to run automatically on boot and the computer is single purpose, for this purpose only. The computer doesn't have a keyboard and normally isn't connected to the network or anything else, other than the HDMI output to the TV and audio input from the turntable.

I managed to get CAVA installed and working. I just can't figure out how to get the program to start automatically when the computer boots.

I can ssh to it from another linux box and run CAVA, but then the spectrum is displayed on my computer, not the TV!

Has anyone been able to cava to start automatically on boot, fullscreen? Or, am I going to need to dig up a keyboard and start it manually every time? I suppose I could always just start X, as I have been for years now, then launch some kind of terminal from X and start cava there. Any ideas?

**Comment by karlstav** [comment]
hi @aaronnewsome 

you don't need to use x, you can run cava straight in the console (tty). Everything works fine except user defined colors. 

There is a note about launching cava remotely in the [readme](https://github.com/karlstav/cava#running-via-ssh), this will only work in the console (without x).

auto starting will vary from distro to distro.
