### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by karlstav** [karlstav/cava#43]
The config file will in INI format:
```
#CONFIG FILE
paramter1=value1
;parameter2=value2
```

Suggested parameters:
* input method
* alsa device
* fifo path
* output method
* color/background color
* frame rate 
* Sensitivity
* number of bars
* cutoff frequencies
 * High frequency cutoff
 * Low frequency cutoff
* smoothing
 * "integral" smoothing
 * "moster cat" smoothing
 * gravity
* equalizer
 * base
 * mid tone
 * treble

Please make suggestions for other parameters.

Other considerations: 
* Should all parameters be overridable via command line arguments?
* Should all parameters be adjustable real time via keyboard shortcuts?(nice to have)
* Should there be a possibility to save adjusted parameters real time back in to the config file?(nice to have)

@CelestialWalrus has volunteered to do the initial work. Feel free to modify or reject any of my suggestions.

**Comment by CelestialWalrus** [comment]
**Library**: https://github.com/benhoyt/inih

**File path**: `~/.config/cava/config` or `~/.cava/config` (I think the first one is better)

**Example file**:

    [general]
    mode=normal
    framerate=60
    sensitivity=100
    bars=63
    [input]
    method=fifo
    path=/tmp/mpd.fifo
    [output]
    method=terminal
    [color]
    background=white
    foreground=blue
    [smoothing]
    integral=1
    monstercat=1
    gravity=0.66
    [eq]
    bass=1.5
    mid=1.25
    treble=2

> Should there be a possibility to save adjusted parameters real time back in to the config file?(nice to have)

We'd have to find another library.

**Comment by CelestialWalrus** [comment]
So I'm using the inih library in my fork: https://github.com/CelestialWalrus/cava

**Comment by karlstav** [comment]
looks very nice, there should be some explaining as what the different parameters do and what the range/options are.

Also i will have to make cava ready for frequency cutoff parameters and eq setting. Or you can decide range and whats supposed to be "normal/max/min" first then I will implement the functionalities when the rest is complete.

**Comment by CelestialWalrus** [comment]
@karlstav I'll make a pull request, I've got the first four sections to work.

**Comment by anko** [comment]
The environment variable [`$XDG_CONFIG_HOME`](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) is a standard location for configuration files:

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

If we'll have only one config file, just make it `$XDG_CONFIG_HOME/cava`?

**Comment by CelestialWalrus** [comment]
> The environment variable $XDG_CONFIG_HOME is a standard location for configuration files

I don't know how to check for it...

**This segfaults:**


    // config: location
    char *configDirectory = "%s/cava/";
    char *configFile = "config.ini";
    char configPath[255];
    char *coPa = configPath;
    char *xdghome = getenv("XDG_CONFIG_HOME");
    size_t xdghomelength = strlen(xdghome);
    if (xdghomelength == 0) {
        char *home = getenv("HOME");
        size_t homelength = strlen(home);
        if (homelength == 0) {
            printf("No HOME found, exiting...");
            exit(EXIT_FAILURE);
        }
        strcpy(&coPa, home);
        strcat(&coPa, "/.config");
    }


    // config: create empty file
    snprintf(configPath, sizeof(configPath), configDirectory, configPath);
    mkdir(configPath, 0777);
    strcat(configPath, configFile);
    FILE *fp = fopen(configPath, "ab+");
    printf(xdghome);
    exit(EXIT_FAILURE);
    fclose(fp);

I'm a Java/JavaScript dev with no C experience.

**Comment by anko** [comment]
@CelestialWalrus 

I suspect `strlen` is segfaulting if `getenv` returns `NULL`. Do you have `$XDG_CONFIG_HOME` set?

[bspwm's analogous code](https://github.com/baskerville/bspwm/blob/master/bspwm.c#L80-L86) might help.

**Comment by CelestialWalrus** [comment]
@anko: thanks. I'll add [smoothing] section and push it.

**Comment by CelestialWalrus** [comment]
@karlstav the eq works like that smooth array. I'll explain it later.

**Comment by karlstav** [comment]
@CelestialWalrus wow this is really promising, looks like you have gotten a lot of things done already.

The EQ gives no output if it is below 1, but maybe you changed how it worked after you made the example values.

The ini file is also empty when it is created. I think the best way to do it is to populate it with all default values but commented. Like `etc/pulse/client.conf`. Also i think that the .ini extension is a bit "windowsy", use .conf instead.

A couple of things on the implementation:

The EQ could be done before the main loop (in the weigh signal to frequencies process) to save CPU. Or could it? I'm not sure how you do it. But the process before the main loop creates bars numbers of constants and multiples them with the signal and is already a kind of "static" EQ. So if it can be placed here I think it would make sense.

The integral filter would also be nice to adjust (not just turn on of). The default value there now is 0.7, tuning this up towards 1.0 creates more smooth experience tuning it down will make it faster, but less smooth. Also cava will segfault without the `if (f[o] < 1)f[o] = 1;`check that is know at the end of this filter, as it gets a divided by zero error in the drawing. Just move the check to its own for loop. (or will this consume more CPU?)

Can the monstercat filter also be adjustable? Not just on/off? 


Anyway verry nice work!

**Comment by CelestialWalrus** [comment]
> The EQ gives no output if it is below 1, but maybe you changed how it worked after you made the example values.

I'll push it soon.

    [eq]
    1=0
    2=1
    3=0
    4=1
    5=0

![3_138](https://cloud.githubusercontent.com/assets/6376571/8670183/a54a851e-29e8-11e5-9eff-346bf6ed91e0.png)

    [eq]
    1=2
    2=2
    3=1
    4=1
    5=0.5

![3_139](https://cloud.githubusercontent.com/assets/6376571/8670181/9db0ef50-29e8-11e5-81bc-3e2bb9892da0.png)

> Also i think that the .ini extension is a bit "windowsy", use .conf instead.

Changed to PATH/config [no extension].

> The EQ could be done before the main loop (in the weigh signal to frequencies process) to save CPU.

I don't think it "wastes" too much CPU. I can play with it.

> The integral filter would also be nice to adjust (not just turn on of).

Already done. Not pushed yet.

> Can the monstercat filter also be adjustable? Not just on/off? 

I have no idea how to make it adjustable. Maybe the number in pow()?

**Comment by CelestialWalrus** [comment]
@karlstav I've documented the config file. https://github.com/CelestialWalrus/cava/blob/modules/README.md (it's at the end).

**Comment by CelestialWalrus** [comment]
Smoothing after eq looks better, but less precise.

[1,0,1,0,1]

![3_141](https://cloud.githubusercontent.com/assets/6376571/8673333/a0138058-2a03-11e5-9737-2d1bd91a0d79.png)

**Comment by karlstav** [comment]
OK, i think we should go for smoothing after eq then.

regarding the readme. I think it would be best to explain the functions of the config in comments within the config file. The readme is getting pretty long...

**Comment by CelestialWalrus** [comment]
@karlstav I don't know how to store the file inside the executable. (as a string?)

**Comment by anko** [comment]
@CelestialWalrus As a string would work—but why? Could distribute an example config file with the program, and have `make install` copy it into the right location, if it doesn't yet exist.

(Sorry for doing lots of talking and little work. I hope I'm more useful than annoying.)

**Comment by karlstav** [comment]
Here is how I whould imagine the config file:
```
## Configuration file for CAVA. Default values are commented out.  Use either ; or # for commenting.

[general]
; mode = normal # defines smoothing mode, can be normal, scientific or waves.
; framerate = 60 # Default: 60. Accepts only non-negative values.
; sensitivity = 100 #  is sensitivity %. Accepts only non-negative values.
; bars = 0 # defines the amount of bars. 0 sets it to auto (25 + fill up leftover space). 

[input]
; method = alsa # supported input methods are 'alsa' or 'fifo'.
; source = hw:1,1 # ALSA device or FIFO path.

[output]
; method = terminal # may be terminal or circle.

[color]
# supported colors are: red, green, yellow, magenta, cyan, white, blue, black.
; background = black
; foreground = cyan

[smoothing]
; integral = 0.7 # multiplier for the integral smoothing calculations. Higher values means smoother, but less precise. 0 to disable.
; monstercat = 1 # disables or enables the so-called "Monstercat smoothing". Default: 1. Set to 0 to disable. 
; gravity = 1 # Set gravity multiplier for "drop off". Higher values means smoother, but less precise. Accepts only non-negative values. Set to 0 to disable "drop off".

[eq]
# This one is tricky. You can have as much keys as you want. More keys = more precision. Look at readme.md on github for further explanations and examples.
; 1 = 1 # base
; 2 = 1
; 3 = 1
; 4 = 1
; 5 = 1 # treble
```

Come to think of it, setting the number of bars is retarted, I should set the bar width instead and then fill up terminal. Maybe number of bars as overieable option...

@CelestialWalrus give me a heads up when you are done in your end. Then I will pull your version and do some adjustments from my end. There are a few things that are needed to make all the customization work ok.

**Comment by CelestialWalrus** [comment]
@karlstav I'm done for now, you can pull it.

**Comment by CelestialWalrus** [comment]
@karlstav could you merge modules into master, please? cava-git AUR package uses master and since modules branch is temporary I'm not changing that.

**Comment by karlstav** [comment]
@CelestialWalrus done, pushing 0.3.1 out as well.

**Comment by CelestialWalrus** [comment]
@karlstav you should mark it as a "release", not a "prerelease" ;-) (release sounds better!)

**Comment by karlstav** [comment]
release does sound better. But I thought that as long as it was 0.x.y it was a prerelease? I'll set it to release anyway, it looks very unusable with the "warning prerelease!" tag.

About the integral, having a total multiply factor of more then or equal to 1 will eventually cause all the bars to raise to maximum and stay there.So the plan is to limit allowed values to 0 - 0.99. Having the setting multiplied by 0.7 will cause 1/0,7=1,429 to be the maximum allowed value so that is not very intuitive.

**Comment by CelestialWalrus** [comment]
@karlstav Well, never thought about that. You should also limit the gravity.

**Comment by CelestialWalrus** [comment]
@karlstav BTW.

>Come to think of it, setting the number of bars is retarted, I should set the bar width instead and then fill up terminal. Maybe number of bars as overieable option...

I use this option. Maybe bar width OR bar count?

**Comment by CelestialWalrus** [comment]
@karlstav I've made a live reload feature. https://github.com/karlstav/cava/pull/47 (& that "ignore" thing)

I'm still trying to figure out how to restart/reload input.

**Comment by karlstav** [comment]
done for now, thanks to @CelestialWalrus again for spearheading the work on this. Further improvements would be to make it use some kind of system wide parser (separate issue)
