### ISSUE TITLE
not parsing color hex correctly

### ISSUE THREAD

**Issue by pjalsGit** [karlstav/cava#430]
**When/where was the bug introduced?**
- Are you using cava from a package repository, like AUR?
- If so, check out the master branch here, is your issue already resolved?
- Don't know how to clone, compile source code? File report to package maintainer instead.
- try using git bisect to find out where the bug was introduced.

**Describe the bug**
I set background/foreground to format `#123abc` and `123abc`, both didn't work

**To Reproduce**
1. set background parameter to "#123abc"
2. observe error
3. set background parameter to "123abc"
4. observe error

**Expected behavior**
for hex colors to parse correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/25231103/147854338-bb454d9d-1d46-4c47-84ad-baf31c3a9af7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Ubuntu] `Linux fedora 5.15.11-201.fsync.fc35.x86_64 #1 SMP Fri Dec 24 11:28:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Version [e.g. 22] `cava 0.7.2`

**Terminal emulator**
- name Terminal (`gnome-terminal`)
- version `Version 3.42.2 for GNOME 41`

**Additional context**
nothing

**Comment by karlstav** [comment]
0.7.2 is not the latest version, please get the latest version and check if the issue still exists.

**Comment by pjalsGit** [comment]
it appears that the fedora repos are outdated.. maybe should put that in the readme

**Comment by pjalsGit** [comment]
tried on git, same error

**Comment by karlstav** [comment]
could you attach your config file?

**Comment by pjalsGit** [comment]
[config.log](https://github.com/karlstav/cava/files/7798978/config.log)
log file because github wont accept no file extension

**Comment by karlstav** [comment]
you have 
```
background = '111111'
foreground = 'c850eb'
```

this will not work it must have the `#` in front like this:


```
background = '#111111'
foreground = '#c850eb'
```

**Comment by pjalsGit** [comment]
huh, for some reason this time it worked, closing as user error
