### ISSUE TITLE
Ignore muted volume

### ISSUE THREAD

**Issue by WilsontheWolf** [karlstav/cava#433]
**Is your feature request related to a problem? Please describe.**
I'd like the bars to be show even if my pc is muted.

**Describe the solution you'd like**
The ability to ignore mute, either as a config option, or something else.

**Additional context**

Is this even possible? Would like to know. Thanks

Heres a video of what I mean

https://user-images.githubusercontent.com/33164598/153797925-23878e75-6ea8-4c5f-a7b8-fe7695124ce1.mp4

**Comment by karlstav** [comment]
by default cava uses the monitor of the default pulseaudio sink and if that sink is muted, then the monitor will get no signal inn either. 

you could output the audio to a pulseaudio null sink and use the monitor for that instead. this way you will be able to visualize the audio without hearing it. if that is all you need.
