### ISSUE TITLE
Reverse order of bars

### ISSUE THREAD

**Issue by WilsontheWolf** [karlstav/cava#434]
**Is your feature request related to a problem? Please describe.**
I was using cava as a backend for a visulizer that was inspired by my cars radio. I noticed that the car had its peaks opposite of cava's when listening to the same audio.

**Describe the solution you'd like**
An option to reverse the order of peaks (sorry not sure what its called). 
Here is an image showing what I mean
![9C0C2616-56BE-4042-986C-7BEF15A1C931](https://user-images.githubusercontent.com/33164598/154584432-9c291b68-6313-4dc9-a8a0-42a76474401b.png)
Right is cava

**Describe alternatives you've considered**
If its too much work, I could just do this on my software end.

Edit: Here is a video to better show this.
https://youtu.be/Mwmk4z8QXtU

**Comment by karlstav** [comment]
why not! implementation was so simple that I managed to type the commit wrong. oh well.

cool car radio by the way.

**Comment by WilsontheWolf** [comment]
Hey, thank you very much for this!
However, after trying this it appears that this was not the effect I desired. Woops! I did some messing with the config, and found that you seem to have the audio go from low-high-high-low. Whereas my car seems to just go from low-high. I found this out by setting the config to make the midpoint noises 0
![](https://media.discordapp.net/attachments/519997113652871181/944343498440728666/unknown.png)
Now in this case just getting double the lines and ignoring them would work, but then I decided to mess with it and reaized one side is for left and the other for right.

https://user-images.githubusercontent.com/33164598/154769883-ac38ac7e-8a1e-4639-8333-7059bc92e5d5.mp4

As such this causes the need to do some kind of merging of data points, so that no matter what side the sound is on, it displays properly.

My friend suggested this
```js
const fold = arr => arr.slice(0, arr.length / 2).map((v, i) => (v + arr.at(-(i+1))) / 2)
```
which does work fine for if both ears are similar;

![image](https://user-images.githubusercontent.com/33164598/154777132-47402153-2538-4ed1-bb6c-bab6f71b3658.png)

But a bit low where one ear is lesser looks a bit low

![image](https://user-images.githubusercontent.com/33164598/154777297-5fe6f854-9fd8-4eda-9c75-ed2a2faa84db.png)

Here I used an alterntive algorithum where it just gets the higher peak. This works fine but might have its own issue I'm not aware of.
```js
const fold = arr => arr.slice(0, arr.length / 2).map((v, i) => (v > arr.at(-(i + 1)) ? v : arr.at(-(i + 1))));
```
![image](https://user-images.githubusercontent.com/33164598/154777379-be33bea8-61ab-46de-9245-b3b993a2c2e1.png)

If you got any other ideas and/or want to add anything that would be absolutely lovely. Thanks!

**Comment by WilsontheWolf** [comment]
Yeah that seems to be the exact option I was looking for. Thanks!
