### ISSUE TITLE
Add support for Noritake VFD display bitmap

### ISSUE THREAD

**Issue by elafargue** [karlstav/cava#439]
This will make it possible to do spectrum displays on old school "green" VFD displays.

The goal is to simply output bitmaps ready to be sent to a Noritake display in DMA mode, so that high refresh rates can be achieved. The output should just be the bitmap, not the control commands required by the display.

**Comment by karlstav** [comment]
i had to make some small adjustments. global variables are dangerous and should not be used. i guess the problem was that they where already in the raw output module. So the build failed for me locally. It was strange that the workflow action in the pull request didn't fail on the build

**Comment by elafargue** [comment]
Very good point yes, I had noticed that but stuck to the same pattern you had used on `raw.c`. Now both are fixed :) Thanks for merging!
