### ISSUE TITLE
Gradient not working

### ISSUE THREAD

**Issue by Tail-0k** [karlstav/cava#441]
I wanted to use gradient colours so I went into the config file and enabled it. I set it to "; gradient = 1" but it still is using the default colours. And yes, I have restarted cava and the computer.

https://user-images.githubusercontent.com/94500063/159143890-04c4f619-0c0d-4d17-97e8-6eb4c0150cce.mp4

Keep in mind, I am dumb.

**Comment by karlstav** [comment]
hi @Tail-0k.

you are not dumb, you are just a beginner, we have all been there. :wink:

```
; gradient = 1
^ 
```
this semicolon means that the config option is "commented out", which again means that it will not be read by the application (cava in this case). Just remove the semicolon and it should work.

I will add a better description about this on the top of the config file, as more people have issues with this.

**Comment by Tail-0k** [comment]
Thank you so much! You are so nice. I appreciate your work.
