### ISSUE TITLE
Feedback on cavacore

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#445]
The release version is working well for me!

The cavacore.c/h files are likely to be copied into other projects. It
would be easier to follow the cava license if it was already included at
the beginning of these two files.

You could consider adding some extra code to the header so it can be
included directly in a C++ source file

   https://isocpp.org/wiki/faq/mixing-c-and-cpp#include-c-hdrs-personal

It would be better if the cavacore functions did not call exit() or print
anything to the screen. If they simply returned the error/error message
then the calling program could choose how to deal with it.

I get a segfault using 0 for the low cut off parameter.

I was able to cross-compile my cava_filter application as a stand-alone
Windows exe by cross-compiling fftw3 as a static library and linking
to that.

Adrian.

**Comment by antiprism** [comment]
I was also unsure about the input buffer size, although this may relate to my exposure to earlier versions.
```
// cava_in, input buffer can be any size. internal buffers in cavacore is
// 4096 * number of channels at 44100 samples rate, but it is recomended to use less
// new samples per execution as this determines your framerate.
// 512 samples at 44100 sample rate mono, gives about 86 frames per second.
```
Why does this include details of the size the internal buffer in cavacore? Does it affect my choice of buffer size? Is it a maximum size?

Does the recommendation to use a smaller buffer only relate to ease of implementing frames per second as cava_execs per second?

What I am currently doing is using a buffer of 1024 samples (2 channels). I work out how many samples I need for my true framerate (bar value lines per second), work out the minimum number of buffers that will hold this, then divide the samples among these as equally as possible. E.g. 3500 samples fits in a minimum of 4 lots of 1024, and the samples in each will be 3500/(1024 * 4), with some buffers having an extra sample to account for rounding in this calculation, and also because 3500 probably has been rounded (the samples required for the true framerate will not generally be a whole number).

If I could use any size input buffer I would use the size I need (which might be big if the specified true framerate is very small e.g. 0.01 frames per second), and the only accounting would be an extra sample on some frames due the the samples per frame not being a whole number.

Adrian.

**Comment by karlstav** [comment]
There could have been more work done on my side regarding how the library is supposed to be used. But i wanted to merge the code into master to avoid it deverging and having to maintain a lot of porting stuff forward and backward. Pluss I had a frame of available time for this project that was coming to an end.


However, there are a lot of available points here that I will try to get in. Maybe making it a header only library. The idea now is that people will clone and build cava and then copy the cavacore object file ane header file into to their project.

**Comment by karlstav** [comment]
Regarding the buffer size, this might be as you say completely unnecessary information from the client perspective. 

I haven't tried using sizes that are not in the power of 2, but this might work just fine. Odd numbers might also work.

I guess the only important points is that the size can vary from execution to execution and that if the size is larger than 4096 * number of channels (@ 44100 or 48000 sample rate), then only the first 4096 samples will be used.

**Comment by antiprism** [comment]
Thanks for the extra information on the input buffer. If there is a limit on what will be processed then I'll stick with the approach I am currently using, but will increase the size of the buffer to the cava maximum. Also, I have realised that I have two input channels, but my algorithm can create an input sample size that is not an even number, which doesn't make sense. I'll fix this.

Adrian.
