### ISSUE TITLE
Bars completely maxxed out without touching config

### ISSUE THREAD

**Issue by ChadFacts** [karlstav/cava#447]
**When/where was the bug introduced?**
- Are you using cava from a package repository, like AUR?
I followed the from source installation instructions

**Describe the bug**
The bars are permanently maxed out regardless of sensitivity

**To Reproduce**
1. install
2. run

**Expected behavior**
I expected bars the same as I see within videos I saw on YT and on the README.md

**Screenshots**
![image](https://user-images.githubusercontent.com/79337475/163684874-6c8a97bb-8ad5-4dfe-b60f-c885d22addb6.png)
![image](https://user-images.githubusercontent.com/79337475/163684886-7ef90269-4089-4d34-a636-d2bc4e4d890c.png)

**Desktop (please complete the following information):**
 - OS: Archcraft
 - Version 5.17.3-arch1-1

**Terminal emulator**
- Kitty
- 0.25.0
- Alacritty
- 0.10.1
- (Tried both, same results on both. Screenshots from kitty.)

**Additional context**
I've tried adjusting sensitivity both in config and via keybind. I've set sensitivity in the config to 1, 10, 100, 150, 200. No change.

**Comment by karlstav** [comment]
Hi @ChadFacts 

Does it make any difference if you disable autosens? Also try adjusting sensitivity after disabling autosens.

**Comment by ChadFacts** [comment]
Autosens was already disabled in the config file and I also tried it with autosens enabled

**Comment by karlstav** [comment]
I can see that there is some movement in the top of those screenshots. Where autosens disabled when those where taken? Does it make a difference when enabling or disabling autosens?

**Comment by ChadFacts** [comment]
Yeah that's the only movement that happens, just a little bit at the top but in most things it seems to be over the limit. With it enabled it has the same result. It was disabled in the screenshots, but I tried it again just to see so I uncommented autosens and made sure it was = 1. It still performed the same. I also tried changing it to 0, still same results. I made sure to restart cava after every change in config.

**Comment by karlstav** [comment]
hmm i am having a hard time trying to reproduce. I did a lot of changes in 0.8.0 can you check out the 0.7.5 tag and see it you have the same issue there? just do:

```
git checkout 0.7.5
make clean
sudo make uninstall
make
sudo make install
```

**Comment by vaskark** [comment]
This is happening for me, too. Latest git on Ubuntu 21.10.

**Comment by karlstav** [comment]
found the issue, my bad! 

should be fixed now.

**Comment by ionenwks** [comment]
Thanks that fixed it for me, ran into this too and was about to bisect but guess no need anymore :+1:

**Comment by vaskark** [comment]
Fixed. Many thanks. And thanks for all your effort.

**Comment by ChadFacts** [comment]
Fixed, thanks
