### ISSUE TITLE
Synchronization Support

### ISSUE THREAD

**Issue by ibootstrapper** [karlstav/cava#453]
This feature request is related to a problem with cava flickering when running inside alacritty (https://github.com/alacritty/alacritty/issues/6045). 

when cava is running inside alacritty. cava rendering seems to be missing lines as well as there are some visible flickering. According to alacrity, this is due the lack of support of synchronization by cava.

**Comment by ibootstrapper** [comment]
![ArcoLinux_2022-05-07_12-47-24](https://user-images.githubusercontent.com/1440852/167349749-769f9306-046b-40b9-aa1b-eaa5474838e3.png)

**Comment by karlstav** [comment]
I notice that alacritty cpu usage is very high. I get that issue with kitty when framerate is higher than the monitor refresh rate. 

Have you tried setting cava framerate to well below monitor refresh rate?

**Comment by karlstav** [comment]
ahh ok, hard to find any good documentation on how to use the sync updates other than:

```
This can be triggered using the escapes `DCS = 1 s` (start) and
`DCS = 2 s` (end).

```

from the alacritty changelog. but I will give it a go.

**Comment by karlstav** [comment]
i think maybe I got it. @ibootstrapper are you able to test the following patch:

```
diff --git a/cava.c b/cava.c
index 76ec7a7..7ed0a40 100644
--- a/cava.c
+++ b/cava.c
@@ -875,9 +875,13 @@ as of 0.4.0 all options are specified in config file, see in '/home/username/.co
                 switch (output_mode) {
                 case OUTPUT_NCURSES:
 #ifdef NCURSES
+                    printf("\033P=1s\033\\");
+                    fflush(stdout);
                     rc = draw_terminal_ncurses(inAtty, lines, width, number_of_bars, p.bar_width,
                                                p.bar_spacing, remainder, bars, previous_frame,
                                                p.gradient, x_axis_info);
+                    printf("\033P=2s\033\\");
+                    fflush(stdout);
                     break;
 #endif
 #ifdef SDL
```

**Comment by karlstav** [comment]
done some more testing and it looks really promising!

added it as a config option now, just add:

```
alacritty_sync = 1
```

under the `[output]` section in the config

**Comment by ibootstrapper** [comment]
Great, 

I'll test it over the weekend.

**Comment by ibootstrapper** [comment]
Great work! seems the flickering is gone. There are still line gaps. I wonder where are these coming from. I've enclosed a picture where on top left there is kitty and the bottom one is alacritty to show the difference. Kitty also does better on CPU, Ha! 
![ArcoLinux_2022-05-07_12-47-24](https://user-images.githubusercontent.com/1440852/168398721-27a08a51-8024-4935-9f26-afa7d279b72a.png)

**Comment by karlstav** [comment]
yea the alacritty cpu usage is through the roof, don't know what's up with that, maybe there are some settings.

that line almost at the top there is most certainly a font or font rendering issue. there have been similar with alacritty before:

https://github.com/karlstav/cava/issues/356#issuecomment-635120187

**Comment by ibootstrapper** [comment]
not sure what the reason but i'll be moving to kitty . Thanks for the fix though!

**Comment by dnkl** [comment]
> ahh ok, hard to find any good documentation on how to use the sync updates other than:

They're called "application synchronized updates" (or just "synchronized updates"), are semi-standard, and supported by quite a few terminals. Alacritty was actually quite late in the game...

Note that many terminals have moved **away from** the original DCS escapes, to a private mode (`CSI ? 2026 h` and `CSI ? 2026 l`), though generally still supporting the old DCSs too. Not sure if Alacritty supports that, or just the DCS escapes. Since Alacritty is, probably, the terminal that most needs this in cava, it might be best to keep using the DCSs.

On compatibility; terminals _should_ ignore DCS escapes they don't implement. This is probably true for all modern GUI terminal emulators. Not sure about e.g. the linux VT though. Same goes for private modes, and I think terminals are even better at ignoring unrecognized private modes than unrecognized DCSs.

Spec: https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/2

**Comment by dnkl** [comment]
There's even a non-standard terminfo entry for this: `Sync`, invented by tmux. Being non-standard, it will unfortunately not appear in any ncurses provided terminfos...

**Comment by SuperNici** [comment]
This unfortunately seems to be an issue with alacritty and it still hasnt been fixed. 

Will probably also move to kitty :)

**Comment by ibootstrapper** [comment]
> This unfortunately seems to be an issue with alacritty and it still hasnt been fixed. 
> 
> 
> 
> Will probably also move to kitty :)

There is actually a fix from cava side to support alacritty sync 

Put this in the config file

alacritty_sync = 1
