### ISSUE TITLE
CAVA Not Working In WSL

### ISSUE THREAD

**Issue by CSNinja11** [karlstav/cava#454]
I Installed All requirements For Ubuntu
And I Tried To Use CAVA With winscap
But It's Not Working 
my config only contains:
[input]
method = fifo
source = /tmp/cava.fifo
sample_rate = 48000

i runed
/mnt/c/path/to/winscap.exe 2 48000 16 > /tmp/cava.fifo
with my path
but CAVA Bars Are Not Working

**Comment by karlstav** [comment]
Should work. What happens when you run cava? Are you seeing the bars at the bottom of the terminal?

**Comment by Aritz331** [comment]
@CSNinja11 why do you use winscap? just run cava directly

**Comment by karlstav** [comment]
@Aritz331 you will need to run both in order to capture audio with wsl. run them in two seperate terminals or do 

```
/mnt/c/path/to/winscap.exe 2 48000 16 > /tmp/cava.fifo & cava
```

**Comment by Aritz331** [comment]
@karlstav oh ok, i didnt know it

**Comment by karlstav** [comment]
is this still an issue @CSNinja11?

**Comment by tloc241** [comment]
@CSNinja11 can you help me making winscap.exe file in cygwin? i still don't know how you can have that @@

**Comment by eltrevii** [comment]
@tloc241 just download it from the official [releases](<https://github.com/quantum5/winscap/releases>) broski
