### ISSUE TITLE
[feature request] Logarithmic frequency scale

### ISSUE THREAD

**Issue by Aritz331** [karlstav/cava#456]
**Is your feature request related to a problem? Please describe.**

Not really, but I like the effect it makes

**Describe the solution you'd like**

Add logarithmic frequency scaling (as an option in the configuration file) to the visualizer

**Describe alternatives you've considered**

I haven't considered any alternative solutions

**Additional context**

**Comment by karlstav** [comment]
it's allready. the math is a bit obscure as it takes some other factors in to account. but with 10 bars you would noramly get the following lower cut off frequencies:
```
50 	85 	144 	245 	416 	707 	1201 	2040 	3466 	5887
```

we could offcourse increase the factor, or make it configurable. but with log10 for example it would scale pretty fast past the interesting frequencies. you would want to have more than one bar between 100 and 1000Hz.
