### ISSUE TITLE
Failed to build cava from AUR arch (libtool: Version mismatch error.)

### ISSUE THREAD

**Issue by cmergny** [karlstav/cava#458]
Just tried to install cava on Arch Linux using the AUR repo following the README instructions but the build failed.

**To Reproduce**

 I have installed the dependencies using:

`pacman -S base-devel fftw ncurses alsa-lib iniparser pulseaudio`

then when running:
`pacaur -S cava  `

I got the following error:

`libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.7-dirty.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make: *** [Makefile:524: cava] Error 63
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build cava package(s)`

**Desktop**
 - OS: Arch Linux
 - kernel: 5.18.3-arch1-1

**Terminal emulator**
- Alacritty

**Comment by karlstav** [comment]
Looks like an issue with the package on aur or your system.

**Comment by sukhmancs** [comment]
I am getting this similar error but with yay.
