### ISSUE TITLE
Bring EQ back.

### ISSUE THREAD

**Issue by samoht9277** [karlstav/cava#463]
**Is your feature request related to a problem? Please describe.**
Not really, just bring back the previously added EQ feature.

**Describe the solution you'd like**
Remove deprecation to said feature.

**Describe alternatives you've considered**
Intercept pulseaudio's `source-output` signal, but its nonsense.

**Additional context**
nope, i just loved that feature, and I'd like it back. happy to help with any testing, if necessary.

**Comment by karlstav** [comment]
I will bring it back!

the only reason i deprecated it was because I didn't think anyone was actually using it. shouldn't be too much work, no time at the moment, but will look at it soon.
