### ISSUE TITLE
File sourcing

### ISSUE THREAD

**Issue by ignamartinoli** [karlstav/cava#464]
Just a quick question:

Is it possible from the config file to source another file like with `bash`?
I couldn't find any info online. I have different colorscheme files and I wanted to directly source them from the main config file

Thanks for your time :D

**Comment by karlstav** [comment]
hi @ignamartinoli,

I'm afraid it's not possible in any straight forward way. You would have to alter the main config file and then reload it.

**Comment by ignamartinoli** [comment]
alright thanks for clearing that out :D
