### ISSUE TITLE
Raw output: slow autosens, missing data?

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#469]
Hi Karl

Just a heads up, as I do not currently have any time to troubleshoot the issue.

Using the latest cava with mpd_oled produces a spectrum with minimal height bars that take around five minutes to adjust to a reasonable (but still low) height. The display of bars also flashes irregularly, averaging maybe one flash per second, with up to three seconds between flashes. I imagine the flash is a result of a failure to read good bar data from cava, for whatever reason (i.e.the "flash" is a one frame display of zero height bars).

I checked a random old version of cava (commit 1b7c395) and it is working fine with mpd_oled. However, as I have not tried to track down the issue I cannot say for sure that it is a cava issue, only that older versions of cava are working fine with the current mpd_oled code and the current version of cava is not.

As you suggested in a previous issue, I have decided to fix on a specific version of cava for the mpd_oled installation instructions, and stop tracking the cava repository.

While I cannot help with troubleshooting, if you look into this and find it is a cava issue and push a fix I would be happy to test the changes.

Adrian.

**Comment by antiprism** [comment]
Slow autosens on the command line.

cava config.txt:
```
[input]
method = alsa
source = plughw:Loopback,1

[output]
channels = mono
```
Running
```
cava -p cava_config.txt
```
I saw the first bar go higher than halfway up the screen at around three minutes.

**Comment by karlstav** [comment]
hi Adrian,

the autosens has a mechanism to normalize the volume. autosens will increase the sensitivity multiplier by 0.1% at every frame if it does not overshoot, if the signal is extremely faint then this can indeed take a long time. However at launch autosens will increase the sensitivity multiplier by 10% at every update until the first time a bar overshoots. This should be very fast, I have been testing it with extremely low input signals (alsa and pulse), and it it still a matter of seconds before it overshoots.

do you limit the volume at the source of the audio pipeline? Or maybe at the alsa device? 

do you also see the same flashes in the command line?

**Comment by antiprism** [comment]
I am using Moode with software volume and loopback enabled by the Moode UI. I have the volume at 15% (as I normally do), which is normally fine for cava. Changing the volume increases the bar height, so it is probably MPD -> softvol -> multi(output device//Loopback).

I had just installed the latest version of Moode, so I installed the old commit of cava to check if it showed the same behaviour I was seeing, but the old commit was working correctly. (quick adaptation with autosens and no flashing)

I do not see any flashing when running on the command line.

**Comment by karlstav** [comment]
looks like the variable for turning on off the initial sensing of values was uninitialized., should work better now. 

this doesn't really explain the flashing, suggest opening a separate issue, if that persists. 

thanks again for the bug report.

**Comment by antiprism** [comment]
autosens is now working correctly.

I checked the cava raw output without consideration of timing and did not see any frames with zero-height bars. I suspect that the issue is that some change to cava is affecting mpd_oled timing, and that the fix is that the mpd_oled timing code should be more robust!

Thanks for your help.

Adrian.
