### ISSUE TITLE
free(): invalid pointer under slackware

### ISSUE THREAD

**Issue by xanmodlouis** [karlstav/cava#475]
cava -v
cava 0.8.2-27-g770f010

 cava
free(): invalid pointer
zsh: IOT instruction  cava

In bash:

bash cava
/usr/local/bin/cava: /usr/local/bin/cava: cannot execute binary file

**OS： Slackware**

**Comment by karlstav** [comment]
very interesting!

how did you build cava? or did you optian the binaries some other way?

**Comment by karlstav** [comment]
if you want to do me an favor you can build and run with the address sanitizer enabled:

```
make clean
./configure --enable-asan
make
./cava
```

this should help locate the bug.

**Comment by louisrc3ys** [comment]
Thanks Karlstav, I just removed the latest version constructed from Git, reinstalled with the old package of Slackware and runs now just the version is a bit old and is 0.6, but I'll try to your thinking, rebuild under the latest version.
