### ISSUE TITLE
Bars not moving on macOS

### ISSUE THREAD

**Issue by BlueFalconHD** [karlstav/cava#476]
**When/where was the bug introduced?**
I installed cava with Homebrew.

**Describe the bug**
Though the Cava bars are showing, they aren't taking any audio input even though I have installed Background Music

**To Reproduce**
1. Set config parameters to:
```
[input]
method = portaudio
source = "Background Music"
```
2. run with macOS v12.3 on a 2020 M1 Macbook Air
4. See the bars stand still even when playing audio.

**Expected behavior**
The bars should move up and down, but they stand still.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/72631767/199625187-fb8ac7f0-b215-426c-8ff7-650bab7655a5.png">

> **Note**: The song is playing and volume is up.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.3

**Terminal emulator**
- Wezterm (GPU Emulator with same feature set as Kitty)
- wezterm 20220904-070558-c38816fc

**Comment by karlstav** [comment]
isn't there some setting you have to do in background music first?

I know there has been some issues with background music recently. you could try soundflower instead

https://github.com/karlstav/cava#macos-1

**Comment by BlueFalconHD** [comment]
I have an M1 Macbook, so Soundflower isn't an option.

**Comment by karlstav** [comment]
I would suggest troubleshooting background music first then. check if you are able to [record audio](https://github.com/kyleneideck/BackgroundMusic#recording-system-audio) at all.

**Comment by BlueFalconHD** [comment]
I am able to.

**Comment by karlstav** [comment]
Ok good. Now I  just remembered I encountered an issue once where the volume slide of the background music interface itself was turned almost all the way down. Can you check in your sound settings that it is on max.

The ideal setup would be to have the volume on max on your application and on background music and then limit the audio on the output device.

**Comment by BlueFalconHD** [comment]
It is all up all of the way. Still not working.

**Comment by karlstav** [comment]
Hmm what version of cava are you using?

**Comment by BlueFalconHD** [comment]
0.8.2

**Comment by karlstav** [comment]
There was a bug in this version that caused the initial automatic sensitivity adjustment to be very slow. I drafted a new release (0.8.3) yesterday that contains a fix for that. It should be on homebrew now. Try to update and see if it works better.

**Comment by BlueFalconHD** [comment]
I updated. Still no luck.

**Comment by karlstav** [comment]
Then I don't know. Other than to play around with the interfaces.

I will try to reproduce the next time I am around a M1 mac

**Comment by BlueFalconHD** [comment]
ok thanks! I will keep trying.

**Comment by karlstav** [comment]
I tried now with my intel mac and I had an issue with background music not being able to capture the system sound unless I selected background music as my output device. 

Then cava would work, but of course I could not hear the audio in my speakers. I guess this can be solved by creating an aggregated interface.

**Comment by neeeerrd** [comment]
Being a wezterm user myself, wezterm does not seem to support cava for whatever reason, as I have tried this with other terminal emulators, with all of them working.

**Comment by es183923** [comment]
This is now resolved in WezTerm nightly. Should be out in a few hours max.
