### ISSUE TITLE
Error: failure in opening stream (Invalid number of channels)

### ISSUE THREAD

**Issue by piotreknow02** [karlstav/cava#478]
**When/where was the bug introduced?**
I installed cava using homebrew with default configuration

**Describe the bug**
Cava throwing `Error: failure in opening stream (Invalid number of channels)` when running with default configuration

**To Reproduce**
1. install cava using homebrew 
2. run

**Expected behavior**
Program should start working as usual

**Screenshots**
![Zrzut ekranu 2022-11-14 o 22 05 05](https://user-images.githubusercontent.com/65082017/201765287-579e6627-bfd5-4212-8c00-24f740d94bd4.png)

**Desktop (please complete the following information):**
 - OS: macOS (M1 mac mini with connected bluetooth headphones)
 - Version 13.0.1

**Terminal emulator**
- iTerm
- 3.4.16

**Comment by karlstav** [comment]
this would try to open the "auto" source which normally is the mic. I have also seen that this results in this error on M1 mac.

follow instructions [here](https://github.com/karlstav/cava#macos-1) to capture system audio with Background music, should work.

**Comment by piotreknow02** [comment]
Thanks
