### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by Hioness** [karlstav/cava#481]
I've looked around online for this, and it seems that Issue#67 on here is the closest thing to the same problem, but that never finished getting resolved, so I have no answer.

So I installed cava through dnf in fedora, and I'm using Gnome. Every time I try to utilize cava it fails, giving me the error in the title. I've tried several distros, including OpenSUSE, EndeavourOS, and of course Fedora. The only time I've ever had cava working is when I used it on Archcraft. It was using OpenBox and bspwm. So to me, this is a Gnome or pipewire issue, since Archcraft is the only one of these distros to use Pulseaudio. There may be something I'm missing. Any ideas?

**Comment by karlstav** [comment]
hi @Hioness,

this sounds like something we should get to the bottom of.

I would need to know a few more things.

what version of cava are you using (run `cava -v`)

could you change your config and try some other input method like fifo? You will not see any movement, I just need to know if it crashes or not.

**Comment by karlstav** [comment]
btw the fora [package](https://packages.fedoraproject.org/pkgs/cava/cava/) looks to be terribly out of date (jul 1 2020). 

can you try to clone from here and build from source instead?

**Comment by Hioness** [comment]
I'll try both of those things, give me a little while and I'll get back to you. Thanks for the help!
