### ISSUE TITLE
Cava headers. Register an application into system through pkg-config

### ISSUE THREAD

**Issue by LukashonakV** [karlstav/cava#486]
I'm going to write additional module cava in [Waybar](https://github.com/Alexays/Waybar) project. I've got cava installed in Gentoo OS. Even cava is installed from the official repository it was surprising that:

1. ls -lh /usr/include/*cava*  - provides me 0 rows.
2. pkg-config --list-all | grep -i cava - provides me 0 rows.

I'm not familiar with autotools configuring. But finally both points should provide information about registered cava in the system.
1. As far as I see it'll be good to have /usr/include/cavacore.h in the system
2. It'll be good to have an opportunity to get information about installed cava in the system through pkg-config in order to provide an opportunity to external application to make cava build configuration... for example meson config:
```meson
libcava = dependency('cava', required: get_option('cava').enabled())
```
In such case meson uses pkg-config to define is cava installed in the system.

Alternatively I have to use cava wrapper ... so while waybar is building ... meson have to download cava source code from the git, unpack... and use it separately... even cava is already installed in the system. Actually I didn't check it... Need to investigate will it work...

**Comment by karlstav** [comment]
hi @LukashonakV 

I'm afraid cava as it is now is actually just an executable not a library. 

However when building cava you will also get the cavacore.o object file. This can be used in other application, but I haven't gotten around to making it an actual library and providing install rules for it and such. Read more on how to use it here:

https://github.com/karlstav/cava/blob/master/CAVACORE.md

**Comment by LukashonakV** [comment]
Hi @karlstav , are there any plans in addition to providing cava as a standalone library?

**Comment by karlstav** [comment]
as the separate issue suggests, I will look  into this.
