### ISSUE TITLE
Parallel make issue, e.g. with make -j5

### ISSUE THREAD

**Issue by hartwork** [karlstav/cava#49]
```
# make -j5
[..]
gcc: error: ./iniparser/libiniparser.a: No such file or directory
[..]
```
The issue is missing dependencies. Target `cava` actually depends on presence of `iniparser/libiniparser.a` but the dependency is not coded into the Makefile.

**Comment by CelestialWalrus** [comment]
There's no need to compile it with "-j5", it compiles fast enough without threading.

**Comment by hartwork** [comment]
Right, but some people have that in their defaults and the makefile does miss the dependency.
