### ISSUE TITLE
Automatic Sensitivity Increase

### ISSUE THREAD

**Issue by RageGamerBoi** [karlstav/cava#491]
**Is your feature request related to a problem? Please describe.**
When Automatic sensitivity is on, sensitivity can decrease when audio is peaking but doesn't automatically lower when audio volume is reduced for an extended period of time.
This causes problems when changing to tracks or applications which are quieter, and it becomes a pain to get the sensitivity correct.

**Describe the solution you'd like**
Automatic sensitivity increase (possibly as a separate toggle) to wait a set period of time and increase the sensitivity to some sort of average.

**Describe alternatives you've considered**
Restarting the app (in this case Cavalier), disabling and re-enabling automatic sensitivity, setting a manual sensitivity, and automatically restarting the app are all solutions that are annoying, and don't address the problem.

**Additional context**
This was originally an issue here: https://github.com/fsobolev/cavalier/issues/56 but has been opened here instead because it is a backed issue.

**Comment by karlstav** [comment]
If you like you can try to increase the number 1.001 on line 526 in cavacore.c
