### ISSUE TITLE
Cava mixes up sink as muted when only the source is muted on the same device

### ISSUE THREAD

**Issue by tkapias** [karlstav/cava#492]
My setup use pipewire-pulse and I use a script to toggle mute my current source/sink with amixer.
Cava is setup to monitor 'pulse' on 'auto'.
**But when I mute the mic (source/capture/input), cava gets flat.** 

- I tried to put the ID in the config but they are the same for the source and the sink, because it's the same device. 
- I tried to put their name (additional .monitor at end of the source) but it does not change anything.
- Note that it's the integrated sound chipset and I don't have a physical mic to connect, I just mute the source per default. 
- The sink on the same device is not mute and every other app see the difference.

I expected cava to diferentiate the sink from the source for the same device by name. 
Maybe it needs one more parameter in the config.

- cava: 0.7.4-1 (apt)
- building: same issue with master
- OS: Debian Testing (12)
- Terminal: URxvt v9.30 (modified)
- Pulse: Pipewire-pulse and wireplumber

Issue related to issue [#422](https://github.com/karlstav/cava/issues/422), which was closed a year ago with some user still searching for help.

**Comment by karlstav** [comment]
hi, #422 was maybe closed a bit early, but #451 is also so the same issue. 

So will be closing this as duplicate.  

Haven't had time to look at this because I have been on ubuntu myself and haven't upgraded. However now i am on 22.10 and will start to investigate.
