### ISSUE TITLE
MSVCR100D.dll missing

### ISSUE THREAD

**Issue by hitontwo2** [karlstav/cava#497]
**When/where was the bug introduced?**
- Are you using cava from a package repository, like AUR?
- No.
- If so, check out the master branch here, is your issue already resolved?
- No
- Don't know how to clone, compile source code? File report to package maintainer instead.
- No
- try using git bisect to find out where the bug was introduced.
- No

**Describe the bug**
MSVCR100D.dll is missing when trying to run the app
**To Reproduce**
1. executing cava.exe from Release folder
2. Error occurs

**Expected behavior**
Cava should run.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10:  2009
**Terminal emulator**
- Command Prompt
- 10.0.19042.631

**Comment by karlstav** [comment]
are you sure that you are in the release folder? the MSVCR100D should only be needed for debug,

anyway there are some dlls that need to be in the same folder or search path for cava to work, or you will need to run it from visual studio.
