### ISSUE TITLE
Doesn't work with Alsa

### ISSUE THREAD

**Issue by illegitimate-egg** [karlstav/cava#498]
**When/where was the bug introduced?**
- From the AUR

**Describe the bug**
Trying to use the Alsa option in the sound config merely yields `ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM auto
error opening stream: No such file or directory` when trying to start cava

**To Reproduce**
1. Install Alsa
2. Install cava-git from the AUR

**Expected behavior**
The program starts as normal

**Desktop (please complete the following information):**
 - OS: Arch Linux, Kernel Version 6.2.11-arch1-1
 - Version Latest (Rolling Release)

**Terminal emulator**
- Kitty
- 0.28.0

**Additional context**
Alsa Version 1.2.8
[Alsa Info Dump](http://alsa-project.org/db/?f=51735064861cbda7a3c716cc7751ae6b7f9e2eae)

**Comment by karlstav** [comment]
from your error message it seems that the source in the cava config is set to "auto". This will not work with alsa.  Read the readme and the comments in the config file.

**Comment by illegitimate-egg** [comment]
Yeah, that's probably it. The solution I went with in the end was just to route alsa through pulse, thanks!
