### ISSUE TITLE
Manual Sensitivy Broken

### ISSUE THREAD

**Issue by anotherhobby** [karlstav/cava#501]
**When/where was the bug introduced?**
0.8.3 Building directly from source.
Manual sensitivity (`autosens = 0`) does not work at all in version 0.8.3 (bars do not move at all)
The bars do move in 0.8.2, but they just keep growing upward continuously, so also not functional

**Describe the bug**
When autosens is disabled, all the bars remain flat at the bottom and do not ever move. Switch autosens to enabled, refresh, and the bars immediately start moving as expected. This happens in both ncurses and sdl.

**To Reproduce**
This simple config below produces bars that do not move at all.
If you change autosens to 1 instead of 0, it immediately works fine and bars start dancing.
I've tried this with 3 different alsa input cards.

```
[general]
autosens = 0
sensitivity = 100
[input]
method = alsa
source = hw:CODEC
[output]
method = ncurses
```

**Expected behavior**
`autosens = 0` should prevent the bars from changing sensitivity

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version: 10 (buster)

**Terminal emulator**
Built-in

**Comment by karlstav** [comment]
confirmed, working on fix

**Comment by karlstav** [comment]
hi @anotherhobby ,

thanks for the bug report, I did break this functionality pretty bad (simply commented out while debugging something else and then committed by accident) .

Should be fixed now!

**Comment by anotherhobby** [comment]
Awesome! Just tested and can also confirm it works great now. Thank you very much, and that was crazy fast!
