### ISSUE TITLE
Segmentation fault (core dumped) on blackbox terminal installed via flatpak

### ISSUE THREAD

**Issue by Adam0148** [karlstav/cava#503]
Hello 
I have this problem : Segmentation fault (core dumped) On Ubuntu 23.04 it was good but on ubuntu 22.04, cava don't work . Thx for helping :) 

cava  version 0.7.4-1

**Comment by karlstav** [comment]
The version in the ubuntu repo is hopelessly outdated, please install from source

**Comment by Adam0148** [comment]
Same problem after updating :(

**Comment by karlstav** [comment]
Are you sure that you're running the one built from source? What's the output of cava -v

**Comment by Adam0148** [comment]
cava 0.8.3, the problem shows after installing flatpak

**Comment by Adam0148** [comment]
Okey the problem  if Im starting cava in blackbox terminal in standard terminal its ok,  But why it isn't staring in blackbox ?

**Comment by karlstav** [comment]
Hmm how can this have anything to do with flatpak... does it work if you remove flatpak?

**Comment by karlstav** [comment]
just tried with BlackBox version 0.14.0-alpha0 on ubuntu 23.04, works fine.

**Comment by karlstav** [comment]
but the one installed via flatpak does indeed segfault. This is most likely due to some permission issue. I don't think it can be expected to work. just use the one via apt get install instead, on latest ubuntu it is also more reason. 

However I would recomend a gpu based terminal like kitty.
