### ISSUE TITLE
May be use other Capturing audio to instead "Background Music" for MacOS

### ISSUE THREAD

**Issue by hungvx-dev** [karlstav/cava#506]
Currently, Background Music has too many issues, 
Ex: https://github.com/kyleneideck/BackgroundMusic/issues/674.
I can't connect with other devices when use with background music. It's very bad.

Macbook Pro M1 Max - Ventura 13.3.1

**Comment by karlstav** [comment]
this is not really the place to ask @hungvx-dev, but as it's mentioned in the readme there is also [soundflower](https://github.com/mattingalls/Soundflower). not sure what's the current status on that.

**Comment by hungvx-dev** [comment]
@karlstav the soundflower not support for M1. And Background Music is unstable on M1 Ventura 13.4.1. Please support other Capturing audio instead.

**Comment by karlstav** [comment]
cava only reads from whatever input available. Soundflower or background music is just different ways of routing the output audio to an input. If none of them work, you will have to try to find another. Loopback by Rouge Amoeba is probably a good tool, but it is not free.

**Comment by Melonchanism** [comment]
OBS is directly able to capture system audio through system screen capture but I'm not sure if that would be available in a terminal environment.

I think something better that currently works is using [BlackHole](https://existential.audio/blackhole/), and creating a multi-output device in Audio Midi Setup.app. This way, audio would still be played on the speakers natively, but also captured through a loopback interface.
