### ISSUE TITLE
The config file doesn't seem to be loaded

### ISSUE THREAD

**Issue by fabriceHategekimana** [karlstav/cava#508]
**Describe the bug**
I have copied the config file given [here](https://github.com/karlstav/cava/blob/master/example_files/config),
but the modifications I make in the color section don't have an effect to the actual color of the bars.
I still need to use the "f" key to change color manually.

Using the -p option:
```
cava -p ~/.config/cava/config 
```
Didn't solve my situation.

**To Reproduce**
```
# default is to keep current terminal color
#; background = default
#; foreground = default

# SDL and sdl_glsl only support hex code colors, these are the default:
; background = '#111111'
; foreground = '#ff0000'
```

**Expected behavior**
Change the bar's color (here to be red)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Terminal emulator**
- name: kitty
- version: 0.21.2

**Comment by karlstav** [comment]
You have to remove the ; in front in order to make cava read the parameter.

This is commom in config files, but I might change to only use # as more and more people are confused by the ;
