### ISSUE TITLE
trying to build from scratch on MacOS, ./configure is not finding brew dependencies

### ISSUE THREAD

**Issue by myrrhkhan** [karlstav/cava#509]
**Describe the bug**
I am trying to build cava from scratch on MacOS so that I can have SDL support. I previously installed cava with Brew and it worked just fine. However, when I install it from scratch, after having installed all of the dependencies with Brew, when I run the ./configure file, I get a "fftw_execute" not found error or something like that. I installed FFTW on my own, built it according to the instructions, and run ./configure again. I see a "building without ncursesw is not recommended" warning, and the ./configure program stops and gives me the "iniparser library is required" error.

**To Reproduce**
1. Run MacOS Ventura and have Brew installed.
2. Install dependencies with Brew.
3. Run the export commands that are shown in the README.
4. Clone the cava repo into a folder within "Documents" rather than somewhere in the root directories.
5. Try to run ./configure within cava.

**Expected behavior**
./configure finds the dependencies and is able to complete the installation successfully.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5 Beta

**Terminal emulator**
- iTerm2

**Comment by karlstav** [comment]
https://github.com/Homebrew/brew/issues/13481

I should probably add something about it in the readme, but I don't have access to any apple silicon computer at the moment.

**Comment by myrrhkhan** [comment]
Ah, that's understandable.
Seems like there are a couple ways to remedy that then.
- Copy libraries manually to a place where ./configure will find them
- Change ./configure to search /opt/homebrew/ as well
- Install packages manually.
Where does ./configure find the libraries? /usr/lib? Any way to change that by any chance?
(Tried copying the iniparser folder t o /usr/local/lib and it didn't work).

Thanks in advance!

**Comment by karlstav** [comment]
try this:
```
export LDFLAGS="-L/opt/homebrew/lib"
export CPPFLAGS="-I/opt/homebrew/include"
```

then do ./configure

**Comment by myrrhkhan** [comment]
Thanks so much! I forgot to tell you that I ran the LDFLAGS command, my apologies, but I ran the CPPFLAGS command as well (was getting a syntax error earlier for some reason in I believe the makefile, so maybe the cppflags fixed that). Got the "not building with ncursesw" support even though I ran the commands in the README, but since I'm building it for desktop it's fine.
Everything works great, thank you so much!

**Comment by karlstav** [comment]
ncurses is not in the same place on apple silicon, probably try something like:

```
ln -s /opt/homebrew/lib/libncurses.dylib /usr/local/lib/libncursesw.dylib
```

or wherever the libncurses.dylib files is. I could probably also solve this by changing the configure.ac script to only look for "ncurses" on mac and not "ncursesw".

anyway, terminal output will still work with the `noncurses` mode.

**Comment by myrrhkhan** [comment]
Gotcha. Couldn't find the libncurses file at first, took me a while to find but I found the following files:

- libncurses++w.6.dylib
- libncursesw.6.dylib

There were two copies of each, one in `/opt/homebrew/Cellar/ncurses/6.4/lib/` and one in `/opt/homebrew/lib/lib/`. 

I ran `sudo ln -s /opt/homebrew/lib/lib/libncursesw.6.dylib /usr/local/lib/libncursesw.dylib` and it built with ncurses support.

**Comment by karlstav** [comment]
lib/lib? really? with two "lib" dirs? that sounds like it might be the real issue right there. maybe some mistake on the part of the ncurses homebrew package maintainer.
