### ISSUE TITLE
"HOME" directory

### ISSUE THREAD

**Issue by antiprism** [karlstav/cava#510]
Feedback and a question.

It seems like there has been a change to cava, where it now requires the user running it to have a "HOME" directory. I run a cava process from a daemon process, mpd_oled, which doesn't typically have a HOME directory set when running. I provide some installation instructions for running mpd_oled as systemd service, and have worked around this by setting a /tmp as the HOME environment variable  (hopefully this doesn't need anything more complicated...). However, mpd_oled is also being run as a plugin on the Volumio player, and the plugin system doesn't use systemd, and so needs its own modifiication.

Is it possible to build or configure cava so it doesn't require a home directory?

Adrian.

**Comment by karlstav** [comment]
Hi Adrian,

Looks like this happend when I added support for shaders. I needed a place to put the shader files so they could be edited if desired. To resolve this issue I could either dump the shader files in /tmp if there is no home or only bother with the shader files if glsl output is set. 

Will look into this soon.

**Comment by antiprism** [comment]
Hi Karl

I did't spot the update. I'll check it tomorrow.. Thanks

Adrian.

**Comment by antiprism** [comment]
Hi Kark

Working great on Volumio without a HOME directory. Thanks for your quick work!

Adrian.
