### ISSUE TITLE
Noise reduction setting always set to 0 if uncommented (?)

### ISSUE THREAD

**Issue by colby-boucher** [karlstav/cava#513]
**When/where was the bug introduced?**
First used the cava-git AUR package, then compiled from the master branch. Issue has been present since at least the start of PipeWire support in commit 0c2672e.

**Describe the bug**
When uncommenting the noise_reduction setting, bar movement becomes extremely erratic, regardless of what nose_reduction is set to (even the default `noise_reduction = 0.77` or the maximum value of 1.0.) Changing the value does not seem to have any effect.

**To Reproduce**
Set method to PipeWire, uncomment noise_reduction and play any audio with cava running (behavior identical between sdl and ncurses).

**Expected behavior**
Presumably, a value of 0.77 should have no effect on cava's behavior vs. leaving the setting commented. Changing the value significantly should cause a significant change in output noise.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ArchLinux 
 - Version: (Installed from the 2023.07.01 release)

**Terminal emulator**
- foot version: 1.14.0 +pgo +ime +graphemes -assertions

**Additional context**
...Honestly now that it's on my system I have no idea how to get audio running through anything _but_ PipeWire, otherwise I would try harder to find when this was introduced.

**Comment by karlstav** [comment]
The options was changed from 0 -
1 to 0 - 100 when adding windows support. This due to windows native ini config not supporting floats
