### ISSUE TITLE
Cava gradient colors problems unchangable

### ISSUE THREAD

**Issue by nghi01** [karlstav/cava#515]
**When/where was the bug introduced?**
Installed cava initially through cloning the repo and compile the source code. Does not work so had to uninstall it to reinstall through AUR. There is no bug if gradient value in the config file is not set to 1. As soon as gradient is enabled, the bug will happen.

**Describe the bug**
The columns visualizing audio becoming gradients of weird colors that could not be altered no matter what the value of gradient_color_1 to gradient_color_8 are. Else, if gradient = 0 then everything is fine, but cava will remain white without gradient colors.

**To Reproduce**
1. Set config parameter to gradient = 1.
2. run cava
3. Play music
4.  The error appeared.

**Expected behavior**
The gradient colors will be changed according to whatever the gradient_color_1 to gradient_color_8 are.

**Screenshots**
![image](https://github.com/karlstav/cava/assets/70782465/c9c0554c-fc12-441a-a947-32c378b85a1b)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: I don't think Arch has one.

**Terminal emulator**
- konsole
- version 23.04.3

**Comment by karlstav** [comment]
If i remember correctly there was some issue with konsole not being able to redefine colors. Try with a different terminal.

**Comment by nghi01** [comment]
It looks like GNOME terminal does not have this problem, while yakuake also has the same problem. Is it more of a konsole, yakuake's colors problem instead of cava's? If that's so I'm gladly closing this issue.

**Comment by karlstav** [comment]
#194
