### ISSUE TITLE
ln: /usr/local/bin/libtoolize: Permission denied

### ISSUE THREAD

**Issue by nithilgadde** [karlstav/cava#517]
**When/where was the bug introduced?**
- Are you using cava from a package repository, like AUR?
- If so, check out the master branch here, is your issue already resolved?
- Don't know how to clone, compile source code? File report to package maintainer instead.
- try using git bisect to find out where the bug was introduced.

**Describe the bug**
(ln: /usr/local/bin/libtoolize: Permission denied)

**To Reproduce**
1. Install Homebrew
2. brew install fftw ncurses libtool automake autoconf-archive pkgconf portaudio iniparser
3. export LIBTOOL=`which glibtool`
export LIBTOOLIZE=`which glibtoolize`
ln -s `which glibtoolize` /usr/local/bin/libtoolize
4. See error: ln: /usr/local/bin/libtoolize: Permission denied

**Expected behavior**
I expected it to produce no errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura 
 - Version 13.4.1

**Terminal emulator**
- Alacritty
- 0.11.0

**Additional context**
Any help would be greatly appreciated.

**Comment by Jir4** [comment]
You can just create an alias instead

**Comment by tenf0ld** [comment]
> You can just create an alias instead 

How would I do this? I'm pretty new to macOS and terminal programs so any help would be appreciated.
