### ISSUE TITLE
On PipeWire, getting "snd_aloop" error message unless capture method is explicitely set to pipewire/pulse

### ISSUE THREAD

**Issue by FeralHedgehog** [karlstav/cava#518]
**When/where was the bug introduced?**
- Are you using cava from a package repository, like AUR?
   **Yes - using the [cava](https://aur.archlinux.org/packages/cava) package from the AUR (also tested with [cava-git](https://aur.archlinux.org/packages/cava-git)).**
- If so, check out the master branch here, is your issue already resolved?
  **No.**
- Try using git bisect to find out where the bug was introduced.
  **Bug introduced in [pipewire support #493](https://github.com/karlstav/cava/commit/0c2672e025fa5fe899ba2c809f16ebe9de9490ad)** 

**Describe the bug**
After upgrading to v0.9.0 and running cava the following error appears:
```
Linux kernel module "snd_aloop" does not seem to  be loaded.
Maybe run "sudo modprobe snd_aloop".
```
However, everything works as expected when setting the `method` setting in the config to either `pipewire` or `pulse`.
I noticed that setting it to `alsa` throws the same error, so maybe the capture method detection logic/order is broken?

**To Reproduce**
1. Leave `method` config parameter unset.
2. Run cava.
3. See error.

**Expected behavior**
Expected cava to run normally without having to configure the capture method.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Audio Server: PipeWire 0.3.77

**Terminal emulator**
- Name: alacritty
- Version: 0.12.2 (9d9982df)

**Comment by andro404-MC** [comment]
Uncommenting the input source from the config fixed it for me, its:
```
method = pipewire
source = auto
```

**Comment by 7ColorsCat** [comment]
> Uncommenting the input source from the config fixed it for me, its:
> 
> ```
> method = pipewire
> source = auto
> ```

It's fixed, tks.

**Comment by FeralHedgehog** [comment]
> Uncommenting the input source from the config fixed it for me, its:
> 
> ```
> method = pipewire
> source = auto
> ```

Yeah but it worked in older versions without having to explicitly set it, and the config comment/documentation says that it should default to pulse and pipewire before the problematic alsa:

```
# Audio capturing method. Possible methods are: 'pulse', 'alsa', 'fifo', 'sndio' or 'shmem'
# Defaults to 'pulse', 'pipewire', 'alsa' or 'fifo', in that order, dependent on what support cava was built with.
```

**Comment by karlstav** [comment]
thanks for the bug report @FeralHedgehog! 

actually two bugs are at play here:

1. pipewire was never added to the list of default inputs
2. the mechanism for selecting default input confused the input enum with a simple counter

**Comment by FeralHedgehog** [comment]
Everything's working after https://github.com/karlstav/cava/commit/b05f8290f65ac62b38c7a7d8395f00b032597f3b.  
Thank you for the fix!
