### ISSUE TITLE
glew.dll not found

### ISSUE THREAD

**Issue by theSoberSobber** [karlstav/cava#520]
**When/where was the bug introduced?**
- Are you using cava from a package repository, like AUR? no.
- If so, check out the master branch here, is your issue already resolved?
- Don't know how to clone, compile source code? File report to package maintainer instead.
- try using git bisect to find out where the bug was introduced.

**Describe the bug**
The sln file of windows cava compiles just fine and launches fine too, but while launching the exe from the shell it says glew.dll not found even though it is in packages installed from nuget.

**To Reproduce**
1. Set config parameter to
2. run
3. do something

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Ubuntu]

**Terminal emulator**
- name
- version

**Additional context**

**Comment by karlstav** [comment]
I haven't bothered making an installer or similar.

When not running from visual studio you will have to copy the dlls needed to somewhere they can be found. Same folder as the executable or in some search path.

**Comment by theSoberSobber** [comment]
I see, that worked. I am closing this now.

**Comment by KoBruh** [comment]
Hey, i see you've closed this but how did you get your hands on all the nuget packages to build it ?
