### ISSUE TITLE
Better error message 

### ISSUE THREAD

**Issue by Arjun31415** [karlstav/cava#522]
Cava package when built `sdl2` and `libGL` libs gives error 
```
Error loading config. cava was built without sdl support, install sdl dev files and run make clean && ./configure && make again
```
when using `sdl_glsl` in config but it launches fine with only `sdl` in config.

This was because even tough I had opengl, i did not have the autoconf archive, and I missed out that message during configure (nix packaging) and only found it while browsing the source code. 

However, this message gives the false understanding that the error is because SDL2 lib was not found, when it could be the case that either libGL or autoreconf archive was not present

This can be changed in line 223 of `config.c`

https://github.com/karlstav/cava/blob/eb74b75dc98dce7b2fbd4faff83f788ec8665b30/config.c#L223-L224

**Desktop:**
 - OS: Nixos 23.11
 - WM: Hyprland (Wayland)

**Comment by karlstav** [comment]
simple copy paste mistake from my side, fixed!
