### ISSUE TITLE
Desktop bottom background Spectrum Analizer

### ISSUE THREAD

**Issue by julas23** [karlstav/cava#523]
First of all, I'd like to thank you for the initiative. I really enjoy cava.
I am a Linux Native Heavy User since 1994. And latelly I using Anrch Linux with KDE/Plasma.
I was running cava partially transparent in konsole, above all windows, full transparent, no titlebar, no scrollbar and no background. So a discrete and transparent spectrum analyzer was jumping over all windows, and when all windows were closed or minimized. The Spectrum came more evident, turning the desktop something with great visual appeal.

My suggestion is to provide a feature to run cava this way, without any adjustments I had to do in konsole for KDE, beacuse now I am running MATE (a lot better than KDE), and is not possible to put cava in desktop background. So, could be possible to provide such resource to run in any Graphical Interface, (MATE, CINNAMON, BUDGIE, WAYFIRE). I do not mention KDE and Gnome, because KDE is the same since ever, with almost all bugs at same age. Gnome was good until 2.8, after 3.0 became something weird and disgusting.

Thanks and regards.

**Comment by karlstav** [comment]
Sounds like a cool project, but out of scope for me I'm afraid. Would need to be specific for each DE i think.

Why is the sollution with a transparent terminal without decorations not possible in mate?
