### ISSUE TITLE
reload cava with a signal or have transparent background

### ISSUE THREAD

**Issue by flick0** [karlstav/cava#524]
**Is your feature request related to a problem? Please describe.**
im trying to change terminal themes(using [theme.sh](https://github.com/lemnos/theme.sh)) on the fly but cava doesnt change its theme unless it is restarted

**Describe the solution you'd like**
have cava reload the colors when a particular signal is sent

**Additional context**

https://github.com/karlstav/cava/assets/77581181/8d4a9c1b-8ba6-48c4-ae82-3475f41d529c

**Comment by karlstav** [comment]
Have you tried

pkill -USR2 cava

As described in the readme?

**Comment by flick0** [comment]
yes, it only seems to affect changes in config and doesnt work when changing the actual terminal colors

**Comment by karlstav** [comment]
Right, what about 

pkill -USR1 cava

?

**Comment by karlstav** [comment]
hi @flick0 

this would be up to the terminal emulator i think. It works in gnome terminal for me, on the fly without having to send any signal.

transparency is also up to the terminal, just make sure to leave the background setting in cava unconfigured.
