### ISSUE TITLE
Help choosing my sound card

### ISSUE THREAD

**Issue by luixiuno** [karlstav/cava#528]
I have 3 cards
```
default:0  HDA Intel HDMi
default:1  HDA Intel PCH
default:2  Loopback
```
I want to use the ALSA method, how can I select the HDA Intel PCH (default:1) card with Cava?

**Comment by luixiuno** [comment]
the default card was something like `hw:Loopback:1`

**Comment by karlstav** [comment]
just copy the example file [here](https://github.com/karlstav/cava/blob/master/example_files/etc/asound.conf) to your /etc folder

you should probably have `"hw:1,0"` as the real device, or maybe you can to `"hw:HDA Intel PCH,0"`, don't remember exactly .

**Comment by luixiuno** [comment]
Hey, thanks for the help, however, I fixed it by uninstalling cava and building it from the source.

**Comment by luixiuno** [comment]
Just clarifying, cava wasn't visualizing, rebuilding fixed it.
