### ISSUE TITLE
Cava no bars on arch linux

### ISSUE THREAD

**Issue by 1MMM10** [karlstav/cava#529]
just cava shows no bars at all
no edit on the config + using arch hyprland kitty
locale confg file set to  LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8 cava
idk what to do next

**Comment by karlstav** [comment]
tried other terminals?

**Comment by mrwormhole** [comment]
I can confirm, that I had the same issue and now I am trying out gnome-terminal

**Comment by karlstav** [comment]
sorry about the late reply, try running:
```
echo -e '\u2588'
```
in your terminal. it should output a box charachter like this one:
█ 
if it does not. Than the issue is most likely with our locale settings. Or font maybe.

**Comment by 1MMM10** [comment]
uhh i totally forgot this
got fixed by uncomment en_US.UTF-8 UTF-8
then run locale-gen 👍
sorry for forgetting this issue
