### ISSUE TITLE
The interface for audio playback is not always recognized

### ISSUE THREAD

**Issue by 0a00** [karlstav/cava#530]
This is my WPCTL Status.。。。。，
I have tried various interfaces but cannot correctly recognize the interface for playing audio unless I manually select loopback as the audio playback interface. However, if I choose this computer and there is no sound, what should I do? This is my device information。。。thanks thanks
❯ wpctl status
PipeWire 'pipewire-0' [0.3.80, fixmin@archlinux, cookie:2099046201]
 └─ Clients:
        31. xdg-desktop-portal                  [0.3.80, fixmin@archlinux, pid:3551]
        32. xdg-desktop-portal-hyprland         [0.3.80, fixmin@archlinux, pid:3559]
        33. WirePlumber                         [0.3.80, fixmin@archlinux, pid:3466]
        34. WirePlumber [export]                [0.3.80, fixmin@archlinux, pid:3466]
        36. pipewire                            [0.3.80, fixmin@archlinux, pid:3486]
        37. waybar                              [0.3.80, fixmin@archlinux, pid:3310]
        65. Chromium input                      [0.3.80, fixmin@archlinux, pid:3942]
        83. Chromium                            [0.3.80, fixmin@archlinux, pid:3942]
       220. wpctl                               [0.3.80, fixmin@archlinux, pid:21558]

Audio
 ├─ Devices:
 │      47. Renoir Radeon High Definition Audio Controller [alsa]
 │      48. Family 17h/19h HD Audio Controller  [alsa]
 │      82. Loopback                            [alsa]
 │
 ├─ Sinks:
 │  *  101. Family 17h/19h HD Audio Controller Speaker + Headphones [vol: 0.40]
 │     115. Loopback Analog Stereo              [vol: 0.64]
 │
 ├─ Sink endpoints:
 │
 ├─ Sources:
 │      88. Family 17h/19h HD Audio Controller Headphones Stereo Microphone [vol: 1.00]
 │  *  106. Family 17h/19h HD Audio Controller Digital Microphone [vol: 0.50]
 │     121. Loopback Analog Surround 7.1        [vol: 1.00]
 │
 ├─ Source endpoints:
 │
 └─ Streams:
       109. Chromium
            107. output_FL       > ALC295 Analog:playback_FL	[active]
            108. output_FR       > ALC295 Analog:playback_FR	[active]

Video
 ├─ Devices:
 │      43. HD WebCam: HD WebCam                [libcamera]
 │      44. HD WebCam                           [v4l2]
 │      45. HD WebCam                           [v4l2]
 │      46. Dummy video device (0x0000)         [v4l2]
 │
 ├─ Sinks:
 │
 ├─ Sink endpoints:
 │
 ├─ Sources:
 │      49. Built-in Front Camera
 │      51. HD WebCam (V4L2)
 │  *   53. Dummy video device (0x0000) (V4L2)
 │
 ├─ Source endpoints:
 │
 └─ Streams:

Settings
 └─ Default Configured Node Names:
         0. Audio/Sink    alsa_output.pci-0000_03_00.6.HiFi__hw_Generic_1__sink
         1. Audio/Source  alsa_input.pci-0000_03_00.6.HiFi__hw_acp__source

**Comment by karlstav** [comment]
pipewire should work out of the box if you just leave cava unconfigured. (it should be default in latest cava)

your `101. Family 17h/19h HD Audio Controller Speaker + Headphones [vol: 0.40]` looks like your default sink and cava should by default also visualize whatever is coming out from there.

if you have some older version of cava it might be trying to use alsa directly. what is the output of `cava -v`?

**Comment by 0a00** [comment]
❯ cava -v
cava 0.9.0

The arch repository used should be the latest version, and I am not sure if it is a problem with my audio service configuration or something else. I also attempted to modify the configuration file.

As shown in the figure, when I selected the playback to Loopback Analog Stereo, CAVA worked normally, but as a result, the computer lost its sound,

![图片](https://github.com/karlstav/cava/assets/59482058/09f70aef-dfd4-48ac-a6a2-a1fde069382e)
![图片](https://github.com/karlstav/cava/assets/59482058/12c9a57a-0b6c-4000-af7a-00166ad52952)

**Comment by karlstav** [comment]
hi @0a00 

0.9.0 is not the latest version

there is a bug in 0.9.0 where this would happen. It is described here #518. This is fixed in 0.9.1. Please make the arch package maintainer upgrade it

**Comment by 0a00** [comment]
The update to the new version is working properly. Thank you
