### ISSUE TITLE
Question regarding right padding

### ISSUE THREAD

**Issue by idzmitry** [karlstav/cava#531]
Hi. It seems that right padding bigger than left.
![image](https://github.com/karlstav/cava/assets/22106087/e657c94e-5825-459a-8bb6-7dc096358d1f)
Can I shrink it via config?
Windows 11, Windows Terminal, built on my own using Visual Studio 2022

**Comment by karlstav** [comment]
hi @idzmitry,

if there is no room for an entire bar at the end, cava will not draw one. Depending on the size of the window and the font size you could get it a bit better:

![image](https://github.com/karlstav/cava/assets/6968928/e9c03b73-f29c-4e14-a1c6-12bffc920efc)


if you don't need to run it in a terminal, you could also try using the sdl output mode:

![image](https://github.com/karlstav/cava/assets/6968928/6addd77b-a5f7-470f-870d-a7943ad3c4d1)

**Comment by idzmitry** [comment]
Got it. Thank you for the answer.

**Comment by idzmitry** [comment]
Got it. Thank you for the answer.

**Comment by idzmitry** [comment]
Looks nice: 
![image](https://github.com/karlstav/cava/assets/22106087/033d2777-a927-46c5-b014-1659d593aea0)

sdl out mode + passing 'SDL_WINDOW_FULLSCREEN_DESKTOP' into `SDL_CreateWindow`

**Comment by karlstav** [comment]
agreed, I will add it as an option.
