### ISSUE TITLE
Question about command line

### ISSUE THREAD

**Issue by obicho** [karlstav/cava#532]
Is it possible to run this software using command line?
eg
astrofox input_audio.mp3 output_video.mp4

**Comment by karlstav** [comment]
I am confused. do you mean use cava similar to astrofox? to create a video? 

not directly, but you could always just record your screen.

**Comment by obicho** [comment]
I have been creating videos using
https://github.com/adefossez/seewav

I wanted to see I can use astrofox similarly. Thanks.

**Comment by karlstav** [comment]
then ask the people at astrofox, this is cava
