### ISSUE TITLE
Not working on FreeBSD 14.0-p2 with sndio 

### ISSUE THREAD

**Issue by dr3mro** [karlstav/cava#537]
Using the cava from freeBSD latest repository and install via PKG
version : 0.7.4

playing music via mocp or firefox 
opening cava 
not output visualizations as expected.

window manager: dwm
terminal: kitty
![Uploading 2023-12-09-014150_1920x1080_scrot.png…]()

**Comment by karlstav** [comment]
Hi @dr3mro 
That version of cava is over two years old. Try to build from source first.

Just follow the instructions in the readme and reach out here if you get stuck.

Uninstall the PKG version first so as to not get them mixed up with the source build.

**Comment by dr3mro** [comment]
Thanks for the reply
I did notice that already and I did contact the maintainer about that the
version lag

The problem is there is a dependency that is not found and the build stops

**Comment by karlstav** [comment]
I can help you out with that. Just try to do the build and we will figure it out. 

My guess is it is iniparser, it used to be bundled with cava, but as more and more distros had it's own package for it i removed it.

You can very easily just build iniparser youself and point to it when building cava.

**Comment by dr3mro** [comment]
![Uploading 2023-12-09-215440_1920x1080_scrot.png…]()

**Comment by dr3mro** [comment]
`checking for alloca.h... no
checking for snd_pcm_open in -lasound... no
configure: WARNING: No alsa dev files found building without alsa support
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libpipewire-0.3... no
configure: WARNING: No pipewire dev files found building without pipewire support
checking for pa_simple_new in -lpulse-simple... no
configure: WARNING: No pulseaudio dev files found building without pulseaudio support
checking for Pa_Initialize in -lportaudio... no
configure: WARNING: No portaudio dev files found building without portaudio support
checking for sio_open in -lsndio... no
configure: WARNING: No sndio dev files found building without sndio support
checking for sqrt in -lm... yes
checking for fftw_execute in -lfftw3... no
configure: error: fftw library is required!

~/Downloads/cava-0.9.1 via C v16.0.6-clang 
❯ sudo pkg install fftw3
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed
pkg: Package database is busy while closing!
`

**Comment by dr3mro** [comment]
solved! had to install gcc as it wont compile with clang 
sorry please close

**Comment by karlstav** [comment]
So it was the fftw3 port that did not compile with clang?

And cava 0.9.1 built from source worked as expected?

**Comment by dr3mro** [comment]
Yes, it was.
But I notices something
That it is showing music playback visualization even that I have paused
the  music player
Is that an intended behavior?

**Comment by karlstav** [comment]
which audio backend are you using? If you are on freeBSD I would have thought you are using the sndio one. But your config log above says it is building without sndio...?

**Comment by karlstav** [comment]
for some of the backends the audio input goes to zero when the music application or similar is paused, for others this behavior had to be implemented (portaudio/fifo). In sndio there is no such implementation at the moment, so I am not really sure. Haven't touched the sndio thnig myself myself.

**Comment by dr3mro** [comment]
Yes I use sndio
 It keeps showing visualizations even I pause audio :)

**Comment by karlstav** [comment]
someone would have to implement some mechanics to detect if the sound is paused (device closed?), similar to this maybe:

https://github.com/karlstav/cava/blob/master/input/fifo.c#L30

or

https://github.com/karlstav/cava/blob/master/input/portaudio.c#L41

or completely different. 

Out of scope for me at the moment I am afraid.
