### ISSUE TITLE
OSS input backend and general improved FreeBSD support

### ISSUE THREAD

**Issue by bsdcode** [karlstav/cava#538]
Hallo CAVA team,

I implemented an OSS input backend for use in FreeBSD.

The effort started with this forum post:
https://forums.freebsd.org/threads/santa-claus-brings-you-audio-cava-with-oss-support.91619/

The implementation is here:
https://github.com/bsdcode/cava/tree/oss

- OSS: add 'enable-oss-input' configure option
- OSS: set to default input method if enabled
- sndio: add to input method selection sequence with high priority
- sndio: fix small bug in channel setting
- FreeBSD: add 'enable-cava-font' configure option, which creates vt(4) font cava.fnt from cava.psf
- doc: extended documentation in example config file and in README.md

Let me know your thoughts about it and if we can merge it with CAVA.

**Comment by karlstav** [comment]
Looks good! I have no experience with freeBSD or oss, but just make a pull request and we will take it from there

**Comment by bsdcode** [comment]
Thank you!

**Comment by bsdcode** [comment]
Thank you for merging and a really fine piece of software that is CAVA. In order to bring the official FreeBSD port and package up to date it would be beneficial to have a new release version of CAVA with the recent changes. Can you create a new release (0.10.0)?

**Comment by bsdcode** [comment]
FYI: I have submitted a patch to update the FreeBSD port and package:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276228

**Comment by bsdcode** [comment]
The version in the FreeBSD ports tree is updated to 0.10.1 now.
