### ISSUE TITLE
`can't load config client.conf` and crashes

### ISSUE THREAD

**Issue by mageowl** [karlstav/cava#541]
**Describe the bug**

I am on Linux Mint 21.1. When trying to use the Pipewire 

## To Reproduce**

1. Uncomment the lines for Pipewire
2. run
3. See error

## Expected behavior**
Doesn't crash.

## Log
```
[W][67122.332269] pw.conf      | [          conf.c: 1016 try_load_conf()] can't load config client.conf: No such file or directory
[E][67122.332345] pw.conf      | [          conf.c: 1045 pw_conf_load_conf_for_context()] can't load config client.conf: No such file or directory
```

## Desktop (please complete the following information):
 - OS: Linux Mint
 - Version 21.1

**Terminal emulator**
kitty 0.30.1

**Additional context**
I am on an Intel MacBook.

**Comment by mageowl** [comment]
It does work with ALSA.

**Comment by karlstav** [comment]
Is mint 21.1 really using pipewire for audio? Try using pulse instead in the cava config

**Comment by mageowl** [comment]
Pipewire is a requirement for using Linux on Intel Macs, but I somehow didn't install it properly. Reinstalling fixed this issue.
