### ISSUE TITLE
Another raw output method that writes bars to output using "▁▂▃▄▅▆▇█ "

### ISSUE THREAD

**Issue by JonathanSteininger** [karlstav/cava#542]
<h2>Is your feature request related to a problem? Please describe.</h2>
I am creating a config for eww widgets and want to add cava's music visualizer into it to allow it to remain in the background on hyprland.
The problem is that eww can't parse the data fast enough. It will use 50% of my cpu just to run cava and get the raw output. It would also have to json parse it to be able to create bars. It is not feasible.

<h2>Describe the solution you'd like</h2>
This solution makes cava have another raw output option (unicodeBlock). Cava outputs the bars as "▁▂▃▄▅▆▇█ " to generate an entire frame. In order to have the bars be taller than a single charecter, cava outputs multiple lines with a delimiter of choice.

With a line delimiter you can then read the last line of stdout and replace the delimiter with new line charecters.

<h4>example:</h4> in this config the line delimiter is ";" and the ascii limit is 23 (0-23 = 3 lines of 8 high bars). <br>
The output would look like this:<br> "█▂▃█  █▅▅█;████▂▃████;██████████"<br>
And when passed to eww and have the delimiter replaced with \n would look like this:<br>
█▂▃█  █▅▅█<br>
████▂▃████<br>
██████████<br>
Then having a monospaced font would make it look exactly like bars. 

The height of the bars can be decided with the ascii_max_range

<h2>Describe alternatives you've considered</h2>
<ul>
<li>eww: I tried changing the output to be in json format but json parsing to iterate over bars was too expensive.</li>
<li>eww: I tried formating the output to be raw yuck widgets but eww can't parse it fast enough to even render.</li>
<li>hyprland: I tried to find an alternative to have a raw cava window be in the background using hyprland. But failed due to it only being</li> <li>psuedo possible through hyprpm on hyprland version 0.34.0 which currently breaks eww buttons.</li>
</ul>

<h2>Add any other context or screenshots about the feature request here.</h2>

I have already made a working version from the cava source by changing the raw ascii output to be what I proposed. I will make a cleaner version that adds it in the way that I proposed in this request rather that leeching off of existing functions.

Here are some examples of it running:
raw output from my cava: https://github.com/karlstav/cava/assets/51342815/2687a99f-04e1-42fd-98be-121ce55fe2cc
<video src="https://github.com/karlstav/cava/assets/51342815/2687a99f-04e1-42fd-98be-121ce55fe2cc"></video>
<br><br>
eww config using my version: https://github.com/karlstav/cava/assets/51342815/1652a159-fa0d-4e14-8646-6485d1f9e07f
<video src="https://github.com/karlstav/cava/assets/51342815/1652a159-fa0d-4e14-8646-6485d1f9e07f"></video>

**Comment by karlstav** [comment]
could it be possible to achieve the same result by just piping the normal noncurses output to the widget?

how is the values from cava passed to the widget?

**Comment by JonathanSteininger** [comment]
values get passed to eww through stdout. There are 3 different variables. static, polling, and listening.
<ul>
<li>static defines a value on startup and can be manually changed.</li>
<li>polling runs a command on a fixed timer and the stdout from that command will become the value.</li>
<li>listening will run a command, and then the last line that was printed into stdout will become the value.</li>
</ul>

So I need eww to get text that can then be turned into bars in some way. All the methods I have tried were too slow.

I have tested noncurses output and eww fails to read it and it remains empty "" (which is the default null value in eww).

**Comment by karlstav** [comment]
I think a good approach might be to write a wrapper to pipe the raw output via. Cava could write the raw output to a fifo and the wrapper could read the values and print the output.

**Comment by JonathanSteininger** [comment]
That seems like a logical thing to do. I will go ahead and make a small program to do this and compare the performance.

**Comment by JonathanSteininger** [comment]
Alright I have Created a wrapper and I am getting about twice the performance than the modifications I made with a cava fork. I will close this issue since this is a lot more maintainable and easier to use. I want to thank you for your quick responses.

**Comment by JonathanSteininger** [comment]
Closing issue
