### ISSUE TITLE
[WORKAROUND FOUND] Cava and Cava-GIT from the AUR is not visualizing audio.

### ISSUE THREAD

**Issue by kerbyyy** [karlstav/cava#543]
As the title suggests, cava and neither cava-git from the AUR is visualizing audio. It was working a while ago but then after I restarted my device, it's not doing anything anymore. Here's a recording for reference:

https://github.com/karlstav/cava/assets/71778389/91cd7103-db83-4fb2-bb1f-8777e3526164

**Comment by kerbyyy** [comment]
### UPDATE:
Fixed the issue by change my locale.
I used the command `locale` to check what locale I was using before, and it was `en_PH`.

I changed the locale in its config file, which is located in `/etc/locale.conf` and changed my locale to `en_PH.UTF-8`. It seems like using locales that are not `UTF-8` breaks cava, this is based on my observation to other issues with the same case as to what happened to me.

**Comment by quincynyan** [comment]
Cava from the AUR is flagged as outdated.
