### ISSUE TITLE
Config ignored on Windows 11

### ISSUE THREAD

**Issue by maddo7** [karlstav/cava#549]
I copied the configs and shaders to C:\Users\"username"\.config\cava but it seems this is ignored.
I always just get the white bars.

![image](https://github.com/karlstav/cava/assets/17200733/3d3fc9da-75c0-4d64-9925-04884a772600)

Running as admin does not help but it seems to put symbols on top of the bars.

![image](https://github.com/karlstav/cava/assets/17200733/d2508cb0-a89a-4c08-9ff7-bd9eb95feb40)

What would be the best way to address this and find a solution?
Any help is greatly appreciated.

**Comment by karlstav** [comment]
hmm on windows you can specify the config path by adding it as a argument when running cava like this:
```
cava.exe C:\Users\"username"\.config\cava
```

does it work then?

also did you remember to remove the semicolon before the config option that you like to change?

**Comment by maddo7** [comment]
Thank you very much for your quick reply.

Today when I tested it again, it worked.
I think yesterday I accidentally modified the wrong file.
