### ISSUE TITLE
Idea: Check for /sys/module/snd_aloop/ if input is ALSA

### ISSUE THREAD

**Issue by hartwork** [karlstav/cava#55]
The error "not permitted"
```
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/pcm/pcm_hw.c:1693:(_snd_pcm_hw_open) Invalid value for card
error opening stream: Operation not permitted
```
is a bit misleading, since adding `sudo` will not fix the problem. It would be cool  if cava could check for the existence of /sys/module/ (sysfs mounted) and then for /sys/module/snd_aloop/ (module loaded). That should allow producing a more helpful error message. What do you think?

**Comment by karlstav** [comment]
agreed, getting the alsa/pulseaudio stuff to work can be difficult and not all people like reading readme files...

I can get to work on it next week, I hope.

Any suggestions would be awesome.

**Comment by hartwork** [comment]
Cool!

**Comment by karlstav** [comment]
guess this one is done also, thanks to @hartwork :+1:
