### ISSUE TITLE
Is it possible to remove the bar heads from idle Cava?

### ISSUE THREAD

**Issue by pkreuzt** [karlstav/cava#550]
I don't know if I'm missing something, but found no way to have a completely clear cava window when no sound is playing. Already tried using ignore parameter, but it doesn't serve to this purpose.

My intent is to use Cava as desktop background, but to be only visible when playing something. Seeing this idling bar heads all the time over wallpaper is a bit annoying.

**Comment by karlstav** [comment]
There is no way at the moment, but I can add an option for it. Should be easy.

**Comment by pkreuzt** [comment]
That would be really great, thank you very much !
