### ISSUE TITLE
Android source code

### ISSUE THREAD

**Issue by Twig6943** [karlstav/cava#552]
Title.

**Comment by karlstav** [comment]
will look in to this

**Comment by Twig6943** [comment]
@karlstav  Soo hows that going?

**Comment by karlstav** [comment]
The android build chain that I have locally is very hacky.

I have to formalise the build stuff and make some changes before I can merge it into the source. 

Little time at the moment I'm afraid. So this will not happen anytime soon.

**Comment by Twig6943** [comment]
@karlstav Could you upload the .apk to the releases tab or to somewhere else for the time being?

**Comment by karlstav** [comment]
putting the app on playstore was mostly for laughs and the learning experience. I will get the android source on to here at some point.

**Comment by Twig6943** [comment]
Ait still waiting 👍

**Comment by Twig6943** [comment]
@karlstav  any updates on this? Would be cool if u uploaded the app as is to a cusom fdroid repo for the time being (assuming that your still rewriting it)

**Comment by ilobilo** [comment]
+1

**Comment by karlstav** [comment]
I will try to get the source up here, have to figure out some meaningful way of distributing it. Not much time for it at the moment.

**Comment by Twig6943** [comment]
@karlstav  are you uploading rn?

**Comment by Twig6943** [comment]
Binaries: https://www.mediafire.com/file/krm3ek75m1hceex/cava-initial-release.apk

**Comment by ilobilo** [comment]
could you add an option in the app to use audio output instead of input?

**Comment by karlstav** [comment]
I made the app free on playstore now. Note that the playstore app does not use the same keystore

**Comment by karlstav** [comment]
I have been trying to grab audio directly from output. There is some extra security thing that makes it difficult, but I think it should be possible. Might look into it later.

**Comment by Twig6943** [comment]
> I have been trying to grab audio directly from output. There is some extra security thing that makes it difficult, but I think it should be possible. Might look into it later.

This + the app on the fdroid + the ability to import & export configs would be pretty cool to have (Ik that its still wip and has a long way to go ty for releasing the source code)

**Comment by Twig6943** [comment]
@karlstav should I create a seperate issue for F-Droid release? (Dont matter if it gets into F-droid or a custom F-droid repo like [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) )

**Comment by Twig6943** [comment]
Putting the apks to the releases tab would also work with [Obtanium](https://github.com/ImranR98/Obtainium)

**Comment by karlstav** [comment]
Nothing will happen at this end for getting cava onto f-droid/Obtanium i am affraid. But if I understand this correctly anyone can request it to go up there.

**Comment by Twig6943** [comment]
FYI Obtanium isn't an app stıre its a utility that pulls and auto-updates the .apk from github/gitlab etc.
