### ISSUE TITLE
Very high sensivity

### ISSUE THREAD

**Issue by Auerd** [karlstav/cava#554]
**Describe the bug**

Without autosense it is needed to set very high sensivity

**To Reproduce**

1. disable autosense in config
2. start cava
3. nothing happening
4. close cava
5. set sensitivity to 2000000 or something in config
6. start cava
7. it's working!

**Expected behavior**

100 or 150 sensitivity needed

**Desktop:**

 - OS: Arch
 - Version: latest

**Terminal emulator**
- Kitty

**Comment by karlstav** [comment]
hi @Auerd,

could you have set the volume very low on your audio source?

**Comment by Auerd** [comment]
hello @karlstav,

you were right, my headphones really loud...
