### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by feelsunbreeze** [karlstav/cava#555]
**READ THIS BEFORE CREATING NEW ISSUE**

Are you using cava from a package repository, like AUR?

I have tried cava from this github repo (I did the ./autogen.sh and ./configure) and from AUR but both give the same error

If so, clone the master branch from here, build and run. Is your issue already resolved?

Don't know how to clone or compile source code? File report to package maintainer instead!

**Describe the bug**

I get a segmentation fault error with the [E] pw.loop. The screen is below.

**To Reproduce**

1. Install & run cava, literally.

**Expected behavior**

Cava to run

**Screenshots**

![img](https://github.com/karlstav/cava/assets/94978059/a7c05605-d0b9-413c-9f8d-813057f6bedb)

**Desktop (please complete the following information):**

- Arch Linux kernel 6.8.1-arch1-1

**Terminal emulator**
kitty
0.33.0

**Additional context**
This is really just a fresh install of arch.

**Comment by karlstav** [comment]
the real issue here is the pw_loop_new cant make support.system... what is your pipewire version? maybe related to #557?

**Comment by feelsunbreeze** [comment]
The issue was resolved, pipewire had not been installed on my system.

Might want to include pipewire in the arch linux install instruction.

Cheers!
