### ISSUE TITLE
Cava ignores the config file

### ISSUE THREAD

**Issue by KittyCinnamon** [karlstav/cava#559]
i've installed cava, everything went smoothly, it works just right, so i decided to customize it and read some guides online, the thing is, when i opened the config file was empty so i copy-pasted a code  i found on git, for the basic config of cava, i then tried to change the colors accordin to the Rosè Pine palette, but it doesn't work, it keeps beign white on black. i don't know what i am doing wrong i i can't find the solution online.

**Comment by Skyfighter64** [comment]
I don't think the default config file should ever be empty, make sure you are using the right path (`'/home/[username]/.config/cava/config`)

You can also try to specify your custom configuration manually using `cava -p /path/to/your/config`.

All of this, and even more is documented in the [README.md](https://github.com/karlstav/cava?tab=readme-ov-file) file.

**Comment by karlstav** [comment]
remove the semicolon before the lines you need to change maybe?
