### ISSUE TITLE
Is it possible to integrate into a console-based music player?

### ISSUE THREAD

**Issue by ghostplant** [karlstav/cava#563]
**Is your feature request related to a problem? Please describe.**
Is it possible to be integrated into a console-based music player? For example, ffplay, mpv, etc.

**Describe the solution you'd like**
Using ffplay/mpv music.mp3, visualization of music tracks will be displayed in a console, instead of showing nothing.

**Comment by karlstav** [comment]
not really no. you would have to run cava in another terminal instance. You could maybe use a terminal multiplexer like tmux
