### ISSUE TITLE
Error: failure in opening stream (Invalid number of channels)

### ISSUE THREAD

**Issue by Andr3wcr0z** [karlstav/cava#564]
Hello! I use am a MacOS user for Cava. I have Sonoma 14.2.1 on a 2014 Macbook pro. I for some reason keep getting the error `Error: failure in opening stream (Invalid number of channels)`

<img width="727" alt="Screenshot 2024-05-14 at 18 07 41" src="https://github.com/karlstav/cava/assets/111403135/411c5991-dd87-45d8-955c-ef09c74b02ce">

Whenever I try to remove the semicolon before the other audio sources, it says that cava was built without that source's input support.

(I have the default config.) Have not modified.

**Comment by karlstav** [comment]
on macbook you would only have the portaudio option so that is fine.

Have you tried following the instructions in the readme here:

https://github.com/karlstav/cava?tab=readme-ov-file#macos-1
