### ISSUE TITLE
 error while loading shared libraries: libiniparser.so

### ISSUE THREAD

**Issue by SherLock707** [karlstav/cava#568]
**Describe the bug**

When I launch Cava I get following error:
`cava: error while loading shared libraries: libiniparser.so.1: cannot open shared object file: No such file or directory`

**To Reproduce**

1. Open terminal
2. Run `cava`

**Expected behavior**

Cava without error.

**Screenshots**

![image](https://github.com/karlstav/cava/assets/26952545/0b0016ac-3f92-45e9-88ab-7d65067719a6)

**Desktop (please complete the following information):**

 - OS: Arch linux
 - Version: latest
 - WM: Hyprland
 - Kernel: Linux 6.9.2-zen1-1-zen
 - Shell: Fish

**Terminal emulator**
- Foot
- 1.17.2-1

**Additional context**
It was working fine for past 6 months.
Did not use it for few days, when I tried today, I got this issue.
I have `/usr/lib/libiniparser.so`

**Comment by leombrunk** [comment]
Looks like this https://gitlab.archlinux.org/archlinux/packaging/packages/iniparser/-/commit/11885ca3a924ac52a0329ccf95f8314663f9ebc6
removed the line ln -sf libiniparser.so.1 "${pkgdir}"/usr/lib/libiniparser.so

**Comment by karlstav** [comment]
could be that the package was changed from providing a .1 to not providing a .1. Try doing a complete reinstall of cava.

**Comment by eyal670** [comment]
I have the same problem
trying to reinstall cava did not solve the problem

**my machine:**
OS: Arch Linux x86_64
Kernel: Linux 6.9.2-arch1-1
Shell: zsh 5.9
DE: bspwm
WM: LG3D (X11)
Cursor: Adwaita
Terminal: alacritty 0.13.2
Terminal Font: Hack Nerd Font (12pt)
CPU: Intel(R) Core(TM) i5-8250U (8) @ 3.40 GHz
GPU: Intel UHD Graphics 620 @ 1.10 GHz [Integrated]
Memory: 3.57 GiB / 7.54 GiB

**Comment by SherLock707** [comment]
> could be that the package was changed from providing a .1 to not providing a .1. Try doing a complete reinstall of cava.

I did try reinstalling before filing here.. error stayed the same.

**Comment by karlstav** [comment]
I thought maybe that a rebuild would make it search for the library again and find the correct one. I don't think that there is anything in the cava build stuff that makes it look for the .1 link or not the .1

You would have to check with the iniparser arch package maintainer why the .1 was removed and how it is supposed to work now.

**Comment by mementomori74** [comment]
i have the same problem. using arcolinux (arch based)

**Comment by Levvonci** [comment]
Same issue here, Arch + Hyprland

**Comment by karlstav** [comment]
I thought that the linker would look for `libiniparser.so`when doing `-liniparser`. Normally  `libiniparser.so` whould be a link to  `libiniparser.so.1` and the the linker would use that file instead, but if it was not a link that should also be fine. However if some update removed the  `libiniparser.so.1` and made  `libiniparser.so` the only file available then any program linking to  `libiniparser.so.1` would start failing. However a rebuild should fix that. 

did any of you arch people actually clone and build from source?

**Comment by Levvonci** [comment]
Got a fix, simply uninstalled the aur pkg `cava`, clone the repo and build it

**Comment by mementomori74** [comment]
> I thought that the linker would look for `libiniparser.so`when doing `-liniparser`. Normally `libiniparser.so` whould be a link to `libiniparser.so.1` and the the linker would use that file instead, but if it was not a link that should also be fine. However if some update removed the `libiniparser.so.1` and made `libiniparser.so` the only file available then any program linking to `libiniparser.so.1` would start failing. However a rebuild should fix that.
> 
> did any of you arch people actually clone and build from source?

nope sorry will do that now

**Comment by eyal670** [comment]
I can confirm that installing the AUR package `cava-git` is working as expected

**Comment by e-dong** [comment]
I was on cava 0.8.0 and got the same error. Updating to the latest (0.10.2) fixed the issue.

**Comment by karlstav** [comment]
Issue is with arch/iniparser

**Comment by karlstav** [comment]
found this old reddit that i think is relevant for this issue:

https://www.reddit.com/r/archlinux/comments/ymv7vp/reminder_to_rebuild_aur_packages_on_soname_updates/
