### ISSUE TITLE
Linking fails on 10.6: `Undefined symbols: _glGenVertexArrays, _glReleaseShaderCompiler, _glBindVertexArray`

### ISSUE THREAD

**Issue by barracuda156** [karlstav/cava#570]
These do not seem to exist on earlier macOS:
```
Undefined symbols:
  "_glGenVertexArrays", referenced from:
      _init_sdl_glsl_window in cava-sdl_glsl.o
  "_glReleaseShaderCompiler", referenced from:
      _init_sdl_glsl_window in cava-sdl_glsl.o
  "_glBindVertexArray", referenced from:
      _init_sdl_glsl_window in cava-sdl_glsl.o
ld: symbol(s) not found
```
Should we try using `mesa` or these symbols can be just enabled conditionally instead?

**Comment by karlstav** [comment]
10.6? Snow leopard? 2009?

**Comment by barracuda156** [comment]
> 10.6? Snow leopard? 2009?

It is still used on earlier Intel (10.6 is the last macOS to run on CoreDuo machines) and PowerPC (ppc code was removed in 10.7).

**Comment by karlstav** [comment]
Right, I forgot about the vintage computer enthusiasts. Some of those old macs were quite sturdy. 

If you are not planning to use the opengl output you can disable it in the configure step with

--disable-output-sdl-glsl

**Comment by barracuda156** [comment]
@karlstav Thank you! Will try it and let you know.

**Comment by barracuda156** [comment]
@karlstav Yes, that worked :)
