### ISSUE TITLE
Cava causing crashes of pipewire

### ISSUE THREAD

**Issue by foxos21** [karlstav/cava#571]
Are you using cava from a package repository, like AUR?
:I installed cava from yay

I played a video/audio/anything on firefox and then started cava, video keeps playing but after i stop it and then try to play again it just infinitely loads.
if i start cava before playing anything it's the same problem but instant.

I am using archlinux with Hyprland

**Terminal emulator**
- Kitty

**Comment by karlstav** [comment]
> :I installed cava from yay

please build from latest version of source before posting issue.

**Comment by karlstav** [comment]
can't reproduce on my system, but might be related to how pipewire is set up, if you are using pipewire
