### ISSUE TITLE
Gradient depends on the window size

### ISSUE THREAD

**Issue by s0la** [karlstav/cava#572]
Hi!

I recently reinstalled Arch and installed cava from source (git) and I'm having strange gradient issues..
I always run cava in a very small window underneath ncmpcpp window, like on the screenshot (bottom window on the right):

![cava3](https://github.com/karlstav/cava/assets/6886981/4f2db3a5-1339-4d9a-9eda-5b41d33e0642)

So, before fresh Arch installation it used to look like on the bigger terminal (alacritty with tmux, btw), but now you can see on the smaller one the separation between the color is very abrupt (almost like there is no color between those two), and on top of that, there is a third (yellow) color which I didn't define..

Here is yet another example of the window of mid size (kinda between those two):

![cava2](https://github.com/karlstav/cava/assets/6886981/74e9cf2e-5ec3-432c-b2dd-aa29b4fae2ab)

I can provide the config file or any additional information if necessary, though I didn't change anything before or after the installation, my home partition was intact, and other apps config files are working correctly..

Any idea of what might be going on?

**Comment by karlstav** [comment]
config file would be nice

**Comment by s0la** [comment]
Sure, here it is:


## Configuration file for CAVA. Default values are commented out. Use either ';' or '#' for commenting.


[general]

# Smoothing mode. Can be 'normal', 'scientific' or 'waves'. DEPRECATED as of 0.6.0
; mode = normal

# Accepts only non-negative values.
framerate = 30

# 'autosens' will attempt to decrease sensitivity if the bars peak. 1 = on, 0 = off
# new as of 0.6.0 autosens of low values (dynamic range)
# 'overshoot' allows bars to overshoot (in % of terminal height) without initiating autosens. DEPRECATED as of 0.6.0
autosens = 0
; overshoot = 20

# Manual sensitivity in %. Autosens must be turned off for this to take effect.
# 200 means double height. Accepts only non-negative values.
sensitivity = 300

# The number of bars (0-200). 0 sets it to auto (fill up console).
# Bars' width and space between bars in number of characters.
; bars = 0
bar_width = 1
bar_spacing = 1


# Lower and higher cutoff frequencies for lowest and highest bars
# the bandwidth of the visualizer.
# Note: there is a minimum total bandwidth of 43Mhz x number of bars.
# Cava will automatically increase the higher cutoff if a too low band is specified.
; lower_cutoff_freq = 50
; higher_cutoff_freq = 10000



[input]

# Audio capturing method. Possible methods are: 'pulse', 'alsa' or 'fifo'.
# Defaults to 'pulse', 'alsa' or 'fifo', in that order, dependent on what support cava was built with.
#
# All input methods uses the same config variable 'source'
# to define where it should get the audio.
#
# For pulseaudio 'source' will be the source. Default: 'auto', which uses the monitor source of the default sink
# (all pulseaudio sinks(outputs) have 'monitor' sources(inputs) associated with them).
# 
# For alsa 'source' will be the capture device.
# For fifo 'source' will be the path to fifo-file.
; method = pulse
; source = auto

; method = alsa
; source = hw:Loopback,1

; method = fifo
; source = /tmp/mpd.fifo



[output]

# Ouput method. Can be 'ncurses', 'noncurses' or 'raw'. 
# 'noncurses' is for systems that does not suport ncurses.
# 'raw' is a 16 bit data stream of the bar heights that can be used to send to other applications.
# 'raw' defaults to 200 bars, which can be adjusted in the 'bars' option above.
; method = ncurses

# Visual channels. Can be 'stereo' or 'mono'.
# 'stereo' mirrors both channels with low frequencies in center.
# 'mono' averages both channels and outputs left to right lowest to highest frequencies.
; channels = stereo

# Raw output target. A fifo will be created if target does not exist.
; raw_target = /dev/stdout

# Raw data format. Can be 'binary' or 'ascii'.
; data_format = binary

# Binary bit format, can be '8bit' (0-255) or '16bit' (0-65530).
; bit_format = 16bit

# Ascii max value. In 'ascii' mode range will run from 0 to value specified here
; ascii_max_range = 1000

# Ascii delimiters. In ascii format each bar and frame is separated by a delimiters.
# Use decimal value in ascii table (i.e. 59 = ';' and 10 = '\n' (line feed)).
; bar_delimiter = 59
; frame_delimiter = 10



[color]

# Colors can be one of seven predefined: black, blue, cyan, green, magenta, red, white, yellow.
# Or defined by hex code '#xxxxxx' (hex code must be within ''). User defined colors requires a
# terminal that can change color definitions such as Gnome-terminal or rxvt.
; background = black
foreground = '#a8b4c4'
gradient = 1
gradient_color_1 = '#a8b4c4'
gradient_color_2 = '#f04b67'

# Gradient mode, only hex defined colors are supported, background must also be defined in hex
# or remain commented out. 1 = on, 0 = off. Warning: for certain terminal emulators cava will
# not able to restore color definitions on exit, simply restart your terminal to restore colors.
; gradient = 1
; gradient_color_1 = '#81a39e'
; gradient_color_2 = '#555555'
; gradient_color_1 = '#81a39e'
; gradient_color_2 = '#ff3399'



[smoothing]

# Percentage value for integral smoothing. Takes values from 0 - 100.
# Higher values means smoother, but less precise. 0 to disable.
; integral = 70

# Disables or enables the so-called "Monstercat smoothing" with or without "waves". Set to 0 to disable. 
; monstercat = 1
; waves = 0;

# Set gravity percentage for "drop off". Higher values means bars will drop faster.
# Accepts only non-negative values. 50 means half gravity, 200 means double. Set to 0 to disable "drop off".
; gravity = 100


# In bar height, bars that would have been lower that this will not be drawn.
; ignore = 0


[eq]

# This one is tricky. You can have as much keys as you want.
# Remember to uncomment more then one key! More keys = more precision.
# Look at readme.md on github for further explanations and examples.
; 1 = 1 # bass
; 2 = 1
; 3 = 1 # midtone
; 4 = 1
; 5 = 1 # treble

**Comment by karlstav** [comment]
you missed the `gradient_count` setting. You would want to set this to 2. If it is not set it defaults to 8, in this case using the default colors from 3-8 and there are some yellow in the middle there. This is not visible when the terminal is very high since the bars only occupy the lower half of the screen.

I can try to change this so that cava only uses the gradient colors that are configured

**Comment by s0la** [comment]
Awesome, spot on! :)

Setting gradient_count to 2 did the trick, nice catch! Not sure how it worked without that setting thus far, but now it works as it did before :)

Thanks for your time and for creating such an awesome app, really appreciate it!

**Comment by karlstav** [comment]
no problem, having to set the count explicitly was sub-optimal anyway, changed the behavior now so it just loads as many as is configured.
