### ISSUE TITLE
Split view or something

### ISSUE THREAD

**Issue by SpomJ** [karlstav/cava#575]
![2024-06-30-184653_hyprshot](https://github.com/karlstav/cava/assets/75751809/2d95473a-8610-4735-8626-ba7d5f8aa61d)

**Is your feature request related to a problem? Please describe.**
The above setup requires 2 terminals, also manual resizing as weird padding occurs by default

**Describe the solution you'd like**
Basically merge the top and bottom views, while anchoring to height/2. This also can be done for left/right (+both inverted). The above screenshot also uses stereo: left on top and right on bottom

**Describe alternatives you've considered**
Some sophisticated terminal or whatever

**Additional context**
screenshot

**Comment by karlstav** [comment]
This was actually intended right from the beginning, but the required block drawing characters didn't exist back then. Now they do! (As the existence of the "top" orientation obviously proves). Looks like they where added in 2020:

https://symbl.cc/en/1FB82/


There was someone else who added the different orientations to cava some years ago and I didn't really consider the possibilities back then.

I will get going on this as soon as I can find some time.

**Comment by SpomJ** [comment]
> This was actually intended right from the beginning, but the required block drawing characters didn't exist back then.

I guess this could've been done without them, by swapping fg & bg colors, I assumed this is how the top view works, but I guess it isn't. And it would mess up some theming anyways.

**Comment by karlstav** [comment]
the [top](https://github.com/karlstav/cava/blob/3f6e9315031b4f7220b79954341a01ec0f6df65e/output/terminal_ncurses.c#L26) view uses the new uncode blocks. Swapping the fg and bg would swap all the stuff already on screen I think

**Comment by karlstav** [comment]
![image](https://github.com/user-attachments/assets/eeded3c7-35b2-4440-bbf3-d314f7398eac)
work in progress, just need some more testing.
