### ISSUE TITLE
Is it possible to use Cava without "Background Music" on MacOS?

### ISSUE THREAD

**Issue by hungvx-dev** [karlstav/cava#578]
https://github.com/kyleneideck/BackgroundMusic has too many errors. Is there an alternative to Background Music or without it?

**Comment by karlstav** [comment]
As the readme says there is also soundflower, but I am not sure if it still works. Other than that I don't know any.

**Comment by hungvx-dev** [comment]
@karlstav Thank you for reply. But Soundflower is too old to use and hasn't been updated since 2014. Also no support for M1 chip. I don't understand much about the technology behind Cava. Can you explain to me why Capturing audio is needed?

**Comment by karlstav** [comment]
both of those can be used yes. They both solve the issue of capturing audio, which is basically sending audio from one application to another.

blackhole looks cool, there is also something called iShowU Audio Capture. If you get any of them working, feel free to add a howto here or make a PR for the readme file.
