### ISSUE TITLE
cava: error while loading shared libraries: libiniparser.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Victinijr** [karlstav/cava#580]
Every time I run cava it says `cava: error while loading shared libraries: libiniparser.so.1: cannot open shared object file: No such file or directory`

What I did

1.` $ yay -S cava`
2. `$ cava`
3. `cava: error while loading shared libraries: libiniparser.so.1: cannot open shared object file: No such file or directory`

**Expected behavior**

I expected to either see an error about the sound thing or to see them bars.

OS Info:

 - Archcraft with hyprland on a surface pro 8
 - Version : most recent one

**Terminal emulator**
- kitty 0.35.2
- zsh 0.49

**Comment by karlstav** [comment]
#568
