### ISSUE TITLE
Can't run cava with lolcat

### ISSUE THREAD

**Issue by safe049** [karlstav/cava#582]
**Describe the bug**
I'm running from the source
When you use lolcat on cava,you will reach a error:
```
  dynamo   ~ git-[ master]-  cava | lolcat
zsh: segmentation fault (core dumped)  cava |
zsh: done                              lolcat
  dynamo   ~ git-[ master]- 
```
When you use the one in the repository of Arch Linux,it will launch but
outputting nothing.

**To Reproduce**

1. Build the cava from github repository and `make install`
2. run `cava | lolcat`
3. error comes up

**Expected behavior**
Able to use cava with lolcat.

**Desktop (please complete the following information):**

 - OS: Arch Linux
 - Version : You don't need a version or what

**Terminal emulator**
-  Alacritty
-  0.13.2-2

**Additional context**
Nothing

**Comment by CocolinoFan** [comment]
I did not know you can pipe `cava` into `lolcat` this is really cool!
