### ISSUE TITLE
Cava erroring when trying to close on Windows.

### ISSUE THREAD

**Issue by KoBruh** [karlstav/cava#585]
**READ THIS BEFORE CREATING NEW ISSUE**

Are you using cava from a package repository, like AUR?
**No, i built from source on windows** 
If so, clone the master branch from here, build and run. Is your issue already resolved?

Don't know how to clone or compile source code? Learn before posting issues here.

**ALWAYS TRY TO BUILD AND RUN FROM THE SOURCE CODE ON GITLAB BEFORE POSTING ISSUES**

If the issue is resolved when building from source, do not post issues here.

**Describe the bug**

When using Ctrl+C on windows to close cava, i get an abort message and cava leaves a ghost in the terminal.

**To Reproduce**

1. Build Cava from source
2. run Cava in terminal
3. Ctrl + C to close

**Expected behavior**

I presume the expected behavior would be it just quitting and taking it back to my shell

**Screenshots**

![image](https://github.com/user-attachments/assets/46a0bf75-0710-4b22-a594-7352a7b08883)
![image](https://github.com/user-attachments/assets/f220d7d7-4693-4076-81c4-d9df342ef55f)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Version	10.0.22631 Build 22631

**Terminal emulator**
- Terminal ( Windows Store ) 
- Version Version: 1.21.2361.0

**Comment by karlstav** [comment]
well, it works in release. It exits fine, so even if it asserts in debug on "invalid signal", i would not worry too much. Just rum the release version.

**Comment by karlstav** [comment]
something is a bit odd though, it should have been signal number 2 when ctrl-c is pressed not 0.

**Comment by karlstav** [comment]
ah the ctrlHandler on windows does not share the signal numbers like on linux, will fix.
