### ISSUE TITLE
No output when specifing a pipewire node

### ISSUE THREAD

**Issue by fabolous005** [karlstav/cava#588]
**Describe the bug**

I want cava to only show sound for some specific applications.
I use pipewire as sound-system, so i created a Node, to which i connect all applications that should be displayed by cava.
But when setting this node as source in cava config i get no bars even though sound is playing.

**To Reproduce**

I'm currently using [coppwr](https://github.com/dimtpap/coppwr) to set this up, but i plan to script it...
1. In Coppwr create a new Node with the `Object Creator` Tool (on the top, in the `Tools` dropdown)
![image](https://github.com/user-attachments/assets/b048282c-d991-44fa-8e60-363e7f8bf41e)
2. I connect my application to the newly created interface
3. I connect the new interface to my actual hardware output
4. Set the object.id or node.name as source in cava config

**Desktop (please complete the following information):**

 - OS: Gentoo
 - cava: Git version
 - PW:
pipewire
Compiled with libpipewire 1.2.4
Linked with libpipewire 1.2.4

**Comment by karlstav** [comment]
hi @fabolous005,

my pipewire implementation is pretty straight forrward, try to grab the output from the default audio sink. So maybe there is something to improve there.


I have never used this coppwr tool before, haven't had much time to play around with pipewire at all actually. It is not like the good old days of linux where fiddling around with the sound system was what you had to do all day. Now it just works, boring.

i did manage to move the wires around to achieve what i think is sort of what you want:

![image](https://github.com/user-attachments/assets/2044d439-0bb9-4656-a8ec-fe013c45a67b)

now cava visualizes spoitify but nothing else. This is of course not a very permanent solution. after restarting cava it will go back
to grab anything

**Comment by karlstav** [comment]
now wait, sorry. I already fixed the thing with the default sink. You have to use the `object.serial` in the cava config, not the id. then it should work:

![image](https://github.com/user-attachments/assets/f3ee9b5e-d38b-4599-854a-d485dd59a230)

**Comment by karlstav** [comment]
The source of confusion here is that if you specify some none existing serial it will simply connect to the default output. This is not deliberate by me, should look into it.

**Comment by fabolous005** [comment]
Actually after a reboot it worked fine, not sure what exactly changed...
I'll still close this for now. Thank you for your effort!
