### ISSUE TITLE
easier windows install

### ISSUE THREAD

**Issue by myudak** [karlstav/cava#591]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when IM CONFUSED WHERE THE FUCK HOW DO I INSTALL THIS SHDJTHING ON WINDOWS WITHOUT WSL

**Describe the solution you'd like**
A FUCKING ONE LINE TERMINAL INSTALL WITH WINGET OR OTHER LIKE SCOOP

**Describe alternatives you've considered**

**Additional context**

**Comment by karlstav** [comment]
this repo is for the cava source code, not for some installers/packet managers. If someone wants to make cava available for scoop or winget, go ahead. But this is not the place to ask for it.

**Comment by myudak** [comment]
but still the normal installations on windows in this repo is still complicated, and i still havent figure how do i compile it

**Comment by karlstav** [comment]
Should be as easy as opening the sln file in visual studio. If you have a specific issue, just open a ticket describing the problem
