### ISSUE TITLE
Cava not starting after brew install cava

### ISSUE THREAD

**Issue by toastsandwich** [karlstav/cava#593]
❯ cava
sh: setterm: command not found
Error: failure in opening stream (Invalid number of channels)

i am facing this error after installing it with brew, and by installing it manually

Please help me with this

**Comment by karlstav** [comment]
Did you go through the steps for capturing audio in the readme?

**Comment by lxjv** [comment]
I'm also getting this while using Background Audio and with it in config

**Comment by karlstav** [comment]
@lxjv: can you give me the list of portaudio devices? Just set cava source to `list` and run. I just comited an improvement for this so it should not break your terminal.

**Comment by lxjv** [comment]
```
Device #1: Background Music
	Input Channels: 2
	Output Channels: 2
	Default SampleRate: 48000.000000
Device #2: Background Music (UI Sounds)
	Input Channels: 2
	Output Channels: 2
	Default SampleRate: 48000.000000
Device #3: MacBook Air Microphone
	Input Channels: 1
	Output Channels: 0
	Default SampleRate: 48000.000000
Device #4: MacBook Air Speakers
	Input Channels: 0
	Output Channels: 2
	Default SampleRate: 48000.000000
```

**Comment by toastsandwich** [comment]
@karlstav I have solved my issue, you can close it...  thanks for the amazing documentation :)

**Comment by willzeng274** [comment]
how did you guys fix it? For me it says "Error: failure in opening stream (Invalid number of channels)" no matter how I change the config. Setting
```
; method = portaudio
; source = list
```
doesn't even work... I tried source "Background Music" too. I used `cava r` several times to refresh and it always gives me the same error

**Comment by willzeng274** [comment]
Is there an alternative other than soundflower and background music for macOS? Soundflower says it does not support Apple silicon chip based macs, and background music is currently incompatible with the latest macOS version (Sequoia 15.1).
