### ISSUE TITLE
Arch: cannot install

### ISSUE THREAD

**Issue by enessmr** [karlstav/cava#597]
**READ THIS BEFORE CREATING NEW ISSUE**

Are you using cava from a package repository, like AUR?
no

If so, clone the master branch from here, build and run. Is your issue already resolved?
no

Don't know how to clone or compile source code? Learn before posting issues here.
no

**ALWAYS TRY TO BUILD AND RUN FROM THE SOURCE CODE ON GITLAB BEFORE POSTING ISSUES**
i used github :)

If the issue is resolved when building from source, do not post issues here.
its not solved, all packages installed

**Describe the bug**

 hyprlanduser@archuser  ~/git/cava   master  ./autogen.sh
configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
/usr/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
/usr/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
configure.ac:306: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1
configure.ac:7: warning: The macro 'AC_PROG_CC_STDC' is obsolete.
configure.ac:7: You should run autoupdate.
./lib/autoconf/c.m4:1669: AC_PROG_CC_STDC is expanded from...
configure.ac:7: the top level
configure.ac:2: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:4: error: possibly undefined macro: AM_PROG_AR
configure.ac:9: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:40: error: possibly undefined macro: AM_CONDITIONAL
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
Makefile.am:13: error: OSX does not appear in AM_CONDITIONAL
Makefile.am:22: error: FREEBSD does not appear in AM_CONDITIONAL
Makefile.am:23: error: CAVAFONT does not appear in AM_CONDITIONAL
Makefile.am:32: error: ALSA does not appear in AM_CONDITIONAL
Makefile.am:36: error: PORTAUDIO does not appear in AM_CONDITIONAL
Makefile.am:40: error: PIPEWIRE does not appear in AM_CONDITIONAL
Makefile.am:44: error: PULSE does not appear in AM_CONDITIONAL
Makefile.am:48: error: SNDIO does not appear in AM_CONDITIONAL
Makefile.am:52: error: OSS does not appear in AM_CONDITIONAL
Makefile.am:56: error: JACK does not appear in AM_CONDITIONAL
Makefile.am:60: error: NCURSES does not appear in AM_CONDITIONAL
Makefile.am:64: error: SDL does not appear in AM_CONDITIONAL
Makefile.am:68: error: SDL_GLSL does not appear in AM_CONDITIONAL
Makefile.am:6: warning: source file 'input/common.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least one source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However, this
automake: behavior may change in a future Automake major version, with object
automake: files being placed in the same subdirectory as the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibility.
Makefile.am:6: warning: source file 'input/fifo.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'input/shmem.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'output/terminal_noncurses.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'output/raw.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled
Makefile.am:6: warning: source file 'output/noritake.c' is in a subdirectory,
Makefile.am:6: but option 'subdir-objects' is disabled

**To Reproduce**

always happens on mine

**Expected behavior**

Just normally install

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Arch Linux
 - Version: 2024-10-11 (i think)

**Terminal emulator**
- Kitty
- 0.36.1

**Additional context**
dont know

**Comment by enessmr** [comment]
Have Google's Meson.

**Comment by karlstav** [comment]
duplicate #594
