### ISSUE TITLE
Can't build cava  NIXOS unstable   failed with exit code 1;

### ISSUE THREAD

**Issue by dwilliam62** [karlstav/cava#599]
**Describe the bug**
Error output during rebuild 

these 12 derivations will be built:
  /nix/store/g0mjcanixacvsvn7zqlm4x9fvl30q0i9-cava-0.10.2.drv
  /nix/store/65261yl684f3fy2jwgdmk709sfdr8s2a-system-path.drv
  /nix/store/wzr7x1c4jfjh615ki4q55vqzrs6w1xkx-dbus-1.drv
  /nix/store/ap2pc8l1j05g5mz0avlfsf8y2z2v1xdi-X-Restart-Triggers-dbus.drv
  /nix/store/05hzdxygq1ddvnz06cblvqqnymhh46nv-unit-dbus.service.drv
  /nix/store/w21a45cb8hbzfachphj76na3bxq1vhyl-X-Restart-Triggers-polkit.drv
  /nix/store/24yb30v8yp7fdvpi7a3zaz39msvdvaay-unit-polkit.service.drv
  /nix/store/lc2nklv3w9qhz953ynmlbc477y0vbb58-user-units.drv
  /nix/store/pgva75l0lcwiq7wdsbqhzm8nwbz8hlrz-unit-dbus.service.drv
  /nix/store/ws6zsc205k8yagdc3l6fs3b1mrkg7nlf-system-units.drv
  /nix/store/9x8934g1xkkbahqzmr80rdx4d7xxqijl-etc.drv
  /nix/store/7i3lmkm326979b9rqjidp65m6rhhlxh0-nixos-system-p520-jakos-25.05.20241115.5e4fbfb.drv
cava> building '/nix/store/g0mjcanixacvsvn7zqlm4x9fvl30q0i9-cava-0.10.2.drv'
cava> Using versionCheckHook
cava> Running phase: unpackPhase
cava> unpacking source archive /nix/store/7n3i4i7mf29fwap22m4srqy73c8vv55n-source
cava> source root is source
cava> Running phase: patchPhase
cava> Running phase: autoreconfPhase
cava> autoreconf: export WARNINGS=
cava> autoreconf: Entering directory '.'
cava> autoreconf: configure.ac: not using Gettext
cava> autoreconf: running: aclocal --force -I m4
cava> aclocal: warning: couldn't open directory 'm4': No such file or directory
cava> configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
cava> lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
cava> lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
cava> /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
cava> lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
cava> /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
cava> lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
cava> lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
cava> configure.ac:306: the top level
cava> autom4te: error: /nix/store/ab13djpkv4pyii8lvz4106bimy62db59-gnum4-1.4.19/bin/m4 failed with exit status: 1
cava> aclocal: error: /nix/store/wky99hgy2w2nb3a6hzgk96yqdbi95zsj-autoconf-2.72/bin/autom4te failed with exit status: 1
cava> autoreconf: error: aclocal failed with exit status: 1
error: builder for '/nix/store/g0mjcanixacvsvn7zqlm4x9fvl30q0i9-cava-0.10.2.drv' failed with exit code 1;
       last 23 log lines:
       > Using versionCheckHook
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/7n3i4i7mf29fwap22m4srqy73c8vv55n-source
       > source root is source
       > Running phase: patchPhase
       > Running phase: autoreconfPhase
       > autoreconf: export WARNINGS=
       > autoreconf: Entering directory '.'
       > autoreconf: configure.ac: not using Gettext
       > autoreconf: running: aclocal --force -I m4
       > aclocal: warning: couldn't open directory 'm4': No such file or directory
       > configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
       > lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
       > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
       > /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
       > lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
       > /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
       > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
       > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
       > configure.ac:306: the top level
       > autom4te: error: /nix/store/ab13djpkv4pyii8lvz4106bimy62db59-gnum4-1.4.19/bin/m4 failed with exit status: 1
       > aclocal: error: /nix/store/wky99hgy2w2nb3a6hzgk96yqdbi95zsj-autoconf-2.72/bin/autom4te failed with exit status: 1
       > autoreconf: error: aclocal failed with exit status: 1
       For full logs, run 'nix log /nix/store/g0mjcanixacvsvn7zqlm4x9fvl30q0i9-cava-0.10.2.drv'.
error: 1 dependencies of derivation '/nix/store/65261yl684f3fy2jwgdmk709sfdr8s2a-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7i3lmkm326979b9rqjidp65m6rhhlxh0-nixos-system-p520-jakos-25.05.20241115.5e4fbfb.drv' failed to build
┏━ 1 Errors: 
┃ error: builder for '/nix/store/g0mjcanixacvsvn7zqlm4x9fvl30q0i9-cava-0.10.2.drv' failed with exit code 1;
┃        last 23 log lines:
┃        > Using versionCheckHook
┃        > Running phase: unpackPhase
┃        > unpacking source archive /nix/store/7n3i4i7mf29fwap22m4srqy73c8vv55n-source
┃        > source root is source
┃        > Running phase: patchPhase
┃        > Running phase: autoreconfPhase
┃        > autoreconf: export WARNINGS=
┃        > autoreconf: Entering directory '.'
┃        > autoreconf: configure.ac: not using Gettext
┃        > autoreconf: running: aclocal --force -I m4
┃        > aclocal: warning: couldn't open directory 'm4': No such file or directory
┃        > configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
┃        > lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
┃        > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
┃        > /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
┃        > lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
┃        > /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
┃        > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
┃        > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
┃        > configure.ac:306: the top level
┃        > autom4te: error: /nix/store/ab13djpkv4pyii8lvz4106bimy62db59-gnum4-1.4.19/bin/m4 failed with exit status: 1
┃        > aclocal: error: /nix/store/wky99hgy2w2nb3a6hzgk96yqdbi95zsj-autoconf-2.72/bin/autom4te failed with exit status: 1
┃        > autoreconf: error: aclocal failed with exit status: 1
┃        For full logs, run 'nix log /nix/store/g0mjcanixacvsvn7zqlm4x9fvl30q0i9-cava-0.10.2.drv'.
┣━ Dependency Graph:
┃       ┌─ ⏸ unit-dbus.service waiting for 1 ⚠
┃       │  ┌─ ⏸ X-Restart-Triggers-polkit waiting for 1 ⚠
┃       ├─ ⏸ unit-polkit.service
┃    ┌─ ⏸ system-units
┃    │        ┌─ ⏸ dbus-1 waiting for 1 ⚠
┃    │     ┌─ ⏸ X-Restart-Triggers-dbus
┃    │  ┌─ ⏸ unit-dbus.service
┃    ├─ ⏸ user-units
┃ ┌─ ⏸ etc
┃ │  ┌─ ⚠ cava-0.10.2 failed with exit code 1 after ⏱ 2s in autoreconfPhase
┃ ├─ ⏸ system-path
┃ ⏸ nixos-system-p520-jakos-25.05.20241115.5e4fbfb
┣━━━ Builds          
┗━ ∑ ⏵ 0 │ ✔ 0 │ ⏸ 11 │ ⚠ Exited after 1 build failures at 22:37:16 after 57s
Error: 
   0: Command exited with status Exited(1)

**To Reproduce**
  I updated my flake and now get this error   I tried override for 10.1, .2, .3   same results
  Another user just reported the same thing 

**Expected behavior**

build successfully 

**Desktop (please complete the following information):**
NIXOS unstable,  hyprland 0.45

NIXOS config here:     https://github.com/jakoolit/NixOs-Hyprland

**Comment by frn-af** [comment]
i have the same issue with this, even when i trying install cava with `nix-env` the installation failed. 
this the log when i install whit nix-env: 

```sh
❯ nix-env -iA nixos.cava
warning: name collision in input Nix expressions, skipping '/nix/store/cpcas9m73hnr9f045b1znmh8c6cv83z3-nixos-24.11/nixos'
installing 'cava-0.10.2'
this derivation will be built:
  /nix/store/821davazpq9vzyczldink8w4shaxb8ky-cava-0.10.2.drv
building '/nix/store/821davazpq9vzyczldink8w4shaxb8ky-cava-0.10.2.drv'...
Using versionCheckHook
Running phase: unpackPhase
unpacking source archive /nix/store/7n3i4i7mf29fwap22m4srqy73c8vv55n-source
source root is source
Running phase: patchPhase
Running phase: autoreconfPhase
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
/nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
/nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
configure.ac:306: the top level
autom4te: error: /nix/store/ab13djpkv4pyii8lvz4106bimy62db59-gnum4-1.4.19/bin/m4 failed with exit status: 1
aclocal: error: /nix/store/wky99hgy2w2nb3a6hzgk96yqdbi95zsj-autoconf-2.72/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
error: builder for '/nix/store/821davazpq9vzyczldink8w4shaxb8ky-cava-0.10.2.drv' failed with exit code 1;
       last 23 log lines:
       > Using versionCheckHook
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/7n3i4i7mf29fwap22m4srqy73c8vv55n-source
       > source root is source
       > Running phase: patchPhase
       > Running phase: autoreconfPhase
       > autoreconf: export WARNINGS=
       > autoreconf: Entering directory '.'
       > autoreconf: configure.ac: not using Gettext
       > autoreconf: running: aclocal --force -I m4
       > aclocal: warning: couldn't open directory 'm4': No such file or directory
       > configure.ac:306: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
       > lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
       > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
       > /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
       > lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
       > /nix/store/fvdsb9i4vb8ca77s8lh60cil33m36dmk-autoconf-archive-2024.10.16/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
       > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
       > lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
       > configure.ac:306: the top level
       > autom4te: error: /nix/store/ab13djpkv4pyii8lvz4106bimy62db59-gnum4-1.4.19/bin/m4 failed with exit status: 1
       > aclocal: error: /nix/store/wky99hgy2w2nb3a6hzgk96yqdbi95zsj-autoconf-2.72/bin/autom4te failed with exit status: 1
       > autoreconf: error: aclocal failed with exit status: 1
       For full logs, run 'nix log /nix/store/821davazpq9vzyczldink8w4shaxb8ky-cava-0.10.2.drv'.
```
i still dont know what should i do to fix that.

**Comment by karlstav** [comment]
This is the same as #594. You can use the source package described in #598

**Comment by dwilliam62** [comment]
Thank you.   I suspect I will have to wait for the nix pacakage maintainer to update it.   I did try an override for 10.3 and that too fails with same error.  I can't just build cava on NIXOS.

**Comment by jack-avery** [comment]
> This is the same as #594. You can use the source package described in #598

nixpkgs (the package manager for Nix and by extension NixOS) doesn't have an easy way to natively expose `libfftw` to path. I tried building with a `nix shell` but `nixpkgs#fftw` doesn't suffice for `./configure`. Nix is weird, and prefers to absorb anything into its' own ecosystem, it seems. Sometimes tedious but I find it rewarding so far. Hopefully the above works for people.

**Comment by karlstav** [comment]
I will close this as duplicate. Please do poke the nix cava package maintainer about the issue.
