### ISSUE TITLE
Здравствуйте! Делал все по инструкции, но при запуске autoconf выходит лог ошибок. весь интернет перерыл, но ничего не смог найти...

### ISSUE THREAD

**Issue by nikaloskut** [karlstav/cava#600]
`Makefile.am:64: warning: source file 'input/sndio.c' is in a subdirectory,
Makefile.am:64: but option 'subdir-objects' is disabled
Makefile.am:68: warning: source file 'input/oss.c' is in a subdirectory,
Makefile.am:68: but option 'subdir-objects' is disabled
Makefile.am:72: warning: source file 'input/jack.c' is in a subdirectory,
Makefile.am:72: but option 'subdir-objects' is disabled
Makefile.am:76: warning: source file 'output/terminal_ncurses.c' is in a subdirectory,
Makefile.am:76: but option 'subdir-objects' is disabled
Makefile.am:76: warning: source file 'output/terminal_bcircle.c' is in a subdirectory,
Makefile.am:76: but option 'subdir-objects' is disabled
Makefile.am:82: warning: source file 'output/sdl_cava.c' is in a subdirectory,
Makefile.am:82: but option 'subdir-objects' is disabled
Makefile.am:86: warning: source file 'output/sdl_glsl.c' is in a subdirectory,
Makefile.am:86: but option 'subdir-objects' is disabled
/usr/share/automake-1.17/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.17/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.17/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.17/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.17/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.17/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.17/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' `again``

**Comment by karlstav** [comment]
duplicate #594
