### ISSUE TITLE
Follow up on previous issue. In kitty, it renders to an extent (no moving bars tho) but in alacritty nothing shows up.

### ISSUE THREAD

**Issue by aa830** [karlstav/cava#606]
**READ THIS BEFORE CREATING NEW ISSUE**

Are you using cava from a package repository, like AUR?

If so, clone the master branch from here, build and run. Is your issue already resolved?

Don't know how to clone or compile source code? Learn before posting issues here.

**ALWAYS TRY TO BUILD AND RUN FROM THE SOURCE CODE ON GITLAB BEFORE POSTING ISSUES**

If the issue is resolved when building from source, do not post issues here.

**Describe the bug**

**To Reproduce**

1. Set config parameter to method = portaudio source = "Background Music"
2. run
3. See some bars on the bottom
4. No moving bars
5. Alacritty shows nothing

**Expected behavior**

Should render and bars move around

**Screenshots**

**Desktop (please complete the following information):**

 - OS: macOS 
 - 15.1.1

**Terminal emulator**
- alacritty
- kitty

**Additional context**

**Comment by karlstav** [comment]
works on my old mac, maybe there is some issue on newer macs, no way for me to reproduce.
