### ISSUE TITLE
Need help accessing the config file

### ISSUE THREAD

**Issue by Parcormaster** [karlstav/cava#608]
When I try to going to the config file using the terminal using
~/.config/cava/config
 I get this:
/home/profilename/.config/cava/config: line 5: [general]: command not found
/home/profilename/.config/cava/config: line 8: syntax error near unexpected token `;'
/home/profilename/.config/cava/config: line 8: `; mode = normal'

sudoing the command just makes my type in my password before giving the same output. What am I missing/doing wrong? I'm very new to Linux so detailed but simple explanations would be appreciated, thank you.

**Comment by karlstav** [comment]
hi @Parcormaster and welcome to linux!

what you are basically doing when typing the path to the config file and hitting enter is to "run" the config file. That is not what you want. You want to open it in a text editor. Maybe start with opening it in a simple gui-based text editor on your computer. 

you can learn more about terminals here:

https://ubuntu.com/tutorials/command-line-for-beginners

you can also use a text editor in your terminal, read more here:

https://itsfoss.com/edit-files-linux/

try reading up/searching before you ask, if you get stuck try asking in general user forum for the distro you are using.

good luck!
