### ISSUE TITLE
cava not displaying moving bars on Alpine Linux

### ISSUE THREAD

**Issue by dtoraelek** [karlstav/cava#609]
**Describe the bug**

Quite simply put, cava displays the bars, with no movement whatsoever despite audio playing. Using default configs, alsa and pulseaudio for sound. 

To answer your question of the source, to my knowledge no one has built an alpine binary of cava for the apk package manager. This program was built using the master git repo and system tools with the musl libraries

**To Reproduce**

execute the cava binary
execute a sound/video player (tried cmus, mpv, musikcube)

**Expected behavior**

Expected behavior is to read off the output and visualize as normal

**Screenshots**

As seen here, I have mpv, pavucontrol and cava running in the photo to prove audio is playing. For copyright problems should they arise (doubtful), the video in question is Daft Punk's Interstella 5555
![2024-12-14-002635_1366x768_scrot](https://github.com/user-attachments/assets/2f3839ac-e599-46b9-9190-03c364831133)

System information provided by neofetch in case this is necessary later on. The issue still persists on i3wm as well as openbox and icewm. (yes I now realize the typo in the hostname, too lazy to change it)
![2024-12-14-002526_1366x768_scrot](https://github.com/user-attachments/assets/e71083fa-c618-4731-b3e6-4e992bd34439)

**Desktop (please complete the following information):**

 - OS: [Alpine Linux]
 - Version [edge]

**Terminal emulator**
- sakura (3.8.8-r0)
- /dev/tty1 (N/A)

**Additional context**

I researched a previous bug report where a person was using arch and i3wm, but locales were not set. Considering I am on a musl system, uncertain whether locales are set, or how to set them if not set, as you are not prompted in the installer scripts.

having a similar issue with a now dormant project (as of November 2024, the page no longer exists) called cli-visualizer by dpayne: [https://web.archive.org/web/20220627182126/https://codeload.github.com/dpayne/cli-visualizer/zip/refs/heads/master](url) That said I do not believe the issue is directly related to cava, but much rather either locale issues or compatibility.

The issue is not related to the semi-rolling status of Alpine Edge, as I built cava on Alpine v3.21 and experienced the same problems.

**Comment by karlstav** [comment]
Hi @dtoraelek,

Your issue is not locale related, then you wouldn't have seen the bottom line of the bars either.

It can be #602. Just go through the capturing audio section of the readme.

**Comment by dtoraelek** [comment]
Looks like the problem was in the configure phase of the package, I managed to get it to work on pulseaudio.

**Comment by karlstav** [comment]
my bet is on the issue reference above. The configure phase detects pipewire dev files and builds cava with pipewire support, pipewire becomes default, but pipewire is not actually used on the system resulting in no moving bars.

I will try to figure out a better solution for this.
