### ISSUE TITLE
Freeze on launch without parameters. [SOLVED] [PEBCAK]

### ISSUE THREAD

**Issue by fauxm** [karlstav/cava#71]
**EDIT:** Massive PEBCAK here, it's been a long day. Turns out reading the top comment and realizing that `;` is used as a comment character as well as `#` would help...

~~It seems the config file parsing is causing a crash, at least for me. Whenever I launch without parameters (ie, it's reading the config), or whenever I refresh the config inside of cava, it freezes.~~

~~For the former (launching w/out parameters), it just sits with the bars all at their lowest value, for the latter (refreshing config while cava is open and working), it blanks the screen and stops working.~~

~~I just re-tried, and it no longer freezes after refreshing in cava, it just fails to load the config.~~

~~I'm on build `cava 0.3.4-10-ge02e383-dirty` on `Linux 4.2.0-gentoo-r1 x86_64`.~~

**Comment by anko** [comment]
It happens. :)
