### ISSUE TITLE
Cannot compile with debug=1 on raspbian (Debian/Jessie)

### ISSUE THREAD

**Issue by andig** [karlstav/cava#76]
This is the error:

	root@moode:~/cava# make debug=1
	cd iniparser && make
	make[1]: Entering directory '/root/cava/iniparser'
	CC      src/iniparser.o
	CC      src/dictionary.o
	AR      libiniparser.a
	a - src/iniparser.o
	a - src/dictionary.o
	RANLIB  libiniparser.a
	LINK    libiniparser.so
	make[1]: Leaving directory '/root/cava/iniparser'
	gcc -std=c99 -Wall -Wextra -DPACKAGE=\"cava\" -DVERSION=\"0.3.5-8-g74e74e4\" -D_POSIX_SOURCE -D _POSIX_C_SOURCE=200809L -Iiniparser/src -DDEBUG   cava.c iniparser/libiniparser.a  iniparser/libiniparser.a -lasound -lm -lfftw3 -lpthread -I/usr/include/ncursesw -lncursesw -ltinfo -o cava
	cava.c: In function ‘main’:
	cava.c:804:28: error: ‘peak’ undeclared (first use in this function)
		    lcf[o], hcf[o], peak[o], f[o]);
				    ^
	cava.c:804:28: note: each undeclared identifier is reported only once for each function it appears in
	cava.c:380:6: warning: variable ‘flastd’ set but not used [-Wunused-but-set-variable]
	  int flastd[200];
	      ^
	<builtin>: recipe for target 'cava' failed
	make: *** [cava] Error 1

**Comment by karlstav** [comment]
oops the old debug mode, I had completely forgotten to maintain that. 

@andig what are you going to use the debug mode for? It was originally used to test different stuff, but mainly to "tune" the equalizer. I can't promise that it works that well, been thinking about removing it for a while.

**Comment by andig** [comment]
No idea- just wantet to start with highest detail output and found it in the readme ;)
