### ISSUE TITLE
Build requirements for fedora

### ISSUE THREAD

**Issue by sedrubal** [karlstav/cava#77]
Maybe you want to add the build requirements for fedora to the readme?

For fedora you need:

 - `alsa-lib-devel`
 - `ncurses-devel`
 - `fftw3-devel`

I also wrote a simple specs file for automated rpm building: https://gist.github.com/sedrubal/617d40deb7452a25d004#file-cava-spec

And thanks for this program ;)

**Comment by karlstav** [comment]
@sedrubal I guess they will be installed like this then:

`yum install alsa-lib-devel ncurses-devel fftw3-devel`

?

I'll link to your rpm script as well.

**Comment by sedrubal** [comment]
yum is going to be replaced by dnf so it's better to write

```
dnf install ...
```

Thanks ;)
