### ISSUE TITLE
config script

### ISSUE THREAD

**Issue by karlstav** [karlstav/cava#79]
@dylanaraps @CelestialWalrus or who ever might be reading this, I started working on the config script in a separate branch. It's not really my area of expertise, yet...  and I'm kinda stuck. I guess I will figure it out eventually, but any help would be much appreciated. Thanks!

**Comment by dylanaraps** [comment]
I have no experience with configure scripts either! I've been looking at some similar project's configure files to get an idea and I almost have something that works. I added an autogen.sh file which generates the configure/makefile from configure.ac/makefile.am and I have the configure script working.

Where I'm stuck now is the makefile, I'll keep working on it though.

**Comment by karlstav** [comment]
@dylanaraps I'm using the guide from [here](https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install), it says nothing about the autogen.sh script..

unless all that does is:

    aclocal
    autoconf
    automake --add-missing

anyways, I got something working now. However it's mostly copy pasted from various places and I'm still not 100% sure of what I'm doing, but it's somehow magically working, should be tested a lot lot more...

**Comment by dylanaraps** [comment]
Yeah, the autogen.sh script I have runs those 3 commands but first checks to see if the user has the make tools installed. 

If you've got it working then that's great! I'll test it out asap.

**Comment by karlstav** [comment]
the auto... commands generated a lot of files and I guess more of them are needed by the configure script to run.

I removed the `configure` script and added an autogen.sh script instead, try running that first and then
 
    ./configure
    make

**Comment by dylanaraps** [comment]
It works now! It builds and runs fine.  Awesome.

**Comment by karlstav** [comment]
config script is now implemented in 0.4.0. keeping this issue open in case someone has ideas for improvements
