### ISSUE TITLE
[Enhancement] Reload config from external signal

### ISSUE THREAD

**Issue by StephenBrown2** [karlstav/cava#81]
I'm loving cava so far, especially now that 0.4.0 has added direct PulseAudio support!

One thing I thought might be cool is if cava can reload the configuration when sent a signal, for example SIGUSR1, like httpd and various other programs which use USR1 as a command to reload the config.

The prime example of this is if I change the pulseaudio output/source, I want to automatically set the appropriate variable in cava's config and tell cava to re-read it, via a script. This would also apply for any other config changes.

Perhaps better, cava could watch the config file for changes and automatically reload it, but I think that may be a bit more involved than necessary.

I'm not sure if this is as simple as adding an `if` statement to `sig_handler`, or not, as I've rather little C experience.

**Comment by karlstav** [comment]
@StephenBrown2 this sounds complicated, but doable...

You can reload the config file by pressing 'r', but that will not reload the audio input settings. This can be fixed by moving the audio init in to the while loop and adding some thread control (the audio grabber is using pthread). 

To automatically reload the configfile whenever it changes sound more complicated. Is it necessary? I can't think of any other programs that does this.

**Comment by StephenBrown2** [comment]
Interesting, I did think it might be complicated, though I thought that load_config read all of the config.

I wouldn't require cava itself to reload the config file when the sound output changes, I could handle this myself via a script I'd write, essentially (pseudocode):

```bash
prompt -v src $(pactl list short sinks)  # prompt for output selection
pactl set-default-sink ${src} # Set the active output sink
sed 's/source =.*/source = ${src}.monitor/' ~/.../config # write monitor source to cava config
killall -s SIGUSR1 cava # reload config
```

Now, I did see that the 'NULL' setting apparently uses the default pulse sink, however, uncommenting the line resulted in an error, and leaving it commented didn't give any output, thus the setting of the source manually, which works flawlessly.

I think it may depend on if the monitor of the source is being read or not. If one can get around it by simply using whatever is the default, that would also fix my particular issue, and make the feature request more easily do-able.

**Comment by karlstav** [comment]
> 'NULL' setting apparently uses the default pulse sink, however, uncommenting the line resulted in an error,

There is a bug here that I forgot to fix, uncommenting this line without changing the 'NULL' to something else will result in cava trying to use the string "NULL" and not the "null-pointer".

Leaving it uncommented will result in cava using your default <i>source</i>. This would most likely be your mic (which might be muted) or some uninteresting line-in. 

The ideal solution would be to implement what you are trying to do in your script in to cava. I. e. first find the active <i>sink</i> name and then append `.monitor` to it.

**Comment by StephenBrown2** [comment]
Ah, that does explain things.

Well then, I shall leave it up to you how to handle it, and for now, will manually restart cava if I need to switch from my speakers to headphones.

**Comment by karlstav** [comment]
@StephenBrown2 I finlly got around to look at this.  Pushing 'r' should now reload audio config from config file.

**Comment by StephenBrown2** [comment]
Whee! I will try to pull the latest once it gets updated in AUR and let you know. :-)

**Comment by karlstav** [comment]
@StephenBrown2 this feature has now been added by @EmilGedda. Look in the [readme file](https://github.com/karlstav/cava#configuration) on how to use it.
