### ISSUE TITLE
[enhancement] Autosense low values as well

### ISSUE THREAD

**Issue by StephenBrown2** [karlstav/cava#82]
Just another thought I had. I frequently listen to music that varies in volume (I can't ReplayGain online streaming services), and I have autosens turned on so that the high peaks get toned down in cava. However, this means for quieter songs, cava is just a bubbling brook at the bottom of the terminal window.

It would be cool to set a lower threshold (or just default to something reasonable, like 80%) for autosens to adjust the sensitivity UP to for the peaks to fall into, to keep it entertaining. I'd imagine the timeout for lows could/should be longer than for highs, but again I'm probably asking for something much more complicated than I realize. :-)

**Comment by karlstav** [comment]
Thanks again for the feedback @StephenBrown2 , I have experienced this problem as well. It's is a bit tricky as some music might have long periods with low intensity. This would leave the sensitivity being adjusted up and down continuously, within the same song.To avoid this we would have to measure the intensity over a pretty long time period. 

In my experience there are some sudden very high peaks. So I'm going to allow a certain amount of "overshoot", to avoid it being adjusted too low.

Remember that you can always manually adjust the sensitivity with up and down arrow keys.

**Comment by karlstav** [comment]
implemented as of 0.4.2
