### ISSUE TITLE
Error on Raspbian at run-time.

### ISSUE THREAD

**Issue by 0xNear** [karlstav/cava#84]
```bash
pi@raspberrypi:~/Desktop/cava $ cava
cava: error while loading shared libraries: libiniparser.so.4: cannot open shared object file: No such file or directory
```
It's not running under Raspberry Pi 2B. I have installed Raspbian GNU/Linux 8.0 (jessie).
There was no errors when I was compiling, I compiled it two times for being sure.

**Comment by karlstav** [comment]
@0xNear I think I might have stumbled upon the bug that you are experiencing. I can see that you have installed cava to your system. For some reason when running from system installation on rasbian (I have version 7 ) it can't find `libiniparser.so.4`. It works if you run it from the build tree (./cava). 

`libiniparser.so.4` is located in the exact same place as on my ubuntu system, in `/usr/local/lib`, which is where  iniparser says it should be. On ubuntu everything works fine as well, so I'm lost here...

**Comment by PlasmaBinturong** [comment]
Hey, I encounter the same error on Ubuntu 14.04. I managed to install it however, by doing:

    export LD_LIBRARY_PATH=/usr/local/lib

before the compilation steps.
Not sure that is the proper way to do it but I know nothing about C++, compilation, linker flags...!

interestingly, it also works if I do `./configure --prefix=/home/me/.local`.

I can show you the output I got before fixing, if you need it.

Thanks for this program, it looks great! =D

PS: for an enhancement, would it be possible to set the background color to transparent? Would be great in a xterm =)

**Comment by karlstav** [comment]
@PlasmaBinturong that looks programming. I think this can be fixed easily in the configure-script/makefile. This issue is getting old, I should have gotten around to fixing it sooner, but have been lazy...

As for transparent background I, think the default is supposed to be "leave untouched". So if you leave it commented in the config and don't touch 'b' while running it's supposed to stay transparent if it where. The background transparency is a feature of the terminal emulator, not the application running in it. So cava itself cannot make the background transparent, if it isn't already. 

I can see now that the config file says default background color is black. That should say "leave untouched".

**Comment by PlasmaBinturong** [comment]
I installed it correctly now, the thing to do was `export LD_RUN_PATH=/usr/local/lib` before compilation.

This message during `make install` helped me:

    Libraries have been installed in:
       /usr/local/lib

    If you ever happen to want to link against installed libraries
    in a given directory, LIBDIR, you must either use libtool, and
    specify the full pathname of the library, or use the `-LLIBDIR'
    flag during linking and do at least one of the following:
       - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
         during execution
       - add LIBDIR to the `LD_RUN_PATH' environment variable
         during linking
       - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
       - have your system administrator add LIBDIR to `/etc/ld.so.conf'

    See any operating system documentation about shared libraries for
    more information, such as the ld(1) and ld.so(8) manual pages.


And transparency works like you say =)

**Comment by karlstav** [comment]
@PlasmaBinturong and @0xNear I added this line to `Makefile.am`:

```
cava_LDFLAGS = -L/usr/local/lib -Wl,-rpath /usr/local/lib
```

that fixed it on my rasbian version 7. As always with this stuff I'm not 100% sure what I'm doing. Could you test it before I close this? I have pushed the fix to the master branch.

Also I have no idea if this is actually a good fix, or just a bloated workround that is going to cause more problems in the future.

**Comment by PlasmaBinturong** [comment]
It works for me!
