### ISSUE TITLE
Cava not showing microphone input.

### ISSUE THREAD

**Issue by JamieOnUbuntu** [karlstav/cava#85]
I have a Raspberry Pi with a USB soundcard and a microphone plugged in.

I have installed FFTW, Cava and PulseAudio.

Other applications on the Pi can record the audio just fine, however Cava will not display the audio.

When running Cava, I can see that it is recording audio from the correct source by looking in the PulseAudioVolumeControl program, however the bars are not moving up and down.

I think this is a problem with FFTW.

See in this screenshot: ![](http://i.imgur.com/XQPHRl6.png) Music is playing in VLC, PulseAudioVolumeControl indicates that Cava is recording audio, but in the top right, Cava is running but there are no bars moving.

Is there a proper way to get Cava working on a Pi?

Thanks

**Comment by karlstav** [comment]
@JamieOnUbuntu this might sound stupid, but in your screenshot the Monitor interface looks like it's muted. As loong as cava is able to run, FFTW should work fine. Also Cava works perfectly on my pi.

**Comment by JamieOnUbuntu** [comment]
No way! I can't believe I missed that!

I have no idea why Cava was muted by default. I did unmute the microphone itself, but I never thought for one second that Cava was also muted from recording audio.

Thanks!
