### ISSUE TITLE
Feature Request: Set the terminal title

### ISSUE THREAD

**Issue by dylanaraps** [karlstav/cava#86]
Cava doesn't currently set the window title so titlebars, etc show the terminal emulator's default title. 

Here's a screen, notice how the terminal running cava still says "urxvt" while the other terminal running ncmpcpp has it's own title. 

![1](https://sr.ht/BWgb.png)

The title doesn't have to be complex, just "cava" would be fine!

Thanks!

**Comment by CelestialWalrus** [comment]
Made a PR for you. #87

**Comment by karlstav** [comment]
thanks @CelestialWalrus! Haven't seen you in a while, was afraid you where gone for good.
