### ISSUE TITLE
Question Regarding Installation

### ISSUE THREAD

**Issue by TheWaveCarver** [karlstav/cava#88]
Not necessarily an issue with the program... but I'm having trouble installing it on Ubuntu 14.04.3 LTS. I really like everything I've seen about the program. With regards to installation, my issues lie when I get to the sections: "Getting Started" and "Installing Manually". I believe I understand the sections after that... I just have no idea how to install it (And somehow allow the program to use FFTW?). Like I said, I'm very interested in using CAVA, I just need some guidance. Thanks!

**Comment by karlstav** [comment]
after installing all requirements:

```
sudo apt-get install libfftw3-dev libasound2-dev libncursesw5-dev libpulse-dev
```

cd in to cava folder and run these commands:

```
./autogen.sh
./configure
make
```

you should now be able to run cava with 
```
./cava
```

if not, look for any error messages when running the three commands above. 

If it works you can now install cava to your system:
```
sudo make install
```

**Comment by TheWaveCarver** [comment]
Thanks! I'll give it a shot!

**Comment by TheWaveCarver** [comment]
So when I attempt to ./autogen.sh I get the following errors:

root@tyler-Aspire-one:/home/tyler/Desktop/karlstav-cava-d654130# ./autogen.sh
./autogen.sh: 2: ./autogen.sh: libtoolize: not found
./autogen.sh: 3: ./autogen.sh: aclocal: not found
./autogen.sh: 4: ./autogen.sh: autoconf: not found
./autogen.sh: 5: ./autogen.sh: automake: not found

Any idea why?

**Comment by TheWaveCarver** [comment]
Okay so I believe I ran into those issues because I was missing automake and libtool. I was able to install both following this:

sudo apt-get update
sudo apt-get install libtool

and

sudo apt-get install automake

Now I have an error that is directly from the cava.c code. So I think I was successful in making cava.c, but now I'm not sure why it's throwing this error:

Linux kernel module "snd_aloop" does not seem to be loaded.

Any idea on how to solve this issue?

**Comment by TheWaveCarver** [comment]
Also needed:

apt-get install git

**Comment by TheWaveCarver** [comment]
How do you ensure that changes made to the config file in example_files are made? Should you leave config in example_files or move it into the cava folder?

**Comment by karlstav** [comment]
I can see that you are struggling a lot here @TheWaveCarver, many of you problems could probably have been solved with a little more linux knowledge and thorougher reading of the manual. But you have stumbled upon one real issue, after I made the config script `automake`, `libtool` and `git` are actually build requirements.  I'll add them to the list.

Now for the config file. Cava does not use the one stored under example files. This file is copied to i$XDG_CONFIG_HOME/cava/config or $HOME/.config/cava/config when cava is build. Look in the folder `/home/"username"/.config/cava`. Cava also looks in the same path when it is launched. So you should build it and run it with the same user.

I can see in one of your post that you might be trying to build cava as root. This shouldn't be necessary. But if you build cava as root your config file would be in `/root/.config `I think. 


> "error opening stream: Operation not permitted." Is this because my input device hw:0,0 is somehow busy in the background?

Yes, if you are using alsa only one application can use the device at a time. Your sound settings program might actually be grabbing the microphone 

Using pulseaudio is by far the easiest method of capturing audio. Please refer to the manual or the comments in the config file. 



> fatal: Not a git repository (or any of the parent directories): .git

Download the sourcecode using git:

```
git clone https://github.com/karlstav/cava/
```

**Comment by TheWaveCarver** [comment]
Thank you for taking the time to type this all out as I really really want
to use your program (And learn some Linux why Im at it haha). I believe
that everything you mentioned should cover all of my issues (Especially
with the config file); but if for some reason I have more, should I message
your through email or on the Github Issue Board? The reason I've been
posting on the Issue Board is so that anyone else who has been having
issues can see my own progression.

**Comment by TheWaveCarver** [comment]
Once you perform:

sudo make install

Is there anyway to launch the program without using the Terminal? For
instance, double clicking an icon and then just modifying the config file
to adjust the characteristics of it? Thanks again.

**Comment by karlstav** [comment]
no problem

I guess the issue section on github should only be used if you are sure that there is something wrong with the program. Now in this case, it turned out that I had forgotten to add those things in the build requirement section. For some of the other questions maybe stackexchange or ubuntu forums could be used. But you could always send me an email also.



> Is there anyway to launch the program without using the Terminal? For
> instance, double clicking an icon and then just modifying the config file
> to adjust the characteristics of it? Thanks again.

I think it's possible to create an icon, but I don't know how. Maybe a good question for something like ubuntu forums.

**Comment by TheWaveCarver** [comment]
Sounds good. Yes I'll move over to the forums for questions that really
only pertain to more fundamental operations. Just to be clear though...
when you personally use CAVA it is launched from the Terminal everytime?

**Comment by karlstav** [comment]
> when you personally use CAVA it is launched from the Terminal everytime?

Yes, cava was created to be used in the terminal (or console which is what the c in CAVA stands for). There are not actually any graphics, it's all text. I use cava on a small monitor connected to a raspberry pi which does not even run a window manager.
