### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by onekreg** [karlstav/cava#93]
I am not capable of using your tool. Everytime I run it nothing happens. I can use "cava -v" and if I press CTRL-C it will stops but it shows no bars at all. By the way I'm running it on a Raspberry Pi.
![unbenannt](https://cloud.githubusercontent.com/assets/17955059/13901803/1f2f8cec-ee30-11e5-91ec-550547a413e9.PNG)

**Comment by karlstav** [comment]
@onekreg it should work fine on Raspberry Pi, might be several reasons why you are not picking up any audio.

I can see that you are running cava as root, if you are using pulseaudio you're audio source must also be running as root, I think. Or pulseaudio must be running is system mode. 

Pulseaudio is the default input method if it's supported. If you don't have it installed on the pi (I don't know if it is installed in MusicBox) cava will use ALSA, which will mean that you need to use a [loopback interface and the multi channel](https://github.com/karlstav/cava#alsa-multi-channel-hard).

**Comment by onekreg** [comment]
I've tried the debug-mode. It has exactly the same result. There is no debugging message at all.

On my Ubuntu does the software work perfectly. Do I need some extra package? Which aren't in the description? How do I install initparser probably? I've tried this:

https://github.com/ndevilla/iniparser/blob/master/README.md
"A simple make at the root of the project should be enough to get the static (i.e. libiniparser.a) and shared (i.e. libiniparser.so.0) libraries compiled.

You should consider trying the following rules too :

make check : run the unitary tests
make example : compile the example, run it with ./example/iniexample"

I would be happy, if you could help me with my silly problem.

**Comment by karlstav** [comment]
@onekreg don't worry, I'm happy to help. Do you know if you are using pulseaudio or just alsa? 

I can see that you are using musicbox, but I can't find out if it is utilizing pulseaudio or not.

If you don't now you coud always just try to run

```
pulseaudio --version
```

and if it's installed run

```
ps aux | grep pulse
```
while playing audio to find out how it's being used.

**Comment by onekreg** [comment]
Hello,

I tried it with ALSA and with PulseAudio. There was no Pulseaudio installed by default but I installed it.

I use pulseaudio 2.0.

` root      2687  0.0  0.2   2036  1144 pts/0    S+   11:18   0:00 grep pulse

**Comment by karlstav** [comment]
doesn't look like pulseaudio is running. Have you set up Mopidy/shairport to use pulseaudio?

**Comment by onekreg** [comment]
No, Do you know how to do that?

**Comment by karlstav** [comment]
look [here](https://docs.mopidy.com/en/latest/config/) for mopidy and in the file ```/etc/defaults/shairport/``` for shairport. At leats I think that's what musicbox uses and it looks like you are using musicbox.

**Comment by onekreg** [comment]
Hey,

I may found the my mistake. Cava needs some graphic memory although it's a console application. But I gave the GPU 0 MB memory since there is no GUI at all. Now it seems to work. Atleast it shows some response.

**Comment by onekreg** [comment]
Which is the correct Alsa source for the rasperry pi?

**Comment by karlstav** [comment]
> Which is the correct Alsa source for the rasperry pi?

it depends, there is no specific "correct" source for rpi or any other platform for that matter. If you want to use alsa, then try reading the alsa part in the readme file. Get back to me if there is something specific that's unclear. 

About the video memory thing, CAVA uses ncurses, maybe ncurses uses video memory while just plain console does not. I don't know enough about these things to put anything meningfull in the readme.
