### ISSUE TITLE
Config not being used?

### ISSUE THREAD

**Issue by Rain288** [karlstav/cava#94]
Greetings! Sorry, I seem to be a bit lost regarding the config of cava.
I installed it really easily and successfully, there is a config under ~/.config/cava/config, I've configured it to only take input from fifo, have a set amount of bars etc, but when i run cava it probably pulls from another config since my tweaks don't seem to be loaded at all (default bars and pulling from Alsa as well).
So I tried doing this `cava -p ~/.config/cava/config` but it yields the same result as `cava` , so it doesn't load my config at all.
I tried looking under ~/cava but the folder doesn't exist.
So where could the config file it's using possibly be? And how come cava -p won't work?

I'm on cava 0.4.1.5

**Comment by karlstav** [comment]
if you find a config file under ```~/.config/cava/config``` then that is the config file that should be used.

you might run into problems if you start cava with a different user, but -p should work either way (just tested it).

I'm sorry to ask, but I'll just have to make 100% sure you removed the ```;``` in front of the config setting you tried to modify?

**Comment by Rain288** [comment]
I did remove it, yes.

I ended up restarting my computer about 10 mins ago and it apparently fixed the issue, weird.

In any case, thanks a lot!
