### ISSUE TITLE
Pulseaudio not working on raspberry pi

### ISSUE THREAD

**Issue by dvereber** [karlstav/cava#95]
I'm using a fully updated raspbian Jessie.

I've installed cava but it doesn't read the input.

I'm attempting to read a line-in microphone from a USB soundcard, which ALSA recognizes as card 0: Set [C-Media USB Headphone Set], device 0: USB Audio [USB Audio]

```
pi@raspberrypi:~ $ ps aux|grep pulse
pi         699  0.5  1.8 109780  8184 ?        S<l  04:36   0:03
/usr/bin/pulseaudio --start
pi         724  0.0  0.1   1900   568 ?        S    04:36   0:00
/bin/sh /usr/bin/start-pulseaudio-x11
pi         834  0.0  0.4   4268  2008 pts/0    S+   04:48   0:00 grep
--color=auto pulse


pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Set [C-Media USB Headphone Set], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Set [C-Media USB Headphone Set], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by karlstav** [comment]
It should should work fine. You have to specify the source name in the config file (use ```pacmd list-sources``` to find it). Also have  a look at the volume level, I have noticed that microphones often are muted by default in pulseaudio.

**Comment by Lokagan** [comment]
Hmm...

Here is the way i made to make it work with raspbian : 
First install dependencies : 
`sudo apt-get install libfftw3-dev libasound2-dev libncursesw5-dev libpulse-dev automake libtool`
Then git clone, configure, compile : 
`git clone https://github.com/karlstav/cava.git`
`cd cava`
`./autogen.sh`
`./configure`
`make`
`sudo make install`
At this point you just have successfully compiled and installed cava...
Now here is the tricky part to activate the alsa-loopback : 
add `snd-aloop` to `/etc/modules`
add `options snd-aloop index=1` to `/etc/modprobe.d/alsa-base.conf`
At this second point, you just have done the wiki howto... ok !
add this now to your .asoundrc file : 

pcm.!default {
    type asym
    playback.pcm "alsa_sink"
    capture.pcm "alsa_monitor"
}

pcm.alsa_sink {
    type plug
    slave {pcm "alsa_loopback"}
    route_policy "duplicate"
}

pcm.alsa_monitor {
    type plug
    slave {pcm "hw:Loopback,1,0"}
}

pcm.alsa_loopback {
    type multi

    slaves.a.pcm "hw:0,0"
    slaves.a.channels 2
    slaves.b.pcm "hw:Loopback,0,0"
    slaves.b.channels 2

    bindings.0.slave a
    bindings.0.channel 0
    bindings.1.slave a
    bindings.1.channel 1
    bindings.2.slave b
    bindings.2.channel 0
    bindings.3.slave b
    bindings.3.channel 1
}

Now it should output audio on both hdmi/jack and the loopback used by cava.
