### ISSUE TITLE
Getting bundled iniparser to build is klunky

### ISSUE THREAD

**Issue by pherelad** [karlstav/cava#97]
Hi there,

I'm running Gentoo and understand that the my installed version of iniparser required by Portage is older than that required by cava. Since I cannot remove iniparser system-wide since it's a dependency of Portage,  I had to go through the following trials to get things compiled:

* I tried to force cava to build it's own version of libiniparser 4. However, within the iniparser directory there is no Makefile, which prevents the top level Makefile from succeeding.
* I tried cloning the upstream libiniparser 4 repository over the iniparser directory, which results in an error since it's missing the all target.
* I received an error saying the target "all" was not found in iniparser's Makefile. I then re-named the "default" target in libiniparser's Makefile with "all" since that's what cava was looking for.
* Another error was displayed about the generated libraries not existing in iniparser/.libs, so I moved 'em there.

At this point, I got cava to compile and run :+1: 

I think there might be room for improvement here for systems that require the bundled statically linked version of libiniparser. It's great that you made the choice to bundle that for users that may not have it, or have a different version though. It'd be nice if more projects did that IMO.

Also, it may be worth considering adding iniparser's upstream repo as a submodule of your project so it can track directly from the upstream repository. It looked like there is a trimmed down version of it in this repository at present.

Thanks for the great project!

**Comment by karlstav** [comment]
Thanks for the detailed troubleshooting log and sorry for the trouble, I know that iniparser on Gentoo can be a hassle. 

Adding a configure option to force use of the bundled should work. But, to quote my self from issue #83:

> To create a permanent fix I will have to use the config script to detect the version. Then in the source I must create a separate code for version 3.1 that uses the old method of detecting number of keys. Just don't have the time right now.


Guess I forgot, I'll look into it soon enough.

**Comment by pherelad** [comment]
Hey @karlstav,

No problemo man, it was kind of fun getting it working TBH. Thanks for the quick response and looking into it. Feel free to lemme know if there's anything I can test for ya.

Thanks again

**Comment by karlstav** [comment]
see #83
